setup.py, src/ape/utils/github.py
fixes: #1545
Fixes: APE-1198
Utilize the retry arg with a special object
First, unset your token:
```sh
unset GITHUB_ACCESS_TOKEN
```
Now, run some bad code:
```python
In [1]: from ape.utils.github import GithubClient
In [2]: client = GithubClient()
In [3]: for i in range(100):
...:     client.get_organization("ApeWorX")
```
You will notice that without this PR, you will get a rate limiting error like the one mentioned in the issue.
But with this PR, it will work, however it will takes ages to complete without your GITHUB_ACCESS_TOKEN, however it will still work.
=> fix: GitHub client retry on rate limiting [APE-1198]

src/ape/types/__init__.py, src/ape/utils/abi.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/transactions.py, tests/functional/test_contract_event.py, tests/functional/utils/test_abi.py
fixes: #1604 
Fixes: APE-1289
* Made it so the events that did not decode would still show up as raw.
So `NodeOperatorAdded` is not still decoding for the tx, going to figure out why exactly before taking this PR out of draft.
So far, all this does and adhere to the advice and still show the events on the tx when they fail to decode.
You should now see events where the event arguments didnt decode right - they are at least on the receipt now and everything else about them works, including the event name and such...
also the warning makes more sense.
Only thing left:
btw, am using some events with strings in it and that didnt cause any bug yet.
=> fix: log decoding issues and missing events [APE-1289]

src/ape/api/networks.py, src/ape/managers/networks.py
fixes: #1433
Fixes: APE-938
When using the `fork()` function, disconnect.
Otherwise, do as normal.
```python
In [2]: provider
Out[2]: <alchemy chain_id=1>
In [3]: provider.name
Out[3]: 'alchemy'
In [4]: provider.is_connected
Out[4]: True
In [5]: with networks.fork("hardhat"):
...:     print("test")
...: 
INFO: Starting 'Hardhat node' process.
INFO: Stopping 'Hardhat node' process.
test
In [6]: provider.is_connected
Out[6]: True
In [7]: with networks.fork("hardhat"):
...:     print(provider.name)
...:     print(provider.is_connected)
...: 
INFO: Starting 'Hardhat node' process.
INFO: Stopping 'Hardhat node' process.
```
=> fix: persistent fork issue when calling `networks.fork()` [APE-938]

tests/functional/test_config.py, tests/functional/test_query.py, tests/integration/cli/test_compile.py
we were getting some intermittent failures in tests because of caplog.
i think i found the reason why but dont know 100%
* removed a call `records.pop()` that was potentially causing issues
* removed unneeded calls to `at_level()` which could potentially hide some INFO based logs on other test s
im hoping just all passing CI both now and in the future can help identify this as a success.
=> test: caplog fixes [APE-1396]

.pre-commit-config.yaml, pyproject.toml, setup.py, src/ape/api/providers.py, src/ape/api/query.py, src/ape/cli/options.py, src/ape/logging.py, src/ape/managers/chain.py, src/ape_networks/_cli.py, src/ape_plugins/_cli.py, src/ape_plugins/utils.py, tests/conftest.py, tests/functional/test_block_container.py, tests/functional/test_config.py, tests/functional/test_contracts_cache.py, tests/functional/test_networks.py, tests/functional/test_query.py, tests/functional/utils/test_abi.py, tests/integration/cli/test_compile.py, tests/integration/cli/test_plugins.py
* Moves web3 loggers to web3 provider
* Fixes a type on a query validation method (was receiving tuples here even tho it says list, but really any sequence should work)
* Soft-rename (non-breaking) of the logger class
* Issue with plugin installs when given dir, only noticed in a xfail test
* create a testing assert log fixtures for our tests here so operations can be retried, this should mitigate the xdist related issues with caplog hopefully
* 
gimme a passing build on merge to main
=> refactor: move web3 loggers and fix test failures [APE-1404]

setup.cfg, src/ape/api/config.py, src/ape/api/networks.py, src/ape/api/projects.py, src/ape/api/transactions.py, src/ape/types/__init__.py, src/ape/utils/__init__.py, src/ape/utils/basemodel.py, tests/functional/test_receipt.py
So as I am working on some pydantic v2 refactor stuff for !0.7, I am noticing some other smaller refactors that would really make it a lot easier, stuff we can do now... stuff we are likely going to have to do anyway...
So this is one of those things.
Right now, we have some weird logic for __getattr__ and everyone is kinda wildwildwesting it but for the most part have to keep in mind the same gotchas. I am finding that v2 of pydantic has even more gotchas in this regard. So, we can isolated those to one place with this new system of allowing getattr / getitem overloads.
A new method in BaseModel `__ape_extra_attributes__` that returns an iterator of this new class containing the attributes, some metadata, and what parts to use it in. It also has a handy method for checking such …
=> refactor: BaseModel getattr logic sharing [APE-1415]

src/ape/types/__init__.py, tests/functional/test_receipt.py
Adds the `.timestamp` property to `ContractLog`, allowing users to pull the raw timestamp when querying events
fixes: #1612
This should be safe to add as both Solidity and Vyper use `timestamp` as a reserved keyword, thus it would not appear as an event arg name
Validate my intution is true re: reserved keyword
=> feat(query): add timestamp to ContractLog [APE-1391]

src/ape/utils/misc.py, tests/functional/test_project.py, tests/functional/utils/test_misc.py
got an unhandled exception when attempting to list installed plugins when there werent any installed.
When given an empty list in the helper function, return empty list.
* Ensure no plugins installed.
* Run `ape plugins list`
=> fix: `ape plugins list` failed when no plugins installed. [APE-1425]

src/ape/plugins/__init__.py, src/ape_plugins/_cli.py, src/ape_plugins/utils.py, tests/functional/test_plugins.py, tests/integration/cli/conftest.py, tests/integration/cli/test_plugins.py
I had accidentally broken `ape plugins list` with the performance PR that merged.
This fixes that and refactors in such as way that actually allows tests to catch some issues.
* Register plugins before listing plugins
* Abstract plugin metadata and str stuff into utilities classes
* Add bunch of tests
=> fix: plugins list, install, and uninstall issues [APE-1427]

src/ape/managers/networks.py, tests/functional/test_network_manager.py
Issue where couldnt use getattr for polygon zkevm ecosystem.
alternate hyphen with underscore as a last attempt
`networks.polygon_zkevm` when you have `ape-polygon-zkevm` installed
=> fix: hyphenated ecosystem names [APE-1437]

src/ape/managers/networks.py, src/ape_networks/_cli.py, tests/integration/cli/test_networks.py
It is frustrating using `ape networks list` when you have lots of networks because the order is inconsistent. Every time I am looking for `polygon-zkevm`, it is in a different spot etc.
This sorts it
sorting
output is sorted
=> feat: sort networks in `list` command [APE-1439]

src/ape_networks/_cli.py, tests/integration/cli/test_networks.py
this was a miss from https://github.com/ApeWorX/ape/pull/1690 when you have multiple providers installed
=> fix: sort providers in `ape networks list` [APE-1442]

src/ape/api/projects.py, src/ape/managers/project/manager.py, tests/functional/test_project.py
Fixes the bug mentioned in this comment: https://github.com/ApeWorX/ape/issues/1594#issuecomment-1673289476
Use `.cached_manifest` instead of `._cached_manifest`
do both on main and this branch
1. run ape compile in a project with contracts
2. observe __local__.json modification time
3. open a console
4. type `project.contracts`
5. observe that modification time was updated unnecessarily on main but not on this branch
=> fix: unnecessary modification of build artifact

build_docs.py, src/ape/managers/compilers.py, tests/functional/conftest.py, tests/functional/test_compilers.py
issue where contract type collision error would not raise when adding contract with same name after compiling,
and in cases where deleted contracts remained, new contracts with the same name would indefinitely re-compile
i think this fixes #1594 (APE-1277) but may need some testing from the user who opened the issue
fixes: #1594 
Fixes: APE-1277
Check already built names for collisions as well
1. compile a project with contract Test.vy
2. add a new contract Test.sol
3. compile again
4. **Notice things compile indefinitely and never properly cache** (maybe fixes: #1594  ?) without this PR and with this PR, you get the expected error
=> fix: an indefinite compile issue [APE-1450]

setup.py
bump to 0.5.8 because 0.5.7 has a bug that affects core.
=> chore: bump ethpmtypes [APE-1454]

src/ape_accounts/accounts.py, tests/functional/test_accounts.py
fixes: #1701
```py
from ape import accounts
a = accounts[0]
a.public_key
>> HexBytes("0x33abababbababababbabababababababba..")
```
=> feat: `public_key` method added to `KeyfileAccount` class [APE-1466]

src/ape/managers/networks.py, tests/functional/test_network_manager.py
* Issue where only one of `:local:foundry`: or `:mainnet-fork:foundry` would be available (depending on user-config and default settings).
* Issue where `ethereum::foundry` would be missing as well
use `if` instead of `elif`
=> fix: issue where network choices were missing [APE-1475]

.pre-commit-config.yaml, setup.py, src/ape/api/networks.py, src/ape/api/providers.py, src/ape/managers/networks.py, src/ape/utils/basemodel.py, src/ape_geth/provider.py, src/ape_networks/_cli.py, src/ape_test/provider.py, tests/conftest.py, tests/functional/test_network_manager.py, tests/integration/cli/test_networks.py, tests/integration/cli/utils.py
fixed bug with Disconnect => reconnect with new settings was bugged when using the same Python session.
also adds `settings` object which is useful for getting all provider settings mashed together.
Also, fixes an issue where settings were not updated when connecting to an already-connected provider with new settings.
**note**: as I was fixing this, I had some random failing tests pop up; bugs highlighted with the networks yaml not actually filtering. I had to fix this in order to get a passing build on this PR.
That caused this PR to be a little out of scope but I don't think it is worth opening more PRs at this point; it is all network related anyway.
Delete provider from connected providers when disconnecting
in combo with 
https://github.com/ApeWorX/ape-foundry/pull/74
you can do: …
=> fix: issue when switching providers when disconnecting [APE-1460]

docs/userguides/networks.md, src/ape/api/networks.py, src/ape/pytest/runners.py
[APE-618] #1297
fixes: #1297 
Fixes: APE-618
=> docs: document ProviderContextManager [APE-1481]

docs/userguides/clis.md, src/ape/cli/__init__.py, src/ape/cli/options.py
For some complex plugins, it'd be nice to be able to customize the shared CLI object context.
This allows that to happen via an `obj_type` kwarg in the decorator and a guide on how to subclass and use this new context.
=> feat: allow custom cli ctx obj types [APE-1483]

src/ape/api/providers.py, src/ape/logging.py, src/ape_geth/provider.py
we did good at sanitizing secrets everywhere in our own logs, however they were still in the web3.py loggers.
This PR add some detection + handling of URLs in ALL loggers from Ape and will automatically clear them.
Now, the logs show:
```
DEBUG: Making request HTTP. URI: https://eth-goerli.g.alchemy.com/[hidden] Method: eth_chainId
```
instead of the alchemy API key
=> fix: remove API secrets from web3.py loggers [APE-1486]

src/ape/api/__init__.py, src/ape/api/networks.py, src/ape_ethereum/__init__.py, src/ape_ethereum/ecosystem.py, tests/functional/test_network_api.py
realizing it was absolute pain to need to do anything with the upstream provider, even at the plugin level.
This aids that by adding properties and such to a new class for forked networks and a method for getting that context as well.
=> feat: upstream provider and forked network tools [APE-1485]

src/ape/managers/project/dependency.py, tests/conftest.py, tests/functional/test_dependencies.py
Currently, NPM dependencies require using a local node modules installs.
This PR will also check your home directory for the install.
Do everything with `Path.home()` that you did to `Path.cwd()`.
=> feat: support global NPM dependencies [APE-1490]

src/ape/api/projects.py, src/ape/exceptions.py, src/ape/utils/basemodel.py
fixes: #1222 
I ran into this as well and got kinda confused for a minute!
This PR does the following to address the problem:
1. If after compiling, a manifest is empty, the user gets another warning
2. If trying to access a missing contract from a manifest, the IndexError is adjusted to also suggest you may be missing compiler plugins.
The full output looks like this now:
```python
(ape310-pydanticv1) ➜  ape-safe git:(feat/safe-api) ✗ ape console                          
WARNING: Unprocessed plugin config(s): solidity. Plugins may not be installed yet or keys may be mis-spelled.
In [1]: project.dependencies["safe-contracts"]["1.3.0"]["GnosisSafe"]
WARNING: Compiled manifest produced no contract types! Are you missing compiler plugins?
ERROR: (ApeIndexError) Unable to find 'GnosisSafe' …
```
=> fix: more warning when missing compiler plugins [APE-1491]

src/ape/cli/arguments.py, tests/functional/test_cli.py
I was trying customize the callback for the non_existing_alias_argument  but it wouldnt let me so i had to redefine it
This will allow future apes to customize these options more.
kwargs, pop, check, missing tests
=> feat: allow alias-based argument click overrides [APE-1502]

src/ape/api/networks.py, tests/functional/test_network_api.py
fixes a mistake from https://github.com/ApeWorX/ape/pull/1714
=> fix: wrong network when accessing upstream provider [APE-1503]

docs/userguides/config.md
Added `.` in the plugins install command in the docs as it requires `.` for plugins to be installed from ape-config.yaml. 
Added a simple dot in the docs.
The plugins won't be installed if there is no `.`.
=> docs: fix plugin install command [APE-1519]

src/ape_plugins/utils.py, tests/functional/test_plugins.py
fixes: #1737
early return
Use an env with no plugins and run
```sh
ape plugins list
```
it should show:
```sh
No plugins installed.
```
=> fix: empty plugins sections repr [APE-1538]

src/ape/api/networks.py, src/ape/cli/commands.py, src/ape/managers/networks.py, src/ape_run/_cli.py, tests/integration/cli/projects/script/scripts/error_cli.py, tests/integration/cli/projects/script/scripts/error_main.py, tests/integration/cli/projects/script/scripts/error_no_def.py, tests/integration/cli/test_run.py
Run the interactive console under a Provider context
fixes: #581 
Before launching the console, run under a new provider context manager because the old one exits
run a script with `ape run -I ...` and evaluate `ape.chain.provider`
=> fix: run console under providercontext [APE-1529]

src/ape/managers/chain.py, tests/functional/test_block_container.py
This alters the behavior of `chain.blocks.poll_blocks()` to prevent an out of bounds `range()` call.
Fixes #1743
Could use a sanity check to make sure I'm not logically skipping a block with the change.
Do docs need to be updated?  I believe this is just a bugfix not a behavior change.
=> fix: do not fetch history if there is no history in poll_blocks()

src/ape/api/providers.py, tests/functional/test_provider.py
fix: added checks to remove `,` from the RPC URI endpoint
Added a check to see if `,` is present in the URL string or not.
fixes: #1752
```py
if "," in rest[0]:
rest[0] = rest[0].strip(",")
```
Trust me bro.
=> fix: added checks to remove `,` from the RPC URI endpoint [APE-1582]

src/ape/managers/project/manager.py, src/ape_accounts/accounts.py, src/ape_pm/compiler.py, tests/conftest.py, tests/functional/conftest.py, tests/functional/test_accounts.py
In ape-safe, I was prompted `"Leave unlocked?"` over and over again and it was because signers were re-checked and reloaded and thus lost the "yes" to my prompt... So it is would be nice if Ape remembered I said "yes" to leave the account unlocked.
Only create the `KeyfileAccount` class once.
see second test. The first one was me trying to figure out but is still a nice test
=> fix: issue where `KeyfileAccount` would not stay unlocked [APE-1586]

src/ape/api/accounts.py, src/ape_accounts/accounts.py, src/ape_test/accounts.py, tests/functional/test_accounts.py
Refactor the definition of sign_message to accept Any. Signers implementing this class can raise when they receive a message type they can't handle.
Account plugins would each individual handle msg objects by type, including how they might display information from them for user feedback in terms of signing. This will improve UX because now we can display the text of a string message to sign (useful for displaying SIWE [EIP-4361](https://eips.ethereum.org/EIPS/eip-4361) authorizations), the complete object body and header for EIP-712 structured messages, and other future types of messages that might become necessary to support within Ape (EIP-4337?)
fixes: APE-1103
Change type signature of sign_message function, and update implementors to match the new definition.
Run existing test suite
=> refactor!: accept any msg type via `AccountAPI.sign_message` [APE-1305]

setup.py, src/ape/api/providers.py, src/ape/contracts/base.py, src/ape/managers/chain.py, src/ape/types/__init__.py, tests/functional/conftest.py, tests/functional/test_block_container.py, tests/functional/test_contract_event.py
Implemented new poll_blocks and poll_events methods in the ProviderAPI
fixes: #1669 
Used the new Web3.py filter objects for polling of new blocks and events. The event polling uses the block polling for confirmations so as to not repeat that logic in both functions.
=> feat!: rewrite poll methods with new API [APE-1411]

docs/userguides/clis.md, src/ape/_cli.py, src/ape/api/__init__.py, src/ape/api/networks.py, src/ape/api/projects.py, src/ape/api/providers.py, src/ape/cli/__init__.py, src/ape/cli/arguments.py, src/ape/cli/choices.py, src/ape/cli/options.py, src/ape/cli/utils.py, src/ape/contracts/base.py, src/ape/exceptions.py, src/ape/logging.py, src/ape/managers/chain.py, src/ape/managers/converters.py, src/ape/managers/project/dependency.py, src/ape/managers/project/manager.py, src/ape/types/trace.py, src/ape_compile/__init__.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_geth/provider.py, src/ape_test/provider.py, tests/functional/conversion/test_ether.py, tests/functional/test_cli.py, tests/functional/test_compilers.py, tests/functional/test_contract_instance.py, tests/functional/test_exceptions.py, tests/functional/test_provider.py
Fixes: APE-1120 (make `compilers_with_missing_ext` be a Set instead of a List)
Fixes: APE-578 (Move ContractError as base class to TransactionError)
Fixes: APE-770 (Remove ape.utils.Aborts - should now use ape.exceptions.Abort)
Fixes: APE-772 (Renamed get_user_selected_account to select_account)
Fixes: APE-822 (Rename ContractError to ContractDataError and other error usage changes)
Fixes: APE-830 (Remove deprecated field `branch` from the Github dependency type. Use `ref` now)
Fixes: APE-685 (Remove ListTupleConverter)
Fixes: APE-1205 (Use block_id instead of block_identified and include in official API, same with state).
Fixes: APE-876 (Delete some methods for gas tracking from the ReportManager - plugins should be using the test runner reference now, same as coverage)
Fixes: APE-1104 …
=> refactor!: a collection of breaking changes [APE-1417]

src/ape/types/signatures.py, tests/functional/test_types.py
In ape-safe, we are sometimes just givens the bytes signatures from the API and stuff... would be nice to be able to get it to the right type. So this PR adds classmethods to do exactly that.
parse bytes back to a message sig
=> feat: `from_rsv()` and `from_vrs()` Signature class methods [APE-1600]

docs/userguides/clis.md, docs/userguides/networks.md, docs/userguides/scripts.md, src/ape/api/networks.py, src/ape/api/providers.py, src/ape/cli/__init__.py, src/ape/cli/choices.py, src/ape/cli/commands.py, src/ape/cli/options.py, src/ape/managers/networks.py, src/ape_cache/_cli.py, src/ape_console/_cli.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, src/ape_geth/provider.py, src/ape_geth/query.py, src/ape_networks/_cli.py, src/ape_run/_cli.py, tests/conftest.py, tests/functional/geth/test_provider.py, tests/functional/test_cli.py, tests/functional/test_ecosystem.py, tests/functional/test_network_manager.py, tests/functional/test_provider.py, tests/integration/cli/conftest.py, tests/integration/cli/test_cache.py, tests/integration/cli/test_networks.py, tests/integration/cli/test_run.py
* `NetworkBoundCommand` renamed to `ConnectedProviderCommand` and no longer requires explicitly setting the network option (base wasn't removed and warns a DeprecatedWarning with instructions how to migrate and it has the legacy behavior).
* Both `@network_option` and `ConnectedProviderCommand` allow key-args in your callback for `ecosystem`, `network,` and `provider` for each instance respectively. You don't need to use any of them either (yay, can delete all the `_ = network  # needed for NetworkBoundCommand` lines).
* Move another class to `ape_ethereum` called `EthereumNodeProvider`.. It is exactly what was in ape-geth, however ape-geth still sorta re-exports because `EthereumNodeProvider` is the default class for custom networks and such and just sounds better and in some cases may …
=> feat!: network customization and tooling improvements

src/ape/api/providers.py, src/ape/api/query.py, src/ape/api/transactions.py, src/ape/managers/config.py, src/ape/managers/project/dependency.py, src/ape/types/__init__.py, src/ape/types/coverage.py, src/ape_compile/__init__.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/transactions.py, src/ape_plugins/utils.py
Pydantic recommends doing this and even includes it in their migration tool, as pointed out by @NotPeopling2day and I agree it is more readable.
However - it is a little problematic imo because their validator decorators already return class methods, so now I am getting errors in Pycharm warning me the decorator types dont match, kinda opposite of what Pydantic warns about in their docs here: 
https://docs.pydantic.dev/latest/concepts/validators/#field-validators
```
@field_validators are "class methods", so the first argument value they receive is the UserModel class, not an instance of UserModel. We recommend you use the @classmethod decorator on them below the @field_validator decorator to get proper type checking.
```
nonetheless opting to use them.
=> chore: add class method decorator to all validators [APE-1606]

src/ape/api/config.py, src/ape/managers/networks.py, src/ape/managers/project/manager.py, src/ape/utils/basemodel.py, tests/functional/test_config.py, tests/functional/test_project.py, tests/integration/cli/projects/bad-contracts/contracts/file_without_ext
Noticed the bug in ape-addressbook
also adds empty ext to list of ignored exts in compiling
* Fixes an issue where dependencies sources being the project sources and causing compiling to take literally years for regular project..
=> fix: issue getting items from pydantic extras in PluginConfig [APE-1607]

setup.py
Update setup.py - removal of urllib3 module version requirement
fixes: #1741
Updated `setup.py` by removal of `urllib3` module version upper boundary requirement
=> feat: update setup.py, removal of urllib3 module version upper boundary requirement [APE-1610]

setup.py, src/ape/api/accounts.py, src/ape/cli/options.py, src/ape/types/address.py, src/ape_accounts/accounts.py, src/ape_ethereum/provider.py, src/ape_test/accounts.py, src/ape_test/provider.py, tests/functional/test_cli.py
realized from more testing that couldnt use network option with other options.
adjusted our tests
=> fix: unreleased regression from using network_option with other options [APE-1612]

docs/conf.py, docs/methoddocs/contracts.md, docs/methoddocs/types.md, docs/userguides/accounts.md, docs/userguides/clis.md, docs/userguides/networks.md, docs/userguides/testing.md, setup.py, src/ape/api/accounts.py, src/ape/api/address.py, src/ape/api/compiler.py, src/ape/api/config.py, src/ape/api/convert.py, src/ape/api/explorers.py, src/ape/api/networks.py, src/ape/api/providers.py, src/ape/cli/options.py, src/ape/contracts/base.py, src/ape/managers/accounts.py, src/ape/managers/chain.py, src/ape/managers/compilers.py, src/ape/managers/converters.py, src/ape/managers/project/manager.py, src/ape/managers/project/types.py, src/ape/types/address.py, src/ape/types/signatures.py, src/ape_ethereum/ecosystem.py, src/ape_geth/provider.py, src/ape_networks/_cli.py, tests/functional/test_config.py
the docs and other random chore-y stuff needed attention from all the changes, that's all
* Fix issue where commands using `@network_option` looked like partials in the generated docs
* Fix issue where AddressType and RawAddress were not in the docs anymore
* Fix tons of param types in the docs
* More sequence usage
* Grammar stuff
* Issue where Ape was randomly compiling stuff when building the docs
* Added a test for ConfigEnum since i wasnt sure it even worked, not sure it is being used, so wanted to be sure.
* Fixes all other WARNINGS from sphinx, such as missing classes and stuff
* Adjusts the env var passphrase to barely mention the kwarg and largely focus on the env var right away to get users doing the right thing more often
* Adds a few missing doc strs
Note i anticipate there …
=> docs: fix a myriad of docs issues for 0.7

src/ape_plugins/_cli.py, src/ape_plugins/utils.py, tests/functional/test_plugins.py
the pip freeze functionality wasnt tracking versions and there was some weird logic for relaying info that was based on that.
1. fix version detection
2. fix conditional leading to warning
3. add tests
`ape plugins install ens --upgrade`
=> fix: issue where user got wrong warnings when updating plugins

src/ape_console/_cli.py, tests/functional/test_console.py
**Background**
* You can customize your ape console by including `ape_console_extras.py` in your .ape dir that takes items from the ape namespace and returns a modified one
* Ape's `console` is launched at several points in the app, like during testing with `-I` or during scripts with `-I`... each case adjusts the namespace it passes to the console, which is great. if locally you have something with the same name as globally, it makes sense the local one is preferred when using the console in this case.
* HOWEVER, it is not really something to ever expect `ape_console_extras` from handling local random items in the namespace, does that make sense? Like `ape_console_extras.py` is only reasonable to expect items from Ape's global namespace, like if you have a local var called `accounts` in …
=> fix: issue where `ape_console_extras` file loaded with wrong namespace

src/ape/api/transactions.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, src/ape_test/provider.py, tests/functional/conftest.py, tests/functional/geth/test_provider.py, tests/functional/test_provider.py
after replaying a tx to try and get a proper web3.py extracted error, if that don't work, we were not erroring.
if get to a certain point, call `receipt.raise_for_status()`
trust me lol...
i dont know how the chain gets in this condition but it seems like it happens on foundry in a forked network when using an impersonated account, or at least that is when i have seen it.
=> fix: issue where would not get a transaction error when expected

src/ape/api/networks.py, src/ape/cli/choices.py, src/ape/managers/networks.py, src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py, tests/functional/test_network_api.py, tests/functional/test_network_manager.py, tests/integration/cli/test_run.py
fixes: #1761
Also, allows adhoc IPC connection like this:
```sh
ape console --network "ethereum:local:$HOME/.ape/ethereum/local/geth/geth.ipc"
ape console --network "$HOME/.ape/ethereum/local/geth/geth.ipc"
```
just adding more handling and checking
I did add some func tests
but also run the console commands i placed above
yo need to start an anvil or geth first, or any node i guess.
=> feat: allow adhoc IPC connect and show a better error for unsupported schemes

src/ape/api/providers.py, src/ape/cli/choices.py, tests/functional/geth/test_provider.py, tests/functional/test_cli.py, tests/functional/test_provider.py
fixes: #1762
pt 1: If the provider uses a custom network, return its uri as the name instead of the provider name in the choice so it knows to connect this way again.
pt 2: if the provider section of the choice-str is missing and the network says to use custom, raise a nicer error that should hopefully help in many ways!
I also added a load of tests
test it out of course!
i use ape console and connection to random connection strs, ipcs, whatever, sometimes specifying networks and sometimes not
=> fix: network choice parsing and re-parsing fix

src/ape/managers/converters.py, tests/functional/conversion/test_address.py
when you need int addresses in ape, you can't use account APIs I noticed.
add another converter for address api to int
=> feat: Allow converting AddressAPI to address-int

src/ape/types/signatures.py, tests/functional/test_types.py
mypy was failing checks in ape-safe because of this, it wasnt honoring the fact that it was coming from a base class. now it does!
use `from typing import Self`
basically same as doing the big long TypeVar dance but so much simpler for this exact use-case.
mypy works now on my branch in ape-safe
=> fix: typing in method `from_rvs()` and `from_vrs()` in signature classes

src/ape/api/accounts.py, tests/functional/test_accounts.py
We were unable to transfer a value of 0 without doing some hack.
note: use-case for this is replacing a tx with a noop one.
check for None instead of truthy.
transfer 0 somewhere
=> fix: issue preventing transferring a value of `0`.

src/ape/managers/accounts.py, tests/functional/test_accounts.py
issue 1: __getitem__ is supposed to raise IndexError when it fails but i was getting conversion errors.
issue 2: I accidentally did `ape.accounts["safe"]` instead of `ape.accounts.containers["safe"]` once and the error was confusing for a second and also was not an index error.
issue 3: when ape-ens or conversion plugin not installed, the index error should hint at that.
catch and handle `ConversionError` in account manager `__getitem__` implementation.
```python
ape.accounts["BOBO"]
ape.accounts["antazoey.eth"]
```
=> fix: use helpful `IndexError` in `AccountManager.__getitem__()`  when conversion error occurs

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py, tests/functional/test_provider.py
I noticed for all the dev providers, when calling a method that didnt exist (such as debug_traceCall in non-updated hardhat nodes), it would **not** fail with `NotImplemented` error. We have some other logic in trace mgmt that depends on these errors being raised so this PR fixes it here in core.
I figured this was shareable, small enough, and generic enough to just put in core.
I noticed this problem when trying to repro https://github.com/ApeWorX/ape/issues/1777 ; it _did_ cause some issues for my in my coverage , but not the same as the ones from the issue so im not sure how related it is.
=> fix: issue where NotImplmeneted error was not raised

src/ape/pytest/runners.py, tests/integration/cli/test_test.py
fixes: #1801
So I never could reproduce the bug...
However, I noticed in the screenshot that locals successfully appear in the repr output.
I know the repr output and the locals namespaces are using the same data, so i went to look and I noticed the repr output logic actually uses the last frame whereas the local namespaces was using the first frame. Perhaps in Wavey's env, this made a huge difference...  So I changed them to match. We have to wait on @wavey0x to confirm if this fixes the issue though, as I am not sure.
I also noticed a test was missing for this feature. We had a test in the `ape run` version of the same feature but not in the `ape test` version, so I added a test. HOWEVER, the test passes on main branch as well as this branch (as like I said, never able to actually …
=> fix: use last frame to get locals when launching interactive test console

src/ape/api/accounts.py, tests/functional/test_accounts.py
fixes: #1797
Type-checking. Unfortunately, this required a local import. However, it is worth it imo... the ramifications of the type being wrong are too big NOT to type-check here, as we have seen with the issue.
So more info: the problem is the a ContractInstance has its own `__call__` implementation and that also makes a txn, so it was like kinda "working" by doing that except itd get a SignatureError and ya it was jus weird... forceful type checking is the way.
try to deploy an instance
=> fix: ContractInstance deploy error message

src/ape/managers/config.py, src/ape/managers/project/dependency.py, src/ape_pm/_cli.py, tests/functional/test_config.py, tests/functional/test_dependencies.py
fixes: #1800 
Make ref or version required, at least one or other
simply make `ref:` required so the error is correct.
=> fix: issues with GitHub dependencies when not specifying `ref:` or `version:`

setup.py
Updates version requirements for urllib3 to allow 2.0.
Some old slow libs are slow to adopt new versions of urllib3 for whatever reason.
I explicitly installed 2.0 and ran the test suite against it, no issues.
=> refactor: loosen up the urllib3 version requirement

src/ape_geth/provider.py, tests/functional/geth/test_provider.py
i think this would have prevented some confusion regarding a convo yesterday!
Thanks!
=> docs: improve error message when geth binary is not found

src/ape_ethereum/ecosystem.py, tests/functional/test_ecosystem.py
=> fix: decoding issues that affect tracing features such as coverage

src/ape/api/networks.py, src/ape/api/projects.py, src/ape/api/transactions.py, src/ape/types/__init__.py, src/ape/utils/__init__.py, src/ape/utils/basemodel.py, src/ape_cache/query.py
This should also be a performance gain.
But more importantly, it lessens the chance of problems occurring from this because now we are only using `__getattr__` overloading where extras are.
* Make new mixin
* Use new mixin in all spots that implement `__ape_attributes_extras__`
=> refactor: move `__getattr__` overload to new mixin and only use where needed

src/ape/managers/config.py, tests/functional/test_config.py
Ape no longer works when specifying a custom contracts folder because it was using unset ProjectManager to figure something out. I am not sure why this is suddenly a problem.
Rely on self.PROJECT_FOLDER rather than reaching out to the `project_manager`.
type `ape` in a project that specifies a custom contracts folder.
e.g. https://github.com/pcaversaccio/snekmate
=> fix: issue where Ape no longer worked AT ALL when using custom contracts folder

src/ape/utils/basemodel.py, src/ape_ethereum/provider.py, tests/functional/test_provider.py
Working around this bug: https://github.com/ethereum/web3.py/issues/3184
(update: not sure it is really a bug, as it only happens in anvil and hardhat and not real nodes.. perhaps they are the ones that are bugged? either way, this change is good still as it allows it to work on all nodes, even geth still... else, maybe the bug is that web3.py is passing null when it should be omitting the value entirely... im not sure!)
fee history was failing always in web3.py with some recent changes.
Default parameter was not handled correctly.
specify default parameter so that the request works.
=> fix: issue with fee history for some nodes

src/ape/api/projects.py, tests/functional/test_dependencies.py
dependencies let you specify `contracts_folder` as a key but also offer a `config_override`.
however, when putting `contracts_folder` in `config_override` (which should be valid because `contracts_folder` is also a project's top-level config item), it fails with `got multiple args for keyword 'contracts_folder'`, so this fixes that.
check if `contracts_folder` is in config override. if no, then put the one you were gonna put else, leave it be.
```yaml
dependencies:
- name: solmate
github: transmissions11/solmate
ref: "v6"
#contracts_folder: src
config_override:
contracts_folder: src
compile:
exclude: 
- ./test/utils/*
```
run `ape pm compile`
=> fix: bug where couldn't put `contracts_folder` in dependency `config_override` config

src/ape/managers/compilers.py, src/ape/managers/project/types.py, tests/conftest.py, tests/functional/conftest.py, tests/functional/test_project.py
* fix: issue where contract type collision occurred from deleted files because of a bad cache
* fix: issue where empty contracts endlessly compiled
fixes: #1780 
only add trailing \n if not empty
compile an empty contract more than once and see what happens
=> fix: contract type collision issues from deleted files and empty file issues

src/ape/managers/config.py, tests/functional/test_config.py
I noticed this user was using `contracts-folder` with a hyphen in their config, which should be fine I think.
if `contracts_folder` isn't there, try `contracts-folder`
=> feat: allow contracts-folder (with hyphen) in ape-config.yaml

docs/conf.py, docs/methoddocs/api.md, docs/methoddocs/contracts.md, docs/methoddocs/managers.md
These are related to pydantic integration are not meant to be public.
I found a way to share the code by setting a default value in `conf.py`
yay deleting code!
=> docs: exclude `model_` prefixed methods appearing in docs

src/ape_ethereum/transactions.py, tests/functional/test_transaction.py
A developer experience enhancement.
When doing a transaction with Ape, if you forget `sender` parameter you get an unhelpful error message.
Adding a help tip for `SignatureError` error message to hint to the user what's probably wrong:
```
raise SignatureError("The transaction is not signed. Did you forget to add sender argument to the transaction function call?")
```
Better error message.
- [-] New test cases have been added  (no functional changes)
=> feat: Adjust `SignatureError` with helpful tip on including `sender=` tx kwarg

src/ape/api/projects.py, tests/functional/test_dependencies.py
Right now, if you have a dependency configured wrong and it produces no sources, you get absolutely no warning or error in Ape, leading to much greater confusion and messed up state down the line.
This PR makes dependency installation completely fail in that case.
I think that makes the most sense because no matter what, you are going to be forced to re-install to fix it.
It is simpler to just not cache then and also just throw an exception.
At the very least, some sort of warning must be shown to the user because right now you just get a "SUCCESS" which even threw me off on the issue!
fixes: #1817 
Raise a `ProjectError` with a helpful tip on using `config_override` when a dependency is completely source-less after installation. Typically, you just need to set a contracts_folder or …
=> fix: raise error when installing a dependency results in zero sources

src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, src/ape_test/accounts.py, tests/functional/test_transaction.py
https://eips.ethereum.org/EIPS/eip-2930
It says it is the same as the legacy types, so the fixes here make that happen.
* Issue where gasPrice was not automatically set during `prepare_transaction` for Access-list transactions
* Issue where Access list transactions failed when you didn't set a `max_fee`, which doesn't make sense because they ain't EIP-1559 transactions
* Issue where signing a tx, access list was in `snake_case` instead of `camelCase`
=> fix: issue where could not create an access-list transaction

src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, src/ape_test/accounts.py, tests/functional/test_ecosystem.py, tests/functional/test_transaction.py
* fix: issue where didnt create access list tx by default when excluding type 2 and including access list stuff
* feat: allow more alias-keys in create_transaction Ethereum method
* fix: issue where could not init a storage key of bytes type
* issue where if hacked in a raw access list using bytes type, serializing the tx would fail
**NOTE**: This is the issue the user was seeing. However, I could never actually hit this state myself without
doing a weird hack. Nonetheless, am confident this issue is even more impossible to happen now in Ape.
* fix: issue where `prepare_transaction` did not set `gasPrice` for AccessLisTransaction (type 1)
=> fix: various bugs regarding `AccessList` usage in transactions (type 1 and 2)

docs/userguides/networks.md, src/ape/cli/choices.py, tests/functional/test_cli.py
including how to configure explorer URL before someone opens issues about it being missing from the docs.
Refers to this com/ApeWorX/ape-etherscan/pull/112
=> docs: document explorer URL in custom networks

.github/workflows/test.yaml, docs/userguides/networks.md, src/ape/api/networks.py, src/ape/api/providers.py, src/ape/managers/networks.py, src/ape/utils/basemodel.py, src/ape_ethereum/provider.py, src/ape_networks/__init__.py, tests/conftest.py, tests/functional/geth/test_contract.py, tests/functional/test_ecosystem.py, tests/functional/test_network_api.py, tests/functional/test_network_manager.py, tests/functional/test_transaction.py, tests/integration/cli/projects/geth/ape-config.yaml
The custom networks for new ecosystems kinda made no sense, so this PR fixes that.
Before:
```yaml
networks:
custom:
- name: shibarium-mainnet
ecosystem: polygon
chain_id: 109
geth:
polygon:
shibarium-mainnet:
uri: https://www.shibrpc.com
```
used via `--network polygon:shibarium-mainnet:geth` which makes less sense.
After:
```yaml
networks:
custom:
- name: mainnet
ecosystem: shibarium
base_ecosystem_plugin: polygon  # Closest base class.
chain_id: 109
geth:
shibarium:
mainnet:
uri: https://www.shibrpc.com
```
used via `--network shibarium:mainnet:geth` which makes more sense.
* Change `ecosystem` to be allowed to be any str and advise users to put custom names here when it makes sense
* Add new config option `base_ecosystem_plugin` to refer to the base-class to use.
* Fix issues where …
=> fix: custom ecosystem work and custom network fixes

src/ape_ethereum/ecosystem.py, tests/functional/test_network_api.py
fix: issue where forked networks config didnt have the expected defaults
fix: now, if you reference a config for a non-existent network, youll get an empty network config instead of an attribute error 
fix: issue where custom network configs were not parsed and remained as dictionaries.
=> fix: issues with custom and forked network config parsing

src/ape/utils/abi.py, tests/functional/test_contract_instance.py
fixes: #1451 
Fixes: APE-979
handle different types in `Struct.__eq__`
pick your poison:
```python
expected_dict = {"a": owner, "b": tx_hash}
assert actual == expected_dict
expected_tuple = (owner, tx_hash)
assert actual == expected_tuple
expected_list = [owner, tx_hash]
assert actual == expected_list
expected_struct = contract_instance.getStruct()
assert actual == expected_struct
```
=> feat: allow comparing Struct types with sequence types

docs/userguides/contracts.md, src/ape/contracts/base.py, tests/functional/test_contract_instance.py
Adds convenience method/props `selector_identifiers` and `identifier_lookup` to `ContractInstance` for easy selector/identifier lookups.
fixes: #1682
Pass through methods to the underlying `ContractType`
See tests?
=> feat: add convenience methods for selector identifiers to ContractInstance

src/ape_ethereum/ecosystem.py, tests/functional/test_network_api.py
this helps Arbitrum utilize the new base class and others who may change the default utilize the base class
```python
class ArbitrumConfig(BaseEthereumConfig):
DEFAULT_TRANSACTION_TYPE: ClassVar[int] = EthTransactionType.STATIC.value
DEFAULT_LOCAL_GAS_LIMIT: ClassVar[GasLimit] = LOCAL_GAS_LIMIT
mainnet: NetworkConfig = _create_config()
goerli: NetworkConfig = _create_config()
sepolia: NetworkConfig = _create_config()
```
see Arby PR: https://github.com/ApeWorX/ape-arbitrum/pull/27
classvar default
=> fix: ecosystem-level default in config for local gas limit

src/ape_ethereum/transactions.py, tests/functional/test_transaction.py
For some reason, storageKeys when not bytes were no longer serializing to JSON correctly.
fixes: #1881 
The fix was change the type from `Union[HexBytes, bytes, int, str]` to just `HexBytes`.
This way, the validators run correctly and it actually works for int, str etc because it turns it to bytes first.
As a bonus, i changed address to be `AddressType` to fix similar, unreported issues there.
=> fix: issue when using hex-str for accessList storage keys

src/ape/managers/networks.py, src/ape/utils/misc.py, tests/functional/utils/test_misc.py
Adds `block_number` argument to `network.fork()`, including negative behind numbers.
fixes: #1740
When the kwarg is provided, it will update the expected config structure for the fork provider with the given block number
```python
from ape import chain, networks
from ape.cli import ConnectedProviderCommand
import click
@click.command(cls=ConnectedProviderCommand)
def cli():
live_block = chain.provider.get_block("latest")
with networks.fork("foundry", block_number=18569420):
block = chain.provider.get_block("latest")
assert block.number == 18569420
with networks.fork("foundry", block_number=-100):
block = chain.provider.get_block("latest")
assert block.number == live_block.number - 100
```
=> feat: adds block_number arg to network.fork()

src/ape/managers/networks.py, tests/functional/conftest.py, tests/functional/test_network_manager.py
The error when trying to fork a non-forkable network was not quite good enough for me, so I fixed it.
Also, adds missing tests for `netowork.fork` context stuff.
Catch the network error and raise a different one with a more custom message for the `.fork()` method use-case.
connect to `local` and then do:
```python
with networks.fork():
...
```
it should fail something like 
```
NetworkError: Unable to fork network local
```
=> fix: issue when forking past genesis

docs/userguides/transactions.md, src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py, tests/functional/test_provider.py
now when using type=1, access lists are automatically prepared on the tx
**question**: should we automatically set access list on type=2? I am too afraid to make that change I think but there isnt really a good way to do in Ape otherwise
=> feat: Use `eth_createAccessList` RPC in type=1 prepared transaction

src/ape/cli/arguments.py, src/ape/cli/choices.py, src/ape/cli/commands.py, src/ape/cli/options.py
Replace top-level imports with ManagerAccessMixin to prevent circular imports in account plugins.
=> fix: circular import issues from accounts plugins

pyproject.toml, setup.py, tests/conftest.py, tests/integration/cli/test_plugins.py
- Adds pytest-timeout to prevent some failing tests from running forever.
- Skips plugin installation integration tests because they will often re-install ape (and dependencies), which means the following tests run against an unwanted versions of packages.
@antazoey we spoke about the latter a bit the other day.  I think I narrowed the behavior down to these tests.  I'm not entirely sure if it's only local test runs or if it may affect CI as well.  Slight suspicion it might be related to my local `src/ape/version.py` file but not sure.  I'd be happy skipping on local only if we'd prefer.
=> test: adds timeout and skips some breaking integration tests

src/ape/managers/converters.py, tests/functional/test_contract_instance.py, tests/functional/test_ecosystem.py
Tuple types were not working for arrays; it'd fail
=> fix: issue where could not pass a tuple for an array

src/ape_ethereum/ecosystem.py, tests/functional/test_ecosystem.py
fixes a bug from Discord when if you have a func return an array of a single struct, it would be all funky and not at all like if 2 structs for example.
Also fixes the issue where arrays of structs were tuples unlike arrays of addresses or other types, which were lists. now arrays are always lists.
Squeeze in some handling without breaking anything.
=> fix: array of structs or tuples when only 1 element would be weird

src/ape/logging.py, src/ape_accounts/_cli.py, tests/integration/cli/test_accounts.py
3rd party lib revealed a bad mnemonic (which is likely very close to the real one).
Remove for security reasons.
=> fix: remove mnemonic from error message

src/ape/api/accounts.py, src/ape/contracts/base.py, src/ape/exceptions.py, tests/functional/test_accounts.py, tests/functional/test_config.py, tests/functional/test_contract_container.py, tests/functional/test_contracts_cache.py
fixes: #1904
1. Check for no deploy bytecode before deploy
2. if not found, raise custom exception. the custom exception helps share the code between account deploy and container deploy
=> fix: raise error when attempting to deploy a contract without init-code

src/ape/api/networks.py, src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
I could not fetch blocks before the consensus changed.
`get_block("earliest")` would be fail because the middleware was only added via a check from the latest block.
(could have swore i already fixed this bug before...)
fixes: https://github.com/ApeWorX/ape-foundry/issues/78
additionally fixes a weird race condition in network context
=> fix: issue with networks that started PoA but currently are not

.pre-commit-config.yaml, setup.py, src/ape/types/__init__.py, src/ape/utils/validators.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, tests/functional/test_config.py, tests/functional/test_provider.py
noticed last merge to main failed,
realized the test was not accurately testing something...
ensure deployments set in config so we know we are reading the config deployment, which will always be at index 0
test was flakey because sometimes the deploy was at index 0 with no config deployments
this test got messed up like last PR when we could no longer deploy empties.
=> test: fix test causing flaky fail

src/ape/managers/networks.py, src/ape/utils/misc.py, src/ape_geth/provider.py, tests/functional/geth/test_provider.py
In ape-geth, if was given a provdider-settings URI, use that no matter what
Also, when generating config defaults, if something is running on the local, still use that as the default just in case.
Then, finally, if the default is available, use that instead of again checking for random public
fixes: #1917
=> fix: provider settings RPC was not being used when it was the default

src/ape/_cli.py, src/ape/plugins/__init__.py, src/ape/plugins/_utils.py, src/ape_plugins/_cli.py, tests/functional/geth/test_provider.py, tests/functional/test_plugins.py, tests/integration/cli/test_misc.py
refactor: move some plugin utils to core for sharing purposes
perf: make `ape plugins list`  faster by only using pip-freeze subprocess checking for modifications, not list
feat: organize ape help by plugins (made possibly by the above too)
fixes: #337 
so really, I wanted the first items but they afforded the 3rd which we had an issue for.
this is roughly the same performance, but probably a smidge slower
```sh
ape --help
```
this is now faster!
```sh
ape plugins list
```
=> feat: CLI help plugin organization

README.md
Updates some smaller things in the README and removes many sections and replaces their idea with links to the user-guides from he Quickstart section.
One of the small changes was renaming Playing with Ape to Quickstart, as many docs-viewers are looking for this.
Additionally:
* removes `:` from headers
* Avoids words like `just`
* Adds spacing for multi-line commands
=> docs: revise readme and rely more on user-guides

.github/workflows/test.yaml, tests/functional/geth/test_contract.py, tests/functional/test_history.py
Just making sure that the wait-for-tx issue was actually fixed in the latest web3.py
=> test: check that web3.py did fix geth

docs/userguides/contracts.md, docs/userguides/scripts.md
Fixes a couple of errors in the docs.
=> fix(docs): minor docs fixes

src/ape/api/config.py, src/ape/api/networks.py, src/ape/api/projects.py, src/ape/api/transactions.py, src/ape/contracts/base.py, src/ape/managers/base.py, src/ape/managers/compilers.py, src/ape/managers/networks.py, src/ape/managers/project/manager.py, src/ape/plugins/__init__.py, src/ape/utils/basemodel.py, src/ape_ethereum/ecosystem.py, tests/functional/test_project.py
perf: evaluates extras lazily
perf: short-circuit during IPython canary check
the combo of these makes it not compile at weird times! people kept saying ape always compiles so much, I think this was the cause.
watch this:
go to ape main branch in an uncompiled projet and launch a console:
```sh
ape console
[1] project
```
it immediately starts compiling the project :[ but why doh
* first i tried __repr__ in project manager, didnt matter though :/ but it seemed like it helped kinda
* then i added the lazy eval for the extras. this is great. now, itll calculate the extras if you ask it to making ape seem a lot faster
* finally, what the heck ipython was triggering stuff in Ape it shouldnt have, like compiling, via this canary attribute: …
=> perf: lazy model extras and IPython canary short-circuitry

src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, tests/functional/test_ecosystem.py, tests/functional/test_provider.py, tests/functional/test_transaction.py
This allows us to decode transactions and receipts from EIP-4844
There are still some issues however that will require updating eth-account and other eth-prefixed python packages.
For example, the hash calculation fails because of an unknown type (3).
=> feat: EIP-4844 (type 3) transactions initial support

docs/userguides/compile.md, src/ape/api/config.py, src/ape/managers/compilers.py, src/ape/managers/config.py, src/ape/managers/project/manager.py, src/ape_compile/__init__.py, tests/conftest.py, tests/functional/test_config.py
Adds the `cache_folder` config var for ape_compile. Compiler plugins will leverage this for various temporary build-storage (mostly dependency sources).
Ref: #1335
=> feat: adds compiler_cache_folder config var

src/ape/__init__.py
Add signal handling for applications that use Ape using threads, this could be APIs, streamlit applications and [prefect flows](https://docs.prefect.io/latest/concepts/flows/)
fixes: #1164 
Checked if we are running in the main thread or not, if we are signaling is applied as usual, otherwise it won't be applied. This means more traceback for threaded applications but it will work.
Previously `ape` fails at import time due to signalling failing to be achieved on a child thread.
Running the following script without the change will result in an error `ValueError: signal only works in main thread of the main interpreter` :
```python
import threading
def import_ape():
import ape
thread = threading.Thread(target=import_ape)
thread.start()
thread.join()
print("Done")
```
Once the change is …
=> fix: threading applications using ape

src/ape/managers/converters.py, src/ape_ethereum/ecosystem.py, tests/functional/conversion/test_decimal.py
Ape has no converter to handle Vyper's `decimal` type, which is translated to the `fixed168x10` ABI type. Testing a contract function with a `decimal` type argument will fail with a `ConversionError`.
- Add `Decimal` as the native Python type for ABI types with "fixed" in the name.
- Add a converter to support using string-formatted float values instead of requiring a strictly `Decimal` value. This converter will translate a "1.0" string in-place. Did not add a `float` converter, because floating-point accuracy will cause subtle errors. 
- Added simple string -> Decimal converter test.
=> feat: add conversion for fixed ABI types

src/ape/managers/compilers.py
Adds missing (?) kwargs to `CompilerManager.flatten_contract()` to match `CompilerAPI.flatten_contract()`.
=> fix: allow kwargs to flatten_contract()

src/ape/api/accounts.py, src/ape/types/signatures.py, src/ape_accounts/accounts.py, src/ape_test/accounts.py, tests/functional/test_accounts.py
Add a new path to `AccountAPI` called `.sign_raw_msghash` that allows signing a raw 32 byte hash without treating it as an EIP191 `SignableMessage` type
fixes: #1962
I needed this for work I was doing on ape safe, but it is a really dangerous thing to allow, so I added a warning message and additionally disallowed autosigning for it. For `AccountAPI.recover_message` I added an additional kwarg `recover_using_eip191=True` that can be set false if you want to opt-in for that behavior for verifying a signature.
Try the experience locally, I have added tests for it. Ultimately, when installled alongside the delegate feature for ape safe (https://github.com/ApeWorX/ape-safe/pull/41) you should now be able to use it to directly sign something with the API
=> feat(AccountAPI): sign raw hash32

src/ape_test/provider.py, tests/functional/test_provider.py
fixes: #1968
does the same as https://github.com/ApeWorX/ape-foundry/pull/59/files but for ape-test
thought: maybe need to squeeze this into the api class to keep things uniform, but i implemented the same as ape-foundry's just in case.
connect to ape-test provider which uses eth-tester, and then you can do this
```python
from ape import chain
chain.provider.automine = True
...
chain.provider.automine = False
```
by default, it is on.
=> test: auto mine functionality to eth-tester

src/ape_ethereum/multicall/handlers.py, tests/functional/test_multicall.py
`allowFailure` was broken in multicall when a call actually failed
```
AttributeError: 'list' object has no attribute 'returnData'
```
- massively simplified the handler by moving to using multicall 3 only. this allows us to have one handler for the result value.
- fixed handling of partially failed calls. such calls would return `None`.
- allow partial failures by default, which is probably what the user want when reading a lot of data.
- (edit: reverted this one) rename `allowFailure` to `allow_failure` when adding individual calls.
```python
$ ape console --network blast:mainnet:geth
In [1]: pos_manager = Contract('0x434575EaEa081b735C985FA9bf63CD7b87e227F9')
In [2]: from ape_ethereum.multicall import Call
In [3]: call = Call()
...: for i in range(5):
...: …
```
=> fix: multicall allow failure

src/ape_init/_cli.py
cleans up this command a bit.
1. fix spelling
2. move gitignore to module level so its easier to see/ edit
3. fix link that was weirdly pointing o the config guide.. use actual cache guide now.
4. use constant for the config file
5. improve some of the file-exists logic
=> docs: fix link and spelling issues in `ape init` command

.github/workflows/docs.yaml, .github/workflows/draft.yaml
looks a classic case of permissions suddenly being required.
we usually see this in the drafter, so i added it there too just to be safe.
=> fix: issue preventing docs CI workflow from updating `gh-pages` branch

setup.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_test/provider.py, tests/functional/test_block.py, tests/functional/test_contract_event.py
somehow the latest web3.py causes intermittent failures with eth-tester get_logs kwargs.
this should take care of it
=> fix: issue with kwargs for get_logs using eth-tester

src/ape/utils/abi.py, tests/functional/utils/test_abi.py
fixes: #2008 
use the field name instead of the method and log the issue
=> fix: bug where could not have same field name in struct as method

src/ape/_cli.py, src/ape/plugins/_utils.py
* cache `is_installed` instead of checking multiple times
* don't call github available plugins during `--help` as it is not used and is a waste of internet
The performance gains I saw were close to twice as fast when doing `ape --help`... still feels slow but is better.
=> perf: make `ape --help` faster

docs/userguides/testing.md, src/ape/api/providers.py, src/ape_geth/provider.py, tests/functional/conftest.py
fixes: #1968
can't merge because this is a breaking change.
=> feat!: add automine abstract property to TestProviderAPI

setup.py
bumps past the web3 versions using the py-evm that wasn't work with Ape's scripting system.
=> chore: bump past problematic web3 version

.pre-commit-config.yaml
Fixes a problem with the pre-commit hook by adding dateutil stubs.
=> fix: add dateutil stubs to pre-commit hook

src/ape_ethereum/provider.py
Fixes issue fetching contract type in a disconnected provider by failing gracefully.  Issue discovered when running tests in ape-alchemy.
=> fix: fail gracefully trying to fetch contract type in Web3Provider.estimate_gas_cost()

.github/workflows/test.yaml
The following issue seems to block python3.8-3.9 for macos arm: https://github.com/actions/setup-python/issues/808
NOTE: Anticipating things may still fail because of gacts/install-geth action
=> fix: use macos-12 instead of macos-latest in CI

src/ape/_cli.py, src/ape/api/compiler.py, src/ape/api/networks.py, src/ape/api/transactions.py, src/ape/managers/project/manager.py, src/ape/utils/abi.py, src/ape_cache/query.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_geth/__init__.py, src/ape_geth/provider.py, src/ape_test/accounts.py, src/ape_test/provider.py, tests/functional/conftest.py, tests/functional/test_block.py, tests/functional/test_contract.py, tests/functional/test_contract_instance.py, tests/functional/test_ecosystem.py, tests/functional/test_transaction.py, tests/functional/test_types.py
* removes `mode="json"` where is not needed.
* rationalizes every usage of `mode="json"` with a comment.
=> refactor: remove and rationalize each usage of `model_dump()` with mode="json"

src/ape/plugins/_utils.py, tests/functional/test_plugins.py
issue where plugin install checking failed because of local dists w/o name attribute
i think related to local or editable installs of packages...
=> fix: issues with local installs

src/ape/managers/plugins.py, src/ape/plugins/_utils.py, tests/functional/test_plugins.py
fixes: https://github.com/ApeWorX/ape-optimism/issues/29
abstracts selecting plugins from dists that handles python 3.9 style dist objects (with a todo) 
reproduced on py 3.9 only
analyzed.
resolved. it seems to work **i tried both editable and not ediable installs of plugins on py 3.9 and the everything in the linked issue **
=> fix: issue with python 3.9 recognizing plugins

src/ape/api/config.py, src/ape/contracts/base.py, src/ape/managers/compilers.py, src/ape/managers/networks.py, src/ape/managers/plugins.py, src/ape/managers/project/manager.py, src/ape/types/__init__.py, src/ape/utils/basemodel.py, src/ape_ethereum/ecosystem.py, tests/conftest.py, tests/functional/test_compilers.py, tests/functional/test_ecosystem.py
* exports `only_raise_attribute_error` decorator can use on all `__getattrr_` implementations (and does)
* uses the `__ape_extra_` style in a few more spots
all with the goal of making the project refactor PR smaller 😅
=> feat: `__getattr__` safety check helper and base-model improvements

docs/userguides/contracts.md, docs/userguides/transactions.md
Clarifies and adds some examples invoking payable methods from contracts using Ape in a couple user-guides.
* Add part to contract guide contract-interaction example
* add short section in transactions guide and make that make sense with some other edits
read through
=> docs: updates for payable method calls in user-guides

src/ape/api/accounts.py, src/ape/api/networks.py, src/ape/api/providers.py, src/ape_ethereum/ecosystem.py, tests/functional/test_ecosystem.py
When an ecosystem has no default network, the logic says to pick the first network. However, you get a `KeyError` in that case because it mistakenly tries `0` instead of the the first key.
Use `next` to get the key and use that instead of `0`.
Install an ecosystem plugin with no `local` network and have the default be unset in the config.
Try it out.
Notice KeyError.
Try with this PR
Notice no KeyError and it actually selects the correct one.
Also added tests.
=> fix: issue with selecting first network from an ecosystem as default

docs/userguides/dependencies.md, src/ape/cli/__init__.py, src/ape/cli/options.py, src/ape/cli/paramtype.py, src/ape/managers/project/dependency.py, src/ape_accounts/_cli.py, src/ape_compile/_cli.py, src/ape_plugins/_cli.py, src/ape_pm/_cli.py, tests/functional/test_cli.py, tests/functional/test_dependencies.py, tests/functional/test_logging.py, tests/integration/cli/test_accounts.py, tests/integration/cli/test_cache.py, tests/integration/cli/test_compile.py, tests/integration/cli/test_console.py, tests/integration/cli/test_misc.py, tests/integration/cli/test_plugins.py, tests/integration/cli/test_pm.py, tests/integration/cli/test_run.py
fixes: #
feat: adds new `config_override_option` and `JSON` CLI param type
fix: when decoding a dependency, checks config override for contracts folder instead of using default
(only a problem when contracts/ exists but changing it to something else anyway)
chore: move `@ape_cli_conext` to top of every cli impl usage list of decors, as a better standard for its placement.
feat: allow package callback in `ape pm` command to work if given a Path (only happens during testing)
test(refactor): for all usage of `runner.invoke` use either `str` or `tuple` if possible for arguments. `str` works for single commands and `tuple` works if you are not building up commands... less chance of mutability accidents and is just better practice.
=> feat: add `--config-override` option for `ape pm install`

setup.py, src/ape/_cli.py, src/ape_accounts/accounts.py, src/ape_test/accounts.py, tests/functional/test_project.py
fix: ignore misleading signHash deprecation warning
fix: issue where python 3.10 and later was never using select-pattern (was always using deprecated approach from 3.9)
fix: ignore deprecation warning for the deprecated 3.9 .. some reason still had to do this, probably because the check does some static analysis.
test: upgrade pytest-timeout to avoid deprecation warnings there
Testing done:
* 3.8 
* 3.9
* 3.10
* 3.11
* 3.12
=> fix: ignore signHash warning and packages.select warning

src/ape/api/networks.py, src/ape/api/providers.py, src/ape_ethereum/provider.py
data_folder being a field is not needed.
every plugin we have uses the name in the `.ape` data folder - so this simplifies things a lot
plugins can still override the data folder if needed.
also fields are special in pydantic so this is less complicated in that regard.
all part of the efforts of making the project refactor smaller btw.
this pr also contains all of https://github.com/ApeWorX/ape/pull/2037/files which is targeting main but itll get rebased out
=> refactor!: make `data_folder` a property instead of a field in network-APIs

Dockerfile
Updates the `Dockerfile` python version to 3.11 because features.
Any reason not to do this?  Will this roll the docker hub versions automagically?
=> chore: update dockerfile to python 3.11

src/ape/cli/paramtype.py, src/ape/managers/project/manager.py, tests/functional/test_project.py, tests/integration/cli/test_compile.py
When you have a file a structure like:
```
contracts/
- foo.jules
- helpers/
- foo.jules
```
`project.lookup_source("helpers/foo")` and `project.lookup_source("helpers/foo.jules")` would return the Path to `contracts/foo.jules` instead of the expected `contracts/helpers/foo.jules`
Test cases I added:
```
Path("path/to/contracts/foo.jules")
"path/to/contracts/foo.jules"
"foo.jules"
"foo"
Path("path/to/contracts/helpers/foo.jules")
"path/to/contracts/helpers/foo.jules"
"helpers/foo.jules"
"helpers/foo"
Path("path/to/contracts/helpers/foo.jules")
"path/to/contracts/helpers/foo.jules"
"helpers/abstract/foo.jules"
"helpers/abstract/foo"
```
=> fix: bug where `project.lookup_source` didn't return most exact match

docs/userguides/clis.md, src/ape/api/projects.py, src/ape/cli/arguments.py, src/ape/cli/paramtype.py, src/ape/managers/project/manager.py, src/ape_compile/__init__.py, src/ape_compile/_cli.py, tests/functional/data/projects/ApeProject/contracts/subdir/ApeContractNested.json, tests/functional/test_cli.py, tests/functional/test_project.py, tests/integration/cli/test_compile.py
**main**
refactor: move missing compiler check from `ape_compile._cli:cli` to `ape.cli.arguments.contracts_file_paths(callback)`... 
so any usage of the argument gets the benefit.
**side quests**
feat: better error message for missing `.vy` and/or `.sol` compilers!
fix: bug with `project.lookup_source` not returning absolute paths for some cases
test: add a bunch of missing tests for `contract_file_paths_argument`
**deprecates** (will remove entirely on a new branch targeting feat/08):
chore: deprecate AllFilePaths click.ParamType (it is bad because it returns lists of lists and that is just uncalled for - no longer used in `contracts_file_paths_argument`
chore: deprecate dependencyApi.exclude and .contracts_folder (use `config_override` for all config-override`)
=> refactor: move missing compiler check to contract-filepaths callback

src/ape/managers/project/manager.py, tests/functional/test_compilers.py, tests/functional/test_project.py
=> fix: show file name instead of attr in missing source error message

src/ape_plugins/_cli.py, tests/integration/cli/test_plugins.py
fixes a bug introduced here: https://github.com/ApeWorX/ape/commit/5eeec421af32ed5a34e65e731f4401bdbc370205#diff-0b86928e81aa95cc356070c25d73b92777562a9465597bf82b802e00736a1f96
where `ape plugins update` (for upgrading full ape suite) was failing because it was looking through dists instead of plugin names.
use `_filter_plugins_from_dists`
=> fix: `ape plugins update` command type error

src/ape/api/networks.py, src/ape/api/providers.py, src/ape/contracts/base.py, src/ape/exceptions.py, src/ape/managers/chain.py, src/ape/managers/compilers.py, src/ape/types/signatures.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, tests/functional/test_compilers.py
fixes: #2035 
Enrichment was skipped for contracts missing source IDs. This adds it.
bonuses that are not needed but were still part of the fun:
* https://github.com/ApeWorX/ape-foundry/pull/100
* https://github.com/ApeWorX/ape-solidity/pull/141
TODO: Refactor CompilerAPI plugins to use new helper method (instead of re-implementing n-places) `compiler_manager.get_custom_error()`
=> fix: issue when contracts w/o source IDs would not enrich

.pre-commit-config.yaml, setup.py, src/ape/utils/basemodel.py, tests/functional/test_contract_container.py
Fixes an issue preventing `ContractContainer.source_id` from working
* fix an issue with attr-lookup returning None and never processing down the extras-chain.
* fix an issue models w/o `__contains__` from working as extra's attributes
* documents attributes more.
* tests that container.source_id works
```python
project.MyContract.source_id
```
=> fix: Issue preventing `ContractContainer.source_id` from working

src/ape_ethereum/transactions.py, tests/functional/test_ecosystem.py
Running into this problem here: https://github.com/ApeWorX/ape-foundry/actions/runs/8939795074/job/24556545952?pr=101
It seems like `None` should be allowed.
Looking at this PR: https://github.com/foundry-rs/foundry/pull/7242/files, they also seem to allow `nil` here.
=> fix: handle `None` blob-receipt gas values

src/ape/utils/basemodel.py, tests/functional/utils/test_basemodel.py
fixes: #2053 
the problem is we are debug logging every atttr error when we shouldnt be
dont debug log attribute errors when they are acually attribute errors
```
ape -v debug
```
with and w/o
=> fix: ignore debug-logging regular `AttributeError`s

src/ape/api/networks.py
noticed this is an unnecessary cached property, as config is essentially cached already. thus this PR removes an instance of double caching
**part of project refactor - believe it or not**
@cached_property -> @property
=> fix: remove double caching for `ProviderAPI.config`

src/ape/cli/commands.py, src/ape/cli/options.py, tests/functional/test_cli.py
fixes: #2055
Issue where could not use `raw` type for network param (which is what legacy mode uses).
when using legacy, add the param in manually in callback and ctx manually.
```python
@command(cls=ConnectedProviderCommand, use_cls_types=False)
@network_option()
```
or
(what use was doing in reported issue)
```python
@command(cls=NetworkBoundCommand)
@network_option()
```
=> fix: issue where couldn't use  scripts with `cls=ConnectedProviderCommand, use_cls_types=False)`

src/ape/cli/arguments.py, tests/functional/conftest.py, tests/functional/data/projects/ApeProject/ape-config.yaml, tests/functional/data/projects/ApeProject/contracts/Exclude.json, tests/functional/data/projects/ApeProject/contracts/subdir/ExcludeNested.json, tests/functional/test_cli.py
* tracks exclude by name to avoid checking names twice when paths differ
* add missing test for exclude used with contract_file_paths argument type
=> refactor: `exclude` track by name instead of path

src/ape/exceptions.py, tests/functional/test_exceptions.py
This exception made no sense when it came up in a situation where a custom ecosystem existed with no networks (was in a test so maybe not realistic, but this is better and fixes those cases if they ever happened)
**part of project refactor stuff**
=> feat: `NetworkNotFoundError` handle case when no networks

src/ape/managers/project/manager.py, src/ape/utils/os.py, src/ape_console/plugin.py, tests/functional/test_project.py, tests/functional/utils/test_os.py
* `project` repr and str now hide the Home dir to be less doxy
* `ape console` won't display any home dir for path's repr now -- all hidden
* make new clean path util
* use it in project repr
* customize the IPython integration to use it for showing paths: 
```
ipython.display_formatter.formatters["text/plain"].for_type(
Path, lambda x, *args, **kwargs: rich_print(clean_path(x))
)
```
=> feat: hide home dir in project.path and all paths in `ape console`

src/ape_ethereum/provider.py, tests/functional/test_provider.py
Env var WEB3_PROVIDER_URL is a special env var in web3.py basically saying _use this RPC URL no matter what_.
So, even though Ape passes in a new one, Web3.py tried to use the one from the env var.
This caused quite a bit of confusion for a good chunk of yesterday morning!
this PR attempts to address this problem by ....
... raising a ProviderError
=> fix: raise error when env var WEB3_PROVIDER_URI set

src/ape/managers/converters.py, tests/functional/conversion/test_address.py, tests/functional/conversion/test_hex.py
Create simple addresses a lot easier by allowing:
```
In [1]: from ape.types import AddressType
In [2]: convert(0, AddressType)
Out[2]: '0x0000000000000000000000000000000000000000'
```
Use `eth_pydantic_types` validator
=> feat: allow `convert(0, AddressType)` to work

src/ape/managers/converters.py, tests/conftest.py, tests/functional/conversion/test_misc.py
I have since fixed the real problem in ape-ens https://github.com/ApeWorX/ape-ens/pull/33
but it is annoying that if an irrelevant `is_convertible()` check fails in Ape, it breaks the whole application when it would have succeeded if just logging the error and continuing... so that is what this PR does!
log the error and continue when `is_convertible` fails
force a converter plugin to fail, like ape-ens, and run anything using an address.
dont use or rely on actual ens
but  before, just having the plugin installed causes failure! now, it should be ok and still tell you something is wrong (the bug in ape-ens)
=> fix: `is_convertible` error handling

src/ape/api/accounts.py, src/ape/contracts/base.py, tests/functional/test_contract_container.py
A small improvement in the process of the larger project refactor for 0.8.
Basically just changes how `contract.source_path` works. Before, it looked it up via name. Now, when deploying, it sets a base path.
=> feat: allow `contract.source_path` from non local project

src/ape/managers/base.py, tests/functional/test_base_manager.py
* Use `@raises_not_implemented()` instead of raise stmt to share code and use the universal method
* Adds tests
=> refactor: use `@raises_not_implemented()` instead of `raise` statements in `BaseManager` ipython methods

src/ape/managers/networks.py, tests/functional/test_network_manager.py
* deletes a method that was unneeded - already present via ape-extra getitem=True
=> chore: delete double-ly implemented `__getitem__`

src/ape_console/_cli.py, tests/functional/test_console.py
`ape_console.console` method accepts a `project` param however it was not fully honored.
(multi-project features are not super available yet in 0.7 but this is part of getting some of the project-refactor work in early to make things go smoother and diffs smaller, thank you)
=> fix: issue where `project` was not honored in `console` function

src/ape/managers/project/types.py, tests/functional/test_project.py
I guess this matching technique was off! Ugh, I am sick of glob patterns and sorry I broken everything by trying to rely on them... Hopefully this does it...
=> fix: .cache wasn't ignored correctly in `project.__getattr__`

src/ape_ethereum/provider.py, tests/functional/test_provider.py
fixes: https://github.com/ApeWorX/ape/issues/2075
fixes in 2 spots:
1. detect APINotImplemented, which is the proper fix
2. when an unknown exception happens while  testing for parity, mark it as non-parity and go for geth. this should prevent future problems like this more.
=> fix: handle HTTPError-based not-implemented RPCs and parity-trace detection error handling easement

src/ape/cli/arguments.py, src/ape/managers/project/types.py, src/ape/utils/__init__.py, src/ape/utils/misc.py, src/ape/utils/os.py, src/ape_compile/__init__.py, tests/functional/utils/test_os.py
finally think i got this....
* issue where couldnt match by solid name
basically fixes an issue where if you change contracts folder and your build is now somewhere it else, it my start "compiling"... so this adjusts the exclusions so it's always excluded, how it was before
* make a helper method to handle and share and do this
=> fix: issues with pattern matching for source file exclusions

src/ape_console/plugin.py, tests/functional/test_console.py
Weird setup...
reassign project to something else in your console, e.g.
```python
project = 123
```
then cause an exception
it flupes out because of 123 has no `.path`
good ol' fashioned type checking
if projet
=> fix: issue when reassigned `project` to something else during exception in console

src/ape_ethereum/ecosystem.py
simple code sharing refactor and add a missing cfg doc
=> refactor: utilize super().config

src/ape/api/projects.py, tests/functional/test_project.py
**this bug is affecting etherscan verification**
=> fix: bug where compilers output selection wasn't updating when contract types changes compiler

src/ape/api/projects.py, tests/functional/test_project.py
re-fix this https://github.com/ApeWorX/ape/pull/2086
we need this, but it needs to use source ID lookup, not contract name.
=> fix: bug where compilers output selection wasn't updating when sources changes compiler

docs/userguides/config.md, docs/userguides/networks.md, docs/userguides/scripts.md, docs/userguides/transactions.md, src/ape_ethereum/ecosystem.py, src/ape_geth/provider.py, tests/functional/conftest.py, tests/functional/geth/test_provider.py, tests/functional/test_config.py, tests/functional/test_ecosystem.py, tests/functional/test_network_api.py, tests/functional/test_network_manager.py, tests/integration/cli/test_cache.py, tests/integration/cli/test_networks.py
wondering if i should target main versus feat/08
=> chore: remove `goerli` network

src/ape_ethereum/trace.py, tests/functional/geth/test_provider.py
**NOTICE:** this is a fix for feat/08 not for main
fixes an issue where estimating gas during a revert would fail for validation errors with CallTrace
allow using models to create CallTrace
allow model value
=> fix: call trace trace fix

src/ape/managers/plugins.py, tests/functional/test_plugins.py
on python 3.12 I noticed the unimplemented methods were not showing in the warning message
this PR fixes it
adjust the check
botch an api impl method and look at the warning
=> fix: plugin warning message didn't show unimplemented methods

src/ape/utils/misc.py, tests/functional/utils/test_misc.py
`get_current_timestamp_ms` claimed to return UTC now but it wasn't actually. Also, `utcnow()` is deprecated.
=> fix: datetime utcnow bug

src/ape/api/config.py, src/ape/managers/networks.py, tests/functional/test_config.py, tests/functional/test_ecosystem.py
noticed when trying to upgrade ape-polygon-zkevm. dang! not sure what happened suddenly
=> fix: bug preventing hyphenated plugin configs from working

src/ape/pytest/coverage.py, tests/functional/conftest.py, tests/functional/test_coverage.py
functions without statements, like immutable calls, were no longer incrementing. I noticed this in ape-vyper, too late somehow...
* Use `project.path` as root instead of `project.contracts_folder`
To test this feature in code, I had to allow overriding the project, adjusting how our mock-compiler works in tests
=> fix: issue where call coverage didn't increment

src/ape/utils/_github.py, tests/functional/utils/test_github.py
Regression from the GitHub refactor - turns out GH only gives you 30 repos at a time, so now we are paging and getting them all.
install a bunch of plugins and type:
```
ape plugins list
```
=> fix: issue where trusted plugins showed up as 3rd party

src/ape/managers/plugins.py, tests/functional/test_ecosystem.py
some code meant for debugging an intermittent CI issue was a bit wrong and caused a problem instead of actually emitting the log info i was looking for
=> test: fix issue in test debug code

src/ape/managers/project.py, tests/functional/test_dependencies.py, tests/functional/test_ecosystem.py
if version was `v3.0.1` could not exclude `v` on `project.dependencies["yearn-vaults"]["v3.0.1"]` and likewise if version is `3.0.1`, v was required.
create a smarter intermediate mapping that smartly checked for both key when it makes sense
```python
In [2]: versions["3.0.2"]
Out[2]: <ProjectManager $HOME/.ape/packages/projects/yearn_yearn-vaults/v3_0_2>
In [3]: versions["v3.0.2"]
Out[3]: <ProjectManager $HOME/.ape/packages/projects/yearn_yearn-vaults/v3_0_2>
In [4]: versions["vvv3.0.2"]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
```
=> fix: issue where `v` prefix mattered in dependency mapping

src/ape/managers/project.py, src/ape_pm/projects.py, tests/functional/test_dependencies.py, tests/functional/test_project.py, tests/integration/cli/projects/with-dependencies/ape-config.yaml, tests/integration/cli/projects/with-dependencies/empty_dependency/README.md
trying to fix everything hehe
1. fix: support `evm_version` reading from foundry.toml
2. fix: issue with empty dependencies (such as ones with only test.sol) causing issues during the unpacking stage, which ape-solidity used... so we just check if contracts folder exists first before unpacking, easy peasy.
3. fix: issue with manifest-only based dependencies when it comes to unpacking, was getting attr errors.
I think I am still hitting another issue, will either put on this PR or another...
=> fix: issues with manifest-dependencies, evm-version in foundry projects, and unpacking

src/ape/managers/project.py, src/ape_pm/_cli.py, src/ape_pm/projects.py, tests/functional/test_dependencies.py, tests/functional/test_project.py
all the massaging needed to get foundry projects really working.
Goes with https://github.com/ApeWorX/ape-solidity/pull/147
ugh.
this beast is now compiling without any ape-config.yaml required: https://github.com/yearn/tokenized-strategy
all from reading the foundry's project stuff.
the trickiest part was handling weird stuff with gitsubmodules and older foundry libs with so many different wways of doing remappings and names and i cant even explain it. Ape as a side-effect is way smarter now.
The attached ape-solidity PR will attempt to correct bad import remappings so things just work now, this also helps compile older Ape projects.
=> fix: issues with remapping and dependency detection in foundry projects

src/ape/api/accounts.py, tests/functional/test_accounts.py, tests/functional/test_project.py
allows you to do `account.deploy(contract_type)`
check isinstance, wrap if needed.
=> feat: allow deploying contract types from account

src/ape/api/config.py, src/ape/managers/chain.py, src/ape/managers/project.py, src/ape/types/coverage.py, src/ape_accounts/accounts.py, src/ape_init/_cli.py, src/ape_pm/dependency.py, tests/conftest.py, tests/functional/test_cli.py, tests/functional/test_compilers.py, tests/functional/test_config.py, tests/functional/test_coverage.py, tests/functional/test_dependencies.py, tests/functional/test_project.py, tests/integration/cli/test_accounts.py, tests/integration/cli/test_compile.py, tests/integration/cli/test_console.py, tests/integration/cli/test_run.py
* fix alway specify encoding to prevent latin-1 issues as well as increase windows support
* makes error look nicer when given wrong file type for `config.write_to_disk()`
* specify encoding (more OS agnostic *hrm windows)
fixes: #2088 
NOTE: The OZ specific issue was actually resolved via other means as both part of 0.8 and https://github.com/ApeWorX/ape/pull/2123 combined but the real problem is fixed by always specifying encoding if we can when calling `write_text()`, so will this PR it will finally close the issue.
=> fix: specify encoding always when writing text to a file

src/ape/managers/project.py, src/ape_pm/_cli.py, tests/functional/test_dependencies.py, tests/integration/cli/projects/with-contracts/ape-config.yaml, tests/integration/cli/projects/with-contracts/dep_with_sol_and_vy/contracts/SolFile.sol, tests/integration/cli/projects/with-contracts/dep_with_sol_and_vy/contracts/VyFile.vy, tests/integration/cli/test_pm.py
was confused for a bit because i had uninstalled `ape-solidity` but `ape pm compile . --force` was not telling me it was successful but it nothing was really happening... 
detect if no result and warn.
additionally, if you notice the dependency has .vy or .sol contracts and you are missing those from
=> feat: better CLI message when compiling a dependency produces no contracts

src/ape/managers/project.py, tests/functional/test_dependencies.py
Don't discern differences between stuff like OpenZeppelin v4.5.0 and OpenZeppelin 4.5.0...
i noticed i had some duplicates.
so the caching system is a bit better now at only needing one or the other, really dont matter
github client is already smart like that, so now the cache can be as well
=> fix: avoid duplicate caching with v versus non-v prefix in dependency versions

src/ape/api/config.py, src/ape/managers/project.py, src/ape/pytest/plugin.py, src/ape/utils/basemodel.py, tests/functional/test_config.py, tests/functional/test_project.py
handle if the dependencies: config is the wrong type (e.g. not a list of dicts)
raise ConfigErrors in model_validate
make  a config like:
```yaml
dependencies:
name: openzeppelin
...
```
(notice forgot the - )
=> fix: better error handling for bad dependencies: config

setup.py
=> chore: upgrade pandas

src/ape/_cli.py, src/ape/api/config.py, src/ape/managers/project.py, tests/integration/cli/test_misc.py
When config failed to parse in Ape 0.7, you got a validation error.
in Ape 0.8, you get an AttributeError during a weird network-option callback (what?)
And the error still didn't show config line numbers.
So this PR does 2 things:
1. Exit early during config file parsing error... because it is too confusing otherwise!
2. Show the line numbers of the bad config
fixes: #1718
with this config:
```yaml
name: {asd}
deployments:
address: ooga
```
you should get this error now:
```
(ape08) ➜  ape-playground git:(main) ✗ ape console -v debug
'$HOME/ApeProjects/ape-playground/ape-config.yaml' is invalid!
Input should be a valid string
-->1: name: {asd}
2: 
Input should be a valid dictionary
4: deployments:
-->5:  address: ooga
```
=> feat: show config error linenos

src/ape/managers/config.py, tests/conftest.py
for helping plugins test stuff that creates data.
=> feat: create `config.isolate_data_folder()` method

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
i forgot to specify a URI for my custom network and nothing was in evmchains yet and i noticed Ape went ahead and tried starting a geth dev for me with this , and that wouldnt really work.
this PR makes it so Ape only uses default localhost URI if nothing is configured AND we are in a dev-net (local or fork).
check `.is_dev` before using DEFAULT_SETTINGS
make a config like:
```yaml
networks:
custom:
- name: mainnet
chain_id: 109
ecosystem: shibarium
base_ecosystem_plugin: polygon
default_provider: node
```
try launching geth
before it would try geth dev because it couldnt find any URI.
but now it fails because it knows you are not using a dev net and there is no Uri
=> fix: issue where Ape tries starting geth-dev for custom networks w/o URIs

setup.py, src/ape_ethereum/provider.py, src/ape_node/provider.py, tests/functional/geth/test_provider.py
I noticed I could not get evmchains to work for my custom network pointed at Shibarium even after adding shibarium to evmchains.
I realized it was because the random RPC stuff was skipped over for custom networks for a couple reason...
basically if it is dev, we can use default, otherwise we can at least check for random RPC to try
Before it would just not find anything, realize it was not dev, and error out
=> fix: allow random RPCs to work for custom networks

docs/userguides/transactions.md, src/ape/api/query.py, src/ape/contracts/base.py
add clarity and more information to the contract-creation metadata feature
fixes: #2118 
Please let me know if there is anything you would like to see
Maybe could use @banteg 's input
=> docs: document more fully the contract-creation metadata feature

docs/userguides/networks.md, src/ape/api/networks.py, src/ape/cli/choices.py, src/ape/cli/options.py, src/ape/managers/networks.py, src/ape_networks/__init__.py, tests/functional/test_cli.py, tests/functional/test_ecosystem.py, tests/functional/test_network_api.py, tests/functional/test_network_manager.py
allows forking custom networks automatically
fixes: #1905
**NOTE**: Works best with this one https://github.com/ApeWorX/ape/pull/2144
if the provider is known for forking, just send it on through anyway.
had to do some finaggling throughout
my cfg:
```yaml
networks:
custom:
- name: mainnet
chain_id: 109
ecosystem: shibarium
base_ecosystem_plugin: polygon
default_provider: node
```
**Note**: cfg is small because using evmchains via https://github.com/ApeWorX/ape/pull/2144
=> feat: allow forking custom networks automatically

docs/userguides/config.md, src/ape/utils/misc.py, tests/functional/test_config.py
Document and test for environment variable expansion in ape-config yaml files
I saw the issue and was like "im pretty sure this was added already" but I noticed both there were not docs or tests for this feature..
fixes: #292 
so this PR completes the request by including the missing docs and tests
=> docs: document environment variable support in `ape-config.yaml` files

src/ape/managers/config.py, src/ape_ethereum/ecosystem.py, tests/functional/test_config.py
I had my config set up with some environment variables that did not exist, and i noticed that instead of Ape crashing where it was supposed to, my error s were dropped and the configs were turned to regular `PluginConfig` and i got attribute errors within the plugin instead, kinda weird... 
Removed duplicate `get_config` method that hid the errors for no reason.
instead, let `ConfigManager` run `ApeConfig.get_config` and the error shows up correctly.
```yaml
foundry:
fork:
shibarium:
mainnet:
block_number: {asdf}
```
try to use foundry
=> fix: issue where plugin config loading error was not shown

src/ape/api/config.py, src/ape/managers/config.py, tests/functional/test_config.py
these were not the errors i set out to fix but ones i found along the way.
im still working on the bug im trying to fix...
fix: an issue where list config errors locations were never found in ape-config.yaml files
fix: an issue where missing key-based errors did not show any lines in config
fix: issue where could not merge configs if one type was a dict and the other was (mistakenly) some other type
=> fix: issue with list-errors and mismatched config types

src/ape/api/networks.py, src/ape/managers/chain.py, src/ape/managers/networks.py, src/ape/managers/project.py, tests/conftest.py, tests/functional/geth/conftest.py, tests/functional/test_cli.py, tests/functional/test_config.py, tests/functional/test_dependencies.py, tests/functional/test_ecosystem.py, tests/functional/test_network_manager.py
I need this fix to fix something else I am working on...
basically there was an issue where any custom network defined in a non-local project was not recognized by Ape.
See my test I added to see what I mean. That failed before but now it does not.
* projects with config override with inject their custom nets to network manager.
=> fix: issue where could not define custom networks in any non-local project

src/ape/managers/networks.py, tests/functional/test_network_manager.py
=> fix: better error when missing base-ecosystem plugin for custom networks

src/ape/api/config.py, tests/functional/test_config.py
OK- this is the issue I have been trying to fix all week...
When problems arise in plugin configs, we can show the lines in the config files.
=> fix: issues showing lines for plugin config validation errors

setup.py, src/ape/api/transactions.py, src/ape/managers/chain.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/trace.py, src/ape_ethereum/transactions.py, src/ape_node/provider.py, tests/functional/data/sources/VyperContract.vy, tests/functional/geth/test_provider.py, tests/functional/test_ecosystem.py, tests/functional/test_receipt.py, tests/functional/test_trace.py
* Show and enrich event data in Call-traces
* Attach missing events to call tree during a `show()`.
* Add `show_events()` method to `ReceiptAPI`
fixes: #834
fixes: #1776 
requires: https://github.com/ApeWorX/evm-trace/pull/66
note: for non structLog approach, logs are injected at top of the trace because that is the best we can do seemingly
=> feat: show events in pretty call-trace or from receipt

src/ape_ethereum/ecosystem.py, tests/functional/test_ecosystem.py
the currency-value broke decoding bools from returndata because bools are technically `isinstance(x, int)`
adjust check to verify isnt a bool before going to currency-val- comparable
```vyper
@view
@external
def view_method() -> bool:
return True
```
=> fix: regression decoding boolean values

src/ape/managers/project.py, tests/functional/test_project.py, tests/integration/cli/test_compile.py
The performance of getting contracts from projects is bad because it pointlessly always reloaded the manifest. Mistake! Fixed!
For testing, using a MASSIVE PROJECT.
With change:
```
In [1]: %time project.get_contract("MyContract")
CPU times: user 116 ms, sys: 12 ms, total: 128 ms
Wall time: 132 ms
```
Without change:
```
In [1]: %time project.get_contract("MyContract")
CPU times: user 1min 19s, sys: 2.88 s, total: 1min 22s
Wall time: 1min 22s
```
Improvement≈99.84%
So, the performance improvement is approximately 99.84%.
delete code.
test.
=> perf: improve performance of `project.get_contract()`

src/ape/cli/arguments.py, tests/functional/test_cli.py
An annoying issue I found while testing where one could not compile a subdirectory with a source file in one go, e.g.
```
ape compile subdir MyContract.vy
```
set unions instead of early return in the loop
from project with subdir and contracts
```sh
ape compile subdir MyContract.vy
```
=> fix: issue where could not compile file and subdir in the same command

src/ape_node/provider.py, tests/functional/test_project.py
data dir was getting removed / created at weird times
also a test failed on merge to main for last PR
=> fix: create data dir in clean method

src/ape/managers/chain.py, tests/functional/conftest.py, tests/functional/test_contracts_cache.py
The error message was confusing and causing a scare for some users, this is my attempt to improve that.
fixes: https://github.com/ApeWorX/ape-etherscan/issues/122
If we detect a rate limit error during fetching a contract type, we only show the error with no other prefix that is potentially scary.
In other cases, the error message was adjusted to sound less assumptuous.
```
(
f"Attempted to retrieve contract type from explorer '{explorer_name}' "
f"from address '{address}' but encountered an exception: {err}\n"
)
```
=> fix: improve the error message for exceptions during fetching contract types from explorer

.pre-commit-config.yaml, setup.py, src/ape/managers/chain.py, tests/functional/test_chain.py
The documentation for querying accounts used an example with an ENS name as the arhttps://docs.apeworx.io/ape/stable/userguides/data.html#getting-account-transaction-datagument: 
however, when I went to try it, it was not seen as valid and no conversion took place.
Thus it is a bug fix since it was a documented feature that isnt working.
convert
```python
chain.history["vitalik.eth"]
```
=> fix: bug where ENS domains were not handled in account history queries

tests/functional/test_contract_instance.py
* Show we can use namedtuples as inputs
* Try out new web3 namedtuple functionality (I found an https://github.com/ethereum/web3.py/issues/3429)
* Adding notes here:
** Unable to have underscore prefixed values in structs which is bad / breaking for Ape... I get it is rare but it is rather unfortunate. I don't see a reason to change our Struct to use namedtuple for reasons like this, also because the name in the namedtuple is not very dynamic in web3.py, it is the same name and not the name of the struct like it is in Ape. Ape's struct seems a lot more powerful so I am tempted to stick with that, albeit overengineered in some respects. I just can't rationalize changing to namedtuple at this time.
fixes: #1893
=> test: show we can use namedtuples and web3 namedtuples

src/ape_ethereum/_converters.py, tests/functional/conversion/test_ether.py
Now, if you convert like this:
```python
convert("10,000 ETH", int)
```
It will work.
I think `10_000 ETH` worked already, but I made sure of it.
Test accounts are pre-funded with 10,000 ETH which is a big number and the commas make the currency string a bit more readable.
Since these are string types, commas are a normal way of expressing separation in numbers, so i think it intuitive to do that
=> feat: handle commas and underscores in currency string conversions

.pre-commit-config.yaml, setup.py, src/ape/utils/basemodel.py, src/ape_run/_cli.py
fixes new mypy complaints and upgrades
=> chore: handle 1.11 mypy upgrades

docs/index.md, docs/userguides/contracts.md, docs/userguides/reverts.md, docs/userguides/testing.md, setup.py, src/ape/api/transactions.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, src/ape_run/_cli.py, src/ape_test/provider.py, tests/functional/geth/test_contract.py, tests/functional/test_contract_instance.py
=> feat: `raise_on_revert=False` kwarg for allowing failures on calls and transactions

src/ape/managers/compilers.py, src/ape_ethereum/ecosystem.py, src/ape_test/provider.py, tests/functional/test_contract_instance.py
we were not catching the right exception in the ape-test provider logic.
catch all exceptions
handle gracefully tracing issues.
```python
def main():
owner = accounts.test_accounts[0]
contract = owner.deploy(project.VyperContract, 0)
contract.setNumber.call(5) 
```
shows like
```
File "$HOME/ApeProjects/ape-playground/scripts/failu.py", line 18, in main
contract.setNumber.call(5)
File "$HOME/ApeProjects/ape-playground/contracts/VyperContract.vy", line 98, in 
setNumber
assert msg.sender == self.owner, "!authorized"
^^^^^^^^^^^^^^^^^^^^^^^
```
=> fix: issue where compiler panics were not detected using Eth-Tester provider

src/ape/__init__.py, src/ape/exceptions.py, tests/functional/test_exceptions.py
The home dir was not being hidden properly in stacktraces 
This makes it so!
When formatting the traceback, do the swap swap swap swap, do the swap.
```python
contract = owner.deploy(project.VyperContract, 0)
contract.setNumber.call(5) 
```
should see 
```
File "$HOME/ApeProjects/ape-playground/scripts/failu.py", line 18, in main
contract.setNumber.call(5)
ERROR: (ContractLogicError) !authorized
```
=> fix: issue where home dir was not hidden in stacktraces

src/ape/exceptions.py, tests/functional/test_contract_instance.py, tests/functional/test_exceptions.py
We show the lines of Vyper files in the Python stack traces well for Transactions.
However, I noticed it was not working for call.
This PR fixes that.
Mostly just remove the unnecessary reliance on the txn= kwarg when setting the traceback
make a call that fails, im doing:
```
contract.setNumber.call(5) 
```
in a script, then you should see the trace showing the vyper lines:
```
File "$HOME/ApeProjects/ape-playground/contracts/VyperContract.vy", line 98, in 
setNumber
assert msg.sender == self.owner, "!authorized"
```
=> fix: issue where Vyper source-lines were not displayed in call-stacktraces

src/ape/managers/project.py, tests/functional/test_project.py
`extra_output` handling ABI was a list of strings instead of a list of objects, in the JSON.
model_dump instead of model_dump_json
improve test
ABI is usable now.
=> fix: ABI output was wrong when using `extra_output`

src/ape/managers/accounts.py, tests/functional/test_accounts.py
In [7]: %time accounts.load("laughing-sepolia-safe")
CPU times: user 566 µs, sys: 497 µs, total: 1.06 ms
Wall time: 729 µs
Out[7]: <SafeAccount 0x872Df5f6CF2C2Eaa9e7511AB079D263AB8fdc79f>
In [8]: %time accounts.load("laughing-sepolia-safe")
CPU times: user 7 µs, sys: 1e+03 ns, total: 8 µs
Wall time: 9.78 µs
Out[8]: <SafeAccount 0x872Df5f6CF2C2Eaa9e7511AB079D263AB8fdc79f>
**Note:** Some accounts plugins a bit slower than others on first load.
=> perf: account alias lookup

src/ape/api/accounts.py, src/ape/api/providers.py, src/ape/managers/accounts.py, src/ape/managers/project.py, src/ape/utils/testing.py, src/ape_node/provider.py, src/ape_test/accounts.py, src/ape_test/provider.py, tests/functional/test_accounts.py
**It is unnecessary for Ape to generate the test accounts.**
This is because the provider already is doing this.
By allowing hooks for accessing the accounts from the provider, we can avoid duplicating the work.
Often times the provider is much faster, such as Anvil, because it is rust.
Account generation is a slow thing to do... so by not doing it, we make Ape as fast as a Texas Rat Snake.
Rely on provider for getting test accounts.
Using Eth-Tester provider, before (main branch):
```
(ape08) ➜  ape-playground git:(main) ✗ ape console
In [1]: %time accounts.test_accounts[9]
CPU times: user 138 ms, sys: 5.47 ms, total: 144 ms
Wall time: 142 ms
Out[1]: <TestAccount 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720>
In [2]: %time accounts.test_accounts[9]
CPU times: user 181 µs, sys: 0 ns, total: …
```
=> perf: avoid duplicate account generation

docs/conf.py
Missing comma in `exclude-members` lead to `model_config` still being compiled in the documentation
fixes: #
=> fix: missing comma

docs/userguides/testing.md, src/ape/api/accounts.py, src/ape/api/providers.py, src/ape/contracts/base.py, src/ape/managers/accounts.py, src/ape/managers/chain.py, src/ape_ethereum/provider.py, tests/performance/test_project.py
I noticed some weird things with impersonating accounts... A bunch of repeated work in places.
And different ways of handling that in `send_transaction()`.
I am working on improving all of that, but in the mean time, I need a more plugin-friendly way of impersonating accounts.
now we get to delete a bunch of code in ape-foundry and ape-hardhat.
hence this PR, which separates the key aspect of that into a new API and has the [] access one use that
things work the same and able to refactor something in ape-foundry (coming soon!)
=> feat: improve impersonating accounts features in core

docs/userguides/networks.md, src/ape_ethereum/provider.py, tests/functional/test_provider.py
allows users to configure a `ws_uri` in their node config (per network, same as uri).
implement a custom `ws_uri` in
=> feat: add `ws_uri` config to `ape-node`

src/ape/contracts/base.py, src/ape/exceptions.py, src/ape_ethereum/provider.py, tests/functional/test_contract_call_handler.py, tests/functional/test_contracts_cache.py
`ContractNotFoundError` was confusing in some cases by no using networkchoice and instead only showing provider name,
like
```
Current provider 'node' has no associated explorer plugin.
```
this pr improves the error message
now shows
```
2C497'. Current network 'ethereum:local:node' has no associated explorer plugin.
```
see tests
=> fix: Show network instead of provider in `ContractNotFoundError`

src/ape/api/networks.py, src/ape/api/transactions.py, src/ape/contracts/base.py, src/ape/managers/chain.py, src/ape/pytest/config.py, src/ape/pytest/coverage.py, src/ape/pytest/fixtures.py, src/ape/pytest/gas.py, src/ape/pytest/plugin.py, src/ape/pytest/runners.py, src/ape/utils/abi.py, src/ape/utils/misc.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/trace.py, src/ape_node/provider.py, src/ape_test/accounts.py, src/ape_test/provider.py, tests/functional/test_contract_call_handler.py, tests/functional/test_exceptions.py, tests/functional/test_provider.py
A collection of perfs to make Ape faster... ongoing research and implementation..
=> perf: RPC / provider level speed optimizations

src/ape/api/providers.py, src/ape/api/transactions.py, src/ape/types/__init__.py, src/ape/utils/misc.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/transactions.py, tests/conftest.py, tests/functional/test_ecosystem.py, tests/functional/test_gas_tracker.py, tests/functional/test_trace.py, tests/functional/test_transaction.py, tests/functional/test_types.py
noticed bugs and also lack of decent use of annotated-validators for hex-to-int situations, so made `HexInt` for that - likely will end up in `eth-pydantic-types` after @bitwise-constructs work is complete there.
also had to delete some unnecessary validators for hex-str and hexbytes as it happens automatically when using those types.
note, did this originally because there was a regression i think with a recent merge validating BlobReceipts, somehow it occasionally go a hex-str for an int there and I was going to add the validator but I am getting tired of repeating this validator everywhere, hence HexInt's birthday
things still work (only better in the case of Blob receipts)!
=> refactor: share hex-related validators

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
Background: The failing call in the test in the linked issue was actually from a proxy-check on the contract, and not one the actual project's contract logic.
fix: handle recursion error in getting a contract type when eth call fails
BUT that was actually not the main problem (but still was good to fix).
The main problem is that tracing-features, including the intense exception handling one expects from failed calls, should be skipped altogether for proxy checks, and the mostly were thankfully except in this one spot.
**perf**: The fixing of this bug should be a rather nice performance upgrade because this means before, all failed proxy checks were fetching contract-types and preparing traces (not calling trace RPCs but doing everything else but)
fixes: #2206
=> fix: skip trace contract-logic errors during proxy-detection and more error-handling in eth_call

src/ape/types/__init__.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_ethereum/trace.py, src/ape_test/provider.py, tests/conftest.py, tests/functional/geth/conftest.py, tests/functional/geth/test_provider.py, tests/functional/geth/test_trace.py, tests/functional/test_coverage.py, tests/integration/cli/test_test.py
metrics from running a test in a real project with lots of stuff going on
before:
`107.63s`
after:
`28.28s`
Use raw trace frames carefully if have not already enriched.
=> perf: avoid enriching entire trace when only requesting `return_value`

.pre-commit-config.yaml, setup.py, src/ape_ethereum/trace.py, tests/conftest.py, tests/functional/conftest.py, tests/functional/test_trace.py
Regression with None revert messages, only noticed in Foundry (though fixed there separately)
=> fix: issue where revert message is None

src/ape/api/accounts.py, tests/functional/test_accounts.py
Let's not check balance for impersonated accounts, as some providers (with the right settings) will allow it to work regardless. In any case, the VM error may be better anyway.
=> fix: bypass balance check impersonated accounts

src/ape/contracts/base.py, src/ape/exceptions.py, src/ape/managers/compilers.py, src/ape/pytest/coverage.py, src/ape_ethereum/provider.py, src/ape_pm/compiler.py, src/ape_test/provider.py, tests/functional/test_contract_instance.py, tests/functional/test_exceptions.py
I had a dream last night that this was the last remaining performance problem.
Basically all call-based Vm errors seems to calculate their source tbs when they don't always have to.
I am hoping by lazy-ifying this, we re-gain some of performance loss from 0.6.22
=> perf: lazy source traceback in transaction errors

src/ape/cli/options.py, src/ape/logging.py, tests/functional/test_cli.py, tests/functional/test_logging.py
A user is showing me a stack-trace ending with "Unknown level: LOGLEVEL.WARNING", likely caused by https://github.com/ApeWorX/ape/pull/2212
**However, no matter what I try, I am not able to reproduce, even in their repo with the same branches and versions.**
This PR is my attempt to "fix" without reproducing, even thought that isn't ideal, I just don't know what else to do.
Look at their stack trace and try to handle LogLevel types in more place.s
=> fix: logger verbosity issues

.github/workflows/build.yaml, Dockerfile, Dockerfile.slim, README.md
Created Dockerfile.slim for a slim version of ape without recommended-plugins
fixes: #2143 
Needed to create the whl files with python:3.11, then switch to python:3.11-slim after the whl files are created. This install ends up being 500MB in size vs 2.24GB in the current Dockerfile build.
I then install the recommended plugins in the Dockerfile for the latest version. The size of the image reduced from 2.24GB to 571MB.
```bash
git checkout feat/create-bare-ape-image
docker build -t ape:latest-slim -f Dockerfile.slim .
docker image ls
...
...      ...               ...   SIZE
ape   latest-slim                500MB
ape   latest                     571MB
```
=> feat: adding slim dockerfile

tests/integration/cli/test_test.py
the `ape test` integration tests were not working for me locally, they were timing out.
i figured out it was because ape was utilizing those installed plugins and downloading compilers which takes forever.
ignore .vy and .sol files; they are not needed for these tests anyway.
=> test: fix issue with `ape test` tests when vyper / solidity installed

src/ape/exceptions.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/trace.py, tests/functional/geth/test_trace.py
Finally - `.return_value` is speedy as it ever was.
stats:
```
Before:
10 passed in 197.45s (0:03:17)
After:
10 passed in 69.65s (0:01:09) 
```
if possible, use a barely enriched raw call tree, as opposed to a fully enriched (least performant) and a trace-calculated return (middle performance).
this is by far the best.
=> perf: most performant `.return_value` calculation

src/ape/cli/choices.py, tests/functional/test_cli.py
an annoying issue where if i mis-typed an alias, even when using the `--account` flag, it would prompt... id then enter the wrong alias again in the prompt but instead of failing, it  would treat it as `None` and try to use it in my script , None has no attribute deploy
fail if we resolve to an alias but that alias does not exist in your accounts
have a script like:
```python
import click
from ape.cli import ConnectedProviderCommand, account_option, ape_cli_context
@click.command(cls=ConnectedProviderCommand)
@ape_cli_context()
@account_option()
def cli(cli_ctx, account):
"""
Deploy the chess contract.
"""
chess_contract = cli_ctx.local_project.chess
account.deploy(chess_contract)
```
run it with a nonsense account like:
```sh
ape run deploy --account "SADFASDFG
```
should get some output …
=> fix: issue where `--account` did not fail when it was supposed to

src/ape/types/__init__.py, tests/functional/geth/test_provider.py, tests/functional/test_contract_event.py, tests/functional/test_types.py
The following bug fixes are in this PR:
1. Can now use `CurrencyComparableValue` as a type annotation (And still using comparison-feature!)
2. Can validate CurrencyComparableValue into int declared type
3. ContractLog serialized event_arguments out of this type because of https://github.com/pydantic/pydantic/issues/10152
Implement a custom serializer in the type that treats it like a normal int
=> fix: issues with `CurrencyComparableValue` appearing `ContractLog.event_arguments` & on Pydantic models

src/ape/utils/misc.py
this warning is annoying, i did some searching and it is quite normal for their to be multiple installs, depending on your install..
i think this warning used to matter more in earlier releases of ape anyway and the weird things we saw back then no longer happen because of switching to importlib.
=> chore: remove an inaccurate warning

pyproject.toml, src/ape/cli/choices.py, src/ape/exceptions.py, tests/functional/test_cli.py
when the ecosystem, network, or provider were slightly off, it did not show me the nice message but instead told me to figure it out (rude!)
we were already getting the nice message earlier so this was an easy fix.
leverage existing error message
```sh
ape console --network etheruem:local:test
ape console --network ethereum:loocal:test
ape console --network ethereum:local:teest
```
=> feat: show nicer errors during bad network choices

pyproject.toml, src/ape/utils/basemodel.py, src/ape_pm/_cli.py, tests/functional/utils/test_basemodel.py
I noticed when trying to manager global dependencies in python, it can be awkward referencing the local project to do this.
this makes it less awkward.
=> feat: make the dependency manager accessible on `ManagerAccessMixin`

src/ape/exceptions.py, src/ape/types/trace.py, tests/functional/test_exceptions.py
unreleased regression affecting dev message detection.
basically it was not trying to make a source traceback if only given a txn
=> fix: issue missing source traceback on error when given only transaction

src/ape/api/networks.py, tests/functional/test_cli.py, tests/functional/test_network_api.py
When using a provider that isn't node for a non-forked custom network would still use forked provider version.
* Notice both classes were registering
* Add condition to make sure the correct class was registering
```yaml
foundry:
blast:
mainnet-tenderly:
uri: "https://[REDACTED]"
networks:
custom:
- name: mainnet-tenderly
chain_id: 69420
ecosystem: blast
base_ecosystem_plugin: optimism
default_provider: foundry
```
connect:
```sh
ape console --network blast:mainnet-tenderly:foundry
```
=> fix: issue where custom-networks defaulted to forked-providers when they were not forked networks.

src/ape_ethereum/trace.py, tests/functional/test_trace.py
anon events have no name.
Likewise, what evm-trace is just bad?
Either way, best not to crash all of everything in the universe.
=> fix: handle anonymous and strange event data in `parse_rich_tree()` method

.github/workflows/build.yaml
The tag that is created when merged to `main` is `main`. We want this to be `latest` and then on version release, we want this to be `stable`
fixes: APE-1769
Added the tag to the build yaml
After merge, check the release
=> fix: incorrect image release tags in build

src/ape/cli/options.py, src/ape/logging.py, src/ape_test/_cli.py, tests/functional/test_cli.py, tests/functional/test_logging.py
Fix the bug in 3 spots because am mad:
* Handle stringified `LogLevel` values with LogLevel prefix everywhere
* Use `.value` in `ape test` because is more performant and makes more sense and you don't run into weird issues in some CI/CD environments.
* Validate pytest args by excluding Ape's usage of `-v` (in case it is ending up in there)
https://github.com/ApeWorX/ApePay/pull/99
=> fix: `ValueError: Unknown level: 'LOGLEVEL.WARNING'`

docs/userguides/console.md
* renamed guide to jus "console" because couldnt find the console guide because it weirdly has `ape` prefix. of course it is ape!
* example didnt work
* not sure where WETH_ADDRESS is coming from
=> docs: console guide fixes

src/ape/managers/project.py, tests/functional/test_project.py
pre 0.8. this happened, and I don't see why it should not happen, so making it happen again.
(here you go @Ninjagod1251 )
=> fix: make `.extract_manifest()` also compile if needed

src/ape/managers/compilers.py, tests/functional/conftest.py, tests/functional/test_compilers.py
Ape shows you all compiler errors across compilers.
That is great, except when there was only a single error, thus causing a pointless exception being thrown on the stack.
if len(errors) is just 1, just raise that error instead.
Compile with 1 compiler failing - should just see the custom
Compile with 2 compilers failing - should see them amassed
I added tests for both of these cases.
=> fix: if only single compiler error, avoid wrapping in a new error

docs/userguides/config.md, docs/userguides/networks.md, src/ape/api/config.py, src/ape/api/networks.py, src/ape/api/providers.py, src/ape/managers/__init__.py, src/ape/managers/config.py, src/ape/managers/networks.py, src/ape/pytest/fixtures.py, src/ape/utils/__init__.py, src/ape/utils/_github.py, src/ape/utils/misc.py, src/ape/utils/rpc.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_node/provider.py, tests/functional/geth/conftest.py, tests/functional/geth/test_provider.py, tests/functional/test_ecosystem.py, tests/functional/test_provider.py, tests/functional/utils/test_rpc.py
* Allow you to configure request headers across the board, via ecosystems, via networks, and via providers.
* Actually use said request_header in web3.py (was missing!)
```yaml
request_headers:
Top-Level: "UseThisOnEveryRequest"
ethereum:
request_headers:
Ecosystem-Level: "UseThisOnEveryEthereumRequest"
mainnet:
request_headers:
Network-Level: "UseThisOnAllRequestsToEthereumMainnet"
node:
request_headers:
Provider-Level: "UseThisOnAllRequestsUsingNodeProvider"
```
then connect:
```sh
ape console --network ethereum:local:node
```
Then verify headers:
```python
In [12]: http = provider.web3.provider._potential_providers[2]()
In [13]: http._request_kwargs
Out[13]: 
{'headers': {'User-Agent': 'Ape/0.8.14.dev0+g228ab19a1.d20240827 (Python/3.12.2 final)',
'Top-Level': 'UseThisOnEveryRequest', …
```
=> feat: support `request_header` driven from configs

tests/functional/data/README.md, tests/functional/data/scripts/update.py
it is annoying updating test contracts for tests in ape, this pr adds a script and a readme to assist in the process
make a script for updating contract JSONs via their sources
* make change to one of the contracts in sources dir
* run `ape run update MyFile`
* see the updates are available now
=> test: make helper script for updating test contracts

src/ape/types/__init__.py, tests/functional/test_types.py
hashing was lost on our custom int type
=> fix: issue where returndata integers could not be used in dictionary

src/ape/exceptions.py, tests/functional/test_contract_call_handler.py, tests/functional/test_contracts_cache.py, tests/functional/test_exceptions.py
`ContractNotFoundError` as confusingly mentioning explorer plugins for local networks.
I have encountered this myself but also saw it in https://github.com/ApeWorX/ape/issues/2262 and I feel like it only makes the error worse when running local stuff (because no explorer plugins often are included for local)
=> fix: avoid mentioning explorer plugins for local-network

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
One of the errors mentioned in https://github.com/ApeWorX/ape/issues/2262
shows we are not handling the error message specific to Tenderly (and the user us not using the  Tenderly plugin but instead the generic node plugin)
adjust regex
pytest using tenderly
=> fix: handle not-implemented method from tenderly in `ape-node`

setup.py
pydantic_setting was released 3 hours ago, and it broken python 3.9 and 3.10 on every plugin
=> fix: pin pydantic_settings as it broke ape

src/ape/managers/project.py, src/ape_pm/compiler.py, tests/functional/test_project.py, tests/integration/cli/test_compile.py
fixes: #2271
To reproduce problem:
1. Have a contract, working good, with a test.
2. Run ape test, all is good
3. Make a change to the contract that causes a compiler error
4. Run ape test again, test acts like it did before, and there is no compiler error.
**They key is that the change must be problematic and cause errors**
Frustratingly find spot where source Id is being overridden
Restore it.
Also, adjust error message
Test tbd
=> fix: mistakenly changed sources to in-memory manifest

setup.py, tests/functional/test_project.py
https://github.com/pydantic/pydantic-settings/issues/390#event-14210829716
has been released in 2.5.2
this pr adjusts the pin accordingly
=> chore: use new patched pydantic settings

docs/userguides/dependencies.md, src/ape_pm/dependency.py, tests/functional/test_dependencies.py
When using the dependency config:
```yaml
dependencies:
- name: uniswap-core
github: Uniswap/v3-core
version: v1.0.0
- name: uniswap-periphery
github: Uniswap/v3-periphery
version: v1.3.0
```
it first tries the GH release API. When that fails, it falls back to searching for the ref.
It finds the ref, but the checking of the API has already caused the destination to exist.
Our GH client will make a subdir in that case of the repo name, and that causes the whole import structure to fail
BTW, this problem wouldn't occur if using a more optimal and correct reference like this:
```
dependencies:
- name: uniswap-core
github: Uniswap/v3-core
ref: v1.0.0
- name: uniswap-periphery
github: Uniswap/v3-periphery
ref: v1.3.0
```
If in the fallback scenario, first ensure the dependency folder does not …
=> fix: issue where using `version:` key for a GH ref-based releases caused invalid directory structure

docs/userguides/dependencies.md, src/ape/managers/project.py, src/ape_pm/_cli.py, tests/functional/test_dependencies.py, tests/integration/cli/test_pm.py
fixes: #2283
Fixes: APE-1817
very carefully
`ape pm list`
play around with install and uninstall
=> feat: avoid installing dependencies during `pm list` command

src/ape/cli/__init__.py, src/ape/cli/options.py, src/ape/cli/paramtype.py, tests/integration/cli/test_test.py
For some reason, `ape test -v debug` was no longer working - I was getting an Invalid Integer problem.
Hack click to ignore type checking..
I wish the callback was enough for this but I guess click does what it wants.
Run:
```sh
ape test -v debug
```
=> fix: invalid integer when using `-v` flag in `ape test`

src/ape/cli/options.py, src/ape/logging.py, tests/functional/test_logging.py, tests/integration/cli/test_test.py
Allows you to use pytest's -v option without clobbering.
Also fixes a perf where would parse sys argv more than once.
=> fix: issue where couldn't use ape test -vvv

docs/userguides/config.md, src/ape/api/config.py, src/ape/managers/networks.py, src/ape/managers/project.py, tests/functional/test_project.py, tests/integration/cli/test_misc.py
Step 1 to getting `pypi:` to work right with snekmate-like projects
=> feat: allow configuring `base_path:` in projects

src/ape/managers/project.py, tests/functional/test_project.py
Was showing `/snekmate/src` and not `/snekmate` when using that fancy package dir
=> fix: better repr string for pythonic projects

src/ape/cli/options.py, src/ape/pytest/plugin.py, src/ape_test/_cli.py, tests/integration/cli/test_test.py
`-vvv` was no longer failing as of recent changes but it also wasn't using the correct pytest verbosity.
The PR makes it actually work in pytest.
Actually really need this for the work I am doing with the snapshotting
a few things had to be fixed, was more difficult than would have liked:
1. In the Pytest plugin itself, verbosity was always getting downgraded in certain conditions; had to make it not do that if the verbosity was already higher than what it would set if it was doing that shit.
2. Make a custom command for ape test to handle parsing args. It needed to parse the -v before click otherwise couldnt get it to work with -v without a value error, even with callback.
3. The validaion of pytest args was ignoing the case of -v by itself in the middle where the next arg isnt an ape …
=> fix: `ape test -vvv` was not using correct pytest verbosity

.github/ISSUE_TEMPLATE/bug.yml
added a place for describing the bug in the template
=> docs: add description field to GH bug report

setup.py, src/ape_accounts/accounts.py, src/ape_ethereum/provider.py, src/ape_node/provider.py, src/ape_test/accounts.py, tests/functional/geth/test_provider.py, tests/functional/geth/test_trace.py, tests/functional/test_ecosystem.py
in prep for the eth upgrades, we need to do this
=> refactor!: Upgrade Ethereum packages and usage

src/ape_pm/dependency.py, tests/functional/test_dependencies.py
allows
```yaml
dependencies:
- github: ApeWorX/ApePay
ref: main
```
to work, where `name:` is not configured.
In this case, it uses he name `apepay` automatically from the GH input.
model validator
use config i just said
=> feat: automatically calculate GitHub dependency name when not provided

src/ape_node/provider.py, tests/functional/geth/test_provider.py
Was getting not-implemented error when would expect it to return True
if we started the process, ret true
if we get not impl error, assume true
```sh
ape console --network ethereum:local:node
```
```python
res = provider.auto_mine
```
=> fix: issue where checking `.auto_mine` in `geth --dev` raised `NotImplementedError`

src/ape/types/__init__.py, tests/functional/test_contract_event.py
When annotating with `Any` and validating with `HexBytes` types, the serializers will fail.
This is because Pydantic hasn't a way of knowing.
The fix is custom serializers in `ContractLog`.
Models annotating with `HexBytes` do no have this problem (what it was made for).
fixes: https://github.com/ApeWorX/eth-pydantic-types/issues/14
Custom serializers on contract log models
@fubuloubu knows
also see test
=> fix: serialized `HexBytes` for `Any` types in `ContractLog`

docs/index.rst
Uses new features from https://github.com/ApeWorX/sphinx-ape/pulls to improve the docs.
* Adds a book-like order to the userguides.
* Adds a plugin prefix so plugin python docs can be separated
auto TOC directive inputs
Use that sphinx-ape branch and build the docs:
=> docs: order guides and put back python-plugin separation

src/ape/api/networks.py, src/ape/pytest/plugin.py, src/ape/pytest/runners.py, tests/functional/test_network_api.py, tests/functional/test_test.py
Prevents running tests on mainnet network
1. If you default network is a mainnet, use Ape's regular default for ape test (eth:local:test or make them specify).
2. If the user passed in --network mainnet type network, exit out right away.
3. dont ask about 3
to test 1:
```yaml
ethereum:
default_network: mainnet
```
to test 2:
```sh
ape test --network ethereum:mainnet:alchemy
```
=> fix: prevent running tests on mainnet if configured as the default network

docs/userguides/config.md, tests/functional/test_config.py, tests/functional/test_project.py
This was an undocumented feature as of 0.8.0 but I actually want it to be a real feature because I am relying on it
* adds a test to make sure it continue working
* adds documentation for it
I am using it here: https://github.com/ApeWorX/ApeProjectTester/blob/main/ape-config.yaml
=> feat: properly support project-level settings

src/ape/cli/options.py, src/ape/logging.py, tests/functional/test_cli.py, tests/integration/cli/test_console.py
noticed `ape console -v debug` was not in debug mode...
index in range was wrong, it never change the final character.
```sh
ape console -v debug
```
should see the anon message thing
=> fix: `-v debug` wasn't working when at end of some commands

src/ape/api/networks.py, src/ape_ethereum/ecosystem.py, tests/functional/test_network_api.py, tests/functional/test_project.py
I need to be able to tell `ape-bsc` that `opbnb` should also be treated as a mainnet but i need this to do it.
So far, mainnet is used as a guard when set as default network to avoid accidentally running tests on it.
See https://github.com/ApeWorX/ape-bsc/pull/29 as an example
=> feat: support for non-mainnet named mainnet networks

src/ape/api/providers.py, tests/functional/test_block.py
* handle hex values in block validation for size
* handle hex values when injected in _size
* always serialize to int for size
field serializer on size to force to be an int even when it is not
=> fix: always serialize block size to int

src/ape/cli/options.py, tests/functional/test_cli.py, tests/functional/test_logging.py
more weird issues i guess where `-v debug` is not working... getting very annoyed at this.
the default was trigger the callback after was already set
use the default as the already set level to avoid resetting to INFO
use `-v debug`
=> fix: use already set level as default

src/ape/managers/chain.py, src/ape/pytest/fixtures.py, src/ape_node/provider.py, src/ape_test/provider.py, tests/functional/test_chain.py, tests/functional/test_provider.py
this bug is preventing us from using `ape test` to test ape.
this may fix other oddities with multi-chain tests and isolation.
* use chain ID when keeping track of snaps
* when disconnecting, also clear snaps from that cache
probably
=> fix: issue where snapshots lingered on disconnect

src/ape_test/__init__.py, src/ape_test/config.py, src/ape_test/provider.py
this makes it easier to do the necessary performance stuff on https://github.com/ApeWorX/ape/pull/2333/files#diff-a76530a2b0343d95792c603a53d55f5d38d7fe3466bebea906bec26bba0a86a3
make a new module in ape_test plugin config.py and put all config stuff in there
things work as they did before
=> refactor: move ape-test cfg to config module

src/ape/pytest/plugin.py, src/ape/pytest/runners.py, tests/functional/test_test.py
fixes: #2342
Move the config error to a later point, check for the `--network` flag.
cfg:
```yaml
ethereum:
default_network: mainnet
mainnet:
default_provider: node
mainnet_fork:
default_provider: foundry
```
then run
```
ape test
```
should fail
and run
```
ape test --network ethereum:local:test
```
should not fail
=> fix: issue running tests when `mainnet` is default network and specifying a different network

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
fixes: #2341
* call callable when callable
gas estimation fail + revert no message
=> fix: callable trace bug when estimating gas on revert-tx with no fail message

src/ape/types/basic.py, tests/functional/test_types.py
was just getting mehh conversion errors that didnt help much in this context.
was expecting pydantic errors instead
if None, dont try to convert. instead let it fail later on in pydantic
have a model using non-optional HexInt
ignore that key
ensure you get a nice pydantic validation error instead of a conversion error
=> fix: delay hex-int validation error when None values for non-optional

src/ape_ethereum/ecosystem.py, tests/functional/test_ecosystem.py
fixes: #2329
basically the problem was that tenderly nodes gave us a field `blobGasUsed: 0` for non-blob receipts (didn't see that field from other nodes so assuming is a bug).
in this case, if there is no blobGasPrice at all, just use the regular receipt cls instead, which makes the detection for shared blob receipt data extra strict
```yaml
node:
ethereum:
mainnet:
uri: https://gateway.tenderly.co/public/mainnet
```
and
```python
In [1]: txn_hash = '0x62fc9991bc7fb0c76bc83faaa8d1c17fc5efb050542e58ac358932f80aa7a087'
In [2]: provider.get_receipt(txn_hash)
```
=> fix: mistaken blob receipt causing serialization problems

src/ape/_cli.py, src/ape/plugins/_utils.py
when you have a trusted plugin installed, even if that plugin is also optimized like we did for the ones with core, it is still has a  small slowdown because of the trusted check, which makes 1 request to GitHub during `--help`
this PR hardcoded the trusted plugin to avoid the request altogether.
hardcode the trusted plugin
first install ape-tokens==0.8.1 (to get the full benefit, will still work on 0.8.0)
then
```sh
ape --help
```
Before i was seeing like 2.23 seconds..
Now I am seeing like 2 seconds
=> perf: hardcoded trusted plugin during `--help` check

src/ape/types/__init__.py, src/ape/utils/basemodel.py
since some of yall insist in importing things from wherever you damn please.
=> refactor: move basemodel types to `ape.types`

src/ape/__init__.py, src/ape/_cli.py, src/ape/cli/choices.py, src/ape/cli/commands.py, src/ape/cli/options.py, src/ape/exceptions.py, src/ape/managers/__init__.py, src/ape/types/basic.py, src/ape_accounts/__init__.py, src/ape_cache/_cli.py, src/ape_networks/__init__.py, src/ape_networks/_cli.py
I think this is better for a few reasons,
1. It may fix that weird bug with UV where it uses a different Ape suddenly when you are using `import_module()`
2. It looks a little nicer
3. It is less subject to bugs
Also had to get rid of `->Any` on those module lvl get attrs because it was causing typing issues
=> refactor: use raw import statements over `import_module` for lazy imports

src/ape_ethereum/__init__.py
this plugin is heavily imported from
before
```python
In [1]: %time import ape_ethereum
CPU times: user 2.09 s, sys: 545 ms, total: 2.63 s
Wall time: 1.71 s
```
after
```python
In [1]: %time import ape_ethereum
CPU times: user 8.22 ms, sys: 2.44 ms, total: 10.7 ms
Wall time: 9.53 ms
```
=> perf: lazy load treatment for `ape-ethereum` core plugin

src/ape/_cli.py, src/ape/plugins/_utils.py
Another big performance improvement for `ape --help`
Just when you thought you were no more...
Only load plugins for given CLIs, not all plugins
noticed it wasnt scaling very well, especially when you installed like every plugin in Ape
even none-cli ones
now, you can avoid tht by only processing the cli plugins.
we went from 1.5 seconds to show help o 1 second (when all plugins installed)
when no CLI plugins are installed, it is like 0.6 seconds
=> perf: only load necessary plugins for CLI

src/ape/_cli.py, src/ape_init/_cli.py
this may be problematic, not sure.
but the reason commands are so slow, like `ape init` is because of the pre-execution config validation.
i believe that was added as part of showing config errors and such, otherwise you may  run into weird problems and not really know why. but oh well, better to have a faster  command. Hopefully we can come up with a better config validation system, if we have to.
also adds `--name` flag to init so you can automate
Before:
```
ape init --name poop  3.46s
```
Now:
```
ape init --name poop  0.29s
```
delete helpful validation
things whip
=> perf: make all commands faster, especially `ape init`, adds `--name` flag to `init` cmd

src/ape/managers/project.py, tests/functional/test_project.py
Eliminate some internal nonsense users won't care about
=> fix: more helpful traceback for `__getattr__` on `project`

src/ape/managers/project.py, src/ape/pytest/runners.py, tests/functional/test_project.py
crushing bottle necks 1 by 1
Avoids config processing in the `project` init and move to `path` to property to make loading project faster
easiest way:
ipython
before:
```
In [1]: %time from ape import project
CPU times: user 2.93 s, sys: 580 ms, total: 3.51 s
Wall time: 2.57 s
```
after
```
%time from ape import project
CPU times: user 1.97 s, sys: 554 ms, total: 2.52 s
Wall time: 1.6 s
```
=> perf: able to load local project faster

src/ape/pytest/config.py, src/ape/pytest/contextmanagers.py, src/ape/pytest/coverage.py, src/ape/pytest/gas.py, src/ape/pytest/plugin.py, src/ape/pytest/runners.py
loading plugins is the main cause of a slow pytest, come to learn
Ape's wasn't helping either.
This makes Ape not th
Before:
```
pytest --help -s  4.31s user 0.78s system 119% cpu 4.240 total
```
After:
```
pytest --help -s  2.08s user 0.30s system 97% cpu 2.439 total
```
=> perf: Ape's pytest plugin performance improvements

src/ape/cli/options.py
Noticed `ape compile --help` was slow and I learned a thing or two about eager click options
=> perf: ape compile --help wasnt fast

src/ape/utils/_github.py, src/ape_plugins/_cli.py, tests/functional/utils/test_github.py
fixes: #2363
Two things
1. Avoid requesting anything from GH during `ape plugins list` (unless `--all`) is given. There is no need!
This is a performance boost as well:
Before:
```
ape plugins list  2.87s user 0.32s system 74% cpu 4.299 total
```
After:
```
ape plugins list  1.49s user 0.20s system 99% cpu 1.700 total
```
2. When receiving a 401 from bad auth in GH client, retry request w/o auth, as it likely will still work. Also, let the user know via a log warning.
```sh
export GITHUB_ACCESS_TOKEN="poop"
ape plugins list
ape plugins list --all
```
The first `ape plugins list` should be fine - no requests to GH are even made anywhere and it is faster.
The second request should still work! Only you get a warning now about your bad auth.
=> fix: `ape plugins list` bad auth and unnecessary requests

src/ape/cli/choices.py, src/ape/cli/commands.py
Before:
```
ape console --help  0.84s user 0.12s system 99% cpu 0.968 total
```
After:
```
ape console --help  0.27s user 0.05s system 97% cpu 0.322 total
```
Mostly by avoiding needing to import something from `ape.api.providers`
```sh
ape console --help
```
=> perf: make `ape console --help` faster

src/ape_test/__init__.py, src/ape_test/_cli.py, src/ape_test/_watch.py, tests/functional/test_test.py, tests/integration/cli/test_test.py
before:
```
ape test --help  1.59s user 0.20s system 99% cpu 1.803 total
```
now:
```
ape test --help  1.27s user 0.17s system 98% cpu 1.461 total
```
**note**: the time of `ape test --help` (e.g. `pytest --help`) largely depends on so many other things - conftests, plugins, etc.
move watch stuff out of cli directly and have it locally imported
=> perf: make `ape test --help` faster

src/ape_plugins/_cli.py
Before:
```
ape plugins --help  0.60s user 0.08s system 99% cpu 0.684 total
```
After:
```
ape plugins --help  0.30s user 0.04s system 98% cpu 0.346 total
```
imports
=> perf: make `ape plugins --help` faster

docs/userguides/networks.md, src/ape/api/networks.py, src/ape/managers/networks.py, src/ape/managers/project.py, src/ape_ethereum/provider.py, tests/functional/geth/test_network_manager.py
* Make it so if you connect to a network Ape hasn't an installed plugin for, it will look it up in evmchains and "just work"
* Make it so if you use a custom network e.g. connecting using a URL only, and that network is found in evmchains, it will set the correct names for the network
Use `evmchains` library.
First, I have no plugin for moonbeam installed, but yet i can do this:
```sh
ape console --network moonbeam
```
and it "just works"
Second, if I connect to a URL in the same fashion:
```sh
ape console --network "https://moonriver.unitedbloc.com"
```
Not only does it work (did before), but the network name and stuff is correct:
```
In [1]: provider.network.name
Out[1]: 'moonriver'
In [2]: provider.network.ecosystem.name
Out[2]: 'moonbeam'
```
taa daaaa
=> feat: lookup network in evmchains; plugin-less networks, adhoc networks w/ correct name

src/ape/contracts/__init__.py, src/ape/contracts/base.py, src/ape_node/provider.py, tests/functional/test_project.py
before:
```
time python -c "import ape.contracts.base"
python -c "import ape.contracts.base"  2.48s user 0.61s system 143% cpu 2.145 total
```
after:
```
python -c "import ape.contracts.base"  1.17s user 0.17s system 99% cpu 1.338 total
```
=> perf: make contracts load faster

src/ape_run/_cli.py
`ape run --help` was still slow because of a few reasons, mostly was the project access that i may look into on another PR.
Use `Path.cwd()` / "scripts"` locally.
Localize some imports as well.
Note: if you have a script module that is just slow to load, this wont help that ofc
(in a project with zero scripts)
BEFORE:
```
ape run --help  4.47s user 0.99s system 98% cpu 5.542 total
```
AFTER:
```
ape run --help  0.29s user 0.09s system 59% cpu 0.638 total
```
With scripts is also much faster, but you wil only be as fast as your slowest script to load in a project. CLI users should have the same knowledge that lazy imports are better for CLIs.
=> perf: make `ape run --help` faster

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
I put in a very non-URI value in my config to demo something and it blew up not how i expected.
This PR fixes it.
Noticed a comment was wrong, that was where to fix.
Basically make it error if given a value that is neither HTTP, WS, or IPC.
```yaml
node:
ethereum:
mainnet:
uri: asdfasdf
```
```sh
ape console --network ethereum:mainnet:node
```
Before, it would recurse until it failed.
Now, you get:
```
ERROR:    (ConfigError) Invalid URI (not HTTP, WS, or IPC): asdfasdf
```
=> fix: recursion error when a bad URI was configured in `node:`

src/ape_console/_cli.py
accidentally did a top level import in https://github.com/ApeWorX/ape/pull/2370
which caused a significant enough slow down to all of `ape --help`
```
ape --help  1.30s user 0.17s system 60% cpu 2.425 total
```
```
ape --help  0.95s user 0.13s system 57% cpu 1.887 total
```
=> perf: localize import for `ape console`

setup.py, tests/functional/geth/test_network_manager.py
Had a CI failure but the URL was actually fine, just was offline for a split second or something.
pytest-rerunfailures plugin
**NOTE:** Personally, plugins like this are a slippery slope and I think they should be avoided. If someone uses `flakey` markers, I will likely object and poke. However, in this situation, it makes sense because it involves an outside URL; I think that element really makes this test rich so I'd like to keep it, but ya it should be considered flakey since it is outside of our control.
CI doesnt fail now.
=> test: rerun random URL connection test if need-be

docs/userguides/developing_plugins.md, src/ape_node/__init__.py
noooooo i wish this was in the last release, so close to have a faster default Ape ecosystem..
(ipython)
before
```
In [1]: %time import ape_node
CPU times: user 1.14 s, sys: 142 ms, total: 1.28 s
Wall time: 1.29 s
```
after:
```
In [1]: %time import ape_node
CPU times: user 7.93 ms, sys: 3.39 ms, total: 11.3 ms
Wall time: 10 ms
```
BASICALLY once all our plugins have this treatment, stuff like `ape console` will be able to launch faster, if my research is correct. And i already have ideas of where the bottleneck moves to. We're optimizing.
=> perf: `ape_node` plugin load time improvement

.pre-commit-config.yaml, setup.py, src/ape/api/networks.py, src/ape/managers/networks.py, tests/functional/test_network_api.py, tests/functional/test_network_manager.py
* fixes: issue where couldnt use `getattr` approach for ecosystems from evmchains - only worked on connection but not when access.
* feat: make auto-forked networks happen for evm-chains based ecosystems (like we did for custom)
move some logic around
copy some idea from 1 place to another
```
moony = networks.moonbeam
rivery = moony.moonriver-fork
```
=> fix: auto fork evmchains networks and better access

setup.py, src/ape/managers/networks.py, tests/functional/test_network_manager.py
Thanks @bitwise-constructs for finding this before we released.
Fixed bug where evm-chains ecosystems were overriding ecosystems from plugins.
change order of dict comprenhension
have plugin installed
make sure uses plugin
=> fix(unreleased): bug where evm-chains ecosystems overrode plugin ecosystems.

src/ape/pytest/config.py, src/ape/pytest/plugin.py, tests/functional/test_test.py
Really small perf but doing it anyway.
Small in that you can't really see it when measuring, but slightly less stuff happens now when passing --help and code is cleaner feeling and more testable. So all good things.
Move logic to ctor
things still work as they did
=> perf: move no-capture check to the inside of the `ConfigWrapper` constructor; avoid when only `--help`

setup.py, src/ape/api/query.py, src/ape/contracts/base.py, src/ape/managers/chain.py, src/ape/managers/converters.py, src/ape/utils/basemodel.py, tests/functional/test_project.py
Pydantic 2.10 is a bit strange...
model_fields return type changed, according to mypy, but couldn really find it.
also had to fix a URL change in ethpm-types were file urls were no longer considered urls
also model_copy signature changed, but that wasnt a huge deal
=> feat: support Pydantic 2.10

docs/userguides/projects.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "Notice that you can configure `you` ape project" to "Notice that you can configure `your` ape project".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

setup.py, src/ape_ethereum/provider.py, src/ape_node/provider.py, tests/functional/geth/test_provider.py
Connecting to an already running IPC process or WS-only geth was working great.
However, I could not start one from the beginning this way...
Adjust the implementation geth dev process class to handle more connecton inputs, this is the class that actually manages the process when starting it in the `ape-node` plugin, not the SubprocessProvider class from `ape-ethereum`, this one comes from the `py-geth` package.
WITHOUT ALREADY HAVING IT RUNNING:
```yaml
node:
ethereum:
local:
uri: ws://localhost:5550
#uri: "http://localhost:5550"
#uri: /Users/jules/.ape/node/geth.ipc
```
Comment out the URI types not being used and ensure it works.
More to test and such, opening PR early...
=> fix: Could not start a Geth process with only WS or IPC

docs/userguides/config.md, docs/userguides/proxy.md, tests/README.md
Changes Overview
This PR addresses several grammatical and spelling issues across multiple documentation files to improve clarity and correctness.
1. docs/userguides/config.md
Old: "Project settings take precedent"
New: "Project settings take precedence"
Reason: Corrected usage of "precedence" (priority/importance) vs "precedent" (previous example/case)
2. docs/methoddocs/proxy.md
Old: "The following proxies are supporting in ape-ethereum"
New: "The following proxies are supported in ape-ethereum"
Reason: Corrected verb tense to passive voice for better technical documentation clarity
3. docs/methoddocs/proxy.md
Old: "Ape will check the address you give it and detect if hosts a proxy contract"
New: "Ape will check the address you give it and detect if it hosts a proxy contract"
Reason: …
=> chore: Fix Grammar and Spelling Issues

setup.py, src/ape/api/networks.py, src/ape/cli/choices.py, src/ape/cli/options.py, src/ape/managers/networks.py, src/ape/managers/plugins.py, src/ape/managers/project.py, src/ape_console/_cli.py, src/ape_test/provider.py, tests/functional/test_cli.py, tests/functional/test_console.py, tests/functional/test_ecosystem.py
doing what i can to get `ape console` to launch faster.
Mostly centers around connecting to networks faster
Also some other small perfs...
Am still working on the main bottle neck..
Before:
```
(ape_no_plugins) ➜  ape git:(main) time ape console
In [1]: exit
ape console  4.79s user 0.61s system 91% cpu 5.916 total
(ape_no_plugins) ➜  ape git:(main) time ape console
In [1]: exit
ape console  4.49s user 0.55s system 94% cpu 5.333 total
```
After:
```
ape console  3.87s user 0.64s system 101% cpu 4.460 total
(ape) ➜  ape git:(perf/console) time ape console
In [1]: exit
ape console  3.74s user 0.57s system 100% cpu 4.274 total
```
obviously this network dependent and such
=> perf: getting `ape console` to launch faster

.github/workflows/test.yaml, pyproject.toml, setup.py
Adds in support for Python 3.13
fixes: 2392
Fixes: APE-1855
=> feat: support python 3.13

src/ape/api/networks.py, src/ape/managers/networks.py, tests/functional/test_network_manager.py
Instead of `mainnet-fork-fork`, you just get another `mainnet-fork` process with a different port
Fix name and use auto host
(ape) ➜  ape git:(feat/allow-forking-a-fork) ✗ ape console --network ethereum:sepolia
```
In [1]: with networks.fork("foundry") as provider:
...:     print(provider.uri)
...:     with networks.fork("foundry") as prov2:
...:         print(prov2.uri)
...: 
INFO:     Starting 'anvil' process.
INFO:     Connecting to existing Geth node at https://eth-sepolia.g.alchemy.com/[hidden].
http://127.0.0.1:8545
INFO:     Starting 'anvil' process.
http://127.0.0.1:52015
INFO:     Stopping 'anvil' process.
INFO:     Stopping 'anvil' process.
```
=> feat: allow forking a forked network

setup.py, src/ape/utils/_web3_compat.py, src/ape_accounts/accounts.py, src/ape_ethereum/provider.py, src/ape_node/provider.py, src/ape_test/accounts.py, tests/functional/geth/test_provider.py, tests/functional/test_ecosystem.py
work was already done in another branch but after discussing with @fubuloubu a couple weeks ago, we are going to push forward with it before 0.9
=> feat: support web3.py v7 (in addition to v6)

src/ape/utils/__init__.py, src/ape/utils/rpc.py, src/ape_ethereum/provider.py, tests/functional/test_provider.py
I created a util for handling rate-limit retry, inspired by https://github.com/ApeWorX/ape-alchemy/pull/35/
I am hoping to start using this everywhere.
inspired by wakamex's work
=> feat: adds a rate limiting utility method and uses it in `ape-node` provider

src/ape_node/provider.py, tests/functional/geth/test_provider.py
how many times have you seen intermittent failures like:
```
(32000) gas exceeds block gas limit
```
We get intermittent failures in the tests I think because of x-dist used with geth --dev and the gas limit changing somehow.
This PRs adds a retry mechanism here (only for geth --dev).
Detect the error.
Reset the gas limit + resign if it can
Resend
no more intermittent failures in tests (Will know after a while)
also - adds a unit test
=> feat: fix + retry transaction for `geth --dev` when gas limit exceeds block gas limit

docs/userguides/testing.md, src/ape/__init__.py, src/ape/exceptions.py, src/ape/managers/chain.py, src/ape/pytest/fixtures.py, src/ape/pytest/plugin.py, src/ape/pytest/runners.py, src/ape/pytest/utils.py, src/ape/pytest/warnings.py, src/ape_test/provider.py, tests/functional/test_exceptions.py, tests/functional/test_fixtures.py, tests/functional/test_plugins.py, tests/functional/test_project.py, tests/functional/test_provider.py, tests/functional/test_test.py, tests/integration/cli/projects/test/tests/conftest.py, tests/integration/cli/projects/test/tests/test_fixture_isolation.py, tests/integration/cli/projects/test/tests/test_fixture_isolation_session.py, tests/integration/cli/test_test.py
Make isolation "work" on session, package, module, and class scopes.
Basically, the bug was that as new fixtures of certain scopes come in after a snapshot was taken in that scope, they wouldn't really persist as the scope below left, like if the module changes or something
fixes: #2262 
fixes: #1287 
Awful. Basically the only way to fix this is to rebase the blockchain as new upper scopes up.
A new session comes in later, we have to undo to the module (or closest lowest) snapshot invalidate those fixture, inject those fixtures in the correct order, and re-set all the snapshots.
Can technically uses scopes / parametrized fixtures in any way now... and it should also "work"... it is just is slow if using higher scoped fixtures later on in the test suite, can be really bad actually. I …
=> fix: update isolation as new fixtures of certain scopes arrive

setup.py, src/ape/managers/converters.py, src/ape_accounts/_cli.py, src/ape_ethereum/ecosystem.py
=> feat: implement cchecksum for ~2x faster checksumming

src/ape/utils/os.py
=> refactor!: remove `is_relative_to()` (unused) util method

setup.py, src/ape/contracts/base.py, src/ape/exceptions.py, src/ape/managers/chain.py, src/ape_ethereum/provider.py, tests/functional/test_contract_container.py, tests/functional/test_exceptions.py
Just simplifies the exception a bit.
=> refactor!: use provider in contract error instead of network choice string

src/ape/managers/config.py, src/ape/utils/basemodel.py
Small refactor, moves an import to a place that makes more sense. Noticed while doing some 0.9 stuff
=> refactor: set `ConfigManager.request_header` in ctor instead of in module namespace

tests/functional/test_provider.py
moves an assertion to happen in each test case.
am investigating the TODO but this was a small win we could do now
=> test: improve ipc path test

src/ape/api/networks.py, src/ape/managers/chain.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/proxies.py, tests/functional/geth/conftest.py, tests/functional/geth/test_contracts_cache.py, tests/functional/geth/test_proxy.py, tests/functional/test_accounts.py, tests/functional/test_contract_container.py, tests/functional/test_contract_instance.py, tests/functional/test_proxy.py
fixes: #1249
I could no longer call `masterCopy()` in a safe proxy since https://github.com/ApeWorX/ape/pull/2400
I not 100% sure why but this PR fixes it.
I think before, it was never actually recognized as a safe proxy...
Anyway, the `masterCopy()` ABI is sort of hidden.
And proxy ABIs in general (that were not hidden) were not included in the contract-types ABIs you could call.
This PR makes both of those things work.
1. When detecting proxies, allow a place for ABIs to be included (not in the cache but just in the API). This helps `masterCopy()` be included.
2. When looking up a contract-type, also check to see if there is proxy info. If there is, it includes some of the ABIs if it is not already there. This way, past cached contract types (safes) will also suddenly work when calling …
=> feat: include proxy ABIs in contract-type ABIs

docs/userguides/dependencies.md, src/ape_pm/dependency.py, tests/functional/test_dependencies.py
Prep work for 0.9, deprecates a key and adds the other one in a non-breaking way.
In 0.9 we can fully remove now.
=> feat: use preferred `.site_package` key instead of `.python` for less confusion

pyproject.toml, src/ape/pytest/config.py, src/ape_test/config.py, tests/functional/test_test.py, tests/integration/cli/test_test.py
I noticed the last fail on merge to main failed...
I then realized some of the stack-trace is missing.. hmm..
Coincidentally, I also noticed this in `ape-safe`, which also uses Ape to test itself.
Thus, I remember the cursed `--show-internal` flag.
How can I just configured this on? Well I could use pytest's `addopts` but that always messy to me and is more of a last resort.
Instead, I made it so you can configure ape this way.
Then I remember I can configure Ape right in the Ape pyproject.toml file. Rad.
This makes sense to be configured for the framework itself, since that is its point
=> feat: allow ``--show-internal`` to be configured and use in framework's tests

src/ape/api/projects.py, src/ape/managers/project.py, src/ape_pm/__init__.py, src/ape_pm/_cli.py, tests/functional/test_dependencies.py, tests/integration/cli/projects/only-dependencies/ape-config.yaml, tests/integration/cli/test_compile.py, tests/integration/cli/test_pm.py
If you have a project that lists a site-package based dependency, such as `snekmate:` (OR an `npm` dependency such as OZ), but that package is not installed in your site-packages / node_modules, the `version_id` will fail, causing complete madness in Ape.
basically handle exceptions everywhere
tbd
=> fix: Python & NPM dependencies when not installed in Python/NPM cause `ape pm list` to fail

src/ape/api/transactions.py, src/ape_ethereum/trace.py, tests/functional/geth/test_trace.py
small perf but just to get me started:
```
before:
10 passed in 74.92s (0:01:14)
10 passed in 74.68s
after:
10 passed in 73.99s (0:01:13)
10 passed in 73.17s (0:01:13)
```
must also use https://github.com/ApeWorX/ape-foundry/pull/121
* caching
* avoid some unnecessary computes
=> perf: minor `trace` improvements

src/ape_ethereum/ecosystem.py, tests/functional/test_ecosystem.py
some tests in foundry show up using `SharedBlobReceipt` which seemed odd.. They had 1 field `blob_gas_price: 1`, seems like just random data coming along.. hoping this solution is more precise
rely on type being 3
tell me if im wrong i guess, i havent fully researched and am just going off my understanding, i dont really blob
=> fix: issue where used `SharedBlobReceipt` instead of `Receipt`

src/ape/pytest/fixtures.py, tests/functional/test_test.py
Received an `AttributeError` for a provider that hadn't used `TestProviderAPI` as a sub-class (stuck to `ProviderAPI`).
This is the only thing really stopping it so worth fixing it. The downside to not using `TestProviderAPI` as a base is you don't opt in to many of the features, but that should still be allowed
handle attribute error; return None (unknown) for statefulness
make and use a provider that isnt a TestProviderAPI subclass
=> fix: handle when a provider is not `TestProviderAPI` subclass during ape-test fixture setup

src/ape/pytest/config.py, src/ape/pytest/fixtures.py, src/ape/pytest/runners.py, src/ape_test/config.py, tests/functional/test_test.py, tests/integration/cli/test_test.py
kinda a use-at-your-own risk feature of disabling fixture rebasing, maybe some users be ok with that and will have somewhat invalid state but if it works and is fasster, perhaps is ok.. cannot yet atest to this being helpful but i think having the ability to disable will at least help meeee debug crap
=> feat(pytest): allow disabling fixture rebasing

src/ape/api/providers.py, tests/functional/test_block.py, tests/integration/cli/test_run.py
Got a weird error in my boa provider because dont have hashes yet for blocks, tracked it down to the transactions.
Also fixed repr so wouldnt even need to bother with txns during repr. double fix...
```
block.hash = None
repr(block)
block.transactions
```
=> fix: issue with Block transactions when `block.hash` was `None`

setup.py, src/ape_ethereum/transactions.py, tests/functional/test_receipt.py
providers should not be expected to checksum addresses the user doesnt need to deal with yet
(for performance reasons)
raw log data seems acceptable to not require checksumming
use lower for decoding logs match checks
my thing in ape-titanoboa works now
see test as well...
=> fix: handle when log address is not checksummed when decoding

src/ape/api/networks.py, src/ape/api/providers.py, src/ape_node/provider.py, tests/functional/test_network_api.py
this allow plugins like `ape-titanoboa` use the name `boa` instead of `titanoboa`.
NAME
(also see the TODOS, itll be cleaner in 0.9)
```
pip install path/to/ape-titanoboa
ape console --network ::boa
```
=> feat: allow provider plugins to define NAME at class-level

src/ape/api/accounts.py, src/ape/api/networks.py, src/ape_ethereum/ecosystem.py, tests/functional/test_accounts.py, tests/functional/test_ecosystem.py
fixes: #926
rlp encode address and the nonce
some ecosystem-api delegation
call the method
deploy
make sure are same address
=> feat: ability to get deployment addresses before deploying

docs/userguides/developing_plugins.md
The word "name" should be in the plural form because it refers to both the module name and the plugin directory name.
Corrected to "names"
=> docs: typo fix Update developing_plugins.md

src/ape/utils/abi.py, tests/functional/utils/test_abi.py
boa gives us log data  that is not always padded with leading zeroes.
i dont see why i cant just pad it myself and move on...
NOTE: We won't need this if this merges instead: https://github.com/ethereum/eth-abi/pull/240
make a custom decoder for uint25
question: is this supposed to happen even when strict=False? ill ask the snake charmers...
see my test
=> fix: could not decode ABIs when missing leading zeroes

src/ape/api/transactions.py, tests/functional/test_transaction.py
THIS ALLOWS US TO USE OUR TRANSACTION MODEL IN THE EVM DIRECTLY.
sorry idk why i put that in all caps...
simple alias to make transactions work better in vm directly for performance, hoping to avoid having to use so many models in boa.
=> feat: alias `tx.gas` for `tx.gas_limit` and `tx.hash` for `tx.txn_hash`

src/ape/managers/chain.py, src/ape_ethereum/provider.py, src/ape_test/provider.py, tests/functional/test_provider.py
I couldnt really send transactions when auto mine was off.
All testing providers should be audited for this.
fixes: #2439 
early return when auto_mine is False rather than waiting and timing out.
note: some more work is needed for the smart-receipt stuff to be better in 0.9, but this at least allows you to transact with auto_mine is False.
1. turn auto mine off
2. make transactions
3. mine
4. ensure transactions went through
=> fix(ape-test): issue where couldn't transact when `auto_mine=False`

src/ape/api/accounts.py, tests/functional/test_accounts.py
=> fix: improve error for transfer argument mixup

src/ape_ethereum/provider.py, src/ape_ethereum/transactions.py, src/ape_test/provider.py, tests/functional/geth/test_receipt.py, tests/functional/test_receipt.py
fixes: #2438 
Fixes: APE-1867
add it in manually
`receipt.transaction.txn_hash` should not fail with sig error
=> fix: transaction was missing signature / couldn't get hash when came from receipt

src/ape_ethereum/provider.py, src/ape_test/provider.py, tests/functional/geth/test_provider.py
same as https://github.com/ApeWorX/ape/pull/2443 but for providers like foundry/hardhat
sorry, test is a little weird because cant actual disable auto mine in geth --dev (i dont think anyway)
=> fix: unable to send transactions during manual mining in other providers

src/ape/api/networks.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, src/ape_node/provider.py, src/ape_test/provider.py, tests/functional/geth/test_network_manager.py, tests/functional/geth/test_provider.py, tests/functional/test_cli.py, tests/functional/test_network_manager.py
fixes: https://github.com/ApeWorX/silverback/issues/179
When a URI is configured or passed in for a connection, use that in `provider.network_choice`
silverback uses the configured URI everywhere now.
I made sure:
=> fix: include URI in `provider.network_choice`

setup.py
Bumped py-geth because it was giving a `ModuleNotFoundError: No module named 'pkg_resources'` Error when connecting to networks. 
Py-geth has been tested on both web3[tester] 6.20.3 and 7.6.1 to ensure that it works on both versions of web3. 
fixes: #
=> chore: bump py-geth

CONTRIBUTING.md
**-pip install -e .'[dev]'
+pip install -e .[dev]**
**-pip install -e .'[doc]'
+pip install -e .[doc]**
> Reasons for changes:
The old version with quotes and dot (.'[dev]' or .'[doc]') could lead to installation errors as pip would incorrectly interpret the package path
The new version (.[ ]) is the standard pip syntax for specifying additional dependencies (extras)
This format is the widely accepted and documented way to install packages with extra dependencies
These changes make the installation commands correct and ensure their proper execution.
=> fix: correct pip install syntax for dev and doc extras

src/ape_ethereum/trace.py, tests/functional/test_trace.py
fixes: #2451 
getattr check with default
=> fix: dont assume has client version

src/ape/utils/testing.py, tests/functional/geth/test_provider.py, tests/functional/geth/test_trace.py, tests/functional/test_exceptions.py, tests/integration/cli/test_console.py
=> refactor!: change default test chain ID to match foundry's

src/ape/api/networks.py, src/ape/managers/chain.py, src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py, tests/functional/test_provider.py
this part was not utilizing the chain ID cache, so this could save a request (or many)
=> perf: utilize chain ID cache on re-connect in Ethereum node provider

docs/userguides/config.md, src/ape/utils/misc.py, tests/functional/test_config.py
allow ape-config to use:
```
[project]
name = "myproject"
```
and use that as the project name so you don't necessarily have to do both configs (tool.ape as well)
during config load from file, grab it.
make a project with pyproject.toml like
```
[project]
name = "myproject"
```
```sh
ape console -c "print(project.name)"
myproject
```
=> feat: config can load project name from `pyproject.toml` project setting

src/ape/managers/accounts.py, src/ape_test/accounts.py, tests/functional/test_accounts.py
fixes an issue where negative indices could get cached thus causing them to no longer refer to their calculated index.
also fixes the performance of the repr methods in both account managers, as it was very slow with some experimental account plugins installed.
basically just a bunch of fixes to test-accounts that i found when working on the new `ape-titanoboa` plugin.
fixes: #2436 
Fixes: APE-1865
```
BEFORE:
In [1]: %time accounts.test_accounts
Wall time: 17.1 ms
Wall time: 10 μs
In [1]: %time accounts.test_accounts[5]
Wall time: 329 ms
Wall time: 30 μs
In [1]: %time accounts.test_accounts[0].address
Wall time: 344 ms
Wall time: 250 μs
AFTER:
In [1]: %time accounts.test_accounts
Wall time: 10.4 ms
Wall time: 7.87 μs
In [1]: %time accounts.test_accounts[5]
Wall time: 335 ms
Wall time: …
```
=> fix: test-account negative index did not refer to correct account

src/ape/api/networks.py, src/ape/managers/compilers.py, src/ape/managers/networks.py, src/ape_ethereum/provider.py, tests/functional/test_network_api.py
This bug did not reveal itself until functionality was required on it, meaning it always was doing this but never mattered until now.
It is supposed to use the generic Node class, not GethDev, but they both come from the same provider and the order is not deterministic so sometimes it would be one or the other. However, the chain ID caching mechanism fails if it is does not use the Node class (as of https://github.com/ApeWorX/ape/pull/2464), so it became a bug at that point, thankfully not released yet.
fixes: https://github.com/ApeWorX/ape/pull/2449#issuecomment-2585322375
adjust if statement to ensure right class
you can consistently use custom networks again
=> fix: custom network would sometimes use the wrong provider class

src/ape_ethereum/provider.py, tests/functional/test_provider.py
last night's PR https://github.com/ApeWorX/ape/pull/2466/files broke the use-case on accident when you do `--network https:///`, this fixes it
really had to discen adhoc from custom here. custom uses hardcoded chain id whereas adhoc does not
=> fix: adhoc network connection fix

src/ape/managers/_contractscache.py, tests/functional/test_contracts_cache.py
inspired by https://github.com/ApeWorX/ape/issues/2465
added a kwarg to skip or provide proxy info to Contract("0x..."
new kwarg to `chain.contracts.instance_at()`
`Contract("0x123...", proxy_info=proxy)`
or
`Contract("0x123...", detect_proxy=False)`
=> feat: ability to skip proxy detection

pyproject.toml, src/ape/api/address.py, src/ape/managers/_contractscache.py, src/ape/managers/chain.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/query.py, src/ape_test/accounts.py, tests/functional/conftest.py, tests/functional/geth/test_chain.py, tests/functional/geth/test_contracts_cache.py, tests/functional/test_project.py, tests/functional/test_proxy.py
Caches code, which is easier to do now that selfdestructs don't matter.
So there are a couples times when not to cache however such as during dev because of chain isolation and also when specifying `block_id=` because you likely are checking for contract creation at a certain time.
caching happens at the chain manager level, which is a familiar pattern.
The provider always checks the RPC, as should be its job.
fixes: #482
=> fix: cache `.get_code()`

src/ape/managers/project.py, src/ape/utils/os.py, tests/functional/test_project.py
this'll help the ape-vyper refactor im doing, makes it a smidge simpler
=> feat: context-manager for switching into a project's directory

src/ape/api/accounts.py, src/ape/contracts/base.py, tests/functional/test_accounts.py, tests/functional/test_contract_instance.py
allows setting `sign=False` when making transactions.
I am thinking this is the first step to getting a faster titanoboa integration, helps us avoid signing the transactions
=> feat: allow setting `sign=False` on transactions (good for titanoboa)

src/ape_test/provider.py, tests/functional/test_accounts.py, tests/functional/test_provider.py
I was trying to demo something and was not able to do even the most basic transactions with eth-tester for some reason because of a base fee issue... Not sure why this hasnt come up in the test, but whatever here we are.
use pending block base instead of latest.
my demo works now
=> fix: eth-tester was failing with too-low base fee errors

.pre-commit-config.yaml, setup.py, src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
I tried using `mode` network but ran into an issue because it was not on the evm-chains package so I just needed to configure it (can also add it to that package if i get a chance), but anyway this error message would have been helpful as I was looping through a bunch of networks when I hit this.
Include network names in the error message.
I added a test, trust me bro
=> fix: improve error message when URI missing

setup.py, src/ape_node/provider.py, tests/functional/geth/test_provider.py
This allows changing the block time (dev-period) in the geth dev provider in Ape.
It requires this PR for py-geth: https://github.com/ethereum/py-geth/pull/248
=> feat: allow setting block time in `geth --dev` provider

src/ape_node/provider.py, tests/functional/geth/test_provider.py
This was bad for me; it should only have deleted the files it needed to delete, not the entire folder.
Delete the known geth-dev files instead of the entire folder during disconnect.
=> fix: `GethDevProcess.disconnect()` deleted the entire data folder on disconnect

docs/userguides/logging.md, src/ape/cli/options.py, src/ape/logging.py, tests/functional/test_logging.py
This works towards one of the 0.9 goals of improving logger / getting logging out of CLI commands for pipe-ing.
At least now you can do `-v NONE` for some cases and you will only get the output you expected
=> feat: improve means to disable logging in ape

src/ape/managers/_deploymentscache.py, src/ape/utils/basemodel.py, tests/functional/test_deploymentscache.py
In my weird setups, I ended up getting a `KeyError` in a place I probably shouldn't have.
This fixes that.
Also, `__contains__` on the disk cache never terminated... fixed that too.
One more thing, file dumping didn't work when the directory didn't exist, so it'll make the dirs now when dumping.
=> fix: `KeyError` on deployments-cache

src/ape/logging.py, tests/functional/test_logging.py
useful for CLIs where output is important.
part of the 0.9 goals as well
=> feat: `@ape.logging.silenced` decorator for ensuring an entire method does not log

src/ape/api/convert.py, src/ape/managers/converters.py, src/ape_ethereum/_converters.py, tests/functional/test_converters.py
This helps me access the ENS conversion class, which makes more sense than any of these, but is still helpful.
This is what I have to do in the meantime to get access to ENS in the ape-ens tests:
```
@pytest.fixture(scope="session")
def converter(chain):
converters = chain.conversion_manager._converters[AddressType]
for converter in converters:
if isinstance(converter, ENSConversions):
return converter
pytest.fail("Failed to find ENS converter registered in Ape.")
```
Ape should be good about testing stuff like `ape-ens`
=> feat: ability to get conversion classes by name

docs/userguides/accounts.md, src/ape/api/accounts.py, src/ape/managers/accounts.py, src/ape/managers/project.py, src/ape_accounts/accounts.py, src/ape_test/accounts.py, tests/functional/test_accounts.py
Adds some improvements for changing the mnemonic.
* setter for `mnemonic` so you can do:
```python
from ape import accounts
accounts.test_accounts.mnemonic = "my new seed"
print(accounts.test_accounts[0].address)
```
fixes: #2498
=> feat: add `mnemonic` setter

src/ape/plugins/_utils.py, src/ape_plugins/_cli.py, src/ape_run/_cli.py, tests/functional/test_plugins.py, tests/integration/cli/test_plugins.py
Two things on this PR:
1. fix: `ape plugins list` was including plugins in the wrong spot
2. feat: adds `--format` option to `ape plugins list` so that i can get it in freeze mode, similar to `pip list --fromat=freeze`
```
ape test tests/integration/cli/test_plugins.py --runxfail
```
=> feat: `ape plugins list` section-header fix AND allowing `--format freeze` option

.pre-commit-config.yaml, setup.py, src/ape/managers/accounts.py, src/ape/plugins/network.py, src/ape/plugins/project.py, src/ape/plugins/query.py, src/ape/types/events.py, src/ape_ethereum/ecosystem.py, tests/functional/test_accounts.py, tests/functional/test_provider.py, tests/functional/test_types.py
I was frustrated this wasn't available, so this makes it available.
1. When getting logs from the provider, use a private property
2. Do a lookup from the address => contract type to find the abi and cache it.
3. craft a default one, last case scenario, this needs works but is very rare and doesnt probably show up
=> feat: adds `.abi` property to `ContractLog`

setup.py, src/ape/types/events.py, src/ape/utils/abi.py, tests/functional/test_provider.py, tests/functional/test_types.py
I need this for implementing `get_contract_logs()` in `ape-titanoboa`
=> feat: adds `ContractLog.topics` property for calculating the topics from a log

src/ape/api/accounts.py, src/ape/api/address.py, src/ape/api/networks.py, src/ape/exceptions.py, src/ape_ethereum/transactions.py, src/ape_test/accounts.py, tests/functional/test_contract_instance.py
it is difficult to test this without a provider that can handle impersonated accounts (can't wait for boa to be part of ape core).
but if your account is a contract and you call a fallback method on another contract, the transaction would never get prepared causing you to have to manually specify `nonce=` and everything else you neeed.
* move `prepare_transaction()` to `BaseAddress` class.
* if the given sender isnt an account but is base-address, still do the `prepare_transaction()` part.
I had to add exception kwarg to `SignatureError` so i can at least verify the txn data is now populated.
I also confirmed with breakpoint and it unblocks me someplace else too. added a test.
=> fix: default call transactions would not get prepared when sender is a contract

src/ape/managers/config.py, tests/functional/test_config.py
allows the `keep=` keyword to pass along items when isolating the data dir..
this is just something helping me switching to use our ape action, i want to keep the data dir isolated in our tests but also copy in the dependencies so we don't have to redownload them. In any case, it is a nice feature though.
=> feat: allow keeping stuff when isolating data dir

src/ape/managers/project.py, src/ape/utils/os.py, tests/functional/test_project.py
we already had `project.chdir()`, but this makes it so you can also do:
```
with project.chdir():
...
```
this is useful for situations where we really just need `.local_project` to be something different, such as testing the framework itself.
made a `ChangeDirectory` context manager and used it
=> feat: allow `project.chdir()` to work in a context

src/ape/managers/chain.py, tests/functional/test_chain.py
I wanted to be able to get the balance of the my ENS name more easily so that is the intent of this.
```
chain.get_balance("myname.ens")
```
=> feat: addd `chain.get_balance()` method

src/ape/managers/accounts.py, src/ape/managers/chain.py, src/ape_console/plugin.py, tests/functional/test_accounts.py
It is much easier to resolve ENS names from an active Ape console now:
```
(apedev13) ➜  ape git:(feat/resolve-account) ✗ ape console                           
In [1]: accounts.resolve("vitalik.eth")
Out[1]: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045'
```
=> feat: `accounts.resolve_address()` method for resolving input into address types

src/ape/api/transactions.py, tests/functional/test_accounts.py, tests/functional/test_transaction.py
Transaction showed data like (3 bytes)
```
data: 0x307833...303762
```
but is now (4 bytes):
```
data: 0x30783334...30303762
```
fixes: #2519
=> fix: show first 4 bytes of transaction data in signing string (instead of 3)

.pre-commit-config.yaml, pyproject.toml, setup.py, src/ape/managers/_contractscache.py, tests/functional/conftest.py, tests/functional/test_accounts.py, tests/functional/test_contract.py, tests/functional/test_contract_container.py, tests/functional/test_contract_instance.py, tests/functional/test_contracts_cache.py, tests/functional/test_ecosystem.py
It seems to unnecessarily use the explorer when you provider the proxy manually and the contract type is already cached.
=> fix: unnecessarily was using explorer when providing proxy info manually

tests/functional/test_ecosystem.py
This pull request introduces the `max_priority_fee parameter` to the `test_create_transaction_with_none_values` function in the `test_ecosystem.py` file. 
This addition allows for more flexibility in transaction creation by specifying a maximum priority fee, which can be useful for optimizing transaction processing in Ethereum.
**Changes made:**
Added `max_priority_fee=None` to the function parameters.
This update aims to enhance the testing capabilities of the transaction creation process.
=> Add max_priority_fee parameter to test_create_transaction_with_none_values

src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py
Ape will now retry up to 10 times before failing to find an RPC using the random public RPC feature
fixes: #2533 
Connect and make sure it is available before giving up
```sh
$ ape console --network :mainnet:node
WARNING:  RPC at 'https://rpc.mevblocker.io/noreverts' not available, retrying 10 more times
INFO:     Connecting to a 'mevblocker' node.
```
=> fix(node): try up to 10 public nodes before failing random RPC method

src/ape/managers/project.py, src/ape/utils/_github.py, tests/functional/test_dependencies.py, tests/functional/utils/test_github.py
if the HTTP returned 404 it was not showing anywhere for a few reasons
this is how i stupidly was configuring it:
```
dependencies:
- name: aragon
ref: 1.3.0
github: git@github.com:aragon/osx.git
```
=> fix: `ape pm install` didn't show error in some cases

docs/userguides/dependencies.md, src/ape/managers/project.py, src/ape_pm/_cli.py, tests/integration/cli/test_pm.py
Allow existing package ID / name for package argument in `ape pm install` command.
Before, it only expected new dependencies here, but since we introduced the concept of "uninstalled" dependencies (not installing unless asked in a project config), this feature was missing.
So do stuff like
```
ape pm install OpenZeppelin/openzeppelin-contracts --version "5.0.0"
```
when it is already in your config like:
```
[[tool.ape.dependencies]]
name = "openzeppelin"
github = "OpenZeppelin/openzeppelin-contracts"
version = "5.0.0"
```
=> feat: `ape pm install` command supports package ID

src/ape/api/networks.py, src/ape_ethereum/provider.py, tests/functional/geth/test_provider.py, tests/functional/test_provider.py
In one terminal do:
```
geth --dev
```
**Notice the IPC path it spits out.**
In another do,
```
ape console --network <path/to/gethdev/ipc>
```
It was failing before, thinking the network was hardcoded. But now, it should realize it isn't.
=> fix: unable to connect to adhoc local network when using IPC

docs/userguides/networks.md, setup.py, src/ape/api/providers.py, src/ape/managers/networks.py, src/ape/utils/basemodel.py, src/ape_ethereum/provider.py, src/ape_networks/_cli.py, src/ape_node/provider.py, tests/functional/geth/test_network_manager.py, tests/functional/test_network_manager.py, tests/functional/test_provider.py, tests/integration/cli/test_networks.py
Allows flows like this:
```
ape networks run --network ::node --background
ape networks list --running
ape networks ping --network ::node
ape networks kill --all
```
basically Ape now tracks the processes it has started and you can easily kill them all from the command line as well more easily background the processes in the same terminal session and w/o losing the PID
fixes: #2528 
Also allows 
```python
with networks.parse_network_choice("pid://12345") as running_node":
...
```
For connecting to local nodes processes via PID.
**Note**: this process must have been started by Ape for this to work currently though.
copied this from the `dfx` tool: https://github.com/dfinity/sdk
tbd
=> feat: local network process MGMT CLI

pyproject.toml, src/ape/managers/project.py, tests/functional/test_project.py
If you are using a non-local project with a source ID that happened to exist in the local project, it would mistakenly return you the wrong paths, which was kinda bad and caused bugs.
Require the source ID also to have the right base path before early returning
=> fix: issue where `project.sources.lookup()` returned wrong path in certain conditions

src/ape_pm/compiler.py, tests/functional/test_compilers.py, tests/integration/cli/test_compile.py
kinda a weird bug but it threw me for a loop, I tried to clean up the logic a bit and fix it.
Check `.is_absolute()` instead of `.is_file()` in the case of checking if path is relative to the given project.
See my test, requires a very oddly specific setup.
=> fix: interface compiler would compile the wrong interfaces when source ID matched local project

src/ape/managers/project.py, tests/functional/test_project.py
`project.unpack()` was not properly handling interfaces... The condition was flipped mistakenly so it would double unpack them... That is fine, but it still would unpack them in the wrong spot anyway, with an extra nested `"interfaces"` keyword.
get the relative path from the parent of the project's path instead of the project's path
=> fix: bugs where interfaces would unpack in the wrong spot

src/ape/plugins/_utils.py, src/ape_plugins/_cli.py, tests/functional/test_plugins.py
Related to issue #2350 
I installed eth-ape using pipx and noticed that `ape plugins install arbitrum` fails since it can't find the virtual environment
Added an optional python venv location so that user can specify the location incase the install fails.
=> feat: Add python loc option for installing plugins

src/ape/plugins/_utils.py
Fixed an issue in the `ApeVersion` class method where it incorrectly compared with the global `ape_version` instead of using the object's current version (`self.major` and `self.minor`).
Replaced `ape_version.major` and `ape_version.minor` with `self.major` and `self.minor` to ensure the method compares the object's version correctly.
Ensure that the method now properly compares the instance version with the given values when called on an `ApeVersion` object. Run the associated tests to confirm the fix.
=> fix: incorrect variable usage in ApeVersion method

setup.py, src/ape/managers/_contractscache.py, tests/functional/test_contracts_cache.py
Noticed that when a contract type was "merged" (by combining ABIs of 2 different types) that it was duplicating the shared ABI between the two. This change instead makes sure that only those ABIs that were missing from the underlying contract type will get merged with the base, ensuring that problems with duplicate methods do not appear.
fixes: #2566
Check relevant ABIs against the set of existing ABIs of the base contract type before merging. Do no merge those that are shared between the existing base contract type and the type to merge it with
see: #2566
=> fix(Contracts): only update contract cache with proper merge of ABI

docs/userguides/contracts.md, docs/userguides/dependencies.md, docs/userguides/proxy.md
1. File: docs/userguides/contracts.md
Old: avoid having to invoking Python directly
New: avoid having to invoke Python directly
Reason: "invoking" is a gerund; after "having to", the correct verb form is the infinitive "invoke". This fixes a grammatical inconsistency.
2. File: docs/userguides/dependencies.md
Old: Oftentimes, the \v` prefix is required...`
New: Oftentimes, the 'v' prefix is required...
Reason: The backticks were unnecessary and inconsistent with surrounding text. Switching to single quotes improves formatting clarity.
Old: ...more adhoc
New: ...more ad hoc
Reason: "Ad hoc" is a Latin phrase and should be written as two separate words. This improves accuracy and professionalism in writing.
3. File: docs/userguides/proxy.md
Old: vyper <0.2.9 create_forwarder_to
New: vyper …
=> docs: minor grammar & style fixes

src/ape_pm/project.py, tests/functional/test_project.py
This PR fixes issue #2564  , where Ape’s `FoundryProject` class does not detect the `via_ir` setting from Foundry’s `foundry.toml` configuration file. 
The change updates the `_parse_solidity_config` method in `src/ape_pm/project.py` to read the `via_ir` key and include it in the Solidity compiler configuration as `viaIR`. This ensures Ape respects Foundry’s `via_ir` setting during compilation, aligning with Foundry’s behavior.
- Modified `FoundryProject._parse_solidity_config` in `src/ape_pm/project.py` to check for `via_ir` in the parsed `foundry.toml` data.
- Added `via_ir` to the `sol_cfg` dictionary as `"viaIR": via_ir` when present, preserving existing logic for other settings (`version`, `evm_version`, `remappings`).
- While ensuring safe handling of missing `via_ir` keys using …
=> Added `via_ir` Detection for Foundry Projects in Ape

src/ape/api/config.py, src/ape_plugins/_cli.py
1. Corrects "dispaly" to "display" in docstring comments in src/ape/api/config.py
2. Fixes the version callback function name from "_version_callack" to "_version_callback" in src/ape_plugins/_cli.py
These changes improve code consistency and readability without affecting functionality.
=> docs: Fix typos in display configuration and version callback function names

docs/userguides/contracts.md, src/ape/contracts/base.py, src/ape_ethereum/provider.py, tests/functional/test_contract_event.py
Added the capability to use topic filters w/ `ContractEvent.poll_logs` in a nice way
Also noticed that the field in `LogFilter` is `topic_filter` not just `topics`
https://github.com/ApeWorX/ape/blob/55a71681e6ad05d5cc44661ab4d6d86be33e4e16/src/ape/types/events.py#L29
=> feat: allow specifying topic filters w/ `ContractEvent.poll_logs` 

.github/workflows/test.yaml, src/ape/api/accounts.py, src/ape/contracts/base.py, src/ape/managers/chain.py, src/ape/utils/misc.py, src/ape_accounts/accounts.py, src/ape_ethereum/ecosystem.py, src/ape_pm/dependency.py, src/ape_test/accounts.py, tests/functional/test_accounts.py
i need to be able to easily access public keys in tests
* makes public_key more of an official api and gives test accounts access to their publi
* adds a couple missing arg docs
* fixes a casing from camelCase to snake_case
* replaces a production assert statement with an actual error
* other small stylistic improvements
=> feat: test accounts public key

src/ape/managers/project.py, tests/functional/test_dependencies.py
fixes: #2599
handle errors on second spot when hitting cache
also non-breakingly changed installed to be all since it is less confusing because there may be uninstalled deps in the installed iterator
=> fix: issue reading dependencies when uninstalled dependency in API data

src/ape/managers/project.py, src/ape_pm/_cli.py, tests/functional/test_dependencies.py, tests/integration/cli/test_pm.py
fixes: #2604 
This can be quite the time saver when you only want to force reinstall the main dependency and not all of its dependencies... like i dont need to install `forge-std` over and over again, but my own projects that are also dependencies, yes i typically need to force reinstall those to get new changes and stuff
=> feat: `--no-recurse` flag on  `ape pm install` command

setup.py, src/ape/api/transactions.py, tests/functional/test_transaction.py
Extended the fix for corrupted calldata strings proposed by @fubuloubu in #2616 to work with full and abridged calldata.
Transform calldata to a bytes representation using `HexBytes` before performing string conversions.
Compare result to functional transaction tests (`test_str_when_data_is_long_shows_first_4_bytes`, `test_str_when_data_is_long_and_configured_full_calldata`). 
Encoded inputs:
```
>>> HexBytes(HexBytes(web3.Web3.keccak(text='setNumber(uint256)'))[:4] + HexBytes(eth_abi.encode(['uint256'],[123]))).to_0x_hex()
'0x3fb5c1cb000000000000000000000000000000000000000000000000000000000000007b'
>>> HexBytes(web3.Web3.keccak(text='setNumber(uint256)'))[:4])
HexBytes('0x3fb5c1cb')
```
=> fix(API): corruption of abridged calldata

setup.py, src/ape/types/address.py, src/ape/utils/abi.py, tests/functional/geth/test_provider.py, tests/functional/geth/test_trace.py, tests/functional/test_contract_event.py, tests/functional/test_ecosystem.py, tests/functional/test_provider.py
Uses the new names of classes after eth_pydantic_types overhaul
fixes: #
in coordination with: https://github.com/ApeWorX/eth-pydantic-types/pull/11
=> refactor: use new types from `eth_pydantic_types`

src/ape/_cli.py, src/ape/api/config.py, src/ape/api/networks.py, src/ape/api/providers.py, src/ape/contracts/base.py, src/ape/exceptions.py, src/ape/managers/config.py, src/ape/managers/project.py, src/ape/pytest/runners.py, src/ape/utils/basemodel.py, src/ape_ethereum/provider.py, src/ape_test/provider.py, tests/functional/test_config.py, tests/performance/test_project.py
Kind of a weird one but doing
```
from ape import config
fn = config.get_config
```
would fail when the config was invalid.
Fixed by re-defining `.get_config` at the manager level instead of relying on the getattr
Also fixes some things like CLI showing the more interesting error (instead of ApeAttributeError)
___
I need this to more cleanly implement https://github.com/ApeWorX/ape/issues/2591
=> fix: `ConfigManager` would crash on attribute access and be un-recoverable when temporary poorly configured

src/ape/managers/project.py, src/ape_pm/dependency.py, tests/functional/test_dependencies.py
Ape is constantly re-fetching dependencies without sources. This fixes it.
Ape was doing this because it thought it was failing to produce a project.
However, you can use `--force` to re-download if something bad happens during fetch. Also, some dependencies may never actually produce a project because they only have `.test.sol` contracts (TBD on that)
=> fix(pm): sourceless dependencies of dependencies are always re-downloaded on compile

src/ape/api/accounts.py, src/ape/api/address.py, src/ape/contracts/base.py, tests/functional/test_accounts.py, tests/functional/test_contract_instance.py
This helps me turn 4 lines of code into 1
```python
tx = contract.MyMethod.as_transaction(sender=me)
prepped_tx = me.prepare_transaction(tx)
signed_tx = me.sign_transaction(prepped_tx)
tx_bytes  = signed_tx.serialize_transaction()
```
to
```python
tx_bytes = contract.MyMethod.as_transaction_bytes(sender=me)
```
fixes: #2631
=> feat(contracts): easily get signed serialized transactions bytes from contract handlers

src/ape/managers/project.py, tests/functional/test_project.py, tests/integration/cli/projects/geth/tests/test_using_local_geth.py, tests/integration/cli/test_test.py
Basically, as soon as I added an `ape-config.yaml` file to a project, `ape compile` stopped working.
fixes: #2636
=> fix: issue where `foundry` config would no longer work as soon as added an `ape-config.yaml` file

src/ape/api/accounts.py, src/ape/contracts/base.py
fixes: #2596 
Put the following contract into the `contracts` folder
```js
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
contract SimpleContract {
address public owner;
constructor() {
owner = msg.sender;
}
function get_value(uint256 value) external view returns(uint){
return value;
}
}
```
Put the following test script in the `scripts` folder
```py
from ape import project, accounts
from rich.console import Console
cs = Console()
def main():
deployer = accounts.load("test")
#deployer.unlock(passphrase="a")
deployer.set_autosign(True)
cs.print("-" * 100)
cs.print("Deploying by contract.deploy")
cs.print("-" * 100)
contract1 = project.SimpleContract.deploy(sender=deployer)
cs.print("-" * 100)
cs.print("Deploying by account.deploy")
cs.print("-" * 100)
contract2 = …
```
=> feat(AccountAPI): show deployment address before broadcast

setup.py, src/ape_ethereum/provider.py
bumped the version of web3 dependency to v7.12.1.
removed MockBatchingContext swap out hack in ape_ethereum/provider.py
Fixes #2677 
Honestly, I am quite new to blockchain and python dev - please let me know if there are better ways to verify.
I just built locally successfully using docker build . <image> following the ape README.md. After a reviewer approves, I was hoping ape project's github CI actions will run tests against it without breakage.
=> fix: bump web3 to v7.12.1; undo MockBatchingContext hack

src/ape/api/networks.py, src/ape/managers/project.py, src/ape_ethereum/ecosystem.py, src/ape_ethereum/provider.py, tests/functional/test_config.py, tests/functional/test_ecosystem.py, tests/functional/test_network_api.py
base fee multiplier was 1.0 on other default live networks.
also, was having some pydantic validation issues when trying to configure, fixed that
also uses AutoGasLimit default instead of string "auto"
also a perf where we use "latest" instead of fetching latest block number, better for faster chains i think
=> fix: gas estimate multiple default value fix

src/ape/api/transactions.py, tests/functional/test_transaction.py
`.gas` was already an alias, it just didn't have a setter, which was confusing for a second.
fixes: #2681
=> fix: ability to set transaction `.gas` (alias for `.gas_limit`)
