ApeWorX/ape

- setup.py
- src/ape/managers/compilers.py
- src/ape_pm/__init__.py
- src/ape_pm/compiler.py
- tests/conftest.py
- tests/test_cli.py
- tests/test_manifest.py
This PR adds support for "compiling" `ContractType`s from JSON files (either ethPM Manifests, or JSON ABI files)
fixes: #29
depends on: #32
---
TODO:
> feat: json compiler

- setup.py
- src/ape/__init__.py
- src/ape/utils.py
- src/ape_plugins/__init__.py
Before, package versions weren't being properly detected by our version extraction function, and it also wasn't very portable. This PR solves both those issues, and fixes a few latent bugs with plugin management
> fix: update package version extractor function to work properly

- src/ape/api/networks.py
- src/ape/managers/config.py
- src/ape/managers/project.py
- src/ape_accounts/accounts.py
- src/ape_infura/providers.py
- src/ape_test/providers.py
Noticed this deprecation warning with `dataclassy`
```
DeprecationWarning: Defining post-initialisation logic in __init__ is deprecated and will be removed in a forthcoming version. 
Please rename your method to __post_init__.
```
> fix: deprecation warning for `__init__` in dataclassy.dataclass

- src/ape/types/contract.py
> fix: missing default for `urls` under `Source`

- src/ape/types/__init__.py
fix https://github.com/ApeWorX/ape/issues/72
> fix: export ABI type

- src/ape/api/accounts.py
Allow specifying additional kwargs like `gas_price = 10` etc.
> fix: allow all kwargs for txn pass-through in AccountAPI

- .github/workflows/test.yaml
- README.md
- pyproject.toml
- setup.py
Removed support for Python 3.6 for the Ape tool. IPython was having difficulties with this version, and due to a change in how core dataclasses work, one of our dependencies was also having an issue with that version, preventing the merge of #89.
Related: https://github.com/biqqles/dataclassy/issues/52
> chore: deprecate Python 3.6 support; upgrade IPython

- src/ape_compile/_cli.py
changed error messages to be more reflective of actual error regarding uninstalled compiler. 
Related issue: # fix: https://github.com/ApeWorX/ape/issues/85
modified the compiler _cli file to look for .vy and .sol files in os.listdir contract folder to base error messages on
try to compile vyper files with no vyper plugin, it should tell you no vyper plugin is installed. same with solidity plugin. 
if there are no .vy or .sol in contracts folder it should say so, and if there is no contracts folder it should say so.
> fix: error warning not accurate for uninstalled compiler

- src/ape_ethereum/ecosystem.py
`eth-account` v0.5.5 was just released today, causing an incompatibility (because we are using an internal-only set of functions to encode transaction types)
duplicated the name change
> fix: add support for eth-account v0.5.5

- setup.py
updated the `eth-account` requirement to match pull 103
fixes: #106
`"eth-account>=0.5.5,<0.6.0",`
if you install 0.5.4 it doesn't work with the new pull from ape
> fix: updates eth-account requirement - fixes breaking change 

- src/ape/managers/networks.py
- src/ape_console/_cli.py
Allow more network choices e.g. `:goerli`, `::test`, `bsc::test`
Try it
> refactor: allow more network choices via defaults

- src/ape/api/networks.py
- src/ape_ethereum/__init__.py
I noticed when using `geth --dev` with the console, there was an issue where the chain ID disagrees with what's expected.
> fix: chain ID for geth --dev was incorrect, so add local network

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape_accounts/accounts.py
- src/ape_ethereum/ecosystem.py
The signing API needed to be refactored to account for using signatures properly. The way we encoded and decoded them before was really bad, so we want to not do that anymore.
modified `AccountAPI.sign_transaction` from returning the input `TransactionAPI` with the signature to returning `SignedTransaction`. It was optional before, but the semantic here changes a bit because now it returns the signature directly.
@sabotagebeats this will affect your work in `ape-trezor`. Please watch for when this merges and update accordingly.
> refactor: change how signing API works

- .github/workflows/docs.yaml
- README.md
- build_docs.py
- docs/_autoapi_templates/python/data.rst
- docs/_autoapi_templates/python/module.rst
- docs/_static/custom.css
- docs/_static/custom.js
- docs/_templates/layout.html
- docs/conf.py
- docs/index.rst
- docs/quickstart.rst
- setup.py
- src/ape/__init__.py
- src/ape/api/compiler.py
- src/ape/api/contracts.py
- src/ape/api/networks.py
- src/ape/managers/compilers.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape/plugins/config.py
- src/ape/types/contract.py
- src/ape/types/manifest.py
- src/ape/utils.py
- src/ape_accounts/_cli.py
- src/ape_console/_cli.py
- src/ape_plugins/_cli.py
- src/ape_pm/compiler.py
- src/ape_run/_cli.py
Related issue: #21 
I used some of the sphinx setup I did in eip712, but added quite a bit of work on top of that, including the [sphinx-autoapi](https://pypi.org/project/sphinx-autoapi/) plugin so we don't have to generate or maintain `.rst` files for full API documentation of modules, classes, and functions.
A new CI job for docs will on PRs, branches, and releases.
> chore: sphinx documentation configs, build script, CI job

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/types/__init__.py
- src/ape/types/signatures.py
- src/ape_accounts/accounts.py
- src/ape_ethereum/ecosystem.py
> fix: use ape-specific types for messages and msg/txn signatures

- src/ape/_cli.py
- src/ape/plugins/__init__.py
fixes: #119
- Add an exception to a core plugin `__init__.py`, to show that it doesn't load and raises a warning instead
- Remove a necessary API abstractmethod, to show it doesn't register and raises a warning instead
- ~~[ ] Documentation has been updated~~
> fix: handle exceptions when loading plugin packages

- src/ape_test/__init__.py
Remove the extra network object that we added in `ape_test`, since `ape_ethereum` is defining it now.
> fix: remove unused network type after geth --dev was added

- src/ape_ethereum/ecosystem.py
Fix issue when using the Ethereum Ecosystem to encode signatures with bytes r and s fields
Related issue: https://github.com/ApeWorX/ape-trezor/pull/1#issuecomment-895454540
> fix: make sure signatures are in the proper format for RLP encoding

- src/ape/api/config.py
- src/ape_http/providers.py
I am inheriting from NetworkConfig for Hardhat, but the behavior of key
lookup vs. attribute lookup is different for the base class vs.
inherited class.
Base NetworkConfig class:
(Pdb) self.config
NetworkConfig(ethereum={'development': {'uri': 'http://localhost:8555'}})
(Pdb) self.config['ethereum']
{'development': {'uri': 'http://localhost:8555'}}
(Pdb) getattr(self.config, 'ethereum')
{'development': {'uri': 'http://localhost:8555'}}
Vs. my inherited class where the key lookup fails:
(Pdb) self.config
HardhatNetworkConfig(ethereum={'development': {'uri': 'http://localhost:8555'}}, fork_url=None, fork_block_number=None, port=8555)
(Pdb) self.config['ethereum']
*** KeyError: "''ethereum'"
(Pdb) self.config.ethereum
{'development': {'uri': 'http://localhost:8555'}}
Since attribute lookup …
> fix: use getattr for EthereumProvider network configs instead of dictionary key lookup

- CONTRIBUTING.md
- build_docs.py
- docs/conf.py
- setup.py
- src/ape/api/networks.py
- src/ape/managers/accounts.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape/utils.py
- src/ape_ethereum/ecosystem.py
- src/ape_http/providers.py
- src/ape_test/providers.py
- tests/functional/manifests/test_manifest.py
I ran `pyupgrade` to upgrade the code base to use syntax for python 3.7 or greater.
During the last meeting, I showed some of the changes. I have concluded that:
1.) The team does not always want to use the latest syntax during cases they find it confusing
2.) The team is not immediately attracted to the idea of another pre-commit hook modifying code.
And also, some contrary things about `pyupgrade`:
1.) `pyupgrade` works best a pre-commit hook. This is because it takes a list of python files as arguments.
2.) `pyupgrade` does not have an opt-out feature natively, but there is a fork that does.
Thus, it does not seem like a good time to automate the usage of `pyupgrade` because of these conflicts.
Related issue: # n/a
I made the precommit hook, ran it, and then removed the precommit. I …
> chore: upgrade python syntax

- src/ape/_cli.py
- src/ape_networks/_cli.py
- tests/integration/cli/test_networks.py
Whilst trying to figure out how to add a network (similarly to `brownie networks add`), I noticed that the `network list` command could be refactored. I also noticed there was not a test for it, so I added that as well.
Pulled out shared logic, broke up the large command-method's implementation to use sub-methods, added a simple test.
Run `ape networks list`, the output should be the same as it was before.
> chore: refactor and test networks list command

- setup.py
- src/ape/utils.py
- src/ape_accounts/_cli.py
- tests/integration/cli/conftest.py
- tests/integration/cli/test_accounts.py
Fixes issue where `ape accounts import <alias>` and `ape accounts generate <alias>` would return 0 exit codes when they failed to import or generate accounts.
Additionally, changed `notify()` to detect when it's `ERROR` and print to `stderr` instead. Thus, `Abort()` can just use `notify()` now in its implementation.
I added tests - I am trying to get a sense of how to write tests for this project.
Also, I added `pytest-mock`, I hope that is okay? It is magical!
This is all part of the efforts of custom exceptions + musing about exception handling. It by no means resolves that issue (I have another branch for that), but it is helpful to have while thinking about exceptions as a whole.
Related issue: #132
I tried to write a unit test and it failed so I realized it was not doing what I …
> fix: accounts failure exit codes

- src/ape/_cli.py
- src/ape/plugins/__init__.py
During implementing the ledger plugin, I had two points of confusion when it  came to the errors from ape.
1.) the suggested command sometimes was identical to the one I typed
2.) I would get an error `such and such has no attribute __name__` during the handling of the actual error.
This PR addresses both of those.
I didn't create an issue because it is a very small bug that is non-critical.
* If the bad arg is the same as the suggested arg, don't say `"did you mean <same-thing-you-just-typed>"`
* Check first if the plugin type is a tuple or list and if it is, use comprehension to form the type names in the warning message.
Install a bad plugin (not fully implemented). Make sure the error messages make sense and you don't run into the issues I described above. You can additionally verify …
> fix: improve error handling for unimplemented plugins

- src/ape/api/networks.py
- src/ape/managers/project.py
- src/ape/utils.py
- tests/functional/test_utils.py
Remove a few `assert` statements from production code.
Reason:
When compiling optimized python coded (`.pyo` files), `assert` statements get removed. They should be avoided in non-debugging or testing scenarios.
fixes: #147 
More info:
https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html#b101-test-for-use-of-assert
Related issue: #132
Noticed the issue from a `bandit` scan.
Realized these should probably be errors instead of `assert` statements.
Changed them to raise `ValueError()` instead.
I wrote unit tests for this one.
_however_ I am still not exactly sure where to put these types of functional unit tests. Should it be in more of an abstract collection such as `test_paths`?
I _really_ prefer tests to match more of the projects structure. This way, if I want to see …
> fix: remove production asserts

- src/ape/api/address.py
- src/ape/managers/accounts.py
- src/ape/options.py
- src/ape_accounts/_cli.py
- tests/integration/cli/test_accounts.py
fixes: #156 
Loop through the `accounts` container rather than all the accounts containers accounts.
1.) Install another account API plugin
2.) Add an account
3.) Run `ape accounts list` and notice that account does not show up in the list
> fix: limit ape_accounts plugin to KeyfileAccounts

- src/ape/managers/project.py
- src/ape_compile/_cli.py
fixes: #166
* Make sure to work with paths on path methods
* Correctly calculate the extensions that are missing from registered compilers
* Handle the case where the contracts/ directory is empty (As far as error message goes).
Start off without any compiler plugins
1. Create a `contracts/` directory with a Solidity file and a Vyper file
2. Run `ape compile`
You should get the error message: `WARNING: No compilers detected for the following extensions: .vy, .sol`
3. Add a Vyper plugin via `ape plugins add vyper`
It should compile the solidity file and warn about the vyper file:
`WARNING: No compilers detected for the following extensions: .sol`
4. Add the Solidity plugin
It should compile both files and not warn.
5. Move both files out of the directory and run `ape compile`
It should …
> fix: handle missing compiler extensions

- src/ape/cli/__init__.py
- src/ape/cli/arguments.py
- src/ape/cli/choices.py
- src/ape/cli/options.py
- src/ape/cli/paramtype.py
- src/ape/managers/project.py
- src/ape_compile/__init__.py
- src/ape_compile/_cli.py
- tests/integration/cli/test_compile.py
* Fixes issue where if you had nested files in a directory with an extension that is not a registered compiler key, it would fail to warn for the missing compiler.
While working on the CLI SDK refactor, I realized we had an opportunity for a `AllFilesPath` `click.ParamType` which essentially just converts a directory structure to a list of file paths (if just given a single file path, it returns a list with that file path).
This gets used in the source file args, but they call now have a callback method that handles flattening the `AllFilesPaths` lists, de-duplicating, and calling `resolve()`.
Additionally, I moved some of this logic to the `ProjectManager`, which now can tell me which extensions do not have compilers and if sources are just generally missing. This makes the …
> fix: warn for missing compilers recursively

- src/ape/cli/arguments.py
- src/ape/cli/options.py
- src/ape_accounts/_cli.py
- src/ape_console/_cli.py
- src/ape_run/_cli.py
There were a few arguments and cli options that were not callable.
We should make them callable from now on because:
1. we can document them
2. we can add parameters without it being a breaking change, so more resilient 
**Believe it or not, this will help make my testing branches smaller as I had to do this fro networks option**
Looked for options and arguments that were not callable and wrapped them in a definition statement and changed all their usages.
N/a
> fix: make all cli options callable

- src/ape/api/accounts.py
- src/ape/managers/accounts.py
- src/ape_test/__init__.py
Creating a config for the test plugin for setting a mnemonic and the number of accounts. This work is also present on the testing wip PR (#215), so it will help focus that PR.
Using this, I can create a testing account and provider setup, which I can open a PR for after this (also work present on the testing wip PR). And I have tested that setup with both geth and ethtester.
I know @lost-theory was working on this, let me know if you want to merge.
Added a config api implementation to the test plugin with the required fields
Verify using the #215 if you want
> feat: test config that includes mnemonic and number of accounts

- pyproject.toml
- src/ape/api/__init__.py
- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/cli/utils.py
- src/ape/managers/accounts.py
- src/ape/plugins/__init__.py
- src/ape/utils.py
- src/ape_networks/_cli.py
- src/ape_run/_cli.py
- src/ape_test/__init__.py
- src/ape_test/accounts.py
- src/ape_test/providers.py
- tests/functional/api/test_accounts.py
- tests/integration/cli/conftest.py
- tests/integration/cli/test_console.py
- tests/integration/cli/test_run.py
Make sure you have this account added in ape: `0xdd23ca549a97cb330b011aebb674730df8b14acaee42d211ab45692699ab8ba5`
Start up a geth, (e.g. check out this repo: https://github.com/unparalleled-js/hdpath-geth and run `make`)
Run the deploy script from my demo project (Use a demo project, e.g. https://github.com/unparalleled-js/ape-demo-project) `ape run deploy`, select the account you added. It should run.
Now, run the same script with the test provider, `ape run deploy --network ::test`. It should automatically use the test account at index 0 and work.
> feat: provider and account testing APIs

- pyproject.toml
- setup.py
* Bumped black version dep
* Added 3.9 target version
Added the new target version and bumped
Black still works
> feat: upgrade black to target python 3.9

- setup.py
- src/ape/__modules__.py
- src/ape_plugins/utils.py
fixes: #229 
Set `py_modules` from magic list in ape
Rely on same list in plugins plugin
Install ape without using -e
Install plugin
Uninstall plugin
> fix: issue where all plugins got counted as 1st class plugins

- setup.py
Adds missing packages to packages_data.. Fixes issue where not all packages had their typing including.
Makes it so it goes off the universal source of truth, so it should not happen in the future!
Noticed package_data. Noticed it was missing some packages. Noticed we could use the same source as truth as `py_modules`.
Install ape, both editable mode and not, make sure it installs expectedly.
Shouldn't need type ignore anymore if was importing from these missing modules? (not exactly sure)
> fix: keep type info for all ape packages up-to-date

- src/ape/api/__init__.py
- src/ape/api/providers.py
- src/ape/utils.py
- src/ape_geth/providers.py
- src/ape_test/providers.py
Creates a base class for providers that use web3 rpc.
I have a branch where hardhat will also use this base class (to help upgrade it and make it fit for ape-test)
Copy shared code to base class and put in Provider api module.
> feat: web3 provider base class

- src/ape/cli/__init__.py
- src/ape/cli/options.py
Creates a new custom `ape.cli.option` for contract.
* The contract type _must_ be a contract within the current project
* The command fails in the arg collection stage when not in a project with the given contract (which is before starting up a network!).
Use case:
So you want to make a custom command that queries logs for a given contract. You have a provider like Infura and you have the compiled ABI etc. This makes it easy to pass in a CLI option for specifying the contract type.
Custom click option in the cli module using `from ape import projects`.
```python
import click
import json
from ape.cli import contract_option
@click.group()
def cli():
pass
@cli.command()
@contract_option(help="The name of the contract to dump the ABI from.", required=True)
def abi(contract):
abi_dict = …
```
> feat: contract CLI options

- src/ape_plugins/_cli.py
- src/ape_plugins/utils.py
I created sets of plugins delineated by first, second, and third class and then had subsets of installed and available plugins.
fixes: PR #211 
#211  was a branch created from sabotages branch
This feature allows ``` ape plugins list, ape plugins list -a ``` to show installed and available First and Second class plugins to install. 
You can verify by running the ``` ape plugins list, ape plugins list -a ```  commands
> feat: plugin feature will display available and installed plugins

- src/ape/exceptions.py
- src/ape_geth/providers.py
- src/ape_test/contextmanagers.py
- tests/functional/http/test_providers.py
* Fixes issue where if a contract reverts with no error message, the `reverts` context manager did not have a specific enough error message. I noticed this while working on `ape hardhat`.
* Fixes issue where the `geth` provider wrongly considered the default error message the contract's revert message.
In general, this work handles the case when there is no revert message in contract reverts. That got missed before.
Detect if error was raised without a contract error message. Don't specify `revert_message` in the custom exception when that happened. Make `revert_message` an optional argument in the custom exception.
Make a call to a contract that reverts without an error message. Example:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;
contract Fund {
bool public …
```
> fix: handle when there is not a message in a contract revert

- src/ape/api/accounts.py
When deploying a contract, show the contract address as a SUCCESS message (also bolden the address)
click and logger
Deploy a contract, you should see some stuff like this (this is a local dev env, so not a real address):
> feat: show contract address on deployment

- src/ape/api/__init__.py
Currently, plugins have to import from both `ape.api` as well as `ape.api.config` if they want to have a config file with their implementation.
This makes it so they can just use `ape.api`
> refactor: make config item classes importable from api module

- src/ape/managers/project.py
- src/ape/utils.py
- src/ape_compile/_cli.py
- src/ape_plugins/_cli.py
- src/ape_plugins/utils.py
Working on dependencies, realizing sharing a GitHub client would be helpful.
This refactor does the following:
1. Creates a GitHub client in `ape.utils` (ideas on a better location for this?)
2. Moves some of the ext missing compiler logic to API, further keeping the `_cli.py` implementation smaller.
> refactor: create GitHub client

- src/ape/__init__.py
- src/ape/api/accounts.py
- src/ape/api/contracts.py
- src/ape/managers/project.py
fixes: #290 
Update the process for retrieving/initializing a  previously deployed contract to be more UX friendly.
Modify  `__getattr__(...)` in `ProjectManager` to return a `ContractContainer` instead of a `ContractType` and refactored `deploy(...)`
```python
contract = project.Fund("0x274b028b03A250cA03644E6c578D81f019eE1323")
```
> feat: ability to initialize contract objects with an address

- src/ape_ethereum/ecosystem.py
fixes: #262 
call `to_checksum_address()` on the data being return so long that it is of an address type.
Two things:
1. Verify that addresses returned from contracts are now checksummed
2. Verify that normal calls unrelated to addresses still work.
Test that tests this new feature: https://github.com/unparalleled-js/ape-demo-project/blob/main/tests/test_fund.py#L17-L21, 
The other tests pass as well in that demo project.
Thus, this addresses the issue.
**NOTE: eth-abi python package naturally returns HexAddress as "normalized". It is not much effort to change that, but to fix their test suite against that is actually kind of challenging believe it or not and I am not sure they would want that.. Though I have started the process to see what it's like: …
> feat: return checksummed addresses from contract calls

- src/ape/cli/arguments.py
- src/ape/cli/choices.py
- src/ape/cli/commands.py
- src/ape/cli/options.py
- src/ape/cli/utils.py
Add missing doc strs to the `ape.cli` namespace.
Lots of revising.
Lots of reading (audience for these particular docs would be plugin writers probably).
> docs: document the CLI utilities

- .gitignore
- src/ape/contracts/base.py
fixes: #310
Update logic to encode `AddressAPI` objects as their underlying address value [str]
Private helper method called in several `Contract encode` methods
Old behavior:
```python
contract.mint(receiver.address, 0, sender=owner)
```
New behavior:
```python
contract.mint(receiver, 0, sender=owner)
```
> feat: add string address encoding

- docs/index.md
Make it only go one level deep for guides on the index page.
Before:
After:
Change the max depth to 1
build docs and check or just take my word for it
> docs: only go 1 level deep for guides in TOC

- docs/methoddocs/types.md
- src/ape/types/__init__.py
- src/ape/types/contract.py
- src/ape/types/manifest.py
- src/ape/types/signatures.py
Makes the `ape.types` method-docs more usable.
**The will fix some of the broken links in the docs**
* Add missing docs
* Organize docs
Note, this module in general seems to need some work. I purposely did not document some of these methods / attributes.
Build docs and check it out.
> docs: add missing method documentation for the types module 

- setup.py
I am seeing weirdnesses where installing `'[dev]'` takes hours because of dependencies issues related to commitize `type-extension`.
This seems to resolve it.
> fix: type ext related build slowness

- src/ape/api/accounts.py
- src/ape/api/address.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/cli/options.py
- src/ape/managers/accounts.py
- src/ape/managers/compilers.py
- src/ape/managers/converters.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape_ethereum/ecosystem.py
Uses `Raises:` sphinx keyword whenever possible.
This makes things look more nice and organized on the site and makes use of the sphinx feature.
Find places where we mention what a method raises and replace it with this syntax.
Find other places where we don't mention it and add it.
read through docs
build and see what I mean by the sytnax.
> docs: use raises keyword in method docs where apt

- docs/index.md
I think the last TOC section is not 100% clear on what it is.
This rename makes things super obvious I think.
Noticed this section was vague and thought about what a new user might think if we they were only looking for the python docs.
Does this make sense to you? (Attachment)
See how it matches the section above "CLI Reference"
> docs: rename to method-docs TOC header to include "python"

- src/ape/api/providers.py
- src/ape_ethereum/ecosystem.py
Remove unneeded method and check.
The `is_valid` method always returns `False` and is not used correctly. The "check" that happens verifies the truthiness of the method existing, it does not call the method or anything, and thus the checked result is always `True` (false positive).
At the same time, there is no implementation or explanation of this property. It should be removed if it not needed or else it should be implemented properly. Since we are getting by without it, I opted for removing here. Let me know otherwise!
I was documenting these methods and noticed the docs did not really say what `is_valid` means. Then, I noticed it was not getting called correctly. Then, I noticed it was never actually getting set o
This PR should have no effect on anything.
> refactor: remove incorrectly used property 'is_valid' from the transaction API

- docs/methoddocs/utils.md
- src/ape/api/accounts.py
- src/ape/api/address.py
- src/ape/api/compiler.py
- src/ape/api/config.py
- src/ape/api/convert.py
- src/ape/api/explorers.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/cli/arguments.py
- src/ape/cli/choices.py
- src/ape/contracts/base.py
- src/ape/managers/accounts.py
- src/ape/managers/compilers.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape/types/contract.py
- src/ape/utils.py
* Switched `:meth:` to `:py:attr:` for `@property` based methods (removes `()` from HTML link output)
* Switch to using `typing` modules types instead of `sphinx` native types where applicable (so `Iterator[str]` instead of `iter[str]`)
* Removes docs from `Web3Provider` so that it uses the base `ProviderAPI` class docs (removes a lot duplication)
* General documentation revising, format fixes, and additions!
> docs: general revisions and fixes

- build_docs.py
- docs/conf.py
- docs/index.md
* Fix path issue causing versioning system not to work right
* Filter out beta and alpha from versioning system
* Keep CLI TOC nested to 1 level to match the other and look cleaner.
Using path lib to sanitize the path (a leading slash was causing issues)
Build docs locally
Copy "latest" folder and create fake folders next to it for "stable", "v0.1.0.beta.1" and "v0.1.0". The beta should be filtered out.
> docs: fix path versioning issue / filter out betas

- src/ape/api/providers.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/providers.py
- src/ape_test/providers.py
- tests/functional/ethereum/test_ecosystem.py
I think I initially made these changes, I was not as knowledgable about how a Receipt gets decodes using values from the transaction. Now that I am aware of this, I realize that this API does not make sense to ask for these parameters because it should already know them. How, this is a breaking change in the `ProviderAPI`. I think it is still okay for us to make this change so long that we update all the provider plugins as quick follow-ups / releases.
Remove transaction parameters from receipt API methods
Add needed attributes to Receipt API
Initialize properties during the decoding phase of the receipt using the transaction values.
Things still work (make sure to use either the test or geth providers here)
> refactor: use transaction values from decoding rather than as new parameters

- src/ape/__init__.py
- src/ape/api/accounts.py
- src/ape/api/convert.py
- src/ape/contracts/base.py
- src/ape/managers/converters.py
- src/ape/managers/project.py
- tests/functional/conversion/test_ether.py
Added support to `ConversionManager` for handling `tuple` and `list` conversions (e.g. recursively applying conversions)
fixes: #376
> feat: handle iterable args

- src/ape_accounts/accounts.py
- src/ape_test/accounts.py
Noticed that when you sign a message using eth-account, it does not return `r` and `s` in the signature the same as with signing a transaction
> fix: ensure the correct type when signing a message using eth-account

- Dockerfile
fix an error with incorrect version of `typing-extensions` for a required dependency `'trie'`
fixes: #387
added the line `RUN pip install typing-extensions==3.10.0.2` to the Dockerfile 
Dockerfile now builds.
```
$ docker build .
$ docker images
REPOSITORY           TAG       IMAGE ID       CREATED          SIZE
<none>               <none>    07f16cf5e34a   47 minutes ago   586MB
$ docker run 07f16cf5e34a plugins list
Installed Plugins:
vyper     0.1.0b1
ens     0.1.0b2
infura     0.1.0b2
etherscan     0.1.0b1
solidity     0.1.0b1
$ docker run -it 07f16cf5e34a console
In [1]:
```
> fix: Dockerfile not building for typing-extensions incorrect verions

- docs/index.md
- docs/userguides/transactions.md
- src/ape/api/providers.py
- src/ape/managers/converters.py
- src/ape_ethereum/ecosystem.py
- tests/integration/conftest.py
- tests/integration/test_ethereum.py
Fixes regression where we were not longer able to specify `type="0x0"` for static fee transactions.
Adds Transactions guide.
handle hexbytes differently than bytes
> fix: bug preventing str-type when specifying transaction types.

- src/ape_plugins/_cli.py
fixed spacing issue with the plugins list and version number
fixes: #
used math and chris math minor to make the plugins list cleaner
use the ape command `ape plugins list` to see the installed version numbers
> feat: align plugins and version number

- docs/methoddocs/managers.md
- src/ape/__init__.py
- src/ape/api/accounts.py
- src/ape/api/address.py
- src/ape/api/explorers.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/exceptions.py
- src/ape/managers/accounts.py
- src/ape/managers/chain.py
- src/ape/managers/converters.py
- src/ape/managers/networks.py
- src/ape/plugins/converter.py
- src/ape/types/__init__.py
- src/ape/utils.py
- src/ape_ethereum/ecosystem.py
- src/ape_test/fixtures.py
- src/ape_test/providers.py
- tests/conftest.py
- tests/functional/conversion/test_ether.py
- tests/functional/ethereum/test_ecosystem.py
- tests/integration/conftest.py
- tests/integration/test_chain.py
fixes: #129
^ Note there are several other related to chain manager, such adding mining support. This work is just to initialize the chain manager as well as swap out the snapshotting login in `ape_test` using the chain manager rather than the `ProviderAPI` alone.
* Create new class ChainManager, a top-level object that takes the `NetworksManager`.
* The chain manager raises an error when not connected to a provider.
* The chain manager keeps track of a "snapshot stack"
See the new test module `tests/integration/test_chain.py`.
> feat: chain manager

- src/ape_ethereum/ecosystem.py
Use correct chain ID for goerli
changed it
I used this list to verify: https://besu.hyperledger.org/en/stable/Concepts/NetworkID-And-ChainID/
when typing `goerli` in chain list, it shows Optimism for some reason, probably how this happened.
> fix: chain id for goerli

- src/ape/api/compiler.py
- src/ape/managers/compilers.py
- src/ape/managers/project.py
- src/ape_pm/__init__.py
- src/ape_pm/compiler.py
- tests/integration/cli/test_compile.py
Fix ethpm-type manifest related validation errors.
The source IDs were full OS paths and should be relevant to the project `contracts/` directory.
This PR  fixes that!
What it was before:
```json
{"sources": {"Users/Jules/Projects/ApeProject/contracts/Fund.sol": ...}, {"Users/Jules/Projects/ApeProject/contracts/nested/Foo.sol": ...}}}
```
What it is now:
```json
{"sources": {"Fund.sol": ...}, {"nested/Foo.sol": ...}}
```
Adjust PM compiler to set source ID as relevant from the `contracts/` directory. Since we don't have access to the `ProjectManager` in the `CompilerAPI`, I made the `base_path` a config property in the `ape-pm` plugin that defaults to `Path("contracts/"). Some other general tweaking to handle this.
tests passing, make sure this makes sense too.
> fix: adhere to ethpm manifest compilation expectations

- build_docs.py
- src/ape/managers/chain.py
Fix docs build issue that happens during an alpha or beta release
make the dir first if not exists
next release?
release from a fork
> docs: issue with docs failing during beta release

- src/ape_console/_cli.py
- tests/integration/cli/test_console.py
Fix bug preventing the console from working with the `-v debug` flag.
Import the python version from `utils`.
```bash
ape console -v debug
```
> fix: bug preventing changing the verbosity when using the console command

- src/ape/managers/config.py
- src/ape_plugins/_cli.py
fixes: #400 
Fixes issue preventing you to use an `ape-config.yaml` to install plugins when that config file contains keys that those plugins use.
Additionally made some small fixes I noticed in `ape plugins li
Change error to logger warning
`ape plugins install`
`ape plugins uninstall`
> fix: warn when unprocessed config items instead of error

- src/ape/managers/project.py
- src/ape_run/_cli.py
- tests/conftest.py
- tests/integration/cli/projects/script/scripts/site.py
- tests/integration/cli/test_run.py
fixes: #396 
Fix bug preventing scripts to have names like `site.py` because `site` is a built-in python package.
Copied brownie.
`brownie` seems to register the user's full path, cache imports, and import the module via its full-path.
Are able to run scripts with names such as `site.py`.
Are able to run any scripts you could before.
> fix: issue preventing scripts from having the same name as a package

- src/ape_test/providers.py
Noticed that I could not set `required_confirmations` in the `ape-test` provider whereas I could in the `ape-hardhat` provider. Thus, I realized we were not passing along the kwarg so I made it so.
Pass the kwarg for `required_confirmations` to the `get_transaction()` call, copied how it was happening in the web3 provider.
Something like 
```
sender.transfer(receiver, "1 gwei", required_confirmations=3)
```
should not stall unless you are mining on another thread or something. But just by itself - it should hang forever waiting for confirmations.
> fix: issue preventing req confs from setting in test provider

- src/ape/exceptions.py
- src/ape_geth/providers.py
- src/ape_test/contextmanagers.py
- src/ape_test/providers.py
* Handle ContractLogic VM-errors in `ape-geth` and `ape-test` when making contracts calls. It was happening in transactions before but never in calls.
* Issue where we did not properly detect an empty revert message in `ape-test` because the message was `"b''"`.
* Other small fixes, like spelling
* Copy logic from `send_transaction()`
* Handle odd case in `ape-test` when empty revert message
```vyper
@view
@external
def valuation(tokenId: uint256):
assert tokenId > 0
```
and a test
```python
import ape
def test_no_portfolio(accounts):
a = accounts[0]
empty = a.deploy(ape.project.empty)
with ape.reverts():
empty.valuation(0)
```
```bash
ape test --network ::test
ape test --network ::geth
ape test --network ::hardhat
```
> fix: add missing error handling for VM-related contract logic errors in calls

- src/ape/contracts/base.py
fixes: #424
Coerce args **and** `abi.inputs` to empty list when they are `None`.
```python
from ape_tokens import tokens
yfi = tokens["YFI"]
yfi.decimals()  # <---   Outputs '18'
```
> fix: handle none args or inputs

- src/ape/cli/commands.py
- src/ape/managers/networks.py
Bug preventing setting default networks from working correctly.
Tried to use mainnet fork and struggles.
This config should work now:
```yaml
ethereum:
default_network: mainnet-fork
mainnet-fork:
default_provider: hardhat
hardhat:
mainnet_fork:
upstream_provider: alchemy
```
^ default network is `ethereum:mainnet-fork:hardhat` and upstreams to `alchemy`.
> fix: bug preventing setting default networks from working

- build_docs.py
- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/project.py
- src/ape_pm/compiler.py
fixes: #150 (not pushed yet)
Issue preventing dependencies from working correctly.
https://github.com/ApeWorX/ape-solidity/pull/20
A change that is part of this and something we wanted is that now, when we download a dependency from Github, instead of caching all the files, we only cache the manifest.
In `ape-solidity` (PR Linked above), we then de-compile the files from the manifest and put them in the `contracts/.cache` directory. Since only `solidity` needs this, it makes sense that it happens in the plugin.
Moves dependencies to `<project>/contracts/.dependencies` folder. Reason: This way, are in the base-path, which seems to be needed.  We still do the mapping (basically ignoring `.dependencies` part). This feels a lot like `remix`.### How to verify it
`simple-nft` project
> fix: bug preventing from solidity dependencies to work properly

- docs/userguides/config.md
- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/project.py
- src/ape_compile/_cli.py
- tests/integration/cli/conftest.py
- tests/integration/cli/test_compile.py
fixes: #409 
Grab / create the path using the value from the conifg `contracts_folder:` property.
If the value does not exist, default to what it was before (`self.config.PROJECT_FOLDER / "contracts"`)
* Create a project. Make things work as they did before.
* Set `contracts_folder: src` in your `ape-config.yaml` and rename `contracts/` to `src/`. Check that things still work. Recompile, etc.
* Renamed `src` back to `contracts`. Now, things should fail and it should not find your contracts.
* Create a global directory, like `$HOME/globalContracts`. Add contracts there. Set in your config the path to there (absolute). Notice things work - it compiles the global contracts.
> feat: allow configuring a global contracts path

- setup.py
Upgrade IPython to resolve vulnerability findings (CVE-2022-21699).
Noticed someone else did it and looked into it....
```python
In [1]: import IPython
In [2]: IPython.__patched_cves__
Out[2]: {'CVE-2022-21699'}
In [3]: 'CVE-2022-21699' in IPython.__patched_cves__
Out[3]: True
```
> fix: upgrade IPython to prevent potential vulns

- src/ape/api/accounts.py
- src/ape/api/address.py
- src/ape/api/explorers.py
- src/ape/contracts/base.py
- src/ape/managers/accounts.py
- src/ape/managers/chain.py
- src/ape/managers/converters.py
- src/ape/types/__init__.py
There is a lot of buggy-ness with trying to link to the docs for `AddressType`, sometimes intermittently and when you least expect.
Instead, just have a few spots where were link to [ChecksumAddress](https://eth-typing.readthedocs.io/en/latest/types.html#checksumaddress)
Otherwise, put things kind of back to the way they were.
Most of this PR is removing dead links.
> docs: fix issue with address type

- src/ape/__init__.py
- src/ape/managers/accounts.py
- src/ape/managers/chain.py
- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/converters.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape/plugins/__init__.py
- src/ape/utils.py
- tests/integration/cli/conftest.py
Removes `dataclassy` from all the managers and makes them regular python classes. Uses `injected_before_use` class to act as a property placeholder for the injected properties
Adds `injected_before_use` class 
Adds `__init__()` methods to pass the required non-injected properties by keyword.
All tests run
> refactor: remove dataclassy from managers

- setup.py
- src/ape/managers/converters.py
- tests/functional/conversion/test_timestamp.py
…ity issue with PyCharm/mypy
Added DatetimeConverter
PyCharm and mypy failed to recognize the need for inputs in DatetimeConverter() on line 163 of src.ape.managers.converters.py
Solves issue #436
Very similar implementation to TimestampConverter. I wonder if we could have just added some functionality to TimestampConverter to read in either a datetime or string. Not necessarily needed, doesn't change anything else
Test passed when there are `None` inputs in datetime_converter = DatetimeConverter() implementation
> feat: added DatetimeConverter

- src/ape/cli/options.py
- src/ape/managers/project.py
fixes: #446
Tried to do `ape compile` bit was segfault-ing because config was not loaded yet and weirdness ensued.
So I made it load earlier
Load config in cli ctx object.
able to compile again and stuff
> fix: load config at earlier point to prevent segfault when trying to access it

- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/project.py
- tests/integration/cli/conftest.py
*NOTE*: This PR is also a design proposal. I am trying to make comping dependency projects into manifest works better. I have everything working well in this PR: https://github.com/ApeWorX/ape/pull/431.  However, that PR is getting very large so this is part of my effort to try and break it down.
* New method `compile_project()` in the `CompilerManager` that takes the project path and the contracts path as well as the sources. The intent is to compile cleanly without the active project's interference. Otherwise, we get weird issues with dependency recursion.
* New method content manager method `using_project` in the `ConfigManager` that temporarily changes the `PROJECT_FOLDER` and the `contract_folder` properties. This is useful for compiling dependencies as well in our tests …
> feat: ability to compile external projects

- src/ape/contracts/base.py
- src/ape/exceptions.py
fixes: #449 
Issue where error was confusing and inconsistent with other contract calls / txs when deploying a contract with the wrong number of constructor arguments.
Check the abi inputs in `ContractContainer` and raise `ArgumentsError` in that case
Create a contract with a constructor that takes arguments:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;
contract Fund {
uint secretNumber;
constructor(uint _secretNumber) public {
secretNumber = _secretNumber;
}
}
```
Try to deploy the contract without giving it arguments and will arguments:
```python
from ape import accounts, project
accounts.test_accounts[0].deploy(project.Fund)   # <-- Fails with NEW-but-old custom exception 'ArgumentsError'
accounts.test_accounts[0].deploy(project.Fund, 5)   # <-- Works
```
> fix: raise ArgumentsLengthError when mismatched arguments length in contract constructor

- setup.py
- src/ape/managers/project.py
- tests/integration/cli/test_compile.py
Fix the bug causing failures in all our CI/CD tests.
Turns out it is real bug, kind of a big one.
Basically, we were short-circuiting `None` without fully searching for the contract in the path.
This prevents contracts from compiling.
Probably fixes: #469 
Explains why I couldn't repro it, it only happens some of the time, depending the order of searching in a path
only return in recurse if not None
passing tests will tell ya
> fix: bug preventing 'ape compile' from finding contract paths

- src/ape/utils.py
Exclude private repos from list.
This is to make the experience consistent for ape devs and **to make demos not accidentally reveal private information**.
check `.private` property of repo
`ape plugins list -a`
> fix: exclude private repos from 'ape plugins list -a'

- src/ape/cli/utils.py
- tests/functional/test_exceptions.py
fixes: #465 
Remove period thing
Make argument optional.
Always coerce to `"Operation aborted."`
```python
raise Abort()
```
> fix: use a default message in Abort when user does not provide message argument

- src/ape/utils.py
Delete method causing `ImportError` in python 3.10 from importing `collections.Mapping`.
Method is not used so deleting it.
`mypy` should work again (causing errors in other PRs). **Thanks mypy for finding this bug btw.**
> fix: handle importing 'collections.abc.Mapping' in python 3.10

- src/ape_plugins/utils.py
Currently, if you have installed plugins in editable mode, you are not able to remove them using `ape plugins remove`. This is because ape does not recognize them as installed.
This PR fixes that issue.
**This makes ape look less bad when demoing!**
Handle editable plugin entries in the `pip freeze` output.
`pip install -e ~/PythonProjects/ape-solidity`
`ape plugins remove solidity -y`
`ape plugins add solidity`
`ape plugins remove solidity -y`
> fix: support uninstalling editable plugins

- src/ape/contracts/base.py
Currently, if you try to access a non-existent function or event on a `ContractInstance`, you get the error:
```
ContractInstance has no attribute 'mint'.
```
Now, you get the error:
```
'BananaJamToken' has no attribute 'mint'.
```
Use `self._contract_type.name` if it is not `None`.
Deploy a contract.
Try calling a method on it but spell it wrong or something.
Check error message.
> fix: use contract name in error message when no attribute found

- src/ape/plugins/__init__.py
Currently, when a plugin is not fully implemented, you can get really nasty warnings, like this:
```
WARNING: '('ethereum', 'rinkeby', <class 'ape_chainstack.providers.Chainstack'>)' from 'ape_chainstack' is not fully implemented.
WARNING: '('ethereum', 'rinkeby', <class 'ape_chainstack.providers.Chainstack'>)' from 'ape_chainstack' is not fully implemented.
WARNING: '('ethereum', 'rinkeby', <class 'ape_chainstack.providers.Chainstack'>)' from 'ape_chainstack' is not fully implemented.
WARNING: '('ethereum', 'rinkeby', <class 'ape_chainstack.providers.Chainstack'>)' from 'ape_chainstack' is not fully implemented.
WARNING: '('ethereum', 'rinkeby', <class 'ape_chainstack.providers.Chainstack'>)' from 'ape_chainstack' is not fully implemented.
```
^ also for some reasons it warns repeatedly. …
> fix: improve warning for not-fully implemented plugins

- src/ape/api/providers.py
Noticed that when you don't assign anything to the output of a transaction, it displays via `repr` by default in `ape console`. However, this was ugly.
> refactor: use repr method instead of str

- src/ape/managers/networks.py
Adds missing `Raises:` doc. I was trying to find what this method raises but had to dig. This should help with that.
> docs: add missing raises statement to 'parse_network_choice()' method

- src/ape/logging.py
Change warnings label color from Red to Yellow. Maybe I am too sensitive right now, but it feels like they are yelling at me a lot when they don't need to be.
> fix: change warning label to bright yellow

- src/ape/api/providers.py
make repr for providers easier to read and not super big/
`ape console`
type `networks`
You should now see something like this:
```
<NetworkManager active_provider=<LocalProvider test>>
```
Before, it was a huge paragraph for provider.
> fix: make ProviderAPI repr more digestable.

- src/ape/api/projects.py
Before, if you compiled a dependency but didn't have any compilers installed, the dependency would get cached as a rather empty manifest file.
Now, if that happens, it will raise.
Still need a way (in the future) to have a way for the users to re-trigger downloading if they need.
Have no compilers.
Specify a dependency.
It show now fail instead of caching a lackluster manifest file.
> fix: raise when nothing compiled in dependency

- src/ape/api/projects.py
- src/ape/api/providers.py
- src/ape/managers/chain.py
- tests/integration/test_chain.py
Made `chain.blocks.range` work even more like python built in range method by making it so if you provide a single value, that value is considered the end of the range instead of the beginning.
check if second arg is None, if so, set second arg to first arg and first arg to 0
```python
for i in chain.blocks.range(5):
print(chain.blocks[i])
```
> refactor: make range work more like python builtin

- src/ape/api/networks.py
Issue where part of the docs was not loading correctly.
build docs
> docs: fix 'get_provider()' argument documentation

- src/ape/api/query.py
- src/ape/managers/query.py
Thought about how if a plugin is slow on first try, but quick after that (e.g. Caching design), there is no mechanism available for the database to update its cache if it is not called. This adds an option method that will be called on all plugins that did _not_ execute the query so that they can do this. 
Add an interface
> refactor: store results of query for plugins that cache

- src/ape/api/networks.py
- src/ape/managers/networks.py
fixes: #500 
* The module approach
Reason: It worked when I tried it and is easy to do. Non-breaking changes. Low risk. I don't see downsides?
https://github.com/ApeWorX/ape-fantom
> fix: use module name when registering providers

- src/ape/managers/project.py
Issue where setting default config data in dependencies always caused config files to get created even when it was not necessary.
> fix: issue where config file would unnecessarily get created

- src/ape_geth/providers.py
- tests/integration/cli/projects/geth/ape-config.yaml
- tests/integration/cli/test_networks.py
Issue where if you set a network default URI for the geth plugin in your project, that the default network URIs for the other networks will now all missing from the config, so you get `KeyError` when trying to access them.
Use default URI when network config missing.
Use `local` network in a project that specified the `mainnet` URI for the geth provide.
> fix: issue where if you set one geth network URI, all other default network URIs would vanish

- src/ape/cli/choices.py
- src/ape_ethereum/ecosystem.py
This part of this check causes issues when trying to get only Ledger accounts using the CLI option.
I don't think it is needed either.
> fix: issue preventing filtering plugin accounts in the CLI util option

- setup.py
- src/ape_init/_cli.py
Created the ape init command to make ape project and its default folders
contracts/
tests/
scripts/
ape-config.yaml
optional command --githhub username/repo
created a first class plugin
install ape
create an empty folder
and type:
`ape init`
`ape init --github username/repo`
> feat: add ape init

- src/ape/utils.py
- src/ape_test/__init__.py
For use in plugins like hardhat and fantom
put in `ape.utils` and use in `ape_test`
import in hardhat or fantom
> refactor: share default test mnemonic

- .github/workflows/test.yaml
- setup.py
We cannot support python versions 3.7 and 3.7.1; they are not part of the list of python versions the `ipfshttpclient` package supports: https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/master/pyproject.toml#L15-L23
And `ipfshttpclient` is a dependency of `web.py`. I raised an issue here https://github.com/ethereum/web3.py/issues/2378 to see if we can get it also upgraded there.
bump!
install ape on your python 3.7 version (which is probably python 3.7.12 or something)
> fix: adjust to honest python versions and upgrade web3.py dependency

- src/ape/api/address.py
- src/ape/contracts/base.py
- tests/integration/test_contracts.py
fixes: #541 
* Use init method since not a pydantic model
* Remove unneeded param
Deploy a contract, remember the address
Initialize contract with address. It fails to find the contract type because we are not yet caching those
> fix: (pydantic refactor continued) handle no contract type address init

- src/ape/contracts/base.py
We were using a default mutable argument, which is python anti-pattern than can lead to some highly unusual situations:
https://duckduckgo.com/?q=default+mutable+arugments+python&t=brave&ia=web
Default to None and coerce to empty list in first line of init
with your eyeballs is fine
> fix: issue where we were using a default mutable argument

- src/ape/pytest/runners.py
- src/ape_test/_cli.py
fixes: #525
Before output:
```bash
collected 0 items / 1 error                                                                                                                                                                    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: (ProviderNotConnectedError) Not connected to a network provider
```
New output:
```bash
==================================================================================== no tests ran in 0.01s =====================================================================================
```
* Don't try to disconnect if connect never happens
* Remove logger error stmt from …
> fix: handle exiting pytest when provider never connects

- src/ape/logging.py
- src/ape/plugins/__init__.py
Currently, if a plugin fails to load, it says you can debug the reason why... but the `-v` argument does not load in time, so you really cannot. Debugging other stuff works but not the failed to load plugins; that stuff happens really early in the lifecycle now.
This PR addresses this bug and forces a more eager setting LogLevel of the logger.
At plugin load time, check `sys.argv` and set the logger then.
Step 1: Break a plugin so it does not load
Step 2: Run `ape` notice it failed to load
Step 3: Run `ape -v debug` and notice you get a stacktrace
Step 4: Run `ape networks list -v debug` and notice the command still works AND you get a stacktrace at top for the failed to load plugin
Step 5: Notice `ape -v` fails the normal way and not in some weird way (careful arg indexing)
> fix: make debug work for failed-to-load plugins

- src/ape/managers/networks.py
fixes: #
Convert config to dictionary first to not use `__getattr__` and cause recursive errors and lack of explanation
Remove `default_provider` from an ecosystem plugin. Things should still "work".
> fix: bug where ecosystem implementations failed to load when their network configs did not have default providers

- src/ape/api/query.py
- src/ape/managers/chain.py
- src/ape/managers/query.py
- tests/functional/api/test_query.py
- tests/functional/conftest.py
Added a default block query under src/ape/api/managers
fixes: #526 
Perform query required a map function in order to deal with potential memory issues when performing large queries
Must add tests, but this was how I tested it from the ape console:
```python
In [1]: a = accounts.test_accounts[0]
In [2]: a.transfer(a, 100)
In [3]: a.transfer(a, 100)
In [4]: a.transfer(a, 100)
In [5]: chain.blocks.query("number")
In [6]: chain.blocks.query("number", "timestamp")
```
> feat: default query provider

- tests/functional/geth/test_providers.py
This mock is not needed. Left over from Pydantic refactor.
Piecing together Ecosystem stuff in my head.
passing tests suffice
> test: (pydantic refactor continued) remove unneeded mock in tests

- src/ape_geth/providers.py
I was confused by own my error message so I sought to fix it.
fixes: #
Mention the currently connected network.
Use `ape-geth` and mainnet without geth actually being running
> fix: improve error message when using non-local geth network

- docs/userguides/config.md
- src/ape/managers/config.py
- src/ape/managers/networks.py
- src/ape/utils.py
Allows user to config a default ecosystem.
* Add new item to config
* Set it as the default
* Also called `load()` before trying to get a config because of a "race" condition.
* Create a project using an ecosystem that is not Ethereum
* Add this to config: `default_ecosystem: the-ecosystem` replacing `the-ecosystem` with whatever ecosystem you are using.
* Run `ape console` and make sure it uses your default ecosystem
> feat: support configuring default ecosystem

- src/ape_accounts/_cli.py
- tests/integration/cli/test_accounts.py
* Fixed bug preventing `ape accounts list --all` from working correctly (it would error).
* Short plugin names in output when user does --all (to see what accounts come from which plugin)
* Added a test to make sure bug does not come back
* Cleaned up other tests
Just needed to handle the types correctly in that scenario.
Run the following with some account plugins installed:
```bash
ape accounts list
ape accounts list --all
```
> fix: issue preventing --all flag from working on accounts list command

- src/ape/api/networks.py
- src/ape/managers/config.py
- src/ape/managers/networks.py
* Make it raise better errors when ecosystems or networks don't exist in the network choice.
* Call `set_default_ecosystem()` in a place (was missing before somehow...)
* Delegate to getter methods that already raise instead of using dict access.
* Use bad networks / ecosystems in `--network` CLI option
* Make sure changing the default ecosystem works
> fix: handle when network values don't exist in choice-parser

- src/ape/utils.py
- src/ape_plugins/_cli.py
- tests/functional/test_utils.py
I wanted to do something similar to what we were doing in `ape plugins list` where we added spacing. I looked for a way to share this logic so we can do this again. While swapping it out in the `list` command implementation, I cleaned up the command's code.
The `ape plugins list` command uses the new method `add_spacing_to_strings()`.
Run these commands like this:
`ape plugins list`
`ape plugins list --all`
> feat: add utils method for adding spacing to strings

- src/ape/managers/query.py
- src/ape/utils.py
Added singledispatch to DefaultQueryProvider
Under the config for the BaseInterfaceModel I added singledispatchmethod to keep_untouched
Then added @singledispatchmethod
Passes original test
> refactor: use single dispatch for DefaultQueryProvider

- src/ape_ethereum/ecosystem.py
- tests/functional/test_chain.py
Noticed that Ethereum blocks had the same value set for both `hash` and `parent_hash`, so I fixed it
fixes: #592
> fix: parent_hash field is set incorrectly

- src/ape/api/projects.py
- src/ape/cli/paramtype.py
- src/ape/managers/compilers.py
- src/ape/managers/project.py
- src/ape/utils.py
- tests/integration/cli/projects/with-dependency/contracts/Other.json
- tests/integration/cli/test_compile.py
fix bug that @Ninjagod1251 found where you give you an argument to `ape compile` and that contract has uncompiled dependencies, it would fail.
Ensure the dependencies are included in sources.
They are missing when the user passes in arguments but not otherwise.
Go to a project with deps and run 
```bash
ape compile MyContractWithDeps
```
> fix: bug preventing compiling individual contracts that use dependencies

- setup.py
- src/ape/api/providers.py
- src/ape/utils.py
Adds `get_transaction_trace()` to `ProviderAPI`.
starts the work on #347 
Added method will throw `NotImplementedError` if the plugin does not support transaction tracing.
Call the method on a provider, once the hardhat implementation is merged, an EVM `TraceFrame` will be returned.
> feat: add get_transaction_trace to provider

- .pre-commit-config.yaml
- setup.py
- tests/functional/conversion/test_ether.py
`click` v8.1.0 was released a few hours ago, however this breaks `black` so update the pin for that as well
fixes: #504
> chore: upgrade click

- src/ape/managers/accounts.py
- tests/functional/test_accounts.py
Added ability to handle slicing when getting accounts
fixes: #605
added another singledispatchmethod item called __getitem_slice
```bash
ape console
```
```python
[1] accounts[-1]
[2] accounts[:2]
```
> fix: added feature to handle slicing when getting accounts

- src/ape_plugins/_cli.py
- tests/integration/cli/test_plugins.py
Fixed the output for `ape plugins list` to have the installed section display the versions
fixes: #
formatted the display to include it. It had it earlier but it broke. 
install plugins and check with `ape plugins list` and/or `ape plugins list --all`
> fix: version issue to display in installed sections

- docs/userguides/config.md
Noticed a sentence is in the wrong spot. Fixed it.
Moved sentence back to expected spot.
Doc makes sense.
> docs: put sentence in correct spot in dependencies config guide

- src/ape/logging.py
Noticed we were setting the log level many times unnecessarily.
Made it only set once.
* Break the loop once it finds a user given log level argument
* Only call setLevel on each logger after finding the log level
You can still set the log level in CLI commands.
> fix: issue causing the log level to get set multiple times

- src/ape_accounts/accounts.py
Fixed the return type for the encryption key in `ape-accounts`. It was marked as being an `EthAccount` but it is actually `HexBytes`.
Noticed the type was wrong and fixed it.
Please let me know if I am misunderstanding something.
> fix: return type of key in ape-accounts

- src/ape/api/query.py
- src/ape/managers/chain.py
- src/ape/managers/query.py
- src/ape_ethereum/ecosystem.py
- tests/functional/api/test_query.py
- tests/functional/conversion/test_ether.py
Pulled functionality of the chain.blocks.range to DefaultQueryProvider
fixes: #595
Refactor of the range function and DefaultQueryProvider as well as some changes to api.query
Built in tests for chain and query
> refactor: leverage query manager to complete historical block range queries

- src/ape/contracts/base.py
- tests/functional/test_contracts.py
fixes: #621 
Also adjust repr for events
Return the ABI with the most inputs? I am not sure what the original intent is. Also, what causes functions to have multiple ABIs? I haven't seen this. I can adjust the test case to account for this once I fully know.
the tests show that this is at least working now, even though more clarification is needed regarding methods with multuple
> fix: contract ABI repr errors

- src/ape_run/_cli.py
- tests/integration/cli/projects/script/scripts/error.py
- tests/integration/cli/projects/script/scripts/error_cli.py
- tests/integration/cli/test_run.py
fixes: #581
Catch the exception on invoke, check for `interactive`, launch console.
As far issue #581  goes, it seems like that is already fixed??? I am
> fix: issue when console would not launch when exception raised

- src/ape/api/query.py
- src/ape/managers/chain.py
- src/ape/managers/query.py
- tests/functional/test_chain.py
Noticed we were no longing using the `step` parameter on `chain.blocks.range()` method.
Fixed it!
Honor `step`.
See test :)
> fix: use step parameter to block_container.range() method

- src/ape/managers/config.py
- tests/functional/test_config.py
Made it so we use warnings instead of errors in config processing.
Reason: I was unable to install `ape-cairo` and `ape-starknet` in my demo starknet project because errors would happen.
Change `raise` statement to be `logger.warning` statements.
> fix: use warnings instead of erroring in config network processing

- src/ape/managers/project/types.py
- tests/integration/cli/projects/one-interface/contracts/Interface-with-hyphens.json
- tests/integration/cli/projects/one-interface/contracts/InterfaceWithNumber123.json
- tests/integration/cli/projects/one-interface/contracts/Interface_with_underscores.json
fixes: #662 
Adjusted the regex pattern that handles extension chains.
Compile OZ contracts
> fix: handle non alpha chars in contract names

- src/ape/plugins/__init__.py
fixes: #155 
Don't exept errors from first class plugins
1. On `main` branch, go to a first class plugin e.g. `ape_ethereum` and mess it up (add random characters to any file so it doesn't load right in Python)
2. Type `ape`
You will get WARNINGs like this:
```
WARNING: Error loading plugin package 'ape_ethereum'.
NameError: name 'asdf' is not defined
```
but ape will still work. **This is how we want second and third class plugins to work but if this happens to a first class plugins, that means the developer is currently messing up and this is not released.**
3. Checkout this branch and repeat step 2, now you should get a full stack trace
e.g.
```
File "src/ape/plugins/__init__.py", line 130, in __init__
plugin_manager.register(importlib.import_module(name))
File …
```
> fix: dont except errors from first class plugins

- src/ape/cli/options.py
- src/ape/logging.py
When using CLI plugins that fails, the `-v debug` flag would not register and I would not get a stack trace whereas it does for the non-CLI plugins. So, I figured out that it was more race conditions from click. Click actually calls the callback methods more than once. It does first to set the default value and again after it processes user args. So, it would get set to INFO, then the CLI plugin would fail to load, and then the DEBUG message would never get seen.
I fixed this.
Make the callback for the `verbosity_option` set from sys argv.
This makes it so plugins can still use this option (as currently it is not automatically given - will need to maybe look into `click-extensions` or whatever its called.
Mess up a plugin, such as a config related error.
Like what I did is add key …
> fix: issue with -v debug when CLI plugins failed to load

- src/ape/managers/project/manager.py
- src/ape_compile/_cli.py
- tests/integration/cli/projects/only-dependency/ape-config.yaml
- tests/integration/cli/projects/only-dependency/dependency_a/ape-config.yaml
- tests/integration/cli/projects/only-dependency/dependency_a/sources/DependencyA.json
- tests/integration/cli/test_compile.py
fixes: #659 
* Before warning and exiting early, check if the project has dependencies, which triggers them to get downloaded
* Additionally, allow `load_projects()` to still load dependencies before early returning (This is extra and may help from a programmatic perspective and help reduce potential for regression)
* Create a project that does not have a `contracts/` directory but does use dependencies.
* Run `ape compile`
* It should download and compile the dependencies
See tests as well!
> fix: bug preventing compiling dependencies in a project with no source files

- src/ape/api/networks.py
- tests/functional/test_config.py
I had a project saying to use `infura` as my default provider.
However - I didn't have the plugin installed. The error message I received was confusing, it said something like
`"No providers to handle network 'mainnet'"`, which simply was not true.
I realized the real error eventually and adjusted the error message and then added a test.
Change error message to say `Provider 'provider' not installed'
Add this to your `ape-config.yaml` file
```yaml
ethereum:
mainnet:
default_provider: DOES_NOT_EXIST
```
See the error message it yields!
> fix: error message when provider not found

- src/ape/api/providers.py
- src/ape_geth/providers.py
- src/ape_test/providers.py
- tests/functional/conftest.py
- tests/functional/test_accounts.py
- tests/functional/test_provider.py
partially fixes: #483 
* Track a cached chain ID.
* Unset when `disconnect()`
* Fix bug where you could not disconnect the `EthTester` provider.
Before this PR, there were 3 requests made to `chain_id()` RPC when deploying a contract.
Now, there are only 2.
There only needs to be 1 but this bug is preventing that: 
https://github.com/ethereum/web3.py/pull/2450
^ The other part to fixing the issue is completing the `web3.py` PR and bump our version of it here
> feat: cache chain ID to make less RPC calls

- src/ape/contracts/base.py
- tests/functional/test_contracts.py
In `ape-starknet` to deploy to `alpha mainnet` currently, you need a token for the whitelisted contract you wish to deploy.
There are several ways to set this, but one way should be via `deploy(token="MY_TOKEN")`. However - currently, that is not liked by the ape core framework. This PR addresses this!
Only convert known kwargs and return the rest as-is for ecosystem plugins to handle on their own.
TBD
> feat: allow ecosystem-specific kwargs in deploy

- src/ape_accounts/accounts.py
- tests/conftest.py
- tests/functional/test_accounts.py
- tests/integration/cli/conftest.py
fixes: #671 
Removed unneeded check and added lots of tests to make sure is working.
Please let me know if there are missing test cases.
1. Transact using keyfile account and leave account unlocked
2. Transact again in same session only when it asks you to sign, say "no". It should not sign! Before, it was.
> fix: bug preventing "no" from working in signing prompt

- src/ape/api/providers.py
Fixes an issue when using `mainnet-fork:hardhat` and you do `vars(provider)`, it would fail with `ProviderNotConnectedError` because it as trying to get the chain ID from the mainnet upstream provider (which is not connected really).
The fix is to do exactly the same thing that we are doing except **in a better, more optimized order**.
The solution: Detect if using a live network and return the hardcoded chain ID without first checking if `web3` is a thing.
Connect to mainnet fork:
```bash
ape console --network :mainnet-fork:hardhat
```
Run this:
```python
vars(networks.provider)
```
It should not fail anymore. Before, it did.
> fix: always return chain id from network when using live network

- docs/userguides/transactions.md
- src/ape/api/providers.py
- src/ape/managers/config.py
- tests/functional/test_config.py
Allow configuring `timeout` parameter on `web.py` `wait_for_transaction()` method.
Allow `ape-config.yaml` to configure the value and pass that value into the web.py method. Leave the default behavior otherwise.
Create a config like:
```yaml
transaction_acceptance_timeout: X
```
> feat: configure transaction acceptance timeout

- src/ape/managers/project/manager.py
- tests/functional/test_project.py
- tests/integration/cli/test_compile.py
added extract_manifest property to project manager
fixes: https://github.com/ApeWorX/ape/issues/703
added property of extract_manifest to project manager for better UX
try to extract the manifest with `manifest = project.Token.project_manager.extract_manifest`
> feat: extract-manifest in project manager

- src/ape_plugins/_cli.py
- tests/integration/cli/test_misc.py
- tests/integration/cli/test_plugins.py
Fix bug where plugin name showed up in available plugins when it was installed
Strip the items in a set.
Run the test.
Note: plugins tests currently are manual because of issues like this: https://github.com/ApeWorX/ape/issues/285
> fix: bug where plugin name showed up in available plugins when it was installed

- src/ape/pytest/fixtures.py
- src/ape/pytest/runners.py
- tests/integration/cli/projects/test/tests/test_fixture_isolation.py
- tests/integration/cli/projects/test/tests/test_misc.py
- tests/integration/cli/test_test.py
fixes: #713 
Also adds docs to fixtures
Use session fixturemanager as point-of-reference for getting fixture info 
You can no run the tests in https://github.com/fubuloubu/ERC4626
> fix: bug preventing the use of pytest built-in fixtures in ape tests

- docs/userguides/config.md
fix typo in an example
source for correction: https://github.com/ApeWorX/ape/blob/2392d53afa6ba2181f62da7aeb14a85b52ae0be6/src/ape_ethereum/ecosystem.py#L61
> fix: typo in mainnet-fork

- src/ape/contracts/base.py
- tests/functional/test_contracts.py
Supports `project.MyContract.my_method.call` to use `eth_call` instead of actually transacting.
Add
```python
@property
def call() -> ContractCallHandler
```
to `ContractTransactionHandler`
You can now do `project.MyContract.my_mutable_method.call(args)`
> feat: support calling transactions

- src/ape/api/accounts.py
- tests/functional/test_accounts.py
`transfer(receiver)` now throws error message
`transfer(receiver, send_everything=False)` now throws error message
`transfer(receiver, send_everything=True)` now works
fixes: https://github.com/ApeWorX/ape/issues/728
discussed at length https://github.com/ApeWorX/ape/issues/728
test cases have been added
> fix: transfer send_everything does not work properly

- src/ape/api/networks.py
- src/ape/utils/basemodel.py
Trying to resolve a Pydantic anomaly but also something we should probably do anyway 
Delegate back to `__getattribute__` when network not found.
If CI/CD passes, that is a good thing!
Also the error is better now when accessing unknown networks on an ecosystem using dot access.
```python
networks.ethereum.remove_network()  # Method not a thing
```
> fix: raise attribute error in EcosystemAPI getattr

- setup.py
- src/ape/api/compiler.py
- src/ape/api/projects.py
- src/ape/managers/compilers.py
- src/ape/managers/project/types.py
Adds `imports` list and `references` list to `PackageManifest`'s `source` object.
Adds check for `references` list when compiling from cache to see if dependent references need additional compiling.
partial fix for #623 
unblocks @sabotagebeats on #81 
Logic for fetching imports is in the compiler plugins, i.e. `ape-solidity`
https://github.com/ApeWorX/ape-solidity/pull/36
Follow the steps in #623   NOTE: One failing test based on a change of account repr, has nothing to do with this PR
> fix: ape compile dependent imports

- src/ape/managers/chain.py
- tests/functional/test_contracts.py
Accidental regression where could no longer specify `contract_type` in `ape.Contract` which broke `ape-tokens`.
> fix: regression where could not specify contract type

- src/ape/managers/chain.py
This was a regression...
Before, we were fetching the contract from Etherscan and that part got somehow dropped out of the PR!
here puts it back! But the problem: **There is no good way to test this feature**
Had a discussion with @fubuloubu about registering the contract cache work as an `ExplorerAPI`, which would solve that concern. I would really like tests for this.
> fix: regression where ape.Contract() would not fetch the contract type from the explorer

- src/ape/managers/project/manager.py
- tests/integration/cli/test_project.py
While working on the source imports, I set up a test that used `project_manager.get_project()` and didn't pass the contracts folder and received a validation error. 
I corrected the contracts folder default behavior and added tests.
fixes: #
> fix: default contracts folder path

- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/managers/chain.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/providers.py
Automatically infer ContractType for minimal proxies
fixes: #734
Match known bytecodes, storage slots and views, then request the target's ContractType.
API changes:
- EcosystemAPI: add `get_proxy_info`
- ProviderAPI: add `get_storage_at`
- [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167)
- [Vyper](https://github.com/vyperlang/vyper/blob/0b3f3b329e59cf90bbff8a883b49f1166eb716a2/vyper/functions/functions.py#L1420)
- [0xSplits Clones](https://github.com/0xSplits/splits-contracts/blob/main/contracts/libraries/Clones.sol#L32)
- [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967)
- [EIP-1822](https://eips.ethereum.org/EIPS/eip-1822)
- [OpenZeppelin UpgradeableProxy](https://github.com/OpenZeppelin/openzeppelin-labs/blob/master/initializer_contracts/contracts/UpgradeabilityProxy.sol)
- …
> feat: detect minimal proxies

- src/ape/utils/github.py
- tests/functional/utils/test_github.py
- tests/functional/utils/test_misc.py
- tests/functional/utils/test_os.py
Fix little issue where we couldn't download repos using the `version:` github method when the github tag was**not** prefixed with a `v`.
Try the way it is first normally.
Then, try either stripping the `v` or adding `v` as a final attempt.
You can now use https://github.com/smartcontractkit/chainlink-brownie-contracts as a dependency with config:
```yaml
dependencies:
- name: chainlink
github: smartcontractkit/chainlink-brownie-contracts
contracts_folder: contracts/src/v0.4
version: 0.4.1
```
> fix: issue where could not use dependencies with non v-prefixed Github release tags

- docs/userguides/console.md
Adds root level namespace items to console guide
A markdown table with links pointing to method docs
links work
> docs: add root level namespace to console guide

- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/project/types.py
- tests/functional/conftest.py
- tests/functional/data/projects/long_contracts_folder/source/v0.1/long_contracts_folder.json
- tests/functional/test_config.py
- tests/functional/test_project.py
Issue preventing using `chainlink-brownie-contracts` as a dependency because of the need to set a more complex contracts folder path
e.g.
```yaml
dependencies:
- name: chainlink
github: smartcontractkit/chainlink-brownie-contracts
version: 0.4.1
contracts_folder: contracts/src/v0.4
```
Changed `path.name` to the suffix after the base path.
can use the chainlink repo as a dep (have to also use https://github.com/ApeWorX/ape-solidity/pull/42)
> fix: bug preventing longer contracts_folder paths in dependencies

- src/ape/api/providers.py
- src/ape_ethereum/ecosystem.py
fixes: #772 
* move error handling logic for VM stuff to base Web3 provider to share code amongst all providers. This was not possible before but now it is since the newly added API method for getting the VM error.
> fix: issue with error handling during proxy contract detection

- src/ape/contracts/base.py
fixes: #751 
Well, it does not actually resolve their error but gives more detail on how to fix it.
It seems problematic to have two events with the same name so I am guessing it is probably best to raise an error.
An alternative is to rename the events to `Initialized_0` and `Initialized_1` and so on (plus a WARNING), but that seems not ideal from the project's perspective.
Any other ideas? Is  `veYfi` able to rename `Gauge.Initialized` event?
> docs: improve error message when multiple events with same name defined

- src/ape_ethereum/ecosystem.py
Handle random VM errors for proxy detection. Observed when working on `ape-foundry`.
> fix: ignore all TX errors in proxy detection

- src/ape/api/providers.py
The type of `block_id` does not seem to match the implementing behavior
changed it!
Tell me I am wrong if I am
> fix: correct type of block ID in abstractmethod

- src/ape/exceptions.py
- src/ape/utils/misc.py
- tests/functional/utils/test_misc.py
This comment: https://github.com/ApeWorX/ape/pull/746#discussion_r893026642
made me realize that the output for not implemented API methods was not very good.
This PR improves that experience!
Make a custom exception that is both an `ApeException` and the stdlib exception `NotImplementedError`.
* Test that the output shows the API method
* Test that the error is also a `NotImplementedError`
> feat: custom not implemented exception

- CONTRIBUTING.md
- README.md
- fixed a couple broken relative paths
- today, the projects guide link returns a 404 when visited via the README or published docs
- misc. cleanup for more consistent markdown use
within a time-box, i couldn't figure out how to make GitHub relative paths satisfy both links served via the README on GitHub and via the published gh-pages docs. Opted for the hard-coded docs link, as is used elsewhere in the README.
- verify the links in the README of my forked repo
- build the docs locally or via CI and test the relevant links in the Quick Start guide
> docs: link repair, misc cleanup

- src/ape/api/transactions.py
- src/ape/utils/basemodel.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- tests/functional/test_ethereum.py
- correctly instantiate transactions coming from `BlockTransactionQuery`, previously they were missing `data` and `signature`
- add `txn_hash` property to `TransactionAPI`
- add `AccessListTransaction` type and optional access list for `DynamicFeeTransaction`
- fix a bug with whitespace bytes being stripped when parsing txn data
`chain.blocks[height].transactions` should yield transactions with correct calculated `txn_hash`
> feat!: add access list transaction type, add transaction api txn_hash, fix block transaction query

- src/ape/managers/config.py
- src/ape/managers/project/manager.py
- tests/functional/test_project.py
Adding the package meta to the project config and project manager 
fixes: #793 
following instructions laid out in issue #793 
When it works, the package meta should be filled out in the contract manifest
> feat: Adding packagemeta to config and project manager

- README.md
- docs/userguides/transactions.md
- src/ape/contracts/base.py
- tests/functional/test_contracts.py
Allows you to estimate fees of a transaction without sending it.
Add a `as_transaction()` method to the `ContractTransactionHandler` that can create a `TransactionAPI` object from which you can pass to `provider.estimate_gas_cost()`.
Am open to alternative designs!
> feat: better estimate fee support

- src/ape/api/providers.py
- tests/functional/test_chain.py
- tests/functional/test_ethereum.py
This just makes life a little easier elsewhere for me :)
Otherwise when initializing blocks using `kwargs`, you have to use camelCase and looks funny in the pythons
In BlockAPI validator, handle both snake_case and camelCase parent hash keys.
I added a test
> feat: handle snake_case parent block hash in BlockAPI

- src/ape/api/query.py
- src/ape/managers/chain.py
- src/ape/managers/query.py
- tests/functional/api/test_query.py
Pandas was removed from `DefaultQueryProvider`, and in turn pulled the dataframe functionality out of Ape all together.
Pandas was brought back into the fold in the chain manager
fixes: #
Instead of return the map from the `DefaultQueryProvider`, in `chain.blocks.query`, we are now pulling the map apart and injecting it into a dataframe.
Run the tests for `test_query.py` and `test_chain.py`
> feat: added pandas back to chain

- src/ape/managers/chain.py
- tests/functional/api/test_query.py
Allow relative indexing for start and stop block numbers in `chain.blocks.query`
```py
chain.blocks.query("*", stark_block=-50)
chain.blocks.query("*", start_block=-50, stop_block=-30)
```
Make relative to absolute by adding `len(chain.blocks)`
Try it out!
> feat: allow relative indexing block numbers in query

- src/ape/managers/converters.py
- tests/functional/conversion/test_timestamp.py
Update the conditional in `TimestampConverter.is_convertible()` to
return false if the string has no whitespace or has more than two
pieces (i.e. whitespace separated tokens)
Also added a test against bad timestamp strings
fixes: #803 
`dateutil.parse()` will actually accept a single integer string, and the output
depends on what number range the integer falls under. Numbers like `6` affect
the date or month, while `2011` affects the year. So if a number is in a valid range
`parse()` will pass meaning the `TimestampConverter` gets used.
Simple integers without units or date formatting - as described 
in #803 - should now raise `ConversionError`:
```python
ape.convert("123", int)
ape.convert("123456", int)
ape.convert("0", int)
```
> fix: prevent TimestampConverter from accepting single integer strings

- src/ape_console/_cli.py
- tests/integration/cli/projects/only-dependencies/dependency_in_project_only/importme.py
- tests/integration/cli/test_console.py
Thanks @banteg for bringing this is our attention.
This PR allows you to import local packages / folders in your ape console
Add cwd to the sys path before launching the console.
Launch your console in a project that contains a folder with some python stuff in it.
Try importing the stuff from that module.
> fix: issue preventing importing local packages in ape console

- src/ape/managers/project/dependency.py
- tests/integration/cli/projects/with-dependencies/ape-config.yaml
- tests/integration/cli/projects/with-dependencies/renamed_contracts_folder_specified_in_config/ape-config.yaml
- tests/integration/cli/projects/with-dependencies/renamed_contracts_folder_specified_in_config/my_contracts/renamed_contracts_folder_specified_in_config.json
- tests/integration/cli/test_compile.py
Noticed it was kind of awkward when using local dependencies when you control both projects and they are both ape projects to have to specify the contracts folder in both places. Instead, attempt to read an `ape-config.yaml` and detect it automatically!
With the help of pydantic root validator as well as the `load_config` util method.
I added a test!
But also, I am working on converting dsnote to be an ape project: https://github.com/unparalleled-js/ds-note
and I need this for tests.
> fix: detect contracts folder automatically when default in local dependencies

- src/ape_accounts/accounts.py
- tests/functional/test_accounts.py
* Only unlock when enabling
* Only warn when enabling
* Only re-lock if disabling
**NOTE**: I think we consider keeping `unlock()` and `set_autosign()` separated. It would be a breaking change or I would have done it now. The reason is because it is weird if you unlock an account, turn autosign on, sign something, disable autosign, and now your account is suddenly re-locked. It is a strange side-effect in that scenario, but generally rare for the use-case if just enabling autosign for automated testnet deploy scripts etc.
if statements everywhere!
see tests
> fix: issue where account would remain unlocked when disabling auto-sign

- src/ape_console/_cli.py
- tests/conftest.py
Prevents IPython from spawning history collection threads when running the test suite
fixes: #881 
Add an auto-used fixture to patch an `APE_TESTING` environment variable in while testing. The IPython embedded instance launches with history disabled if this environment variable is set.
If the tests weren't failing from "too many open files", you can change the soft limit on your machine with this.
```shell
$ ulimit -n  # check current value so you can restore it later
...
$ ulimit -Sn 256  # set value to what was default in #881's repro steps
$ pytest tests/integration
```
This should produce a failure without these changes
> fix: disable console history in tests

- src/ape_geth/providers.py
when using a connection uri which contains `user:pass`, it was output as plain text:
```
INFO: Connecting to existing Erigon node at 'https://bunny:carrot123@bunny-server.com/'.
```
added `GethProvider._clean_uri` which strips username and password from connection string and use it when we print it. the `yarl` package i import is a dependency to `web3`.
now it's printed like this:
```
INFO: Connecting to existing Erigon node at 'https://bunny-server.com/'.
```
> feat: strip uri credentials from logs

- tests/functional/test_provider.py
- tests/functional/test_types.py
Noticed this test did not test anything from the provider and was more about `ape.types.LogFilter` so I moved it.
> test: put type decoding test in test_type module

- src/ape_ethereum/transactions.py
- tests/functional/test_receipt.py
Noticed while upgrading the starknet plugin that we were making an unnecessarily API call sometimes, in the cases where the user passes in EventABI objects
check if not None instead of if truthy, This prevents the `__len__` call which makes an API call (note: the `__len__` method making an API call seems unexpected and maybe should be re-visited)
> fix: prevent unnecessary API call when decoding events from ABI

- .pre-commit-config.yaml
- docs/userguides/testing.md
- pyproject.toml
- setup.py
- src/ape/api/accounts.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/managers/chain.py
- src/ape/pytest/fixtures.py
- src/ape/pytest/runners.py
- src/ape/utils/misc.py
- src/ape_test/providers.py
- tests/conftest.py
- tests/functional/conftest.py
- tests/functional/data/projects/ApeProject/ape-config.yaml
- tests/functional/test_accounts.py
- tests/functional/test_chain.py
- tests/functional/test_cli.py
- tests/functional/test_contract_container.py
- tests/functional/test_contract_event.py
- tests/functional/test_contract_instance.py
- tests/functional/test_networks.py
- tests/functional/test_provider.py
- tests/functional/test_query.py
- tests/integration/cli/projects/test/contracts/MyContract.json
- tests/integration/cli/projects/test/tests/test_networks.py
- tests/integration/cli/projects/with-contracts/tests/test_contract.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_test.py
Fixes issue where the provider context as not properly handling multiple providers.
* Don't disconnect providers until very end of test run
* Manage a stack of provider IDs to keep track of the order of provider to pop / push... However! If the provider was previously added, it is already connected and remains so, only the stack ID changes.
See these tests: https://github.com/unparalleled-js/ape-demo-starknet/tree/main/tests
> fix: issue preventing provider context manager from switching in test fixtures

- docs/userguides/testing.md
#934 follow-up.
Adding the same kind of link for the account fixture
Proof-reading
- [n/a] New test cases have been added
> docs: add links to the reference page (follow-up)

- tests/functional/utils/test_abi.py
The previous regex was allowing some invalid inputs such as `(,)` to get through.
Updated the regular expression to match expected Vyper decls like:
- type identifiers
- array declarations
- tuples of type/array
- tuples of type/array/tuple/etc
I split the various expected sub-patterns to their own variables so they're easier to read and can be commented on separately
__NOTE:__ I used non-capturing groups (?:) on the regex site just to make the highlight colors a little less chaotic 👀 the groups in the Python code don't need to be non-capturing so I omitted them there
The regular expression (i.e. the value of `TYPE_DECL`) and some sample input are here:
https://regex101.com/r/dVmiYA/1
Screenshot for posterity, the non-highlighted text below shows invalid input that we don't want to use …
> test: update test_parse_type() regex

- docs/userguides/contracts.md
- docs/userguides/transactions.md
- src/ape/api/accounts.py
- src/ape/contracts/base.py
- src/ape/exceptions.py
- src/ape/managers/chain.py
- src/ape/utils/trace.py
- tests/functional/conftest.py
- tests/functional/test_accounts.py
- tests/functional/test_chain.py
- tests/functional/test_contract_container.py
- tests/functional/test_contract_instance.py
- tests/functional/utils/test_trace.py
fixes: #806 
* Adds `txn_hash` to `ContractInstance` that gets set whenever possible, such as after deployments as well as if instantiating a contract that was previously deployed (using the `instance_at()` method).
* Adds `.receipt()` convenience property to the `ContractInstance`. Now, after you deploy, you have access to the receipt pretty immediate.
**This is needed to unblock my work for publishing deployments but is also kind of nice to have anyway and I think exists in Brownie.**
* Add `txn_hash` arguments to `contracts.instance_at()` and `contract.at()`
* Add `transaction_hash` key to the deployments cache
* Set the `txn_hash` automatically when calling `.deploy()`
* Have `instance_at()` try to look up the `txn_hash` when it is not provided (if it was from a deployment)
* Had to …
> feat: add `receipt` / `txn_hash` to `ContractInstance`

- src/ape/api/config.py
- src/ape/api/networks.py
- src/ape/managers/config.py
- tests/functional/test_config.py
During testing today, noticed that if I set a `default_provider` in my `ape-config.yaml` file, it would remove the default value of `block_time` that gets set in the ecosystem plugin.
It has to do with Pydantic models updating from keys where the value is a dict. It replace all the values instead of updating the sub-dicts individually.
Recursively update PluginConfig from user overrides. Made a helper class method for this (`from_overrides()`.
Have a config file like this:
```yaml
ethereum:
rinkeby:
default_provider: alchemy
```
Launch a rinkeby console `ape console --network ethereum:rinkeby:infura`
Before my changes:
```python
In [2]: provider.network.block_time
Out[2]: 0
```
After my changes 
```python
In [2]: provider.network.block_time
Out[2]: 15
```
> fix: issue where setting a config item would remove defaults of the other items

- src/ape/contracts/base.py
- src/ape_geth/providers.py
- tests/conftest.py
- tests/functional/test_geth.py
- fixed log fetching with geth provider, which had a `_make_request` before it was added to web3 provider with a different api. bug was introduced in #943.
- fixed `ContractEvent` instantiating a `LogFilter` with no search topics, which resulted in fetching all contract logs and not just the ones corresponding to the event.
> fix: incorrect log filters, broken logs with geth

- src/ape/api/providers.py
@helloibis pointed out the web3provider kwargs were not present in the method docs. This adds them to the `Web3Provider`.
Re-doc the differing methods in `Web3Provider` and include the updates parts.
Read through em!
> docs: document differing web3provider behavior

- docs/userguides/publishing.md
- src/ape/managers/project/manager.py
- src/ape/utils/github.py
- tests/functional/conftest.py
- tests/functional/test_chain.py
- tests/functional/test_project.py
fixes: #530 
* Build the `EthPMContractInstance` artifact in the new `track_deployment()` method.
* Have it store the build artifact in `<project>/.build/deployments/<bip122-chain-id>/<contract-name>.json`.
In an Ape project, run:
```python
from ape import accounts, project
acct = accounts.load("metamask0")
contract = project.MyContract.at("0x...")
project.track_deployment(contract)
```
The ensure the build artifact is present in the `deployments` list
> feat: track deployments

- src/ape/api/networks.py
- src/ape/managers/networks.py
- tests/conftest.py
- tests/functional/test_geth.py
- tests/functional/test_networks.py
While testing Blake's work, noticed this issue and it was bugging me so fixed it right quick.
Catch non connected error and it is ok!
See tests
> fix: handle repr on network API when no connected

- src/ape/types/__init__.py
- tests/functional/test_types.py
Adds missing tests that ensure `str()` and `repr()` work, as it was brought up by the community.
Now we know it for sure works in the latest.
Add tests.
Add `repr` method to `ContractLog`.
tests
> test: ensure contract log str and repr work

- src/ape/api/config.py
- tests/functional/test_config.py
This unfortunately is causing issues in `ape-hardhat` right now.
Allows keys not present in case that subkeys are dicts instead of classes.
See test!
> fix: bug where plugin config would not update when default was empty dict

- src/ape/api/projects.py
- tests/conftest.py
- tests/functional/test_dependencies.py
- tests/functional/test_project.py
Another distracting warning that kept appearing in my ape tests from using a dependency that used a branch.
The warning would be about the use of `LegacyVersion` which `packaging.parse()` will return if the given param is not a PEP440 version ID (such as the string `"main"`).
To remedy, instead of using `parse()`, we attempt to init a `Version()` directly and catch the error when it fails. Then, the warning never arrives. This also is slightly more efficient.
When you run tests in a project that use a dependency that uses a branch n GitHub, you don't get the `LegacyVersion` warning.
See the test I added!
> fix: warning from using LegacyVersion

- src/ape/api/providers.py
Noticed the link to web3.py was broken in the `Web3Provider` class doc.
Also think it is useful to include a doc str for the `web3` property so people know it is there.
```sh
python build_docs.py
python -m http.server --directory "docs/_build/" --bind 127.0.0.1 1337
```
make sure link works
make sure can see `web3`  prop doc
> docs: fix web3 link and doc web3 prop

- .github/workflows/test.yaml
- tests/integration/cli/test_run.py
* Speeds up test runs by utilizing x-dist
* Fixes warnings from coverage
* Fixes flakey script test
> test: use x-dist in tests

- setup.cfg
- src/ape/cli/options.py
- tests/functional/test_cli.py
Add `required` parameter to `network_option`.
self explanatory!
You can now require the user to input a value when they use the `--network` flag
```python
import click
from ape.cli import network_option
@click.command()
@network_option(required=True)
def cmd(network)
print(network)
```
> feat: required param in network option

- setup.cfg
- setup.py
- src/ape/utils/misc.py
- tests/functional/utils/test_misc.py
I am working through an environment issue today that is blocking me on everything.
I was also getting a warning about duplicate package names, I thought it might be related to my env issue, so I explored it.
Turns out, I somehow had an egg install of ape that I could not get rid of. It would appear everytime I did an editable install of ape because the egg file was in the ape directory, so it gave me warning: `WARNING: duplicate pkg_name 'ape'` or something... I wanted more info to help me debug it so I made it say this instead:
```
WARNING: Found 2 packages named 'eth-ape'.
Installation paths:
/Users/jules/virtualenvs/alien/lib/python3.7/site-packages/eth_ape-0.4.4.dev1+ge33d2ca0.d20220815.dist-info,
/Users/jules/PycharmProjects/ape/src/eth_ape.egg-info
```
Now I know exactly what is …
> docs: better warning when multiple installation paths

- docs/userguides/cache.md
- setup.py
- src/ape/api/providers.py
- src/ape/api/query.py
- src/ape/api/transactions.py
- src/ape/managers/chain.py
- src/ape/managers/query.py
- src/ape_cache/_cli.py
- src/ape_cache/models.py
- src/ape_cache/query.py
- src/ape_ethereum/ecosystem.py
- tests/integration/cli/test_cache.py
Added CacheQueryProvider to ape cache and created initial database structure and methods to instantiate an sqlite database for caching provider data.
fixes: #632
created cli and added init, purge and query functions
I used the infura plugin
```bash
ape plugins install infura
```
Then instantiate the caching database
```bash
ape cache init --network ethereum:mainnet:infura
ape console --network ethereum:mainnet:infura
```
Run this multiple times:
```python
In [1]: chain.blocks.query("number", start_block=0, stop_block=100)
```
You should see that the query occurs quicker after the first call. This will take a few seconds to grab the data from the provider
Also run transaction calls multiple times:
```python
In [2]: chain.blocks[-2].transactions
```
You should see that the query is quicker …
> feat: added ape cache plugin

- src/ape/plugins/__init__.py
Editable plugin installation was giving me another issue with a value like this:
```
__editable___ape_starknet_0_4_0a2_dev0_gf91d85b_d20220818_finder
```
so this PR handles that.
**NOTE**: This is not really a user facing bug, only someone who develops plugins would hit this. There is not really an easy way to test this.
> fix: issue with editable plugins

- src/ape_ethereum/ecosystem.py
- tests/functional/test_ecosystem.py
Regression from cache PR where could not decode pending blocks in `ape-hardhat`
Handle when hash is None in data when decoding block
Launch hardhat console
```sh
ape console --network ethereum:local:hardhat
```
Get pending block
```python
networks.provider.get_block("pending")
```
It should work
> fix: issue with decoding None block hashes

- src/ape/managers/compilers.py
- src/ape/managers/project/manager.py
- tests/functional/test_compilers.py
- tests/functional/test_project.py
There are a couple places in core ape where we forget to filter sources paths being passed to the compilers.
* Filters sources by suffix before passing to compiler methods.
> fix: filter sources when passing to compiler methods

- src/ape/api/networks.py
- src/ape/plugins/__init__.py
- tests/functional/test_plugins.py
I attempted to install `ape-arbitrum` in editable mode and hit the same issue.
After investigating, I noticed the value was `__editable___ape_arbitrum_0_4_0_finder` which was not handled properly.
Adjust regex.
Add tests.
Tracking all variations in a test now.
> fix: handle another strange edition of editable plugin installations not registering

- docs/userguides/console.md
- src/ape_console/_cli.py
As it is good practice to explicitly use the `np.` and `pd.` namespaces in larger scripts using numpy/pandas, some users prefer always using the ape prefix as in `ape.networks`, `ape.accounts` etc. for more clarity.
Having the `ape` name available by default in the console allows for sending code from script to console easily and using the same syntax/habits in both.
> feat: add `ape` to console namespace

- src/ape/managers/project/types.py
- tests/functional/test_compilers.py
- tests/functional/test_project.py
```greentext
> be me
> dont compile project for long time. get told about bug. now try to compile again
> *dies*
> realize that it is failing because there are references in the cached manifest pointing to the sources that no longer exist
> by references, I don't mean deleted source files... we handle those fine.. I mean that a file has "changes" but also in the cached manifest, it has reference entries but those point to non-existent files. that is what is missing.
> fix bug easily
> write a test but that takes a little while but feel good about it
```
Filter out deleted files.
Add test
> fix: bug when cached sources contain deleted references

- src/ape/api/providers.py
Otherwise puts out a lot of noise:
> refactor: make stdout-logger only log debug, not info

- src/ape/api/address.py
- src/ape/managers/chain.py
- tests/functional/test_accounts.py
- tests/functional/test_chain.py
Noticed that if my explorer breaks, which is does a lot during development, and if I don't have a cached contract type and I provide the contract type as a parameter, things don't work.
I'd expect things to still work since I am providing the contract type.
This makes things still work while refactoring / documenting the decisions as to why it is the way it is now.
Additionally, fixes a weird thing would happen when comparing `Address` classes to other non `Address` classes (minor fix but nice none-the-less)
In both cases, handle exceptions.
* Install ape-etherscan
* Break it 
* Have a contract type locally that is deployed as well on a live network
* Try to create an instance using this contract type... Notice it won't work because of Etherscan.
See tests as examples too!
Also try …
> fix: ignore exceptions when given a contract type during `instance_at` / `Contract`

- src/ape/api/query.py
- src/ape/contracts/base.py
- src/ape/managers/chain.py
- tests/functional/test_query.py
Refactor how dataframes are pulled from the query plugin system (pulls attributes from objects instead of using Pydantic's `.dict` method)
This allows querying objects that don't appear in a model's Pydantic schema
Also refactored how `validate_and_expand_columns` works so that you pass a model instead of a list of fields
slight abuse of MRO and `vars`
`df = chain.blocks.query("transactions")`
> feat: support querying properties of Blocks and Events

- src/ape/managers/chain.py
- tests/functional/test_chain.py
When you ask for receipts using an explorer for a contract address, you get back transactions made to the contract as well. This would cause a collisional error via a caching mistake because of a faulty check before caching where we checked for the contract address instead of the sender. This caused errors.
This PR fixes the check to use the sender instead. Now, there are no more errors.
I added a test to be sure. This test fails when undoing the single line of source change.
Use `receipt.sender` instead of `address_key`.
> fix: check sender for already-cached receipt instead of address key

- src/ape/managers/chain.py
It can be annoying when appending a known transaction and it error.
I think a warning is better so you don't fail everything.
> refactor!: warn instead of err when appending a known txn

- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape/managers/chain.py
- tests/functional/test_chain.py
* Changes `txn.sender` and `txn.receiver` to be `AddressType` instead of `str`
* Changes `chain.contract.instance_at()` to only accept `AddressType` and not `str`
* Changes `ContractInstance` to only accept `AddressType` and not `str`
* Removed unneeded calls to `decode_address()`
> refactor: Use `AddressType` instead of `str` when possible

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
Pinning evm-trace to 0.1.0a7 so that we can refactor tracing with out breaking the API layer.
> chore: pin evm-trace

- docs/userguides/projects.md
correct url ends in .html , not .md
Fixed a typo
fixes: #
- before: https://docs.apeworx.io/ape/stable/userguides/installing_plugins.md
- after: https://docs.apeworx.io/ape/stable/userguides/installing_plugins.html
> fix: broken url

- .github/workflows/test.yaml
- README.md
- src/ape/cli/paramtype.py
- src/ape_ethereum/__init__.py
Fix flakey tests failing in CI
Readme adjustments (to re-trigger builds)
Uninstall eth-ape first before installing before running tests
Also readme fixes
Passing build last 3x in a row.
> test: fix flakey tests

- tests/functional/test_accounts.py
- tests/functional/test_chain.py
- tests/functional/test_contract_instance.py
receipt.transactions attributes can be directly called, and these tests should reflect that.
fixes: #1044 
search and remove .transaction from receipt calls
pytests still pass
> fix: properly calling receipt transaction objects in tests

- src/ape/managers/networks.py
- src/ape_geth/providers.py
- tests/functional/test_config.py
- tests/functional/test_contract_container.py
- tests/functional/test_networks.py
If a provider plugin has a single bug in it currently, every core plugin that uses the `network_option` fails to load.
This is because the config loads in the plugin attempting to set the default but the default provider "does not exist" but it fails to load.
Instead of failing to return any ecosystems at all when attempting to set the default provider fails with a `NetworkError`, log the error and move on.
> fix: allow ecosystems to still load when default provider or network not found

- docs/userguides/config.md
- docs/userguides/networks.md
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/managers/config.py
- src/ape/types/__init__.py
- src/ape_ethereum/ecosystem.py
- src/ape_test/providers.py
- tests/conftest.py
- tests/functional/test_config.py
- tests/functional/test_contract_container.py
- tests/functional/test_networks.py
- tests/functional/test_provider.py
fixes: #985
Added `gas_limit` as an available parameter for `NetworkConfig` (and subsequently `NetworkAPI`)
WIP
> feat: add gas limit configuration

- src/ape/managers/chain.py
- tests/functional/test_chain.py
Ran into a concurrency failure because the address list was empty.
Make fail early to prevent such failure.
Also never let `max_thread` be < 0 just to be extra safe.
Additionally, only convert non-AddressTypes as a perf
> fix: strange error when getting logs from multiple addresses when addresses list empty

- src/ape/utils/github.py
- tests/functional/utils/test_github.py
All PRs been getting intermittent failures in CI from 429.
Change test to not need to clone repo.
Patch clone repo and verify callbacks functionally.
Intermittent test failures in CI go away.
> test: prevent actually cloning repo in tests

- tests/functional/test_geth.py
- tests/functional/test_provider.py
Running into an issue where the `receiver` is missing on receipts. I think the issue from Hardhat but there was not an assertion anywhere for receiver so I am adding one to clear the name.
In our main positive test for `get_receipt()`, verify the receiver is the expected contract's address.
> test: verify receiver on `get_receipt()` call

- src/ape/api/providers.py
- src/ape/exceptions.py
- tests/functional/test_geth.py
- tests/functional/test_provider.py
I need a reliable way to know if a transaction or a block is not found without relying on 3rd part exceptions.
* Adds custom exception `BlockNotFoundError(ProviderError)`
* Adds custom exception `TransactionNotFoundError(ProviderError)`
* Except `web3.exception.BlockNotFound` in `Web3Provider` and then raise our own.
> feat: custom exceptions for when block and transaction not found

- src/ape/utils/github.py
- tests/functional/utils/test_github.py
Seeking ways to make less GH calls because we are suddenly 429ing all over.
> fix: use `get_repo` cache in `GithubClient` when calling `get_release()`

- src/ape/cli/paramtype.py
- src/ape/cli/utils.py
- src/ape/managers/chain.py
- src/ape/managers/config.py
- src/ape/managers/project/dependency.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
- src/ape/utils/github.py
- src/ape/utils/misc.py
- src/ape/utils/os.py
- tests/conftest.py
- tests/functional/conftest.py
- tests/functional/test_cli.py
- tests/integration/cli/conftest.py
- tests/integration/cli/test_accounts.py
Was debugging an issue with compiling and I fixed it in `ape-solidity` (about to open PR). Except while fixing that bug, also fixed all of these, so this is small PR to change `exists()` usage to be `is_file()` or `is_dir()` depending on the situation.
> refactor: use `is_file()` and `is_dir()` over `exists()` whenever makes sense

- src/ape/api/providers.py
- tests/functional/test_geth.py
- tests/functional/test_provider.py
It is nice to have a more convenient way to check if provider supports tracing. This helps me in my gas reporting efforts but I think will come in handy elsewhere, so opening it up separately.
Check for `APINotImplementedError` when calling `get_call_tree()`. If it fails with that, no tracing. Any other result indicates a tracing implementation.
Launch console using various providers calling `provider.supports_tracing` and making sure it is expected.
> feat: add `supports_tracing()` calculated property to `ProviderAPI` and `Web3ProviderAPI`

- src/ape/utils/trace.py
Use minimal box type
So it'll look like this now:
```
SYMBOL Gas
╷              ╷      ╷      ╷      ╷
Method                │ Times called │ Min. │ Max. │ Mean │ Median
╶───────────────────────┼──────────────┼──────┼──────┼──────┼────────╴
callContractCMethodC3 │ 1            │ 7977 │ 7977 │ 7977 │ 7977
╵              ╵      ╵      ╵      ╵
```
> feat: use minimal box

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape_test/providers.py
- tests/functional/test_provider.py
- tests/functional/test_receipt.py
Begin adding in parameters to facilitate explicitly raising on transaction failure. We'll need transactions that fail to deliberately raise an exception for `RevertsContextManager`. That functionality is a dependency for the tracing ticket #251.
Adding `raise_on_fail: bool` parameter to the following:
- `ReceiptAPI.await_confirmations()` (default `False`)
- `ProviderAPI.get_receipt()` (default `False`)
- `ProviderAPI.send_transaction()` (default `True`)
- `AccountAPI.call()` (default `True`)
- `ImpersonatedAccount.call()` (default `True`)
- `Web3Provider.send_transaction()` (default `True`)
- `ContractTransaction.__call__()` (default `True`)
- `LocalProvider.send_transaction()` (default `True`)
Added a test against flipping this parameter when calling the contract function to ensure that …
> feat!: allow transaction raise on fail

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/contracts/base.py
- src/ape/managers/chain.py
- src/ape_test/providers.py
- tests/functional/test_chain.py
- tests/functional/test_provider.py
**I almost have a solid end-to-end on gas reporting in tests.**
However - this is one bit of logic I'd like to extract to its own PR to have it reviewed on its own...
Adds another index to the `AccountHistory` such that we can **rapidly** look up a cached `Receipt` by its `transaction_hash`. Then, attempts to do this in `chain.get_receipt()` so save an RPC call.
**NOTE**: The transactions presently in the `AccountHistory` should all be valid on exist on the chain. Because, when we restore to an older snapshot, we remove those transactions. If the provider cannot find the receipt, it will use the RPC call method instead. Any receipts send by your accounts will for sure be already cached!!! This greatly speeds up testing and will **definitely speed up the gas reporting work I am doing**.
* …
> feat: adds `chain.get_receipt()` method

- setup.py
- src/ape/api/providers.py
- src/ape_geth/provider.py
Correct issue with the `protobuf` dependency of `web3.py` which was causing issues running tests on some macOS machines 
fixes: #1068
Update `web3.py` to [v6.0.0b6](https://web3py.readthedocs.io/en/latest/releases.html#v6-0-0-beta-6-2022-09-26) and `eth-account` to [v0.7.0](https://eth-account.readthedocs.io/en/latest/release_notes.html#eth-account-v0-7-0-2022-08-17)
The only breaking change that affected us seemed to be the `isConnected()` rename, I didn't run into any other issues so far with the updated dependencies but would be best to double check or chime in if there's a known reason preventing us from upgrading `eth-account`
Attempting to launch `ape test` in a new project no longer results in `ImportError` (per #1068 reproduction steps)
> fix: update web3 dependency

- README.md
When I tried to use the command "ape run --verbosity DEBUG" as you can see in README.md file I saw:
```
$ ape run --verbosity DEBUG
Usage: ape run [OPTIONS] COMMAND [ARGS]...
Try 'ape run -h' for help.
Error: No such option: --verbosity
```
--verbosity is the option of ape method as you can see at:
```
Usage: ape [OPTIONS] COMMAND [ARGS]...
Options:
-v, --verbosity LVL  One of ERROR, WARNING, SUCCESS, INFO, or DEBUG
--version            Show the version and exit.
--config             Show configuration options (using `ape-config.yaml`)
-h, --help           Show this message and exit...
```
I replaced the command "ape run --verbosity DEBUG" by "ape --verbosity DEBUG run" in README.md.
```
$ ape --verbosity DEBUG run
Usage: ape run [OPTIONS] COMMAND [ARGS]...
Run scripts from the "scripts/" …
```
> docs: correctly command is "ape --verbosity DEBUG run"

- .gitignore
- src/ape/managers/project/manager.py
- tests/functional/conftest.py
- tests/functional/test_compilers.py
added error message in case compiler extensions are missing
fixes: #964
fixes: APE-273
If the attribute throws an error then it checks the missing extensions and shows them as the error message
building tests soon
> feat: error msg to say missing compiler

- .gitignore
- docs/userguides/testing.md
- docs/userguides/transactions.md
- src/ape/api/transactions.py
- src/ape/pytest/fixtures.py
- src/ape/pytest/plugin.py
- src/ape/pytest/runners.py
- src/ape/types/__init__.py
- src/ape/utils/__init__.py
- src/ape/utils/misc.py
- src/ape/utils/trace.py
- src/ape_ethereum/transactions.py
- tests/functional/utils/test_trace.py
- tests/integration/cli/test_test.py
fixes: #350 
* Add `--gas` flag to `ape test` command
* In function isolation fixture, build the tree on each incoming receipt
* In terminal reporting pytest hook, output the gas report
1. Make sure to use a provider like `ape-hardhat` or `ape-foundry` that supports tracing.
2. Go to your project with tests
3. Run `ape test --gas` or however you run your tests, just include `--gas`.
> feat: add `--gas` flag to `ape test` command to output gas reports after tests

- src/ape/pytest/runners.py
- tests/integration/cli/test_test.py
Addressing feedback from @fubuloubu regarding the error log during no tracing support. Now, this is what it looks like:
* Check `supports_tracing()`.
* Use terminalwriter markup.
* Run tests with `--gas` and not using provider with tracing support (such as the native test provider)
* Run tests that use no contracts and use `--gas`, You will get the original warning as before where there was no gas usage found. This time though it will be yellow.
> fix: Improve error log when no tracing support during gas profile display in tests

- src/ape_ethereum/ecosystem.py
- src/ape_geth/provider.py
- tests/functional/conftest.py
- tests/functional/test_chain.py
- tests/functional/test_compilers.py
- tests/functional/test_config.py
- tests/functional/test_geth.py
- tests/functional/test_networks.py
- tests/integration/cli/test_cache.py
- tests/integration/cli/test_networks.py
Ropsten, Kovan, and Rinkeby are all done. This PR removes their existence.
Hello Goerli, my new best friend!
Also changes the required confs in mainnet to be `2` instead of `13`, because of PoS.
Also no longer added PoA middleware to Goerli since it is now PoS
A big flamethrower and I burnt it all.
What could be salvaged was handed to Goerli.
It doesn't seem like this breaks any of the plugins, which is what I was curious about.
> fix: remove `ropsten`, `kovan`, and `rinkeby`.

- docs/userguides/config.md
- docs/userguides/networks.md
- src/ape/api/providers.py
- src/ape_ethereum/ecosystem.py
- tests/functional/test_accounts.py
- tests/functional/test_config.py
- tests/functional/test_contract_instance.py
- tests/functional/test_networks.py
Updated local config to use max gas limit
Also updated documentation to reflect the two defaults
Set `EthereumConfig.local` to `gas_limit="max"`
Shown in tests that the local config uses "max" by default
> feat: set local networks to max gas_limit

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/managers/converters.py
- src/ape_ethereum/ecosystem.py
- tests/functional/test_contract_instance.py
- tests/functional/test_receipt.py
exclude from CHANGELOG, as is unreleased fix
regression from https://github.com/ApeWorX/ape/pull/1097 where we estimate gas too early in txn life cycle.
Pass along `max` or `auto` values when set until they reach `prepare_transaction()` so less chance of missing appropriate base fee.
> fix: regression

- src/ape/managers/compilers.py
Using this PR to open up a discussion on creating a clearer compiler message.
Slightly edited the compiler message to be clearer about what is causing the contract type clash. I was having an issue where ape compile would fail if there was a JSON file that had the same name as a contract and I was confused until @fubuloubu pointed out that JSON files (ABIs) are treated as contract types. 
fixes: #
Edited the compiler error message
> fix: use sourceId rather than contractType name for error message

- docs/userguides/developing_plugins.md
> docs: fix typos from the developing-plugins guide

- docs/userguides/testing.md
- src/ape/api/transactions.py
- src/ape/managers/chain.py
- src/ape/pytest/config.py
- src/ape/pytest/fixtures.py
- src/ape/pytest/plugin.py
- src/ape/pytest/runners.py
- src/ape/types/__init__.py
- src/ape/utils/trace.py
- src/ape_test/__init__.py
- tests/integration/cli/conftest.py
- tests/integration/cli/test_test.py
fixes: #1092 - Note uses glob instead of regex though, is that okay?
Additionally fixes bug where if two receipts had same transaction hash, the second one would not show in the gas report.
* Add config wrapper to handle both CLI args and `ape-config.yaml` as one and pass that as a dependency in the `pytest-plugin` code.
* Change `receipt_map` in `ReceiptCapture` to first use a key of the source ID so can trace transactions with same hash from different sources.
https://github.com/fubuloubu/ERC4626/pull/18
> feat: configure gas report, including skip files

- src/ape/api/accounts.py
- src/ape/api/address.py
- src/ape/contracts/base.py
- src/ape_test/provider.py
- tests/conftest.py
- tests/functional/test_accounts.py
- tests/functional/test_contract_instance.py
- tests/functional/test_networks.py
- tests/functional/utils/test_github.py
- tests/integration/cli/conftest.py
The implementation for `__dir__` in both `AccountAPI` and `ContractInstance` API was wrong.
It called `__dir__` on the an uninstantiated super-class type, which yields different results than `__dir__` on a class instance.
Thus, the results for auto-tab completion in `ape console` contained many unusual and unnecessary methods from Pydantic, differing from the intent of the `AddressAPI` implementation which returned a much more controlled list.
This PR:
* Use the controlled list in `AddressAPI` to achieve the original intent
* Removes contract-only related methods from the `AccountAPI.__dir__()` implementation
* Ensures quality constrained tab-completions via new tests.
* Uses programmatic approach to retrieving method and property names when possible.  **NOTE: Currently there is an …
> fix: issue with `AddressAPI.__dir__()` implementation and its base-classes

- setup.py
- src/ape/api/providers.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/provider.py
- tests/functional/test_geth.py
Issue preventing the use of local geth (like `geth --dev`) from working with traces.
Parity traces have been tested to death but regular geth hadn't.
This makes it so you can run tests using `etheruem:local:geth` and get tracing support.
**We have tracing support within core ape. We have really had it this whole time! Let's use it more.**
> fix: issue preventing use of geth with non parity traces

- src/ape/utils/trace.py
- src/ape_geth/provider.py
- tests/functional/test_geth.py
OK, so I figured out why memory was missing on all my geth trace subcalls. It needs to be enabled.
This PR does that!
Enabled memory using RPC params
* Take care to have `geth` installed
* Launch your favorite project to test gas reporting in (e.g. https://github.com/fubuloubu/ERC4626)
* Run `ape test --network :local:geth --gas --show-capture=no`
* Notice the magic!
Try again without this PR and you will see why it is needed. None of the subcalls are recognized otherwise.
> fix: include memory when using geth to get geth-style traces

- src/ape/utils/trace.py
Squeezing this change in before release.
Simplify manager-based access in call trace by removing receipt as intermediary object.
> refactor: simplify manager calls in tracer

- src/ape/managers/chain.py
Getting a contract type for a proxy pointing to a non-verified contract as target fails and there is no way to specify the default contract type for the target. 
I changed the call to `get(proxy_info.target)` so that it passes the default argument that was specified when calling `get` for the proxy contract. Resulting in `get(proxy_info.target, default)`
the code now passes the optional argument
> fix: pass default contract type to proxy target

- .github/workflows/test.yaml
- pyproject.toml
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape_geth/__init__.py
- src/ape_geth/provider.py
- tests/conftest.py
- tests/functional/test_chain.py
- tests/functional/test_contract_instance.py
- tests/functional/test_geth.py
- tests/functional/test_provider.py
- tests/integration/cli/projects/geth/ape-config.yaml
- tests/integration/cli/projects/geth/tests/conftest.py
- tests/integration/cli/projects/geth/tests/test_using_local_geth.py
- tests/integration/cli/projects/test/ape-config.yaml
- tests/integration/cli/projects/test/tests/test_fixture_isolation.py
- tests/integration/cli/projects/with-contracts/ape-config.yaml
- tests/integration/cli/projects/with-contracts/tests/test_contract.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_console.py
- tests/integration/cli/test_networks.py
- tests/integration/cli/test_project.py
- tests/integration/cli/test_run.py
- tests/integration/cli/test_test.py
- tests/integration/cli/utils.py
* Updates `test.yaml` to install `geth`
* Replaces most mocks in `tests/functional/test_geth.py` with using the real thing.
* Replaces our `ape_tester` with `pytester` in the `ape_test` integration tests and adds tests to the `geth` project
* Copies some tracing tests we had in `ape-hardhat` to here.
> test: run `geth` in tests

- .github/workflows/test.yaml
- src/ape_geth/provider.py
- tests/functional/test_geth.py
Implement `snapshot()` and `revert()` APIs from `TestProviderAPI` that the local Geth provider now subscribes too.
fixes: #
RPC `debug_setHead` to revert to an old block number.
And for the snapshot, use the latest block number.
Not perfect but it works in most use-cases.
> feat: local geth provider `snapshot()` and `revert()` implementations

- src/ape/contracts/base.py
- tests/functional/test_contract_instance.py
Added a function, `method_call(method_name: str, *args, **kwargs)`, to the `ContractInstance` class. This makes it possible to directly call a method of the contract using `<contract_name>.method_call('<method_name>', *args, **kwargs)`.
fixes: #627 
Instead of relying on `__getattr__` to place the unknown attributes, the `method_call` function uses the `method_name` input to look up the `ContractCallHandler` object associated with that method name. It then executes the smart contract function by executing `ContractCallHandler` with `*args` & `**kwargs`. It then returns the output of the smart contract call.
This is easily verifiable by calling any smart contract function using `<contract_name>.method_call('method_name', *args, *kwargs)`. For examples you can look at lines 26-35 of …
> feat: ability to interact with contracts by method string name

- src/ape/managers/chain.py
- tests/functional/test_chain.py
When users use hardcoded addresses, there is the risk that they are not checksummed and they get cached with non-checksum keys. This PR makes it so it will always use the checksum version of the address in the contract  cache.
First check if connected and use the connected ecosystem.
Else, assume Ethereum-style checksums (with a warning).
Either way, fix the key before using it.
See test!
> fix: issue where contract cache allowed non-checksum addresses

- src/ape_ethereum/transactions.py
Noticed a missing type hint here and wanted to make sure it was accounted for
> fix: add BaseTransacrtion.txn_hash type hint

- .pre-commit-config.yaml
- setup.py
Use new `types-setuptools` package and remove unneeded type ignore.
> chore: use setuptools types

- setup.py
- src/ape/utils/github.py
- tests/functional/utils/test_github.py
Curently, we use `pygit2` when dependencies are specified via branch names instead of release versions because the GitHub release API does not support branches as arguments for obtaining releases; only release version IDs.
There are several reasons to not use `pygit2` as a core dependency for ape though:
* Installation issues on some operating systems
* It is not used in branch; just in a single use-case.
And more that I won't get into right now.
Replace usage of `pygit2` with `subprocess.run()` calls. Now, the expectation of certain git environments are not enforced. Users can avoid branch-based dependencies (as they should anyway) when they don't have the ability to use `git`, and it does not affect the core ape installation.
Use github dependencies that are branch based:
``` …
```
> refactor: replace pygit2 with subprocess calls to `git`

- src/ape/contracts/base.py
- tests/functional/test_contract_event.py
Noticed error message contained wrong method name. Fixed it and adjusted test.
> fix: correct method name shown in error multi-event error message

- docs/userguides/testing.md
Adding in documentation for `ape.reverts()` as well as the new `dev_message` feature (and its current caveats)
> test: add reverts test documentation

- tests/functional/conftest.py
- tests/functional/test_revert_context_manager.py
The revert context manager test are causing issues for me locally.
I figured out we can use the geth provider and don't need to patch `ProviderAPI`.
> test: replace reverts mocks with geth provider

- src/ape/api/providers.py
- tests/functional/test_contract_instance.py
fixes: #1145
this might be a bit of naive approach, a more thorough solution might lay in understanding why `web3.provider.make_request` does not properly handle `block_identifier` as an int (it should convert to hex for the final raw rpc call).
see #1145 for a example call to run
> fix: convert `block_identifier` to hex

- src/ape/managers/compilers.py
- src/ape_pm/compiler.py
- tests/integration/cli/test_compile.py
Currently, when you have a contract type collision, it looks like this:
```
ERROR: (CompilerError) ContractType collision across compiler plugins with contract: abi/v0.6/Ownable.json
```
but now with these changes, it looks like this:
```
ERROR: (CompilerError) ContractType collision between sources 'abi/v0.6/ENSInterface.json' and 'abi/v0.7/ENSInterface.json'.
```
> feat: improve error when contract type collision

- docs/methoddocs/managers.md
- src/ape/api/projects.py
- src/ape/managers/compilers.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
- src/ape/utils/os.py
- src/ape_compile/_cli.py
- tests/integration/cli/test_compile.py
While poking around https://github.com/smartcontractkit/chainlink-brownie-contracts/tree/main/contracts/abi/%40openzeppelin/ and comparing ape and brownie, I noticed ape was failing to compile certain `.sol` "files"... Turns out, they are actually directories, such as this gem: https://github.com/smartcontractkit/chainlink-brownie-contracts/tree/main/contracts/abi/%40openzeppelin/contracts/proxy/Proxy.sol
I located the bug in core ape and fixed it (this PR).
Check for `is_file()` as well.
> fix: issue where directories with compiler extension in name would cause issues

- src/ape/plugins/__init__.py
- tests/functional/test_plugins.py
Okay, fixes this once and for all and learned more about why it happens.
Cross check with `pip list --format freeze`, which is the official workaround it seems. Note that `pip freeze` doesn't even work with editable installs anymore!
> fix: another issue where editable plugins would not install correctly

- src/ape/api/projects.py
- src/ape/managers/chain.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
- tests/functional/test_dependencies.py
- tests/integration/cli/test_compile.py
fixes: #799 
Goes with https://github.com/ApeWorX/ape-solidity/pull/84
Dependency's no longer need to compile. Instead, we create a contract-type-less `PackageManifest` that contains the sources to be imported in a project. This makes compiling works a lot better and certain dependencies don't compile if they don't ever need to.
Use dependencies.
> feat: don't compile dependencies

- src/ape/utils/github.py
- tests/functional/utils/test_github.py
This works in CI better than SSH.
> fix: change to http default in github clone for dependencies

- docs/userguides/testing.md
- src/ape/pytest/contextmanagers.py
- tests/functional/test_revert_context_manager.py
- Added regex support in `ape.reverts()`
- Cleared up `RevertsContextManager` tests and test docstrings
fixes: #873 
fixes: APE-311
Allow `expected_message` and `dev_message` in `RevertsContextManager` to accept `re.Pattern` objects
```python
with ape.reverts(re.compile(r"^dev: (foo|bar)$")):
...
with ape.reverts(dev_message=re.compile(r"^dev: (foo|bar)$")):
...
```
> feat: support regex in ape.reverts()

- src/ape/api/projects.py
- src/ape/managers/project/types.py
- tests/functional/test_dependencies.py
- tests/integration/cli/test_compile.py
When working on the brownie-style deps ticket, I forgot to include this part!
So dependencies no longer compile by default. However, when you request them, they will compile.
They compile only once! Once they are part of their cached manifest, they don't need to compile again. Both in session and out.
idk see code, just some refactoring and stuff
First time:
```sh
(yoko) ➜  ape-demo-project git:(main) ✗ ape console
In [1]: dep = project.dependencies["ds-test"]["master"]
In [2]: dep.DSTest
INFO: Compiling 'test.sol'.
Out[2]: <DSTest>
In [3]: dep.DSTest
Out[3]: <DSTest>
```
Notice it only compiled the first time we request it.
Second time:
```
In [1]: dep = project.dependencies["ds-test"]["master"]
In [2]: dep.DSTest
Out[2]: <DSTest>
```
Notice it does not need to compile at all because it …
> fix: issue where dependency contract type would not compile

- tests/integration/cli/test_accounts.py
added testing for seed phrase length output
fixes: APE-346
parsing seed phrase from runner output message
```
word_count = 24
...
mnemonic_length = len(result.output.split(":")[4].split("\n")[0].split())
assert mnemonic_length == word_count
```
tests are passing
> test: added testing for `accounts generate` seed phrase length

- docs/userguides/accounts.md
- src/ape_accounts/_cli.py
- tests/integration/cli/test_accounts.py
created a click command in ape accounts cli to export private keys from keyfiles
fixes: APE-345
fixes: APE-328
created a click account that loads the alias keyfile and then decrypts the private key with a password prompt
tests coming soon
> feat: `ape accounts export <ALIAS>` exports private key

- src/ape/api/providers.py
- src/ape_test/provider.py
Some providers don't support "auto", so just avoid getting gas estimation for those types by removing the argument
fixes: #1176
> fix: gas_limit of "auto" causes failure with unsupported providers

- docs/userguides/accounts.md
- src/ape/api/address.py
Allow setting an account's balance directly
Tried to add a setter to the `balance` property, but that didn't work, so I had to override Pydantic behavior a bit
Load an `Address`, any `AccountAPI` subclass, and then any `ContractInstance` and try `account.balance += "1 ether"`
Needs some tests
> feat: allow setting balance if current provider supports it

- .pre-commit-config.yaml
- setup.py
- src/ape/api/projects.py
- src/ape/managers/project/dependency.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
- tests/functional/test_project.py
- tests/integration/cli/test_compile.py
Regression from https://github.com/ApeWorX/ape/pull/1152
We changed dependencies so that they would not compile at download time.
We did this to better support dependencies that are not meant to be compile-able entirely on their own, such as `chainlink-brownie-contracts`. So now dependencies only get compiled if they are needed to be. And once compiled, their artifacts remain in the cached manifest file in `.ape/packages/`. This explains why some people didn't have this problem locally - their dependencies were already fully contract-type-ified.
So the fix here:  realizing the huge flaw in our change - config files... When we cache a project's sources, we need to also know its configuration if we plan to compile it at a later time, especially if that config tells you to how to do mappings …
> fix: issues with dependencies of dependencies

- src/ape_ethereum/ecosystem.py
Prior to v1.1.0, `masterCopy` was not available as an external method. This means that our proxy detection would not be able to detect it as a Gnosis Safe-style proxy. Additionally, once deployed, this style of proxy is immutable, so even if the Safe itself is upgraded to a newer version, this method still would not be available to be called.
NOTE: This slightly modifies the proxy info's target to be obtained
dynamically from retreiving the storage for `masterCopy` directly.
Since `masterCopy()` is not an available method to call, but `NAME()` has always existed in every Gnosis Safe version, I decided to use that instead. I noticed that there are few different names in use, so we check that it matches one of those
Go load a safe via `Contract` for every version that's been deployed
> fix: allow Gnosis Safe style proxies to work with earlier deployments

- src/ape/api/projects.py
- src/ape/managers/project/manager.py
Fixes regression from #1183 where accidentally compiled dependencies before their time when extracting the compiler data needed to compile it later.
Made it so you don't have to compile dependencies to get compiler data.
* Tests work again in `ape-solidity` (brownie-style dependencies work again)
* Can still compile the yearn repos related to what #1183 fixed
> fix: issue where compiled dependencies before their time

- src/ape/managers/project/manager.py
Another failed test in `ape-solidity` caught this issue where the path was being mistakenly reset, causing issues with calculated contracts folder
> fix: use cached path

- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- src/ape/api/transactions.py
- src/ape/managers/chain.py
- src/ape/pytest/runners.py
- tests/functional/conftest.py
- tests/functional/test_chain.py
Fixes an issue where a re-org was never detected.
Additionally, when a chain reorganization occurs, `poll_blocks()` yields the missed blocks even if they were previously yielded with different block numbers.
There are also spelling fixes and other small fixes in the `chain.py` module.
Noticed reorg detection wasn't working.
Realized `chain.py` had several warnings (thanks Pycharm)
Fixed everything and added a test.
Poll blocks on mainnet; you should get a sequential amount of blocks (nothing changed).
Poll blocks with unreasonable small required confs to test reorg works.
> fix: issue where `poll_blocks()` did not detect chain re-org

- src/ape/api/accounts.py
Noticed a weird bug where if you have accounts and ecosystems in the same plugin and the plugin fails verification, you get an account `AttributeError` about the ecosystem. A simple fix to except `AttributeError`. This helps the core tests pass before Starknet is updated in the case where the Starknet plugin is installed locally.
fixes: #
Except `AttributeError` in account checker.
`tests/functional/test_accounts.py::test_accounts_contains` PASSs when the Starknet plugin fails plugin verification and is installed locally.
> fix: except `AttributeError` when checking for account

- .pre-commit-config.yaml
- pyproject.toml
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/managers/project/manager.py
- src/ape/types/__init__.py
- src/ape/types/signatures.py
- src/ape_accounts/accounts.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/provider.py
- src/ape_test/accounts.py
- tests/functional/utils/test_misc.py
Figured out how to remove a gazillion type ignores!
This fixes an issue where typing concerns of Signature objects were ignored.
Followed advice from https://github.com/python/mypy/issues/6239
by utilizing the Pydantic plugin that ships with Pydantic.
> fix: issue from type-ignoring `TransactionSignature`

- src/ape/exceptions.py
fixes: [Ape-369](https://linear.app/apeworx/issue/APE-369/make-outofgaserror-a-virtualmachineerror) 
fixes: APE-369
change the base class of outofgas to virtualmachineError
> feat!: Make OutOfGasError a VirtualMachineError

- src/ape/types/signatures.py
- tests/functional/test_types.py
Adds missing 0x prefix to `TransactionSignature` repr.
Am debugging something and this was a red herring.
Use `to_hex` from `eth_utils` to handle multiple byte suptypes.
Set a breakpoint and analyze the signature on a signed txn.
> fix: add missing 0x prefix to Signature representation

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/contracts/base.py
- src/ape_accounts/accounts.py
- src/ape_test/accounts.py
- tests/functional/test_transaction.py
BREAKING CHANGE: This is done to ensure account plugins have the ability to modify the transaction they are signing, i.e. for Gnosis Safe plugin.
fixes: APE-388
When working on `ape-safe`, it became apparent that there needs to be a way for an account plugin that wraps some more complex processes with other accounts to be able to mutate the transaction to a different type.
This is also handy if the account plugin wants to make adjustments to things like gas, etc. of the transaction it is giving over to the signing process.
All tests pass, check with other account plugins (Trezor, Ledger)
> refactor!: modify `AccountAPI.sign_transaction` to return `TransactionAPI`

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/exceptions.py
- src/ape_ethereum/transactions.py
- src/ape_test/provider.py
Align `TransactionError` with other Exceptions to take message as the first position argument. This will allow for passing message w/o the keyword. This PR is a first pass before further updating `TransactionError` with logic for trace backs.
Reorganized exception arg ordering and removed message keyword from calls.
> feat!: update `TransactionError` arg order

- src/ape_ethereum/ecosystem.py
While working on trace back exception handling, found that chain errors weren't being caught during the proxy info method. These chain errors were interrupting the flow of caching contracts that weren't proxy or didn't have proxy info.
fixes: APE-460
Generalized the exceptions caught so that it would also include ChainErrors.
> feat: update proxy info errors

- docs/userguides/config.md
Update docs. Current setup throws:
```sh
pydantic.error_wrappers.ValidationError: 1 validation error for EthereumConfig
gas_limit
extra fields not permitted (type=value_error.extra)
```
> docs: fix `gas_limit` example in config guide

- docs/userguides/accounts.md
- src/ape/contracts/base.py
- src/ape/managers/accounts.py
- tests/functional/test_default_sender_context_manager.py
Added the support for default_sender in contract transactions
fixes: #
Implemented a new context manager to use in tests.
Run the tests.
> feat: add default sender manager

- src/ape/api/address.py
- tests/conftest.py
- tests/functional/test_accounts.py
- tests/functional/test_contract_instance.py
- tests/functional/test_geth.py
Noticed from a mistake in someone's code that we are not properly handling the case when `get_code()` returns a `str`, as it says it might. In some ecosystems, it might, I suppose.
Wrap the code in `HexBytes` before checking the length.
** Else `len("0x")` will be truthy **
> fix: issue with str type in `is_contract()`

- docs/userguides/transactions.md
- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape_ethereum/transactions.py
- tests/functional/test_contract_event.py
- tests/functional/test_receipt.py
Since we know the number of logs should be small enough on receipts, if we decoding logs for a specific receipt, uses lists instead of iterators.
This simplifies tests for everyone.
> refactor!: use lists for logs on receipt instead of iterator

- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape/managers/converters.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- src/ape_test/provider.py
- tests/functional/conversion/test_timestamp.py
- tests/functional/test_contract_instance.py
- tests/functional/test_receipt.py
I noticed while debugging https://github.com/ApeWorX/ape-optimism/issues/12 that the issue was because of static fee transactions. I was able to reproduce with Ethereum as well.
* Remove `Union` type from `TransactionAPI` and require the transaction type to be an `int`.
* Make a `HexIntConverter` class
* Fix weird chain ID issues on receipt's transactions that I found during txn-replay for extracting revert messages.
* `contract.method(arg, sender=me, type=0)`
* Also make sure works in reverts testing
> fix: issues with static fee transactions

- src/ape/api/providers.py
- src/ape/exceptions.py
- src/ape_test/provider.py
Prepping for tracing errors in `TransactionErrors` based classes. Also, standardizing the call signature for `get_virtual_machine_error` error handling. Moving web3 logic to `Web3Provider` and made `ProviderAPI` return a simple `VirtualMachineError` that can be overridden in other ecosystems.
fixes: #
> refactor: TransactionErrors and standardize transaction passing

- src/ape/api/providers.py
Noticed some `address: str` in the API that seems like it should be `address: AddressType`, even when working on Starknet.
> fix!: change some `str` items to `AddressType` where it makes sense

- src/ape/api/projects.py
- src/ape/managers/config.py
- src/ape/managers/project/dependency.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
A strange issue that preventing `cairo` dependencies from working.
Also, it explains some of the weird things seen in tests regarding projects.
Basically, the contracts folder in the config was not honored for dependencies.
fixes: APE-562
> fix: issue where `contracts_folder` was not honored in dependency

- src/ape/api/transactions.py
- src/ape/managers/chain.py
Noticed these args weren't used anymore but never got deleted.
Note, this is not a breaking change because this is not a public API (it is internal to the framework)
> chore: remove unused arguments on non-public API

- src/ape_run/_cli.py
- tests/integration/cli/projects/script/scripts/error_forgot_click.py
- tests/integration/cli/test_run.py
Had a script with missing click decorator; it causes Ape to crash in an unusual way without letting me run any scripts.
Make sure that `cli` is a click command before moving forward. Else, return `None`.
Have a "script" like this:
```python
def cli():
print("I am not real")
```
and try to run it. You should get a warning and it shouldn't be able to run.
> fix: issue where missing click decorator in CLI scripts caused all scripts to fail

- src/ape_run/_cli.py
- tests/integration/cli/projects/script/scripts/error.py
- tests/integration/cli/projects/script/scripts/error_cli.py
- tests/integration/cli/test_run.py
Adds locals to the namespace when using `-I` and error occurs
fixes: #1280
`globals()`
> fix: include active namespace in interactive script console

- src/ape/api/projects.py
- src/ape/managers/project/types.py
Creating multiple abi files for compile
fixes: APE-479
Changed ape.managers.project.types.create_manifest to have seperate files.
Just run compile command and /abis folder should have compiled contracts as seperate.
> feat: create abi files per contract

- src/ape/managers/compilers.py
- src/ape/pytest/fixtures.py
- tests/functional/test_compilers.py
Noticed that it is not the easiest to get a hold of one of the compiler API implementation classes, like `ape-solidity`.
Perhaps there are use-cases (like weird Solidity stuff) where one may need the Solidity compiler at their fingertips.
Before, you had to do this:
```python
project.compiler_manager.registered_compilers[".sol"]
```
but now you can do this:
```python
compilers.solidity
```
* Adds method `get_compiler()` to `CompilerManager` that allows getting a compiler by name
* Adds `__getattr__` so you can do the ape-fancy dances that uses `get_compiler()`
* Adds `compilers` pytest fixture to our pytest integration.
Use solidity in a fixture or in a test. Call the methods.
> feat: way to get compilers easier [APE-607]

- src/ape/utils/__init__.py
- src/ape/utils/testing.py
- src/ape_test/__init__.py
- src/ape_test/accounts.py
- tests/functional/test_accounts.py
Refactored generate_dev_account to allow any hd path and mnemonic to be used from config
fixes: #
> feat: Allow any mnemonic to be used with generate_dev_accounts [APE-625]

- src/ape/api/projects.py
- src/ape/managers/compilers.py
- src/ape/managers/project/manager.py
- tests/functional/test_project.py
* Adds `sources` property to `ProjectManager` so I can get source content by source ID easier.
* Improves `lookup_path` math to handle source ID arg types
* Fixes more issues related to directories with matching source file extensions getting sucked into places they shouldn't
e.g.:
```python
source = project.sources[ct.source_id]
line = source[line_index]
src_path = project.lookup_path(ct.source_id)
```
* use internal project api `classmethod` for building source dict. NOTE: No compilation is necessary!
* wrap arg in `Path()` so it always works.
> feat: sources and source path lookup improvements [APE-628]

- src/ape_run/_cli.py
- tests/integration/cli/projects/only-script-subdirs/scripts/subdirectory/subdirectory_click_print.py
- tests/integration/cli/projects/only-script-subdirs/scripts/subdirectory/subdirectory_main_print.py
- tests/integration/cli/test_run.py
changed the suffix to be able to detect `.` from subdirectories to fix bug where subdirectory scripts would not run unless there was a click script in the `/scripts/` folder. 
fixes: #1302
fixes: APE-630
detects `.` in the suffix in order to see if it is in the main scripts folder or is in a subdirectory, then returns the suffix accordingly
tests run, can also try in a project with scripts only in subdirectories (this is working for me)
> fix: scripts not running unless click script in scripts folder [APE-634]

- src/ape/api/projects.py
I'd like to be able to call this when working with Vyper dependency interface imports.
> refactor: make dependency compile method public [APE-641]

- src/ape/api/providers.py
- src/ape/types/trace.py
Similar to `CallTreeNode`, allow the raw trace data to be accessible from the frame. This permits plugins to make ecosystem-specific assumptions about the data if they choose to.
> feat: include raw trace-frame data in `TraceFrame` class. [APE-646]

- setup.py
- src/ape/managers/chain.py
- src/ape/types/trace.py
Simplifies `merge_reports` usage because it now handles the case when it is given 0 reports.
Mostly delete code.
Everything still works.
I already tested with `ape-hardhat` and `ape-foundry`.
> refactor: utilize new evm trace [APE-649]

- src/ape/api/projects.py
- src/ape/managers/project/manager.py
- tests/integration/cli/test_compile.py
Follow up to https://github.com/ApeWorX/ape/pull/1298
Right now, if you migrate from 0.6.2 to the soon-to-be 0.6.3, you will get issues where Ape cannot find your contracts because of some recent in-memory caching advancements. This PR does 2 things:
1. Allows migration to 0.6.3 by searching for the missing contract and recompiling it
2. Handles the case where if you manually delete a file JSON from your .build cache, it will re-compile it and give it back to you.
* Install ape 0.6.2 and compile a project
* Switch to ape env with this branch installed
* Try to run a script or tests that uses one of the compiled scripts
* Before, it would fail saying the contract was not found, which may be confusing. Now, it will seemlessly work like nothing every happened (migration).
Additionally, if …
> fix: handle missing contract type JSONs [APE-650]

- src/ape/utils/misc.py
- tests/functional/utils/test_misc.py
Needing to parallelize something potentially and wanted to use this method. However, it only supports 1 coroutine at a time, which isn't super helpful for parallelization. 
Also, `ape-starknet` already had to implement this, so delete it from there and use this on next release.
> feat: `run_until_complete()` support multiple coroutines [APE-653]

- src/ape/logging.py
- src/ape/pytest/plugin.py
When something went wrong while loading `conftest.py` in an Ape project, the exception was very bare and I was not able to use `-v debug`. For example, I had a `KeyError` and it looked like this:
```
ERROR: Unable to load project. Reason: 'args'
```
and so this PR does 2 things:
1. Includes Exception type in default message (while also alluding to the use of `-v debug`)
```
ERROR: Unable to load project. Use `-v DEBUG` to see more info.
Failure reason: (KeyError) 'args'
```
2. Allows `-v debug` to reveal full stack-trace:
```
...
... (more stuff but omitting here) ...
...
...
File "My/Home/PycharmProjects/ape-vyper/ape_vyper/compiler.py", line 267, in compile
while end_args["args"]:
KeyError: 'args'
ERROR: Unable to load project. Failure reason: (KeyError) 'args'
```
> feat: support debugging from `conftest.py` load failure [APE-668]

- recommended-plugins.txt
Because these aren't necessarily something every user would have we can remove them from the recommended-plugins install to make that process a bit simpler/faster
> fix: remove trezor/ledger from reccomended plugins [APE-681]

- docs/conf.py
- setup.py
It would be really helpful for us to monitor growth by seeing our analytics from the docs page
fixes: APE-453
I chose Plausible because they are privacy-preserving and open source
Once docs are released (on main) should be able to see the page
> docs: add anonymized analytics

- src/ape/managers/chain.py
- tests/functional/test_chain.py
Allow things to not fail when not connected. Prevents me from having to connect to a provider for no reason while testing something. Otherwise would get `ProviderNotConnectedError`.
> fix: skip deployments when not connected [APE-680]

- Dockerfile
1. remove apt-get commands as they were no longer needed and a security issue
2. use a docker python build image to build the wheel files
3. copy the wheel files to a new docker image using -slim
4. install the wheel files
fixes: #
reducing docker build size because it is big and annoying
`docker build . && docker images`
> feat: reduced docker build size to 448MB from 1.7GB [APE-702]

- docs/userguides/console.md
- src/ape/api/networks.py
- src/ape/contracts/base.py
- src/ape/pytest/runners.py
- src/ape_console/__init__.py
- src/ape_console/_cli.py
- src/ape_console/config.py
- src/ape_console/plugin.py
- src/ape_run/_cli.py
- tests/conftest.py
- tests/functional/conftest.py
- tests/integration/cli/test_console.py
Am looking for more IPython integration opportunities with tracebacks.
Ended up here. But look, this is kinda of neat and sets us up to integrate more with IPython, which ultimately is what we need...
* Creates an `%ape` magic for `ape-console` that allows running CLI commands within the `ape console` session:
```shell
ape console --network ethereum:mainnet:alchemy
In [1]: %ape accounts list
Found 1 account:
0x1e59ce931B4CFea3fe4B875411e280e173cB7A9C (alias: 'test0')
Out[1]: <Result okay>
```
A `%bal` magic that gets a balance in human-readable form:
```shell
In [2]: account = accounts.load("metamask0")
In [3]: %bal account
Out[3]: '0.00040634 ETH'
```
* `start_ipython` for CLI command but use `embed` everywhere else (`ape test -I` and `ape run -I`)
* Register as an official IPython …
> feat: two new `ape console` Magics [APE-726]

- src/ape/api/transactions.py
- src/ape/pytest/contextmanagers.py
- tests/functional/test_contract_instance.py
- tests/functional/test_receipt.py
Adds `.receipt` property to `TransactionAPI` which simplifies usage when we need to check trace stuff from exceptions.
simplifies things for showing traceback lines too.
> feat: convenience property for getting receipt from a transaction [APE-744]

- src/ape_geth/provider.py
Same thing as https://github.com/ApeWorX/ape/pull/1172 but for `ape-geth`
Realized `ape test` output when using `geth` provider is extremely ridden when subprocess logs and i was like "i thought i got rid of these!!!!" but then realized `ape-geth` uses `py-geth` package and not `SubprocessProvider`, then realized how to fix.
overrode the `start()` method to use `DEVNULL` when not `DEBUG`
> fix: send geth process output to devnull when log level above DEBUG [APE-753]

- src/ape/_cli.py
- src/ape/cli/__init__.py
- src/ape/cli/utils.py
- src/ape/exceptions.py
- src/ape/pytest/runners.py
- src/ape_console/plugin.py
- src/ape_run/_cli.py
- tests/integration/cli/projects/with-contracts/scripts/txerr.py
- tests/integration/cli/projects/with-contracts/tests/test_contract.py
- tests/integration/cli/test_console.py
- tests/integration/cli/test_run.py
- tests/integration/cli/test_test.py
fixes: #442 
Fixes: APE-157
* Removes noisy framework traceback frames in `ape console` during `TransactionError` handling
* Removes noisy framework traceback frames in `ape run` during `TransactionError` handling
* Remove noisy framework traceback frames in `ape test` during `TransactionError` handling.
This makes the PR #1337 a lot simpler to follow and smaller.
There is also a lot of benefit to this alone so wanted to include it incase #1337 does not make it in the next release.
* filter out frames that didn't occur in the local Ape project during the handling of `TransactionError` in CLI, pytest plugin, and IPython plugin.
Cause unhandled TransactionError (e.g. ContractLogicError) in all 3 environments.
> feat: filter out irrelevant traceback frames [APE-758]

- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/types/__init__.py
- tests/functional/test_chain.py
- tests/functional/test_contract_event.py
- tests/functional/test_receipt.py
Add some linked data to `ReceiptAPI` and extra processing on `BlockAPI.timestamp` to get a datetime obj
fixes: #1257
Uses `ChainManager.blocks` to fetch the blocks in order to take advantage of the query manager
Call the methods directly and via `AccountHistoryContainer.query`/`BlockContainer.query` to verify if any issues are introduced
> feat: add datetime block [APE-734]

- src/ape/pytest/runners.py
- tests/integration/cli/conftest.py
- tests/integration/cli/test_test.py
- tests/integration/cli/utils.py
regression from #1360  causing `--showinternal` to crash pytest terminal output
correct type
can use `--showinternal` now
added a test
> fix: issue where `ape test --showinternal` would cause crash [APE-782]

- src/ape/api/transactions.py
- tests/functional/test_transaction.py
Dynamic fee overrides weren't processing via their validators, so I added that
fixes: #1369
Using Validators
Test suite passes, any normal usage of this should function
~~- [x] Documentation has been updated~~
> fix: dynamic fee conversion [APE-781]

- docs/userguides/config.md
- src/ape/exceptions.py
- src/ape/managers/project/dependency.py
- src/ape/utils/github.py
- tests/functional/utils/test_github.py
fixes: #1381 
Fixes: APE-820
* document stuff about tags
* if version not found, try as a reference
* if missing `v` prefix, try with `v` prefix.
this will work now:
```
dependencies:
- name: Uniswap
github: Uniswap/v3-core
version: 1.0.0
```
tho youll get a warning.
best to do this:
```
dependencies:
- name: Uniswap
github: Uniswap/v3-core
ref: v1.0.0
```
> feat: smarter handling of references and versions in dependency configs [APE-829]

- src/ape/managers/project/types.py
Changes character `/` to `os.path.sep`
fixes: #
On Windows manifest for dependencies is empty because `contracts_folder_config_item` equal to `\contract`. Reason for that: predefined file path delimiter instead of system delimiter. 
Compile any project with dependency on Windows
> fix: uses system path separator in BaseProject.process_config_file [APE-843]

- src/ape/api/networks.py
- tests/functional/test_ecosystem.py
noticed i couldnt configure my forked networks 
fixed it
hyphen underscore swap
```python
ethereum.mainnet_fork.gas_limit
>> max  # the default, before would say auto which is the default default when config is missing
```
> fix: issue preventing Ethereum forked network config from working [APE-844]

- docs/userguides/testing.md
- src/ape/pytest/plugin.py
- src/ape/pytest/runners.py
- tests/integration/cli/projects/geth/tests/test_using_local_geth.py
fixes: #587 
Fixes: APE-176
Was working on coverage when was trying to learn about adding custom markers.
It is rather easy to do, so I figured I'd knock this ticket out with my new found knowledge (it took like 15 minutes soooo it is worth it to close this out).
Examples:
```python
@pytest.mark.use_network("ethereum:local:test")
def test_use_test(chain):
assert chain.provider.name == "test"
@pytest.mark.use_network("ethereum:local:foundry")
def test_use_foundry(chain):
assert chain.provider.name == "foundry"
```
but you can change the ecosystem and network for more realistic scenarios
> feat: pytest `use_network` marker [APE-868]

- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/managers/chain.py
- src/ape/pytest/fixtures.py
- src/ape/pytest/gas.py
- src/ape/pytest/plugin.py
- src/ape/pytest/runners.py
- src/ape/utils/basemodel.py
- src/ape_geth/provider.py
This refactor is going to help the coverage stuff feel right I think...
Basically, the internal class `ReportManager` is great for interfacing with `rich.console` but doesn't make the most sense fore tracking session gas, so made a `GasTracker` class in `ape.pytest` and have it live there. I am going to do the same thing with a `ContractCoverage` class.
Move everything related to the tracking of session gas to a new class in `ape.pytest.gas` module from the internal for using rich console. **NOTE**: Not a breaking change because the class is internal
* everything still works
> refactor: move gas tracker logic to `pytest` module [APE-875]

- codeql-config.yml
- setup.py
- src/ape/api/compiler.py
- src/ape/api/projects.py
- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape/exceptions.py
- src/ape/managers/chain.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
- src/ape/types/__init__.py
- src/ape/types/trace.py
- src/ape_ethereum/transactions.py
- src/ape_geth/provider.py
- tests/functional/test_geth.py
- tests/integration/cli/test_compile.py
fixes: #867 
Fixes: APE-217
Fixes: APE-577
* Adds `traceback` property to `ReceiptAPI` with implementation in `ape_ethereum`
* Adds `show_source_traceback()` method to `ReceiptAPI` the same.
* Using AST, trace execution, and PCMap. Only works with Vyper at first.
Create `interfaces/IRegistryF.vy`:
```python
@external
def register_f(addr: address):
pass
```
Create `RegistryF.vy`:
```python
addr: public(address)
@external
def register_f(addr2: address):
assert self.addr != addr2, "doubling."
self.addr = addr2
```
Create `JustFail.vy`:
```python
import interfaces.IRegistryF as IRegistryF
_balance: public(uint256)
registry: public(IRegistryF)
@external
def __init__(registry: IRegistryF):
self.registry = registry
@external
def addBalance_f(
num: uint256
) -> uint256:
assert num != …
```
> feat: show source code lines / traceback from `ReceiptAPI` [APE-708]

- src/ape/pytest/config.py
- src/ape/pytest/runners.py
When using `--showinternal`, the locals in the traceback is overwhelming.
This disables it when using internal tb.
Also, even when not, it wil be truncated now to be less overwhelming when dealing with large reprs, like dicts and stuff
> fix: better handling of `showlocals` in pytest traceback [APE-936]

- setup.py
`awscli` depends on an older version of pyyaml, and I don't think we rely on any advanced behavior of this dependency, so opening up the pin seems safe
> refactor: widen PyYAML pin to >=5.0,<7.0 [APE-947]

- src/ape/contracts/base.py
- tests/functional/test_contract_instance.py
Was noticing that the printout I get in IPython wasn't really as helpful as I would like it
Before:
```py
functools.partial(withdraw(address creator, uint256 stream_id) -> uint256, <TestAccount 0xc89D42189f0450C2b2c3c61f58Ec5d628176A1E7>, 0)
```
After:
```py
functools.partial(<Stream 0x274b028b03A250cA03644E6c578D81f019eE1323>.withdraw, <TestAccount 0xc89D42189f0450C2b2c3c61f58Ec5d628176A1E7>, 0)
```
> refactor: update contract method repr to display info nicer [APE-939]

- src/ape/contracts/base.py
I added a check to see if start_block is in the past, if so it will yield from self.range called on the full range of blocks between start_block and chain head before proceeding into the new blocks iterator as currently implemented
fixes: #1436 
conceptually separated historical blocks from future blocks and built better handling for historical case
Just fetch some events
> perf: minimize unnecessary calls for poll_logs [APE-948]

- src/ape/api/compiler.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape/exceptions.py
- src/ape/managers/chain.py
- src/ape/managers/project/manager.py
- src/ape/pytest/fixtures.py
- src/ape/types/__init__.py
- src/ape/types/trace.py
- src/ape_ethereum/ecosystem.py
- src/ape_pm/compiler.py
- src/ape_test/provider.py
- tests/functional/test_compilers.py
- tests/functional/test_project.py
- tests/functional/test_receipt_capture.py
- tests/integration/cli/test_test.py
Fixes several things that came up from people trying to use the source tracing feature....
1. Add ability to check if compiler supports it (will need this in Coverage feature anyway)
2. Performance improvement by preventing the calculation of the source traceback more than once in certain situations
3. **Critical issue** causing never-ending loop (hanging) when trying to create the source traceback. For this reason, we may want to patch Core ape after this...
4. Better error when txn hash is not found
5. Issue where `contracts_folder` was `None` when it should not have been (only happened when using normal Python REPLs).
6. PC values are now present in the source traceback but also requires that `ape-vyper` PR
> fix: fixes for source tracing [APE-972]

- docs/index.md
- docs/userguides/clis.md
- docs/userguides/developing_plugins.md
- docs/userguides/scripts.md
- src/ape/cli/choices.py
- src/ape/managers/accounts.py
- src/ape_test/__init__.py
- tests/functional/test_accounts.py
- tests/functional/test_cli.py
Support using test accounts in `account_option` through special syntax `TEST::{i}`
fixes: #854
By having the `TEST::` prefix, we disambiguate from any "normal" alias (e.g. for built-in loaded accounts), allowing people to make a call to a script for testing purposes using a pre-funded test account that functions on a development or mainnet fork environment. This is safer or more simple than what people are currently doing, which is maintaining their own expansive scripts for doing what is essentially the same thing
Just added support for parsing additional choices to `AccountAliasPromptChoice`
Try making some different scripts, see if there's any UX gotchas
Example:
```sh
$ ape run scriptname --account TEST::0 --network ::test
```
> feat(cli): add support for using test accounts in `account_option()` [APE-945]

- Dockerfile
set the dockerfile homedir owner to user harambe
fixes: #1447
fixes: APE-975
add chown to dockerfile
```
$docker build -t ape .
$ docker run -it --entrypoint /bin/bash ape
harambe@8a0cb64afbeb:~/project$ cd ..
harambe@8a0cb64afbeb:~$ ls -la
total 32
drwxr-xr-x 1 harambe harambe 4096 May 26 19:11 .
drwxr-xr-x 1 root    root    4096 May 26 19:10 ..
-rw-r--r-- 1 harambe harambe  220 Mar 27  2022 .bash_logout
-rw-r--r-- 1 harambe harambe 3526 Mar 27  2022 .bashrc
-rw-r--r-- 1 harambe harambe  807 Mar 27  2022 .profile
drwxr-xr-x 1 harambe harambe 4096 May 26 19:11 project
```
> fix: set homedir owner to harambe [APE-976]

- src/ape/utils/testing.py
noticed that the docs did not match what the actual default was
> docs: fix generate_dev_account documentation for HDPath default [APE-980]

- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/exceptions.py
- src/ape_geth/provider.py
- src/ape_test/provider.py
- tests/functional/test_contract_instance.py
- tests/functional/test_geth.py
- tests/functional/test_provider.py
base error was missing on txn failed
looking at this in a debug perspective for some solidity crap
> fix: pass through base_err on empty contract logic errors [APE-985]

- src/ape_accounts/accounts.py
turn cached key warning into a `logger.warning` instead of a `click.echo`
without this I can't stop the incessant beeping with `ape_logger.set_level(logging.ERROR)`
changing `click.echo` to `logger.warning`.
also removed the unnecessary else statement because sourcery told me to.
trust me bro, the `using cached keys` warning doesn't bother me any more 👌
> fix: quiet cached keys warnings [APE-1001]

- src/ape/api/providers.py
updated src/ape/api/providers.py `web3provider getblock` to accept none type gas `baseFeePerGas`
fixes: # https://github.com/SilverBackLtd/silverback/issues/2
resolves nonetype error for basefeepergas
run a silverback test with geth provider
> fix: validation error accept none type gas baseFeePerGas [APE-1036]

- tests/conftest.py
- tests/functional/test_chain.py
- tests/functional/test_compilers.py
Adds internal test decorator for skipping core tests if the given plugins are installed.
to improve test readability. note, the decorator's impl is not that great because i wanted to keep it fast (prevent importing or looking up package).. however, it wont always work, it is just for our core tests so not that important.
if
tests pass
> test: skip if plugin installed [APE-1051]

- pyproject.toml
Related to https://github.com/ApeWorX/github-action/pull/20
Here was my problem:
* I have a workflow that install from a remote branch of Ape. That was working!
* Yesterday, I merged a feature that allows installing plugins from a remote branch. That was also working!
* But then things went wrong.... So when installing ape, it showed the version as 0.1.0 because setuptools_scm is how we calculate the version, and pip, when cloning from a remote install, does not include tags nor will it ever.... thus, the latest version of Ape 0.6.10 would replace my branch-install after installing the plugins.. :(
* So what I didddd here is add a fallback version that should get used whenever the real version is not known..
If you don't like this for some reason.... get this... this is what happens …
> fix: issue when CI wouldn't use a remote version of Ape [APE-1029]

- src/ape/utils/trace.py
- tests/integration/cli/test_test.py
This helps with reproducing gas reports during testing and bug fixing, but will also help uses locate methods in gas report.
use sorted
methods always sorted
> fix: sort methods in gas report [APE-1052]

- Dockerfile
changed chown command in dockerfile to --recursive 
may fix: # https://github.com/ApeWorX/ape/issues/1476
changed chown command in dockerfile to `--recursive` instead of `-hR`
```
$ docker build -t ape .
$ docker run -it --entrypoint /bin/bash ape
harambe@8650e9ff7e66:~/project$ ls -la
total 8
drwxr-xr-x 1 harambe harambe 4096 May  4 15:48 .
drwxr-xr-x 1 harambe harambe 4096 Jun 12 20:55 ..
```
> fix: change chown to --recursive for reliability and readability [APE-1072]

- src/ape/utils/os.py
- src/ape_run/_cli.py
- tests/integration/cli/test_run.py
`ape run` would always run the wrong deploy script after i installed ApePay.
i also made an issue there: https://github.com/ApeWorX/ApePay/issues/14
but to fix it in Ape, I can make it ignore existing modules named `scripts`, so that is what this PR does.
remove from both sys module and sys path to get it to work properly. was a pain to figure that out.
* install ApePay (before anything fixed there)
* try running different ape script
* notice it is trying to run the deploy script from `ApePay` without this PR but with this PR it works
> fix: issue where installed module names `scripts` would interfere with `ape run` [APE-1073]

- src/ape/api/config.py
- src/ape/api/providers.py
Fixes an unreleased regression from https://github.com/ApeWorX/ape/pull/1458 where if a network was missing from an ecosystem (adhoc), it would fail in a bad way
use dict access
the newly added type checking helps
> fix: issue when network config is missing, txns would fail with a config error [APE-1076]

- docs/userguides/contracts.md
- src/ape/api/accounts.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/contracts/base.py
- src/ape/utils/misc.py
- tests/functional/test_contract_container.py
- tests/functional/test_contract_instance.py
- tests/functional/test_networks.py
1. Added send_private_transaction as an abstract method to ProviderAPI
2. Added a `private` bool to `transfer` and `call` methods of AccountAPI to test that a "not implemented" error is raised
fixes: https://github.com/ApeWorX/ape/issues/1112
Pretty much as described in https://github.com/ApeWorX/ape/issues/1112. Will follow up with a PR on ape-alchemy that actually implements the `send_private_transaction` abstract method created here.
WIP
> feat: private transaction support [APE-915]

- src/ape/managers/converters.py
- tests/functional/conversion/test_hex.py
Hex to integer conversion now requires a prefix of "0x" for string values otherwise the value is not converted.
fixes: #1435
> fix: hex string converter [APE-1082]

- src/ape_ethereum/ecosystem.py
Add check for "value" kwarg and convert it if it is not an `int` value in `create_transaction`.
fixes: #1441 
It can be verified by running this in `ape console`:
`txn = networks.ecosystem.create_transaction(receiver="0x", value="1 wei", data=b"", type=convert(2, int))`
> fix: convert value for create_transaction [APE-960]

- src/ape/cli/__init__.py
- src/ape/cli/choices.py
- src/ape/cli/options.py
- src/ape/logging.py
- src/ape_run/_cli.py
- tests/functional/test_cli.py
- tests/integration/cli/test_run.py
* feat: now instead of `from ape.cli.options import verbosity_options`, you can do `from ape.cli import verbosity_option`.
* feat: automatically add `--verbosity` option to `main` and `cli` based scripts
* fix: `AttributeError` from certain custom option classes not having an attribute named `.name`
* feat: Allow `verbosity_option()` to work without passing in the logger as an argument
* feat: Will accept integer values for `--verbosity`
**needed for silverback https://github.com/SilverBackLtd/silverback/pull/9**
> feat: automatically add `--verbosity` to scripts and other CLI fixes [APE-1091]

- src/ape/api/projects.py
- tests/functional/test_project.py
If you have 1 source file on one branch but not on the other, compiling would always be like "Corrupted, rebuilding manifest". because the source was always missing there but got previously compile and carried over in the `.build` folder.
now, that doesn't happen.
When looking at a cached manifest, don't put on the contract type JSONs if they are missing from the sources.
Have 2 branches with different files in them, you should be able to compile without the manifest corrupted issue
> fix: issue where manifest was corrupted when changing branches [APE-1101]

- src/ape/managers/project/manager.py
- tests/functional/test_project.py
Here is how to repro the bug:
1. Use coverage branch for both ape and ape-vyper
2. Compile a project
3. Switch ape core off the coverage branch
4. Attempt to run a script using the contract container that got compiled
5. Notice it complains about not being able to call a `ContractNamepace`
6. HuhThatIsWeird.jpg
7. Ok, it works if switching back to correct branches but surely it is should not be confusing this with ContractNamespace
8. Look at the code- ah wasn't actually checking correctly
```python
"."
```
Follow steps. Now you should see a more expected error.
`ape-vyper` fails to load so it complains the plugin is broken and that you are probably referencing something from it
> fix: issue where project manager mistakenly thought an old contract was a `ContractNamespace` [APE-1111]

- tests/functional/utils/test_github.py
an upgrade in pygithub caused this but it is not a big deal because only happen in tests.
only type checking in the tests failed, no other issues detecting
change how we make an exception class in tests
type check works again
> test: type check fail from tests [APE-1125]

- src/ape_ethereum/ecosystem.py
add support for autodetecting [solady push0 minimal proxies](https://github.com/Vectorized/solady/blob/8c751db06e614e26e6acb9b385b463feef5e3a9f/src/utils/LibClone.sol#L168).
a deployer for them can be found [here](https://etherscan.io/address/0x4de3505c938d1e6af47c0ff94ba4baf9163d7b81#code) and an example instance can be found [here](https://etherscan.io/address/0x39a0f5da85b4a08686b6e931860e5192deb685f0#code)
originally found [here](https://twitter.com/optimizoor/status/1646418810717736962).
added a pattern to the existing proxy info detector.
```python
>>> chain.contracts.get_proxy_info('0x39a0F5da85b4a08686B6E931860E5192DeB685f0')
ProxyInfoAPI(target='0x0000000000006396FF2a80c067f99B3d2Ab4Df24')
```
> feat: detect solady push0 minimal proxies [APE-1123]

- docs/commands/pm.rst
- docs/index.md
- docs/userguides/compile.md
- docs/userguides/dependencies.md
- src/ape/api/projects.py
- src/ape_compile/__init__.py
- src/ape_compile/_cli.py
- tests/integration/cli/projects/only-dependencies/ape-config.yaml
- tests/integration/cli/test_compile.py
fixes: #1326 
Fixes: APE-682
* Adds a new CLI flag for `--include-dependencies` so you compile dependencies during `ape compile` if you choose
* Allow config:
```yaml
compile:
include_dependencies: true
```
to always do this
* Allow skipping cache for dependency compiling via `dep.compile(use_cache=False)`
* Pass along `use_cache` value so `--force` works with `--include-dependencies` to still compile dependencies even when their contract types are already filled out. This is great for compiling with new settings!
* new config
* new click option
* callback in click option looks at config when it is not set
* during compile command, if the value is true, loop through the project's dependencies and call compile and pass along the use_cache value
* handle use_cache in dep.compile
you can …
> feat: `--include-dependencies` flag for `ape compile` command and setting [APE-682]

- src/ape/api/projects.py
- src/ape/contracts/base.py
- src/ape/exceptions.py
- src/ape/managers/compilers.py
- src/ape/managers/networks.py
- src/ape/managers/project/manager.py
- src/ape/plugins/__init__.py
- src/ape/types/__init__.py
- tests/functional/test_compilers.py
- tests/functional/test_project.py
I spent too long being stuck, so I added an extra warning after I figured it out.
Also made the error a lot prettier by using our base class as well as attribute error
It looks like this now:
```
(yoko) ➜  ape-playground git:(proxy) ✗ ape run beacon
File "/HOMEApeProjects/ape-playground/scripts/beacon.py", line 9, in main
contract = ape.project.file.deploy(sender=account)
ERROR: (ApeAttributeError) ProjectManager has no attribute or contract named 'file'. However, there is a source file named 'file', Did you mean to reference a contract name from this source file?
```
> fix: better warning for attribute error [APE-1139]

- tests/conftest.py
- tests/functional/test_accounts.py
- tests/integration/cli/projects/test/tests/test_fixtures.py
finally fixes a few warnings that were appearing when tests failed
for some reason have to set `__test__ = False` _in the test_... setting it in the class alone is not enough.
for another one, have to return a function starting with `test_` even if it is skip
> test: fix pytest collection warnings that appear when tests fail [APE-1146]

- docs/userguides/dependencies.md
- src/ape_compile/_cli.py
- src/ape_pm/_cli.py
- tests/integration/cli/test_pm.py
2 fixes that should have been in #1504 
* `ape pm compile` with no args to compile all dependencies in the project, matching `ape pm install` with no args.
* when encountering an error during compiling a dependencies, (which is likely, and will happen if you use chainlink), it will log the error and carry on compiling the rest instead of failing out entirely there.
* ^ this same change for `ape compile --include-dependencies` (should have been part of #1506)
> feat: `ape pm compile` for all dependencies and prevent failing on first dependency during compile [APE-1143]

- docs/conf.py
noticed the version selector was not really working and it is just broken in general.
this is because it builds the docs before committing to the gh-pages, so it doesnt know all the versions to build, each version had a different list in its list of versions - got weird...
use the web as the source of truth, so you get em all
one issue tho is locally you wont have access to those versions in your _build unless you have built them before
```
cd docs
```
```python
from conf import get_versions
get_versions()
```
```sh
cd ..
python build_docs.py
python -m http.server --directory "docs/_build/" --bind 127.0.0.1 1337
```
> docs: fix version selector [APE-1163]

- src/ape/types/coverage.py
found a small issue with favicon when running coverage in CI and including HTML.
the favicon just wouldnt exst, it wouldnt cause any issues or anything so this a non-emergency, but just something the tests in `ape-vyper` caught
> fix: issue with HTML favicon when running in CI [APE-1165]

- src/ape/contracts/base.py
- src/ape/exceptions.py
- tests/functional/test_contract_container.py
- tests/functional/test_contract_instance.py
fixes: #1363
Fixes: APE-761
passing ABI
make sure to not let this be a breaking change to still handle old way
using italics and newlines and showing all inputs nicerly
call some methods, includig ctor, with wrong number of args
> feat: a better error for wrong number of arguments [APE-761]

- docs/userguides/config.md
- setup.py
- src/ape/managers/config.py
- tests/conftest.py
- tests/functional/test_config.py
was seriously impossible to use alchemy without hacking config files in places i shouldnt be, when working on silverback related work
fixes: #379 
Fixes: APE-153
read both places but read global first so it gets override by project settings
> feat: support global `ape-config.yaml` files [APE-153]

- src/ape/contracts/base.py
- src/ape/managers/project/manager.py
i found this while working on other stuff
> chore: fix return type of `ContractContainer.__getattr__` [APE-1166]

- src/ape/managers/chain.py
when using a local net and poll blocks times out waiting for a new block, encourage user to adjust mining settings on node.
> fix: improve error when polling for blocks on local networks [APE-1176]

- src/ape/api/address.py
- tests/functional/test_address.py
am debugging failing tests here https://github.com/ApeWorX/ApePay/pull/12
> test: address `__eq__` checking [APE-1178]

- src/ape_init/_cli.py
one-liner to add `.python-version` to the `.gitignore` file of newly initialized ape projects. 
[the bunny is right](https://twitter.com/bantg/status/1677475400048312320?s=20) about the convenience of declaring local virtualenv instances. more smol context on pyenv-virtualenv [here](https://realpython.com/effective-python-environment/#pyenv-virtualenv).
inspect the `ape init`-generated `.gitignore` file
> chore: add .python-version to generated .gitignore [APE-1182]

- src/ape/api/providers.py
- src/ape/utils/misc.py
- tests/functional/test_geth.py
- tests/functional/test_provider.py
- tests/functional/utils/test_misc.py
Noticed that sometimes gas price is a hex str and sometimes it is `None`.
This problem was hidden by this type ignore statement that I put on there and forgot to address (https://github.com/ApeWorX/ape/commit/3a20280ed70083392ea99ead3e475772adca49a9)
Let this be a lesson to us all to avoid type ignore, as they may conceal bugs.
Check type and handle other types
Look at Ganache! They are hex strings there now, or the latest web3.p idk, that is where i saw the failing test.
Also the return type says it can be optional. When using our geth dev, it was None, so i made it default to 0 in that case.
> fix: gas price type errors [APE-1193]

- src/ape/pytest/coverage.py
Moved the `functions_incremented` variable outside of the for loop because it wasn't being accessed properly and giving a error: `UnboundLocalError: cannot access local variable 'functions_incremented' where it is not associated with a value`
fixes: #
> fix: move functions_incremented outside loop [APE-1184]

- src/ape/api/providers.py
- tests/functional/test_provider.py
fixes: #1540 
* add missing support
* add block id alias
> feat: support block id for provider `get_code()` [APE-1203]

- src/ape/api/transactions.py
- src/ape/contracts/base.py
- src/ape/managers/chain.py
- src/ape/managers/project/manager.py
- tests/functional/test_chain.py
- tests/functional/test_contract_instance.py
- tests/functional/test_query.py
**Please** review + merge #1547 first! this PR depends on those changes so it has all the same changes but i will rebase after and the diff will look nicer. I am leaving it in draft until that is done
* Adds `chain.get_contract_receipt()` method to help get receipts for contracts.
* Changes `receipt` on `ContractInstance` to no longer be optional. If it does not have it, it will call the new method to get it.
* fixes: #1062  Changes the default `start_block` to use the start block of the contract's receipt when not given for event queries
@fubuloubu wrote the start of the algo, i fixed the bug in it, pasted in it, made mypy happy, added some tests, wired it up in some places that make it work nicely in the bg.
> feat: improved contract receipt related logic

- src/ape/managers/chain.py
issue where would repeatedly search history it should have known it didnt need
use mid block + 1 as the start because we know the contract was not yet deployed at this point
f***ing c-net works again
> fix: search algo [APE-1215]

- .pre-commit-config.yaml
- setup.py
- src/ape/cli/arguments.py
- src/ape/cli/paramtype.py
- tests/functional/test_cli.py
I think we are finally able to do this.
For sure click, we will see if mypy works in CI
> chore: bump click [APE-1212]

- src/ape/exceptions.py
- src/ape/managers/chain.py
- src/ape/managers/project/manager.py
- tests/functional/test_chain.py
Makes it easer to handle downstream occurrences of this problem.
Also, allows the improved error message to be shared with `__getitem__`'s `IndexError`.
> feat: `ContractNotFound` custom exception [APE-1211]

- src/ape/pytest/contextmanagers.py
- tests/functional/test_reverts_context_manager.py
I am not sure if this is exactly related to the anomaly I am seeing, but this will at least guarantee that no 2 revert infos are the same.
Create a new RevertInfo object for each entered context
can use reverts context still
> fix: issue where revert infos were the same [APE-1210]

- Dockerfile
changed dockerfile so that it actually installs ape instead of installing it as a dependency of the recommended plugins text file.
updated dockerfile
build it
> fix: actually install ape [APE-1217]

- src/ape/managers/config.py
- tests/functional/test_config.py
Before, only top level keys worked, if you overrode one in a project, you had to override everything.
Now, it will merge the objects the best it can, thus global mainnet providers work a lot better as most projects still configure local Ethereum providers and that was causing conflicts / loss of config specs
carefully merge the objects
can now config Ethereum in both places and have it merge and use both
> fix: handle nested structures in global config merge [APE-1218]

- src/ape/api/transactions.py
- tests/functional/test_transaction.py
Specify encoding as utf-8 when calling bytes
fixes: #1535
fixes: APE-1181
in this case we should always be dealing with utf8 strings
I kept getting contract deployment failures like reported in the discord and in #1535 
with this fix I was able to deploy contracts successfully
> fix: specify encoding when calling `bytes` [APE-1186]

- src/ape_cache/query.py
when using the ape logger in projects that contain multiple cache databases, the context is suddenly missing.
This PR very simply adds missing context
mention `ape-cache`
> docs: clarify doc message [APE-1224]

- src/ape/api/transactions.py
- tests/functional/test_receipt.py
This would cause issues where lines were mistakenly marked as covered! Specifically, the builtins seems to get mistakenly covered the most
> fix: dont track deploys yet [APE-1228]

- .mdformat.toml
- docs/index.md
- docs/userguides/dependencies.md
- docs/userguides/logging.md
realized no one knows what `-v debug` means, ooooops
here ya go
> docs: add logging user guide [APE-1227]

- src/ape/pytest/runners.py
- `pytest_runtest_setup` will skip doctests now too
if `item` is `pytest.DoctestItem`, do not inject anything
add doctests to some functions in the code, ensure pytest includes them when collecting the tests
> fix: does not add  fixture when it's a doctest [APE-1231]

- .github/workflows/publish.yaml
- src/ape_geth/provider.py
Noticed that if your URL contains API keys, they would not get sanitized properly.
I think the only way we can really do this in such a generic way to just always sanitize the path when they exist.
Check if there is a path.
If there is, do `with_path("")` and put `[hidden]` at the end of the URL.
(I borrowed this from some AWS logs I happened to see).
Otherwise, keep as normal, so `[hidden]` is only appended when actually hiding the path.
This was my log before (except im not actually pasting my API key, but it was where `apikeythatwasnotactuallyhidden` is):
```
INFO: Starting 'Hardhat node' process.
INFO: Connecting to existing Geth node at  https://eth-mainnet.g.alchemy.com/v2/apikeythatwasnotactuallyhidden.
```
This is in it now, so the whole path is just `[hidden]` now.
```
INFO: …
```
> fix: better URL sanitization in `ape-geth` connection [APE-1233]

- src/ape/pytest/runners.py
My previously merged PR wouldn't have fixed the issue because the check for fixturenames was performed before the check if the item is a DoctestItem.
Previous PR: https://github.com/ApeWorX/ape/pull/1567
TLDR; of the issue in previous PR:
made the order correct. First check if it's a DoctestItem, if not, then continue with the other check.
> fix: does not add  fixture when it's a doctest [APE-1236]

- setup.py
> fix: remove pin on evm-trace [APE-1230]

- .github/workflows/publish.yaml
- src/ape/cli/options.py
- src/ape_accounts/_cli.py
- src/ape_pm/_cli.py
type checkers were reading this as a return type of `None` when it is actually `NoReturn`, this fixes various hacks we had to do.
> fix: correct return type of `abort()` function [APE-1242]

- .pre-commit-config.yaml
- docs/userguides/networks.md
- setup.py
- src/ape/api/providers.py
- src/ape/cli/options.py
- src/ape/logging.py
- src/ape_geth/provider.py
- src/ape_networks/_cli.py
- tests/functional/test_chain.py
- tests/functional/test_contract_instance.py
- tests/functional/test_logging.py
- tests/functional/test_project.py
- tests/functional/test_provider.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_networks.py
A CLI for starting development nodes
fixes: #1453
fixes: https://github.com/ApeWorX/ape-hardhat/issues/128
Fixes: APE-981
Fixes: APE-725
> feat: `networks run` CLI [APE-981]

- setup.py
now that web3 6.7.0 (and other eth deps) is out, we can bump mypy correctly
> chore: bump mypy [APE-1255]

- src/ape/utils/github.py
change kwarg we use to auth to gh so it stops being mad
> fix: warning from authenticating to Github in deprecated way [APE-1258]

- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/managers/chain.py
- tests/functional/test_chain.py
Show network and ecosystem in error message when contract type not found.
fixes: #1577
Fixes: Ape-1247
Otherwise it is confusing when you think you are on a fork when you are actually on local.
Make shared network choice and use all over, including in that error, without being a breaking change for the error
> fix: show full network name in `ContractTypeNotFoundError` [APE-1259]

- setup.py
fixes this error on ape load
```python
ModuleNotFoundError: No module named 'github.auth'
```
ape required pygithub>=1.54, while in fact auth module [was added](https://github.com/PyGithub/PyGithub/blob/main/doc/changes.rst#version-1590-june-22-2023
) to pygithub in 1.59.
bump version
try a fresh install from the repo and then run any ape command
> fix: pygithub breaking change [APE-1276]

- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/proxies.py
detect a new proxy type [described here](https://github.com/wighawag/clones-with-immutable-args/blob/master/src/ClonesWithImmutableArgs.sol) and used in [ajna protocol](https://etherscan.io/address/0x5b14144DA6FD5e3B158d6dF7B6ED8345829aAB78#code).
using exiting way to add a proxy type
```python
> chain.provider.network.ecosystem.get_proxy_info('0x5b14144DA6FD5e3B158d6dF7B6ED8345829aAB78')
ProxyInfo(target='0x05bB4F6362B02F17C1A3F2B047A8b23368269A21', type=<ProxyType.ClonesWithImmutableArgs: 11>)
```
> feat: detect clones with immutable args [APE-1278]

- setup.py
- src/ape/api/address.py
- src/ape/api/compiler.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/managers/chain.py
- src/ape/managers/converters.py
- src/ape/managers/project/manager.py
- src/ape/pytest/contextmanagers.py
- src/ape/pytest/coverage.py
- src/ape/pytest/fixtures.py
- src/ape/utils/trace.py
- src/ape_accounts/accounts.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/provider.py
This helps in the case when a transaction fails before a dev message and a user gets confuses as like ape is not actually finding the dev message when actually the line it is failing on earlier. This PR shows the source traceback in that case.
before it was this:
```
/Users/jules/ApeProjects/yearn-vesting-escrow/tests/functional/VestingEscrowFactory/test_deploy_escrow.py:269: in test_vyper_donation
with ape.reverts(dev_message="dev: lost donation"):
```
now it looks like this:
```
/Users/jules/ApeProjects/yearn-vesting-escrow/tests/functional/VestingEscrowFactory/test_deploy_escrow.py:269: in test_vyper_donation
with ape.reverts(dev_message="dev: lost donation"):
E   AssertionError: Could not find the source of the revert.
E   Traceback (most recent call last)
E     File …
```
> fix: more source traceback improvements [APE-1335]

- src/ape_plugins/_cli.py
- tests/integration/cli/test_plugins.py
when using the github action, the versions are all strung together, so this PR makes it parse that correctly.
split(" ")
```sh
ape plugins install "tokens==0.6.1 polygon"
```
> fix: issue where couldn't specify multiple versions when installing plugins [APE-1345]

- src/ape/api/transactions.py
- src/ape/types/__init__.py
- tests/functional/test_contract_event.py
Because of a check that ignored all fasley values, log-assertion checks would have false-positives, meaning your tests pass when they shouldn't! dun dun dunnn.
check that `is not None` instead of falsey.
This passes on main branch believe it or not:
```python
tx = c.setNumber(1, sender=owner)
assert tx.events == [c.NumberChange(newNum=0)]  # actual value was 1 but Ape didn't care
```
however with these changes, it correctly fails.
> fix: false-positives bug when making mock-log assertions [APE-1352]

- .github/FUNDING.yml
> docs: remove gitcoin link from funding [APE-1360]

- src/ape/api/projects.py
- src/ape/managers/compilers.py
- src/ape_pm/compiler.py
- tests/functional/test_chain.py
- tests/integration/cli/test_compile.py
somehow a good friend of mine ended up with their .build folder within their contracts folder, maybe from an odd usage of using_project (TBD).
anyway, there is not reason to ever compile such things so i added it to the ignore list.
same we do for .cache
tbd
> fix: don't compile `contracts/.build` [APE-1358]

- src/ape_ethereum/ecosystem.py
improve the display of symbols for tokens that use a `bytes32` symbol in `ReceiptAPI.show_trace()`
one major example being MKR, tracked back to [ds-token](https://github.com/dapphub/ds-token/commit/08412f94a62529d7853c1e817c9406a4d0735d4a).
different handling for the returned `str` and `bytes` value, while keeping the fallback to contract type name.
before
```python
VoteDelegate.free(wad=200000204806431039674) [121538 gas]
├── b'IOU\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
│   0\x00\x00\x00\x00\x00\x00'.pull(src=tx.origin, wad=2000000000000000000) [30756 gas]
├── DSChief.free(wad=2000000000000000000) [59556 gas]
│   ├── b'IOU\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
│   │ …
```
> feat: decode bytes32 symbols in traces [APE-1368]

- src/ape_pm/_cli.py
- tests/integration/cli/test_pm.py
* Fixes issue where `ape pm list` would unnecessarily compile
* Fixes issue where there was no header in `ape pm list`
* Uses pager when there many dependencies installed.
fixes: #1619 
Fixes: APE-1347
Small list:
Big list:
(notice pager)
> fix: `ape pm list` fixes [APE-1347]

- src/ape/exceptions.py
- src/ape/types/__init__.py
Noticed we were not alway showing the last line in pytest exception repr.
Using `end_lineno` instead of `begin_lineno` fixed that.
> fix: pytest trace shows wrong lineno [APE-1388]
