- setup.py
- src/ape/_cli.py
- src/ape_accounts/_cli.py
v8.0 adds a couple of necessary improvements to testing invocation paths
> chore: upgrade to Click v8.0.0

- .github/release-drafter.yml
- .github/workflows/draft.yaml
NOTE: Won't work until installed
> chore: add `release-drafter`

- src/ape_compile/_cli.py
This PR changes `ape compile` CLI endpoint behavior, allowing to filter selections from the current project when compiling (default is all paths)
> refactor: update how compile CLI works to select contracts

- .github/workflows/test.yaml
- setup.py
> chore: python 3.9

- setup.py
- src/ape/api/accounts.py
- src/ape/api/base.py
- src/ape/api/compiler.py
- src/ape/api/config.py
- src/ape/api/explorers.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape_infura/providers.py
- src/ape_test/providers.py
fix for https://github.com/biqqles/dataclassy/issues/46
> fix: dataclassy regression

- .gitignore
- CONTRIBUTING.md
- setup.py
- src/ape/_cli.py
- src/ape/api/accounts.py
- src/ape/api/config.py
- src/ape/api/networks.py
- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape/plugins/network.py
- src/ape/utils.py
- src/ape_accounts/accounts.py
- src/ape_infura/providers.py
- src/ape_pm/compiler.py
- src/ape_test/providers.py
* Use error text color for Abort error
* Return empty dict when config is None on load
* Fix f-str, missing `f`
* Fix spellings
Additional questions:
* Do docs work / exist? Seems like there is a plan for readthedocs and also the link on the site for docs does not really go anywhere. I just want to make sure I have all the material.
* Plans for more thorough unit tests?
* Loading the config at module load time seems bad because you miss out on available click features, such as `click.Exception`.
I will continue on tomorrow, just wanted to open some dialogue and contribute, even if small. The big change here is the text color for `Abort` exceptions. Another big change is that is fixing a weirdness when you try to load an empty `yml` file as a config, the parse actually returns `None` which …
> fix: small updates

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/work-item.md
- .github/PULL_REQUEST_TEMPLATE.md
Copying over issue and PR templates from `project-template`.
> chore: add issue and PR templates

- src/ape_accounts/_cli.py
notify error on key import
Related issue: #
> fix: notify error on key import

- src/ape/api/networks.py
> fix: chain/network ID values in NetworkAPI are not properties

- src/ape_plugins/_cli.py
> fix: allow skipping confirmations if desired

- .github/workflows/test.yaml
Add runners for mac
Related issue: #95
> chore: use different OSs for CI

- src/ape/api/accounts.py
> fix: set `txn.chain_id` based on Network's expected value

- src/ape/api/accounts.py
- src/ape/api/providers.py
Fixed a bunch of little issues concerning the use of default values when making a call with an account
> fix: make sure transactions defaults function properly

- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape_http/providers.py
- src/ape_test/providers.py
> fix: raise if not connected to correct chain via HTTP provider

- src/ape/_cli.py
Create a fuzzy command suggestion to improve the UX of ape.
difflib magic
Try:
`ape acconts` (accounts is spelled wrong)
notice it says:
`Error: No such command 'acconts'. Did you mean accounts?`
Try it with other commands as well.
> feat: fuzzy command suggestions

- src/ape/_cli.py
- src/ape/api/accounts.py
- src/ape/api/address.py
- src/ape/api/contracts.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/exceptions.py
- src/ape/managers/compilers.py
- src/ape/managers/config.py
- src/ape/managers/converters.py
- src/ape/managers/networks.py
- src/ape/managers/project.py
- src/ape/types/abstract.py
- src/ape/utils.py
- src/ape_accounts/_cli.py
- src/ape_compile/_cli.py
- tests/functional/conversion/test_ether.py
- tests/integration/cli/test_accounts.py
- tests/integration/cli/test_compile.py
Created and used custom Ape exceptions
Related issue: #132
Created a python module `ape.exceptions` that contains custom exceptions that end users can easily import if needed (for either raising in their custom plugin implementations _or_ handling when `ape` raises them naturally).
Then, I used these custom exceptions 
* Make sure ape still works as it did before
* Make sure exceptions make sense and named in a way that is agreeable and include data that is helpful for users who are debugging.
* Make sure there are not more places where custom exceptions seem useful that should be added as part of this work.
> feat: custom exceptions

- .github/PULL_REQUEST_TEMPLATE.md
This will make is easier to not forget to use `fixes: #`.
It will also encourage the creation of tickets more.
> fix: uses 'fixes' keyword in PR template

- src/ape_networks/_cli.py
- tests/integration/cli/test_networks.py
fixes: #163
* Looked at the history of the command
* Re-ran old version before refactor
* Noticed difference (not sure how! I thought for sure I checked that the outputs were the same before)
Run the command and make sure the output looks good.
> fix: correct networks list output

- src/ape/_cli.py
- src/ape/cli/__init__.py
- src/ape/cli/choices.py
- src/ape/cli/options.py
- src/ape/cli/utils.py
- src/ape/utils.py
- src/ape_plugins/_cli.py
fixes: #145 
* Added some more tooling to the CLI module ( from the Ledger plugin)
* Made things more importable from `ape.cli`
* Moved `Abort()` to `ape.cli.exceptions`
* Created an `ape.cli.choices` sub-module
* Renamed `yes_option` to `skip_confirmation_option` (as is in `ape-ledger`)
Upgrade plugins, such as I did on this branch: https://github.com/unparalleled-js/ape-ledger/tree/chore/upgrade-ape
> feat: cli module

- src/ape/exceptions.py
- src/ape_accounts/accounts.py
- src/ape_ethereum/ecosystem.py
- src/ape_http/providers.py
- src/ape_pm/compiler.py
fixes: #153
* Replaced `raise Exception()` in 1st class plugins with custom exceptions that, for the most part, already existed from previous work.
* Make sure the custom exceptions make sense.
> feat: custom errors in 1st class plugins

- README.md
Nice to have them in quick to access place
```
penguins walking:
_      _
<`)     <`)     <`)    (v)    (v)
/V\     /V\     /V\   //-\\  //-\\
\(_)>  \<\_)>  \< _/>  (u_/)  (\_u)
~~      ~~      ~~       ^    ^
```
> docs: update website and doc links in README

- src/ape_geth/providers.py
specified optional values instead of using positional arg
No bug fix or anything but just wanted to do this before I forgot.
> refactor: specify optional value in call instead of using arg position

- src/ape/api/__init__.py
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape_ethereum/__init__.py
- src/ape_geth/providers.py
- src/ape_networks/_cli.py
- tests/integration/cli/test_networks.py
- tests/integration/cli/test_run.py
I totally forgot to merge the last PR before deleting that branch :[ (#255 )
This adds the support upstream providers
> feat: support upstream providers

- tests/integration/cli/projects/test/tests/test_test.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_run.py
- tests/integration/cli/test_test.py
tests test
test_test calls test on tests/test_test
> test: test test

- src/ape/utils.py
I didn't realize this existed
swap out my implementation with builtin
> refactor: use builtin tempfile context manager

- src/ape/api/address.py
Add method docs strs to `AddressAPI`
Played a "Guess the Doc Str" game with @Ninjagod1251 
Read through 'em
> docs: document AddressAPI

- src/ape/api/accounts.py
- src/ape/contracts/base.py
- src/ape/managers/project.py
fixes: #312
Do a local import for now. There is a cyclic dependency because between accounts and contracts.
Example:
```python
account.deploy(project.Fund)
```
> fix: resolve import error preventing deploying contracts from working

- src/ape/api/providers.py
added doc strings to provider.py
fixes: #
Solo Dolo feat @Ninjagod1251 and no Kid Cudi. He walked off the plank on the doc_string
Please read it and let me know where i went wrong.
> docs: added provider API doc strings

- setup.py
Update the development status to `Development Status :: 4 - Beta`
> chore: update development status to beta

- .github/workflows/test.yaml
- setup.py
> chore: add support for Python 3.10

- docs/index.md
- docs/methoddocs/exceptions.md
> docs: Document exceptions module

- README.md
I noticed this disclaimer still references the alpha
I tried to update it to make it sound more beta.
Adjust language to be less severe than the alpha.
Read it, give feedback.
> docs: use more beta-like language in readme

- docs/methoddocs/api.md
- src/ape/api/compiler.py
- src/ape/api/networks.py
- src/ape/api/providers.py
* Add missing documentation to the Network API module
* Address unaddressed feedback on provider API
* Fix other API-docs related issues, such as improperly formatting links.
Using sphinx docs, same old.
Build and verify the docs, particularly for the networks api.
read through them.
> docs: Document Networks API

- docs/methoddocs/cli.md
split up and organize the CLI utilities method docs
Use subsections
Add header doc
Read through + build
> docs: split up and organize the CLI utilities method docs

- docs/index.md
- docs/methoddocs/contracts.md
- src/ape/contracts/base.py
Document the contract module.
Document the two classes that users will be using from this module.
Make sure it all makes sense when building and looking at the docs.
Builds the docs.
Make sure it makes sense.
> docs: document ape.contracts public classes and methods

- docs/index.md
- docs/methoddocs/plugins.md
- docs/userguides/plugins.md
- docs/userguides/projects.md
- docs/userguides/quickstart.md
- src/ape/api/providers.py
- src/ape/plugins/__init__.py
- src/ape/plugins/account.py
- src/ape/plugins/compiler.py
- src/ape/plugins/config.py
- src/ape/plugins/converter.py
- src/ape/plugins/network.py
- src/ape/plugins/pluggy_patch.py
this is as far as i got fixing the guides!
> docs: document projects and plugins via guides and more method docs

- docs/userguides/plugins.md
- docs/userguides/quickstart.md
added logging tutorial to quickstart and plugins documentation.
fixes: #
> docs: added logging tutorial to quickstart and plugins

- src/ape_plugins/_cli.py
added messages to add and remove plugins to help the user confirm their commands.
fixes: #
check the result of the subprocess call
add and remove plugins
> feat: add and remove success message to plugins commands

- src/ape_plugins/_cli.py
- src/ape_plugins/utils.py
added an uninstall command so we could uninstall all the plugins from the config.yaml
fixes: #
added a block of code in the _cli.py to make the command
install and uninstall the config list of plugins in your own project!
just remember the schema for the config file.
> feat: added uninstall command and made install have confirmations

- docs/userguides/config.md
- src/ape/managers/networks.py
- src/ape_ethereum/ecosystem.py
fixes: #399 
Similar to how we set the default provider from the config.
Use this in a project:
```yaml
ethereum:
default_network: mainnet-fork
```
> feat: allow specifying default network

- src/ape/exceptions.py
fixes: #422 
Just deleted this over-zealous nonsense
tests should pass
> fix: remove code that automatically added periods to exception messages

- setup.py
updated requirements
fixes: #417 
updated requirements as mentioned in issue
`docker build .`
> fix: docker build failing for requirements

- src/ape/contracts/base.py
fixes: #423 
When initializing a `ContractInstance`, make the check then.
Using the follow code:
```python
from ape_tokens import tokens
yfi = tokens["YFI"]
yfi.decimals()
```
Should work:
```bash
ape console --network :mainnet:infura
```
Should fail:
```bash
ape console --network :ropsten:infura
```
> fix: check if contract prior to transacting

- src/ape/_cli.py
- src/ape_compile/_cli.py
> fix: issue preventing stacktrace from showing in -v debug

- docs/userguides/plugins.md
- docs/userguides/projects.md
- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/cli/__init__.py
- src/ape/cli/choices.py
- src/ape/cli/options.py
- src/ape/managers/chain.py
- src/ape/managers/networks.py
- src/ape/plugins/network.py
- src/ape_ethereum/__init__.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/providers.py
- src/ape_test/__init__.py
- src/ape_test/providers.py
- tests/integration/cli/projects/geth/ape-config.yaml
- tests/integration/cli/test_networks.py
Breaking changes PR.
Any rename, get them in now.
fixes: #457
> refactor: rename 'development' to 'local' and other renames (breaking changes PR)

- Dockerfile
> refactor: prevent overwriting anything in root

- setup.py
- src/ape/api/networks.py
- src/ape/contracts/base.py
- src/ape_ethereum/ecosystem.py
- src/ape_pm/compiler.py
Breaking changes introduced in `ethpm-types` b4/b5. This fixes them.
> fix: breaking ethpm types

- docs/methoddocs/api.md
- docs/methoddocs/managers.md
- docs/methoddocs/plugins.md
- setup.py
- src/ape/_compat.py
- src/ape/api/__init__.py
- src/ape/api/query.py
- src/ape/exceptions.py
- src/ape/managers/accounts.py
- src/ape/managers/chain.py
- src/ape/managers/config.py
- src/ape/managers/query.py
- src/ape/plugins/__init__.py
- src/ape/plugins/query.py
- src/ape/types/__init__.py
Getting a base structure started for @johnson2427 and myself.
> feat: add query base structure

- src/ape/api/query.py
Some quick fixes when using the `QueryType` Pydantic classes
> fix: query type issues

- docs/userguides/config.md
Add quick guide to changing Geth settings
> docs: add config guide for geth provider URI

- src/ape/api/networks.py
> fix: forgot to fetch config from provider origin module

- README.md
Added line 91 help new users access test accounts
> docs: Added line about test accounts

- docs/userguides/quickstart.md
> docs: have user update their version of pip before installing

- src/ape_geth/providers.py
fixes: #534 
Allow passing of extra fields via the pydantic Config class
> refactor: allow config to pass extra fields

- docs/userguides/projects.md
- src/ape/managers/project.py
- src/ape/utils.py
- src/ape_run/_cli.py
- tests/integration/cli/projects/script/scripts/_utils.py
- tests/integration/cli/projects/script/scripts/click.py
- tests/integration/cli/projects/script/scripts/deploy.py
- tests/integration/cli/projects/script/scripts/site.py
- tests/integration/cli/test_run.py
Allow scripts that use click to function correctly. Also load in extra locals correctly using interactive. Basically entire scripting engine overhaul.
fixes: #369
> refactor: do script loading more dynamically

- src/ape/exceptions.py
- src/ape/managers/project.py
- tests/README.md
Fixes missed from subprocess provider.
Stuff needed for demo
Demo worked
> fix: (subprocess provider continued) remove unused call and other clean-up

- src/ape/convert/__init__.py
- src/ape/managers/config.py
- src/ape/utils.py
- src/ape_accounts/accounts.py
- src/ape_test/accounts.py
fixes: #539
make sure you can import to address from utils
> refactor: moved to_address to utils module

- docs/userguides/plugins.md
> docs: edited the tokenlist plugin name to be correct

- README.md
- setup.py
> docs: update docs to be stable

- build_docs.py
- docs/_static/custom.css
- docs/conf.py
- setup.py
fixes: #565
* bump all docs dependencies
* configure myst to continue allowing html links
* better error processing in build_docs.py
* make links in docs site discoverable (they were the same color as the text before and it was not obvious that links were there without hovering).
> fix: support latest sphinx

- src/ape/managers/chain.py
added deltatime capability to chain.ChainManager.mine
fixes: #569
Added the deltatime kwarg to ChainManager.mine
Create test (will do following some back and forth) and test the new mining capability
> feat: add deltatime kwarg to chain.mine

- docs/userguides/projects.md
- src/ape/api/providers.py
- src/ape/contracts/base.py
- src/ape/utils.py
- tests/functional/test_contracts.py
> feat: support deploying from contract container

- setup.py
- src/ape/api/providers.py
Top pins `ethpm-types` for managing upcoming breaking changes.
fixes: #
> chore: pin ethpm-types version

- src/ape/managers/compilers.py
update compiler collision error message output to include collision name
fixes: #178 
updated error message with f string
put a contract called Token.sol and another called Token.vy and then try to compile and you will get an error pointing to the contract.
> docs: update compiler collision error to add helpful information

- setup.py
> chore: bump ethpm-types

- src/ape/api/networks.py
Added default value to None on provider settings
fixes: #495 
- ~[ ] New test cases have been added~
- ~[ ] Documentation has been updated~
> fix: add default for provider settings

- README.md
> fix: ape console in quickstart to not show up in index

- src/ape_ethereum/ecosystem.py
> fix: edge case found in hypotheses test

- src/ape/api/providers.py
- src/ape_geth/providers.py
- src/ape_test/providers.py
Starts fixing #720 
Move geth's implementation to ProviderAPI as default.
Things still work
> feat: add method to handle getting virtual machine error from Provider

- Dockerfile
- README.md
- setup.py
Adds an install extra to install commonly used plugins to reduce installation issues
Add plugin packages to an install extra
`pip install -U eth-ape[recommended-plugins]`
> feat: add recommended plugins install extra

- .pre-commit-config.yaml
- setup.py
`flake8` was having a conflict with the install requires.
> chore: update flake8

- src/ape/managers/project/types.py
> fix: issue when compiling a source where references was None

- src/ape_plugins/_cli.py
- tests/integration/cli/test_plugins.py
> fix: correct error code for plugins upgrade command

- src/ape/managers/compilers.py
Updated an older doc string for `get_references()` to match the correct parameter description.
fixes: #
> docs: fix get_references()

- docs/userguides/transactions.md
fixes: #
This is will improve #651.
I want to add a note link users to Ape Academy for an in depth guide on how to deploy with ape console. I kept it brief.
Please let me know if it clear and if this is a good idea to link here.
> feat: add docs deployment from ape console

- src/ape_ethereum/ecosystem.py
add support for a more-minimal proxy [described here](https://medium.com/coinmonks/the-more-minimal-proxy-5756ae08ee48).
using the existing bytecode matching system we have
> feat: add 0age proxy detection

- src/ape/managers/chain.py
Add `ProxyInfoAPI` disk cache, this massively speeds up contract loading speeds.
The disk cache is similar to what `ContractType` cache uses.
```python
%time Contract(some_proxy)
%time Contract(some_proxy)
```
> feat: proxy info disk cache

- src/ape/managers/chain.py
- src/ape_geth/providers.py
Same idea from https://github.com/ApeWorX/ape-hardhat/pull/74
> refactor: avoid attr dicts when making requests for tracing

- src/ape_geth/providers.py
Grab results list from response
**note: this was not yet released... wish it wasn't hard to test geth also!**
> fix: grab results list from trace_transaction response

- setup.py
- src/ape/api/accounts.py
- tests/functional/test_accounts.py
Adds test to ensure we support EIP-712 messages (in process of debugging something).
fixes: #75 
* eip712 package dependency
> test: ensure support for eip712

- tests/functional/test_receipt.py
Demo how to get a failed  receipt (until we come up with a better API)
Add test showing how to get a failed receipt
> test: add test for getting failed receipt

- src/ape/types/__init__.py
- src/ape_ethereum/ecosystem.py
- fix: event name
- fix: insufficient data bytes
fixes: #
> fix: log printing and decoding

- README.md
> docs: remove non-existent CLI flag from README example

- setup.py
- src/ape/api/networks.py
- src/ape/utils/abi.py
- tests/functional/test_networks.py
All fixes in this PR relate to other PRs - no changelog item necessary
> chore: address issues found from testing

- docs/userguides/networks.md
I wanted to more clear. lmk if that is okay
> fix: the example scheme for networks

- docs/userguides/compile.md
Fixed a broken link in the `compile` docs
> fix: fix a broken link in the docs

- .github/workflows/draft.yaml
While aligning ape-alchemy to match ape core, noticed this incorrect comment in the draft yaml.
> chore: update draft comment

- src/ape/exceptions.py
- src/ape/utils/basemodel.py
Looking for errors to raise noticed this unused exception. The code that references the exception in its docs doesn't raise for an address error but instead a provider error.
> chore: removed unused exception

- docs/userguides/contracts.md
@Ninjagod1251 pointed out to me that there was gap in the user guide regarding the at() method.
This PR fills in the gap to assist the education content we are producing!
words words words
Link checks?
> docs: update contracts user guide to include `at()` method reference

- setup.py
- src/ape/utils/trace.py
- tests/functional/data/python/__init__.py
> chore: update pinnings

- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/managers/query.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- tests/functional/test_provider.py
fixes: #1057 
Also fixes issue with `None` `max_fee` and `max_priority_fee_per_gas` when using `EthTeseter` and `get_transactions_in_block`
* Handle when data is str in pydantic validator
* Handle differing keys when creating a transaction in `ape_ethereum`
You no longer get the weird `SignatureError`
> fix: issues with getting transactions in a block

- src/ape/utils/trace.py
Round `mean` gas in gas report.
**This can be lumped in with the gas report changelog...**
> fix: round floats in gas report

- src/ape/contracts/base.py
- tests/functional/data/projects/ApeProject/contracts/Contract.json
- tests/functional/test_contract_container.py
add source_path property
fixes: #1005
add source path property within contract container
> feat: Add source_path (path) property to ContractContainer

- src/ape/utils/trace.py
> feat: address more trace feedback

- src/ape/types/signatures.py
- tests/functional/test_accounts.py
added recover_signer to ape.types.signatures
fixes: #1052
implemented recover_signer function in ape.types.signatures
`ape test tests/functional/test_accounts.py::test_recover_signer`
> feat: `recover_signer()` utility method in `ape.types.signature`

- src/ape_test/__init__.py
- src/ape_test/provider.py
- src/ape_test/providers.py
- tests/functional/test_accounts.py
- tests/functional/test_contract_instance.py
- tests/functional/test_geth.py
- tests/functional/test_networks.py
- tests/functional/test_provider.py
- tests/functional/test_query.py
- tests/functional/test_receipt.py
> fix: issue where revert message missing when specify gas using EthTester

- src/ape/api/accounts.py
- src/ape/api/providers.py
- tests/functional/test_accounts.py
So this PR came about while debugging a failing test from https://github.com/ApeWorX/ape/pull/1097.
Turns out, using max gas is so high that there is plenty of remainder in that situation to afford attempting to send full balance again. This makes sense but throw @helloibis and I for a head-spin for a while.
* Refactor code to make sense of what the heck is going on
* Set breakpoints to compare estimated gas limit and max gas limit
* Notice that max is magnitudes higher and thus does not drain balance sufficiently to cause user unable to transact afterwards because the value set from `set_everything=True` is safely assuming usage of full gas, as it has to.
We need to update the test is all in @helloibis 's branch. We can rebase off this PR to have the insight "previously" known. Sorry for …
> test: demonstrate transfer with `send_everything=True` and setting a very high gas

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
- src/ape/_cli.py
- src/ape/api/projects.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape/cli/choices.py
- src/ape/contracts/base.py
- src/ape/logging.py
- src/ape/managers/accounts.py
- src/ape/managers/chain.py
- src/ape/managers/config.py
- src/ape/managers/project/dependency.py
- src/ape/managers/project/manager.py
- src/ape/utils/trace.py
- src/ape_cache/query.py
- src/ape_console/_cli.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- src/ape_geth/provider.py
- tests/functional/test_cli.py
- tests/integration/cli/test_accounts.py
- tests/integration/cli/utils.py
> fix: resolve typing issues found in pre-commit and upgrade lint dependencies

- setup.py
> chore: upgrade `web3py` dependency to `6.0.0b7`

- docs/userguides/compile.md
> docs: add more detail on interfaces

- src/ape/managers/converters.py
- tests/functional/test_contract_instance.py
Is convenient for not having to put quotes around addresses.
> feat: support integer-type input values for `AddressType`

- src/ape_init/_cli.py
Adding in a .gitignore file on ape initialization
[APE-230
](https://linear.app/apeworx/issue/APE-230/adding-in-a-gitignore-file-on-ape-initialization)
wrote a creation file to implement the git ignore with the basic ignores
`ape init` and open up the directory
> feat: Adding in a .gitignore file on ape initialization

- setup.py
- src/ape/managers/accounts.py
- src/ape/managers/compilers.py
- src/ape/utils/misc.py
- src/ape_cache/query.py
Small changes from running `pyupgrade`.
> chore: changes from pyupgrade

- setup.py
- src/ape_geth/provider.py
Very simple refactoring made while working on geth-style trace gas discrepancies.
> refactor: use callTracer for geth style traces

- src/ape_init/_cli.py
- tests/integration/cli/test_init.py
Add test for ape-230
fixes: # Ape-354
created a test file in `tests/integration/cli/test_init.py`
run the test
I would like some help:
- verify the project name in ape-config.yaml
> test: ape init

- CONTRIBUTING.md
> docs: fix discord link

- .github/workflows/stale-prs.yml
The description field causes the action to fail, Unexpected value 'description'
> fix: remove description

- .github/workflows/test.yaml
- .mdformat.toml
Makes mdformat run number automatically
fixes: #
The mdformat config
Sorry, no pyproject.toml yet :(
> chore: make mdformat run number automatically

- setup.py
Noticed that you can add additional links to a PyPI page (including funding) so I added some
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls
> docs: update PyPI Links

- .github/workflows/codeql.yml
- .github/workflows/commitlint.yaml
- .github/workflows/docs.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
Noticed some of the github actions were out of date with bug fixes, some of which have been causing issues
> chore: update github actions to latest versions

- src/ape/api/providers.py
- tests/functional/test_provider.py
- tests/integration/cli/projects/geth/tests/test_using_local_geth.py
changed the address arg to an AddressType
made a test for it
fixes: Ape-368
> feat!: change address arg to addressType

- docs/userguides/accounts.md
- src/ape/api/accounts.py
- src/ape/managers/accounts.py
- src/ape/utils/testing.py
- src/ape_test/accounts.py
- tests/functional/test_accounts.py
Changed TestAccountContainer and TestAccountManager to implement.
Run tests.
> feat: add support to create test accounts runtime

- src/ape/managers/accounts.py
- tests/functional/test_default_sender_context_manager.py
Cleanup part of the use_sender implemented.
fixes: #
> fix: cleanup for use_sender manager

- .github/FUNDING.yml
Updated the sponsor link that we just got approved for, points [here](https://github.com/sponsors/ApeWorX)
> docs: update sponsor link

- Dockerfile
update org.label-schema.docker.cmd to reflect user harambe
fixes: APE-508
update dockerfile
try it out
> fix: update org.label-schema.docker.cmd to reflect user harambe

- docs/_static/custom.css
> docs: update style and font for docs

- src/ape/api/providers.py
Add kwargs to ProviderAPI.get_receipt() to match what is present in the Web3Provider.get_receipt()
fixes: APE-302
> feat!: conform ProviderAPI.get_receipt()

- .gitignore
- src/ape/exceptions.py
- src/ape_ethereum/transactions.py
- tests/functional/test_receipt.py
- tests/integration/cli/test_compile.py
Follow up to https://github.com/ApeWorX/ape/pull/1250
> feat: allow setting txn on OutOfGasError

- docs/_templates/layout.html
- setup.py
Updated doc tools versions
fixes: APE-515
> docs: update versions and setup.py

- src/ape/api/providers.py
With this PR released, we can delete the hacky code in hardhat and foundry we had to add yesterday
https://github.com/ApeWorX/ape-hardhat/pull/123
https://github.com/ApeWorX/ape-foundry/pull/30
fixes: APE-566
> fix: handle none sender

- src/ape_ethereum/ecosystem.py
- tests/functional/test_ecosystem.py
Noticed this issue while running tests in a yearn strategy repo that I know worked before.
Hyphen causing issues.
fixes: APE-565
Replace hyphen with underscore before lookup
> fix: issue with default txn type and hyphen

- src/ape/api/projects.py
Addresses some last items from https://github.com/ApeWorX/ape/pull/1239
> chore: missing feedback from single-contract type JSON PR [APE-605]

- src/ape/api/accounts.py
- src/ape/api/providers.py
- src/ape_test/accounts.py
Improved performance of transaction handling
fixes: APE-563
> perf: improve performance of web3 provider send transaction

- src/ape/managers/networks.py
> feat: ad-hoc network forking [APE-612]

- src/ape/api/query.py
- src/ape/managers/query.py
A couple of small improvements to the QueryManager / default query provider, and one bug fix to improve estimation of single item queries (it previously was replying 0)
> refactor: improve query manager [APE-639]

- docs/userguides/console.md
- src/ape/api/projects.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
> perf: improve performance of ape [APE-620]

- setup.py
Update pin for new-style EIP712 messages
> chore: update EIP712 pin [APE-644]

- .pre-commit-config.yaml
- setup.py
> chore: bump ethpm-types [APE-675]

- docs/userguides/cache.md
- docs/userguides/contracts.md
- src/ape/api/projects.py
- src/ape/contracts/base.py
- src/ape/managers/accounts.py
- src/ape/managers/networks.py
- src/ape/managers/project/dependency.py
- src/ape/managers/project/manager.py
- src/ape/managers/query.py
- src/ape/utils/misc.py
- src/ape/utils/os.py
- src/ape_cache/query.py
- tests/functional/utils/test_misc.py
- tests/integration/cli/test_compile.py
Fix 404 errors for links in the documentation as well as a few other things.
fixes: APE-541
> docs: fix links [APE-671]

- src/ape/api/transactions.py
- src/ape/types/__init__.py
- src/ape_ethereum/transactions.py
- tests/functional/test_contract_event.py
Added more functionality for tx.events
fixes: #
> feat: implement contract log container [APE-662]

- SECURITY.md
> chore: bump version in `SECURITY.md` [APE-727]

- .pre-commit-config.yaml
- setup.py
- tests/integration/cli/projects/script/scripts/deploy.py
helping address https://github.com/ApeWorX/ape/pull/1346#discussion_r1142417914
> chore: upgrade flake8 [APE-733]

- src/ape/api/query.py
- tests/functional/test_query.py
Fixes https://github.com/ApeWorX/ape/pull/1277#discussion_r1137889014
Make error message the same.
> fix: show columns when unknown column argument [APE-732]

- .pre-commit-config.yaml
- setup.py
- src/ape/api/providers.py
- src/ape/contracts/base.py
- src/ape/managers/accounts.py
- src/ape/managers/compilers.py
- src/ape/managers/project/manager.py
- src/ape/utils/basemodel.py
- src/ape_accounts/accounts.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- src/ape_test/provider.py
- tests/integration/cli/conftest.py
Upgrade black to next breaking release.
One caveat is also required upgrading `packaging`, hope that is ok.
tried to upgrade black
realized some other incompats
fixed those
upgrades black
ran black
passing ci
objected conflicts from bumping packaging
> chore: upgrade black [APE-745]

- src/ape/types/signatures.py
> fix: leftpad signature encoding so it's 65 bytes [APE-752]

- setup.py
- src/ape/api/providers.py
* requires successful release of eip712 (gh seems down or something)
upgrade and run tests and fix things
> feat: upgrade web3.py to official 6.0 release [APE-759]

- src/ape/api/transactions.py
Changed the log message so that it will display only the explorer URL instead of the hash and URL if an explorer is installed. 
fixes: #1271
> chore: condense the explorer log message for a txn [APE-787]

- src/ape/api/providers.py
- src/ape_geth/provider.py
- src/ape_test/provider.py
- tests/functional/test_geth.py
> perf: add cache middleware to `ape-geth` web3 instance [APE-799]

- src/ape_geth/__init__.py
- src/ape_geth/provider.py
> feat: allow configuring a `geth` executable [APE-823]

- src/ape/plugins/__init__.py
> fix: silence pip version update warning [APE-835]

- README.md
Added missing '.'
fixes: #
Fixed missing '.'
See green '.'
> docs: style updates

- src/ape/api/projects.py
- src/ape/managers/project/dependency.py
- tests/functional/test_dependencies.py
goes with https://github.com/ApeWorX/ape-solidity/pull/98
> fix: issue with reference-based dependencies [APE-891]

- .github/workflows/test.yaml
> chore: put 3.8 back in the CI test matrix [APE-922]

- src/ape/api/accounts.py
- src/ape/managers/accounts.py
- src/ape_ethereum/transactions.py
- tests/functional/test_accounts.py
> fix: ignore signature check on impersonated accounts [APE-931]

- setup.py
- src/ape/types/trace.py
going through affected plugins and fixing stuff....
> fix: fixes need to get this dang release out [APE-949]

- setup.py
Alright wasn't that fun?
lets try this again gain gain gain gain (fades out)
(disc jockey sounds)
> chore: pin typing-ext [APE-970]

- setup.py
now that pydantic is patched, we can remove our pin hack
> fix: typing ext pydantic fix [APE-973]

- src/ape/api/compiler.py
- src/ape/managers/compilers.py
- tests/functional/test_compilers.py
> feat: flattened api [APE-984]

- docs/userguides/contracts.md
Update the contracts guide to have a link to the publishing guide. 
fixes: #
> docs: update contracts guide [APE-992]

- docs/userguides/installing_plugins.md
- setup.py
- src/ape_plugins/_cli.py
- src/ape_plugins/utils.py
- tests/functional/test_plugins.py
fixes: #896
Fixes: APE-225
was there a ticket for allowing version constraints like >= and stuff? i cant find it
> feat: allow version constraints and tag, branch, remote versions for plugin installs [APE-225]

- docs/index.md
- docs/userguides/config.md
- docs/userguides/dependencies.md
- docs/userguides/projects.md
- src/ape/managers/project/dependency.py
- tests/functional/test_dependencies.py
> feat: npm dependency [APE-1000]

- .github/workflows/test.yaml
- setup.py
- src/ape_geth/provider.py
now that py-geth is released, we can delete this part and upgrade it in setup.py
> chore: upgrade py-geth and delete unneeded code [APE-1083]

- docs/userguides/config.md
- docs/userguides/developing_plugins.md
Update the guide so that the plugin configuration is more clear for users.
fixes: #1464
> docs: update plugin naming in config [APE-1085]

- src/ape/api/providers.py
Adds a mock API (to be implemented by testing providers) for setting raw storage slots
fixes: #360
> feat: add ability to set raw storage slots [APE-1088]

- src/ape/api/providers.py
base fee is just 0.... cmon now
tests are in the fact that hardhat wont work AT ALL without this change.....
> fix: issue where some providers falsely reported no base fee [APE-1099]

- setup.py
- src/ape_test/provider.py
- tests/functional/test_provider.py
having to bump this because of `ape-solidity`
Could bump it there but figured is simpler to do it here and might as well to prevent other issues like this
> feat: web3 6.5 panic error handling [APE-1113]

- src/ape_ethereum/ecosystem.py
reverted #1178 because 1.1.0 was more or less the first public release of gnosis contracts
check for `masterCopy()` and additionally check it matches the address stored in slot 0. keep the check that it's initialized to a non-zero address.
> fix: use master copy for gnosis safe proxy [APE-1124]

- docs/userguides/testing.md
reading through the cov doc, fixed a couple things
> docs: small revisions for coverage doc

- setup.py
- src/ape/exceptions.py
- tests/functional/test_contract_container.py
- tests/functional/test_contract_instance.py
> fix: remove italics from last PR [APE-1168]

- src/ape/cli/arguments.py
- tests/integration/cli/test_accounts.py
> fix: more alias validation [APE-1171]

- setup.py
looks like we are finally able to uprade mypy
**this makes having Ape installed in the same environment as other projects like Silverback work together**
now i dont need separate envs necessarily =
> chore: mypy upgrade [APE-1172]

- docs/userguides/networks.md
- src/ape/api/providers.py
- src/ape_test/provider.py
- tests/functional/test_contract_instance.py
fixes: #1573 
Fixes: APE-1240
both kwargs
use kwarg
> feat: block id kwarg support [APE-1240]

- README.md
fixes: #1558 
Fixes: APE-1221
Warn about upgrading pip
> docs: mention upgrading pip in readme [APE-1221]

- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/proxies.py
- save 3 rpc calls when we can be certain from the code alone a contract is not a proxy.
- add [sequence wallet](https://github.com/0xsequence/wallet-contracts/blob/master/contracts/Wallet.sol) proxy detection
- add [0xsplits proxy detection](https://github.com/0xSplits/clones-with-immutable-args/blob/864a87af085eabc27744ecbfa7ae733af4e3433e/src/ClonesWithImmutableArgs.sol) (for exmaple used for the [protocol guild](https://app.0xsplits.xyz/accounts/0xF29Ff96aaEa6C9A1fBa851f74737f3c069d4f1a9/) vesting contract)
> feat(proxy): detect new proxies and improve performance [APE-1300]

- src/ape_ethereum/ecosystem.py
- tests/functional/test_ecosystem.py
when default to None when was actually set as 0, noticed in arb plugin
> fix: issue where could not have gas limit of 0 [APE-1307]

- src/ape/api/providers.py
- tests/functional/test_geth.py
- tests/functional/test_provider.py
Adds two small properties that'll make it easier to grab the raw URIs to connect with
fixes: #1622
> feat(ProviderAPI): add uri str fields for easier use [APE-1317]

- src/ape_cache/query.py
```
File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/ape_cache/query.py", line 186, in _transaction_estimate_query_clause
select([func.count()])
File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/_selectable_constructors.py", line 489, in select
return Select(*entities)
File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 5130, in __init__
self._raw_columns = [
File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/selectable.py", line 5131, in <listcomp>
coercions.expect(
File "/Users/bryan/llamanodes/web3-this-then-that-py/venv/lib/python3.10/site-packages/sqlalchemy/sql/coercions.py", …
```
> fix(cache): sqlalchemy.exc.ArgumentError from selecting counts

- src/ape/logging.py
This will help debug stuff in the logs.
> feat: show plugin name in log messages [APE-1327]

- docs/userguides/networks.md
fix docs typo
Typo in networks.md
/
/
/
> docs: typo in networks.md [APE-1329]

- .github/workflows/test.yaml
suddenly 403 on a geth install from ci so throwing a dart in the dark here
> fix: attempt fixing geth install [APE-1333]

- setup.py
- src/ape/plugins/__init__.py
> fix: delete pluggy type-hack [APE-1332]

- src/ape/api/compiler.py
man sometimes providers give you the weird frames.
> fix: weird type error when checking for dev messages [APE-1331]

- src/ape_geth/provider.py
replace a yuck with a yum
use `__contains__`
* Start a local PoA geth
* Connect to it using Adhoc provider
> refactor: simplify the adding of middleware [APE-1340]

- src/ape/api/providers.py
noticed someone getting an error while handling the real error
thinking this wil fix it but tbd
> fix: index error in trace handler [APE-1342]

- src/ape/pytest/fixtures.py
- tests/functional/test_fixtures.py
> fix(pytest): fix double yield problem in isolation fixture [APE-1353]

- setup.py
I was constantly having issues with this, I think the pin should have been updated
> fix(deps): update pin of ethpm-types [APE-1383]

- src/ape/api/providers.py
- src/ape/exceptions.py
- tests/functional/geth/test_provider.py
- tests/functional/test_provider.py
fixes: #1605 
Fixes: APE-1348
Forward  the actual message to be included in the error message.
Make sure you see the full error message now.
> feat: improve txn not found [APE-1348]

- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/exceptions.py
- src/ape/plugins/pluggy_patch.py
- src/ape/types/__init__.py
- src/ape_cache/query.py
- src/ape_console/_cli.py
- src/ape_console/plugin.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- src/ape_geth/provider.py
- src/ape_test/_cli.py
- src/ape_test/provider.py
- tests/functional/test_contract_instance.py
* cleans up unused type ignore statements
* Sets default parameters so method is like base method (prolly was a miss)
* rm non-existing item from __all__
* adds missing types (will cause issues during pydantic v2)
* fix check for ipc path (was hidden behind a type ignore)
> chore: remove unused type ignores and other small items [APE-1419]

- docs/userguides/compile.md
- src/ape/api/compiler.py
- src/ape/managers/compilers.py
- src/ape_pm/compiler.py
- tests/functional/test_compilers.py
fixes: #688 
fixes: #789 
Fixes: APE-203
Fixes: APE-192
> feat: adhoc code compile [APE-1476]

- src/ape/pytest/plugin.py
> feat: better error when pytest option collision [APE-1479]

- CONTRIBUTING.md
- SECURITY.md
- src/ape/contracts/base.py
> fix: typos [APE-1513]

- src/ape/api/networks.py
- src/ape/api/providers.py
- src/ape/managers/chain.py
- src/ape/managers/project/manager.py
- src/ape_cache/query.py
* adds `is_fork`, `is_local` and `is_dev` to `NetworkAPI` and used them all over.
> feat: is local helper properties on NetworkAPI [APE-1518]

- src/ape/utils/basemodel.py
> fix: use getattribute [APE-1539]

- src/ape/api/providers.py
- src/ape/types/coverage.py
- src/ape/utils/basemodel.py
- src/ape_ethereum/ecosystem.py
- src/ape_geth/provider.py
- src/ape_plugins/utils.py
- tests/functional/test_network_manager.py
- tests/functional/test_plugins.py
* Issue where all enums were values instead of enum types
* Prevents exceptions in `__repr__`
* Fix issues where plugin type was a str instead of enum
* add some tests
* fix issue where geth connection ID was not very identifiable
> fix: enum values were raw [APE-1551]

- .pre-commit-config.yaml
- setup.py
fixed a regression in ethpm-types, bumping here
> fix: bump past broken source map ethpm-types [APE-1605]

- pyproject.toml
- setup.py
> chore: bump dependencies

- src/ape/cli/commands.py
- tests/functional/test_cli.py
Two bugs prevented this feature from working for me, I tried both on main and on the current released Ape.
1. interactive mode was honored in some cases, for the released mode I think that was only the default network.
2. The logic for checking for the interactive flag in the parents context had an issue because it used `False` as a default and then checked for None before looking in parents, and that never happened, so some cases interactive mode was not known during recycling provider.
> fix: issue with interactive scripts would not be connected to right provider

- setup.py
> chore: bump ethpmtypes for final time

- tests/functional/test_types.py
add tests to prove AddressType works for https://github.com/ApeWorX/ape/issues/1790
> test: prove that `AddressType` works

- setup.py
bumps out of the problematic ethpmtypes which couldnt update source props
> chore: bump ethpm-types to fixed version

- src/ape_ethereum/provider.py
- tests/functional/geth/test_provider.py
seeing nodes having all sorts of differences here causing problems, so need this...
needed for https://github.com/ApeWorX/ape-foundry/pull/80 which will fix  #1783
> fix: more issues with eth fee history response handling

- .pre-commit-config.yaml
- setup.py
> chore: bump lint dependencies

- docs/_templates/layout.html
- docs/conf.py
fixes: #1815 
Changes button to bring you to page where can easily edit the page and rename it to Edit on GitHub
> docs: "Edit on GitHub" button

- docs/methoddocs/types.md
- docs/userguides/accounts.md
- src/ape/types/signatures.py
> docs: document sign message functionalities

- docs/userguides/testing.md
> docs: adjust tests guide fixtures section to make more sense

- docs/userguides/contracts.md
> docs: document difference between CALL versus TRANSACT in contract-interaction guide

- src/ape_accounts/_cli.py
> docs: improve message for adding extra account entropy upon generation

- docs/userguides/config.md
> docs: elaborate more on RPC connection via config file

- docs/userguides/accounts.md
> docs: more documentation on how `ape-accounts` plugin works with keyfiles and storage

- docs/userguides/config.md
- docs/userguides/networks.md
> docs: improve networks guide, specifically around L2s and custom networks

- docs/userguides/contracts.md
> docs: elaborate on deploying contracts

- docs/userguides/networks.md
> docs: correct network script example

- docs/userguides/networks.md
> docs: networks guide update

- setup.py
Expanded the allowed dependency version of the rich package to include v13.
Output looks the same on tree list commands and tests pass.
> chore: allow rich v13 as dependency

- src/ape_geth/provider.py
making things less confusing as much as possible before 0.8
> refactor: make error more node generic

- src/ape/api/address.py
- src/ape/managers/chain.py
- src/ape/utils/basemodel.py
- tests/functional/utils/test_basemodel.py
> feat: make `.provider` on `@classproperty` on all manager-access models

- src/ape/_cli.py
- src/ape/pytest/plugin.py
- src/ape_accounts/_cli.py
- src/ape_console/_cli.py
- src/ape_networks/_cli.py
- src/ape_run/_cli.py
I was checking out something, trying to import from `ape_run` from an Ape Project (don't ask yet).
Anyway, I got another circular import issue and this resolves it.
> fix: more circular import issues when importing from `ape_run`

- setup.py
- tests/functional/geth/test_provider.py
- tests/integration/cli/test_networks.py
i am hoping this fixes the failed ci from last merge to main
> fix: bump out of broken py-geth

- docs/index.md
- docs/methoddocs/ape_accounts.md
- docs/userguides/accounts.md
- src/ape/cli/arguments.py
- src/ape/utils/validators.py
- src/ape_accounts/__init__.py
- src/ape_accounts/_cli.py
- src/ape_accounts/accounts.py
- tests/conftest.py
- tests/functional/conftest.py
- tests/functional/test_accounts.py
- tests/functional/test_default_sender_context_manager.py
- tests/integration/cli/test_accounts.py
Adds a `generate_account()` function so accounts can be created using Ape as a lib.
fixes: #1760
fixes: #1779
> feat: adds account generation and import API functions

- src/ape_ethereum/ecosystem.py
- tests/functional/test_ecosystem.py
fixes: #1896 
following advice from issue
> fix: decoding fails when indexed values not first in log

- .github/workflows/codeql.yml
- .github/workflows/commitlint.yaml
- .github/workflows/docs.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/stale-prs.yml
- .github/workflows/test.yaml
> chore: upgrade actions

- docs/userguides/installing_plugins.md
- src/ape_plugins/_cli.py
- src/ape_plugins/exceptions.py
- src/ape_plugins/utils.py
- tests/functional/test_plugins.py
> fix: issue where installing a plugin would change Ape version

- docs/index.md
- docs/methoddocs/cli.md
- docs/userguides/forking_networks.md
- docs/userguides/networks.md
I realized through Discord the docs for forked network was lacking, so i made a guide.
Also - I realize we have no way to fork custom networks right now, I am thinking about what to do there.
> docs: document forked networks

- docs/userguides/networks.md
- src/ape/managers/config.py
- src/ape_ethereum/ecosystem.py
- tests/functional/test_ecosystem.py
- tests/functional/test_network_api.py
> fix: configuring custom ecosystems

- README.md
- setup.py
Add badges to the top the readme.
note it also looks good in the docs
> docs: add README badges

- README.md
these two parts seemed like links but they werent
> docs: readme add some links

- .pre-commit-config.yaml
- setup.py
- src/ape/managers/networks.py
- tests/functional/conftest.py
- tests/functional/geth/test_network_manager.py
- tests/functional/test_network_manager.py
> fix: issue where wouldn't use expected URI in `.fork` context

- docs/userguides/accounts.md
Corrected misspelling in accounts userguide.
fixes: #
> docs: account misspelling

- tests/integration/cli/test_test.py
these changes are needed for the tests in https://github.com/ApeWorX/ape/pull/1930 to pass
> test: improve geth integration tests

- src/ape/exceptions.py
- src/ape_ethereum/provider.py
- src/ape_geth/provider.py
- tests/integration/cli/test_test.py
this allows traces to work for failed estimations... i really dont like this solution much, and i know itll be much better on 0.8 because of the refactor there, but i can try to find ways to improve ahead of time...
> fix: tracework for failed gas estimates

- src/ape_ethereum/provider.py
Shows the call trace on a failed transaction.
Ref: #1945
> feat: show trace on failed transactions in Web3Provider

- src/ape_ethereum/provider.py
Cleaned up some of the code in a failing part of the codebase
fixes: #1957
renamed `trace` into `call_trace` because it was ambigious
> fix: unbound parameter `traces`

- src/ape_test/accounts.py
- tests/functional/test_accounts.py
fixes: #1961
Copied ape-accounts implementation
tests pass
> fix(ape-test): add support for signing eip712 messages

- src/ape_ethereum/provider.py
- tests/functional/geth/test_provider.py
> fix: block id not working in base Ethereum node class

- setup.py
- src/ape_ethereum/provider.py
- tests/functional/test_contract_instance.py
the latest web3.py broke some things in Ape; this PR fixes them.
**this is causing much of our CI to fail in core rn**
> fix: support latest web3 changes

- src/ape_ethereum/provider.py
- tests/functional/geth/test_provider.py
another miss from the web3 upgrade.
> fix: issue getting correct error message for contract-reverts

- src/ape/utils/abi.py
- tests/functional/utils/test_abi.py
> feat: make dynamic structs pickleable with this one simple trick

- setup.py
- src/ape/_cli.py
- src/ape/plugins/_utils.py
- src/ape/utils/misc.py
- src/ape_plugins/_cli.py
- tests/functional/test_plugins.py
fixes: #1995
use importlib distributions
> fix: replace usage of `pkg_resources`

- src/ape/api/projects.py
- src/ape_ethereum/provider.py
> chore: fix typos

- src/ape/managers/compilers.py
- src/ape/managers/project/manager.py
- src/ape/pytest/coverage.py
- src/ape/utils/os.py
- src/ape_compile/_cli.py
- src/ape_ethereum/provider.py
- tests/functional/utils/test_os.py
fixes some misses from this old PR: https://github.com/ApeWorX/ape/issues/636
this is really helpful for vyper 0.4.0 support - will use here https://github.com/ApeWorX/ape-vyper/pull/110/files
> fix: issues where "full extension" was not always honored

- setup.py
- src/ape/managers/converters.py
fixes: #
use type shed, remove type ignore,
fixes a mypy warning.
> chore: use dateutil type shed

- src/ape/plugins/__init__.py
- tests/functional/test_plugins.py
another place we should replace pip freeze
> perf: replace pip freeze with importlib.metadata

- src/ape/utils/abi.py
- tests/functional/test_ecosystem.py
fixes: #2007 
Missing recursion
The test in the linked issue works now.
> fix: issue encoding nested structs in calldata

- setup.py
- src/ape/_cli.py
> chore: replace importlib_metadata with importlib.metadata

- src/ape/api/accounts.py
> docs: add missing doc-strs and adjust docs in `api.accounts`

- docs/userguides/data.md
mdformat seems to not like this (sometimes?). Idk it keeps changing in my PRs so I am fixing it a way that is more like the other examples so it is better.
> docs: fix guide example formatting

- .pre-commit-config.yaml
- setup.py
- src/ape/_cli.py
- src/ape/exceptions.py
- src/ape_run/_cli.py
* uses better type for paths in handle_ape_exception
* changes needed so type checking works on that path
* uses correct isort pre-commit mirrow
* upgrades for lints
> chore: improve `handle_ape_exception` type

- src/ape_ethereum/provider.py
a test to see if this is needed.
> chore: delete unnecessary awaiting on web3 calls

- docs/userguides/accounts.md
- docs/userguides/clis.md
- docs/userguides/contracts.md
removes some unnecessary spacing in the docs (trying to make PR for project refactor smaller)
> docs: remove bad spacing in some docs examples

- src/ape_ethereum/_print.py
> chore: set contractName using constructor

- src/ape/api/projects.py
- src/ape/cli/__init__.py
- src/ape/cli/choices.py
- src/ape/cli/paramtype.py
- src/ape/managers/project/dependency.py
- tests/functional/conftest.py
- tests/functional/test_config.py
- tests/functional/test_dependencies.py
- tests/integration/cli/projects/only-dependencies/ape-config.yaml
- tests/integration/cli/projects/with-dependencies/ape-config.yaml
Remove deprecated and unused constructs from the framework, targeting 0.8
> refactor!: delete deprecated stuff

- docs/userguides/compile.md
- docs/userguides/dependencies.md
- src/ape/managers/config.py
- src/ape/managers/project/manager.py
- src/ape_compile/_cli.py
- src/ape_pm/_cli.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_pm.py
adhoc try out settings using `--config-override` option on `ape compile` and `ape pm compile`
**a part of the project refactor hoisting in**
> feat: `--config-override` option for `compile` CLIs

- src/ape/api/projects.py
- src/ape/managers/compilers.py
- src/ape/utils/misc.py
* adds more entries to `SOURCE_EXCLUDE_PATTERNS`
* relies it on more
> feat: add more entries to `SOURCE_EXCLUDE_PATTERNS`

- src/ape/managers/chain.py
I get this mypy error locally in some of my environments and so I am fixing it, it reads better anyway.
> chore: fix anomalous typing concern

- src/ape/contracts/base.py
- src/ape/exceptions.py
- src/ape/managers/converters.py
- src/ape/managers/networks.py
- src/ape/utils/__init__.py
- src/ape/utils/misc.py
- src/ape/utils/os.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- src/ape_pm/compiler.py
- tests/integration/cli/test_init.py
* rm false warning (contracts source_path)
* put note in a doc str instead (conversion manager)
* rename local var (ecosystems from plugins)
* include type in repr (converter)
* add missing ape.utils exports get_full_extension, only_raise_attr_error,
* random refactors
* documents some stuff in Ethereum config
**All part of making project refactor diff smaller**
> refactor: misc, small changes

- src/ape/cli/arguments.py
- src/ape/utils/misc.py
- tests/functional/test_cli.py
DANG IT really sorry.... somehow regressed where .cache was no longer ignored.
> fix: `.cache` files wasn't ignored in source file collection

- src/ape/api/compiler.py
- src/ape/managers/compilers.py
- src/ape/managers/project/manager.py
- src/ape/managers/project/types.py
- src/ape_pm/compiler.py
- tests/functional/test_compilers.py
fixes: #660 
Part of the project refactor but wanted it separate for more thorough review
> refactor!: In CompilerAPI, use Iterable and Iterator instead of Sequence and Dict

- src/ape/api/transactions.py
- tests/functional/test_receipt.py
I came across a weird bug today where `TransactionAPI` was attempted to be initialized on its own (no sub class).
fixed it.
Replace faulty code with using ecosystem t
o create a tx 
create a receipt using a raw tx dict for the key "transaction"
> fix: `TransactionAPI` abstract methods bug during receipt decoding

- src/ape/api/trace.py
- src/ape_ethereum/trace.py
im getting `ape-vyper` / coverage stuff updated and tested now
> fix: trace API changes (again)

- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- docs/conf.py
- docs/userguides/accounts.md
Add github workflow for doctesting and some basic testing on the accounts userguide.
fixes: #
> feat: add doctesting with github workflow

- docs/conf.py
- docs/index.md
- docs/methoddocs/ape_ethereum.md
- docs/methoddocs/ape_node.md
- docs/methoddocs/ape_test.md
- src/ape_cache/__init__.py
- src/ape_ethereum/__init__.py
- src/ape_ethereum/multicall/__init__.py
- src/ape_node/__init__.py
- src/ape_test/__init__.py
Add methoddocs for core plugins to Plugin Python Reference section for further documentation.
fixes: #
> feat: core plugin methoddocs [APE-1750]

- src/ape/managers/plugins.py
- src/ape/plugins/_utils.py
- src/ape_plugins/_cli.py
- tests/functional/test_plugins.py
emergency: this is preventing 0.8 upgrade unfortunately
> fix: issue where non-core plugins showed up in core plugins

- docs/userguides/transactions.md
Update the userguide so that it reflects the new changes from `ContractInstance.receipt` to `ContractInstance.creation_metadata` for transactions.
fixes: #
> docs: update userguides for 0.8 changes

- src/ape_pm/dependency.py
- tests/functional/test_dependencies.py
Just some fixed around checking version / references for v or non v prefixed during fetching of GH dependencies.
i added lots of tests which is really helpful
> fix: issue where `v-prefix` was required if using ref as a version in GH dependencies

- docs/userguides/dependencies.md
Update solidity dependency mappings
fixes: #
> docs: solidity mapping

- src/ape_ethereum/ecosystem.py
- tests/functional/test_ecosystem.py
im no sure if this will actually fix the issues i am seeing in CI.
something happened to my OS where I can no longer work with many of my python venvs because of some SSL reasons so im digging into that to try and repro more , not sure if this will actually fix my problems but it definitely adds resiliency ... so it is a start, and ok for a friday morning.. :coffee:
> fix: handle enum types more in trace enrichment

- src/ape_accounts/accounts.py
better display of bytes data in eip-712 message when signing.
fixes: #
> fix: eip-712 hex data display

- src/ape/api/providers.py
- tests/functional/test_block.py
> fix: block validation issues

- src/ape/managers/project.py
- tests/functional/test_project.py
> fix: issue where deleted contracts remained in `ContractManager`

- src/ape/managers/project.py
- tests/integration/cli/test_pm.py
seeing some random test failures / flakinees on other PRs.
This my attempt to resolve that.
Ensure tests start off in a cleaner state (expected)
Leave the rest to gremmlins i guess..
no more flaky tests
> test: fix flakey tests

- docs/userguides/accounts.md
- tests/functional/test_block.py
- tests/integration/cli/test_accounts.py
- tests/integration/cli/test_init.py
> chore: fix some comments

- .github/workflows/test.yaml
> test: re-enable `macos-latest` in CI

- .github/workflows/test.yaml
> chore: use official install-geth-tools

- setup.py
> chore: pin numpy i guess

- .github/workflows/test.yaml
- setup.py
- src/ape/managers/project.py
- src/ape/utils/os.py
- tests/conftest.py
- tests/functional/test_dependencies.py
- tests/functional/test_project.py
- tests/integration/cli/test_test.py
- tests/performance/test_contracts.py
- tests/performance/test_project.py
Before:
```
In [1]: time project.get_contract("Flat")
CPU times: user 18.3 ms, sys: 1.52 ms, total: 19.8 ms
Wall time: 18.6 ms
Out[1]: <Flat>
In [2]: time project.get_contract("Flat")
CPU times: user 3.14 ms, sys: 1.13 ms, total: 4.27 ms
Wall time: 3.34 ms
Out[2]: <Flat>
```
After:
```
In [1]: time project.get_contract("Flat")
CPU times: user 19.4 ms, sys: 1.61 ms, total: 21 ms
Wall time: 19.7 ms
Out[1]: <Flat>
In [2]: time project.get_contract("Flat")
CPU times: user 50 µs, sys: 0 ns, total: 50 µs
Wall time: 55.1 µs
Out[2]: <Flat>
```
> perf: massive performance improvements for project / sources manager

- .pre-commit-config.yaml
- setup.cfg
- setup.py
- src/ape/api/config.py
- src/ape/api/projects.py
- src/ape/api/providers.py
- src/ape/api/transactions.py
- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- tests/functional/test_transaction.py
- tests/integration/cli/test_test.py
> chore: utilize flake8-pydantic

- src/ape_ethereum/ecosystem.py
- src/ape_ethereum/transactions.py
- tests/functional/test_ecosystem.py
> fix: issue with snake_case keys in `ape_ethereum.transactions.ShareBlobReceipt`

- src/ape_ethereum/trace.py
- tests/functional/test_trace.py
regression from https://github.com/ApeWorX/ape/pull/2208
> fix: issue where `trace.return_data` was no decoded in some cases

- docs/userguides/clis.md
Make example code work with click
added a few lines
got i working local
`Usage: ape run scripts/test.py [OPTIONS] COMMAND [ARGS]...
Options:
-v, --verbosity LVL  One of ERROR, WARNING, SUCCESS, INFO, or DEBUG
-h, --help           Show this message and exit.
Commands:
cmd-1
cmd-2
cmd-3
`
> docs: update cli example code

- docs/_templates/layout.html
- docs/userguides/clis.md
- docs/userguides/console.md
- docs/userguides/contracts.md
Hello
I found and fixed several spelling issues.
Hope it helps.
Br, Elias.
> docs: fix spelling issues

- pyproject.toml
- tests/functional/test_project.py
I had in my notes to fix this but it doesn't seem like a problem. In any case, there were no tests for this so i am just making sure...
> test: show we can have sets of projects

- setup.py
for safety reasons, repinning these
> chore: re-pin dependencies

- docs/methoddocs/api.md
- src/ape/api/convert.py
Add examples of how to use `convert()`. 
fixes: #
> docs: add convert examples

- docs/conf.py
- src/ape/api/convert.py
Noticed that a few methods that should be excluded in the docs weren't being excluded properly. 
fixes: #
> docs: add exclusions and clarify convert examples

- .github/workflows/build.yaml
I used an old keyword argument for the retention policy, updated to use latest version
fixes: #
Changed the keyword args
TBD
> fix: bad kwarg in snok retention

- .github/workflows/build.yaml
Account is required for ape, adding the account to the container retention policy
fixes: #
Added account keyword to container retention policy
> fix: need to add account to snok

- src/ape/managers/chain.py
- tests/functional/test_contracts_cache.py
local contract creation not cleared, causing issues.
the name was wrong in the method
after clearing cache, creation no longer there
> fix: issue where local contract creation not cleared

- funding.json
> chore: add OP rPGF project ID

- src/ape_test/_cli.py
- tests/integration/cli/test_test.py
> fix: issue causing `ape test -w` not to work (non-string arugments)

- src/ape/logging.py
- tests/functional/test_logging.py
would be helpful for me right now but dont have
> feat: add logger.at_level context manager method

- docs/userguides/dependencies.md
> docs: snekmate example fix

- .pre-commit-config.yaml
- setup.py
- src/ape/utils/trace.py
- src/ape_ethereum/provider.py
getting weird failings in mypy but maybe not related. in any case, upgrades
> chore: lint upgrades

- src/ape/logging.py
- tests/integration/cli/test_accounts.py
- tests/integration/cli/test_cache.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_networks.py
- tests/integration/cli/test_pm.py
- tests/integration/cli/test_run.py
Align logs
fixes: #2312 
Adding padding to severity prefix
TODO
> feat: align logging statements

- setup.py
need this for my etherscan work
> chore: bump evmchains

- .github/workflows/test.yaml
- pyproject.toml
- tests/conftest.py
- tests/functional/conftest.py
- tests/functional/geth/test_contract.py
- tests/functional/test_accounts.py
- tests/functional/test_cli.py
- tests/functional/test_contract_event.py
- tests/functional/test_default_sender_context_manager.py
- tests/functional/test_provider.py
- tests/integration/cli/test_accounts.py
- tests/integration/cli/test_console.py
- tests/integration/cli/test_networks.py
APE TEST | TEST APE
being meta
tests pass
> test: use `ape test` to test ape

- src/ape/managers/project.py
- src/ape/pytest/coverage.py
- src/ape/utils/os.py
- src/ape_pm/compiler.py
- tests/functional/test_compilers.py
- tests/functional/utils/test_os.py
> perf: use `p1.relative(p2)` when it makes sense

- docs/userguides/console.md
- setup.py
Handle all the mdformat updates
> docs: handle mdformat updates

- .github/workflows/test.yaml
> feat: support local `geth --dev` 1.14.12

- docs/methoddocs/ape_accounts.md
- docs/methoddocs/ape_compile.md
- docs/methoddocs/ape_ethereum.md
- docs/methoddocs/ape_node.md
- docs/methoddocs/ape_pm.md
- docs/methoddocs/ape_test.md
the performance stuff regressed some of the auto-doc stuff from core plugins. sorry!
thanks @bitwise-constructs for pointing this out.
specified sub modules in autodoc
```
sphinx-ape build .
sphinx-ape serve --open
```
> docs(fix): fix core plugin method auto-doc

- src/ape/contracts/base.py
- src/ape/managers/project.py
> docs: fix some typos in comments and doc strings

- docs/userguides/compile.md
Misspell on Output Extra caption along navigating for intended section links 
fixes: #
Revise the current section links
Accessing documentation page by the link
> docs(compile): section links Output Extra

- src/ape/utils/abi.py
> chore: remove redundant words

- docs/userguides/testing.md
- src/ape/pytest/config.py
- src/ape/pytest/fixtures.py
- src/ape_ethereum/ecosystem.py
- src/ape_test/config.py
- tests/functional/test_fixtures.py
- tests/functional/test_test.py
> feat: support individual isolation-scope configs

- src/ape/exceptions.py
- src/ape/types/coverage.py
fix some typos in comment
fixes: #
> chore: fix some typos in comment

- tests/functional/test_chain.py
this test keeps randomly failing in PRs, I don't really see why other than x-dist messing it up.
> test: mark test as flaky

- tests/functional/test_project.py
x-dist is really screwing these up in unpredictable ways lately.
> test: another flaky test

- src/ape/types/events.py
- tests/functional/test_types.py
This just makes my life easier sometimes.
> feat: allow creating `LogFilter` object from Nones (coercing to empty list / dict when possible)

- src/ape/managers/accounts.py
- tests/functional/test_accounts.py
would have saved time to see the provider name here.
> feat: include provider name in impersonate account error

- src/ape/api/networks.py
this method is just... wrong... it is like it is supposed to be on TranssactionAPI but it is on EcosystemAPI. It is not used anywhere, wouldnt work even if you called it
> fix: delete unused, misleading, and error-prone method

- .github/ISSUE_TEMPLATE/bug.yml
Noticed that the Bug issue was not a choice on the New Issue page
- [c] All changes are completed
~~- [ ] Change is covered in tests~~
> chore: fix bug issue template

- src/ape/managers/project.py
- tests/functional/test_dependencies.py
Add a method for isolating changes in the dependencies packages cache, needed for https://github.com/ApeWorX/ape/pull/2513/
> feat: isolate changes context in packages cache

- src/ape/managers/_contractscache.py
- tests/functional/test_contracts_cache.py
Attempted to fix 2511 but I can't reproduce. My tests still pass on the main branch.
fixes: #2511
> fix: avoid attempting to cache None for a contract-type

- src/ape/contracts/base.py
Pass-through `proxy_info` and `detect_proxy` kwargs through to `ContractCache.instance_at`
> refactor(contracts): add proxy kwargs to `ContractContainer.at`

- setup.py
> fix: update py-geth to 5.3.0

- src/ape/contracts/base.py
- tests/functional/test_contract_event.py
> fix: filter out logs from other contracts in `ContractEvent.from_receipt`

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
- src/ape_node/provider.py
> chore: handle `ruff` upgrade

- src/ape/api/address.py
- tests/functional/test_hash_address.py
Add hash function to BaseAddress class
Fixes: #2476
Add new tests, checking for membership in dict and set
> refactor: add hash protocol to BaseAddress

- src/ape/managers/project.py
- tests/functional/test_project.py
this is a nice performance boost when unpacking a project, prevents having to re-compiling most of the time.
> feat: include build stuff in the unpacking of a project

- docs/userguides/contracts.md
- src/ape/contracts/base.py
- tests/functional/test_contract_instance.py
This helps me a lot
fixes: #2571
> feat: allow `decode=False` to get the raw returndata from calls

- .github/workflows/test.yaml
- setup.py
- src/ape/managers/project.py
- src/ape_node/provider.py
- tests/functional/geth/test_network_manager.py
- tests/functional/test_project.py
was not able to use latest  geth; fixes it
> fix: support for geth 1.15.x

- src/ape_ethereum/transactions.py
Logic was trying to decode an anonymous event by looking at it's first topic, so break out earlier
fixes: #2570
~~- [ ] Change is covered in tests~~
> fix(Ethereum): decoding bug w/ anonymous events

- docs/userguides/dependencies.md
- src/ape/utils/_github.py
- src/ape_pm/dependency.py
- tests/functional/test_dependencies.py
> fix: issue where could not clone a repo using SSH

- src/ape_accounts/accounts.py
- tests/functional/test_accounts.py
> fix: show full eip712 msg when signing

- .github/workflows/test.yaml
- src/ape/managers/project.py
- src/ape_compile/_cli.py
- src/ape_ethereum/provider.py
- src/ape_node/provider.py
- src/ape_pm/dependency.py
- tests/functional/conftest.py
- tests/functional/geth/test_network_manager.py
- tests/functional/geth/test_provider.py
- tests/functional/test_contract_container.py
- tests/functional/test_contract_event.py
- tests/functional/test_dependencies.py
- tests/functional/test_project.py
- tests/integration/cli/test_compile.py
- tests/integration/cli/test_networks.py
- tests/integration/cli/test_test.py
fix: if configuring a version, use it for python - helps when not installed yet and not published anywhere
fix: if didnt configure a version, attempt to look one up from pypi
> fix: uninstalled dependencies causing issues

- docs/userguides/networks.md
- src/ape_ethereum/provider.py
- src/ape_node/provider.py
- tests/functional/geth/test_provider.py
- tests/functional/test_config.py
> feat(node): Able to launch a local `reth` node

- src/ape/managers/project.py
- tests/functional/test_project.py
> fix(project): issue where multi-project unset config would override actually set items

- src/ape/types/events.py
> docs: fix typo in comment

- .github/workflows/test.yaml
> test: testing out gh action path version w/ extras

- src/ape/api/transactions.py
> docs: fix typo

- setup.py
> fix(Deps): upgrade hexbytes to <=1.2.0
